import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: '3pl-portal',
    name: '3PL Customer Portal',
    icon: '\u{1F3D7}\u{FE0F}',
    dept: 'Operations',
    deptColor: '#7C3AED',
    description: 'White-label customer portal with inventory, ordering, billing, and AI support',
    valueProposition: 'Give every 3PL customer self-service access that cuts support calls by 60% and gets you paid 12 days faster',
    enabled: true,
    buildBatch: 3,
  },
  tabs: [
    {
      id: 'overview',
      label: 'Overview',
      kpis: [
        { label: 'Active Customers', value: 12, change: 20, trend: 'up', icon: '\u{1F465}' },
        { label: 'Inventory Units', value: 48300, change: 8, trend: 'up', icon: '\u{1F4E6}' },
        { label: 'Open Orders', value: 23, change: 15, trend: 'up', icon: '\u{1F6D2}' },
        { label: 'Monthly Revenue', value: 67400, prefix: '$', change: 11, trend: 'up', icon: '\u{1F4B0}' },
      ],
      columns: [
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'code', label: 'Code', sortable: true },
        { key: 'skus', label: 'SKUs', sortable: true },
        { key: 'openOrders', label: 'Open Orders', sortable: true },
        { key: 'balance', label: 'Balance', sortable: true },
        { key: 'paymentStatus', label: 'Payment', sortable: true },
      ],
      rows: [
        { customer: 'Mountain West Supplements', code: 'MWS-001', skus: 16, openOrders: 2, balance: '$4,847', paymentStatus: 'Current', autoPayEnabled: 'Yes', contractEnd: '2027-03-15', monthlyRevenue: '$7,240' },
        { customer: 'Rocky Mountain Nutrition', code: 'RMN-002', skus: 24, openOrders: 4, balance: '$12,340', paymentStatus: 'Late 15', autoPayEnabled: 'No', contractEnd: '2026-12-01', monthlyRevenue: '$11,200' },
        { customer: 'Peak Performance Labs', code: 'PPL-003', skus: 8, openOrders: 1, balance: '$0', paymentStatus: 'Current', autoPayEnabled: 'Yes', contractEnd: '2027-06-30', monthlyRevenue: '$3,890' },
        { customer: 'Frontier Health Co', code: 'FHC-004', skus: 31, openOrders: 5, balance: '$8,920', paymentStatus: 'Current', autoPayEnabled: 'No', contractEnd: '2026-09-15', monthlyRevenue: '$14,100' },
        { customer: 'Summit Retail Dist.', code: 'SRD-005', skus: 12, openOrders: 3, balance: '$22,470', paymentStatus: 'Late 30+', autoPayEnabled: 'No', contractEnd: '2026-07-01', monthlyRevenue: '$8,750' },
        { customer: 'Wasatch Wellness', code: 'WW-006', skus: 19, openOrders: 2, balance: '$3,100', paymentStatus: 'Current', autoPayEnabled: 'Yes', contractEnd: '2027-01-15', monthlyRevenue: '$6,420' },
        { customer: 'Alpine Supplements', code: 'ALS-007', skus: 6, openOrders: 1, balance: '$0', paymentStatus: 'Current', autoPayEnabled: 'Yes', contractEnd: '2027-09-01', monthlyRevenue: '$2,980' },
      ],
      expandedFields: ['autoPayEnabled', 'contractEnd', 'monthlyRevenue'],
      chart: {
        type: 'bar',
        title: 'Monthly Revenue by Customer',
        xKey: 'customer',
        dataKeys: ['storage', 'handling', 'shipping'],
        colors: ['#2A9D8F', '#F5920B', '#1B2A4A'],
        data: [
          { customer: 'MWS', storage: 2800, handling: 2940, shipping: 1500 },
          { customer: 'RMN', storage: 4200, handling: 4100, shipping: 2900 },
          { customer: 'PPL', storage: 1200, handling: 1690, shipping: 1000 },
          { customer: 'FHC', storage: 5400, handling: 5200, shipping: 3500 },
          { customer: 'SRD', storage: 3100, handling: 3150, shipping: 2500 },
          { customer: 'WW', storage: 2400, handling: 2520, shipping: 1500 },
          { customer: 'ALS', storage: 980, handling: 1200, shipping: 800 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Summit Retail Dist. is 30+ Days Late on $22,470', description: 'SRD-005 has an outstanding balance of $22,470 that is over 30 days past due. Their contract expires Jul 1 and auto-pay is not enabled. Consider escalating collections or requiring prepayment.', impact: 'Recover $22,470 and reduce DSO', action: 'View Account' },
        { priority: 'high', title: 'Enable Auto-Pay for Rocky Mountain Nutrition', description: 'RMN-002 is your second-largest customer at $11,200/mo but consistently pays 15 days late. Offering the 3% auto-pay discount would save you collections effort and guarantee on-time payment.', impact: 'Eliminate $12,340 late balance', action: 'Send Auto-Pay Invite' },
        { priority: 'medium', title: 'Frontier Health Contract Renewal in 6 Months', description: 'FHC-004 is your largest customer at $14,100/mo. Their contract ends Sep 15. Start renewal conversations early and consider a multi-year deal with volume pricing.', impact: 'Lock in $169K annual revenue', action: 'Prepare Renewal' },
        { priority: 'low', title: 'Onboard 3 Pending Prospects to Portal', description: 'You have 3 prospects in the sales pipeline who have requested portal demos. Activating their demo accounts could accelerate close rates.', impact: 'Potential $18K new MRR', action: 'Create Demo Accounts' },
      ],
      actions: [
        { label: 'Add Customer', description: 'Create a new customer account and portal login' },
        { label: 'Send Auto-Pay Invites', description: 'Invite customers without auto-pay to enroll for 3% discount' },
        { label: 'Generate Billing Report', description: 'AI summary of all customer balances, aging, and payment trends' },
        { label: 'Portal Health Check', description: 'Audit all customer portals for completeness and engagement' },
      ],
    },
    {
      id: 'billing',
      label: 'Billing',
      kpis: [
        { label: 'Total AR', value: 51677, prefix: '$', change: -4, trend: 'up', icon: '\u{1F4B3}' },
        { label: 'Auto-Pay Rate', value: 57, suffix: '%', change: 8, trend: 'up', icon: '\u{1F504}' },
        { label: 'Avg Days to Pay', value: 18, suffix: ' days', change: -12, trend: 'up', icon: '\u{23F1}\u{FE0F}' },
        { label: 'Past Due', value: 34810, prefix: '$', change: -6, trend: 'up', icon: '\u{26A0}\u{FE0F}' },
      ],
      columns: [
        { key: 'invoice', label: 'Invoice', sortable: true },
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'amount', label: 'Amount', sortable: true },
        { key: 'dueDate', label: 'Due Date', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { invoice: 'INV-2026-048', customer: 'Summit Retail Dist.', amount: '$22,470', dueDate: '2026-01-31', status: 'Overdue', daysLate: '32 days', autoPayEnabled: 'No' },
        { invoice: 'INV-2026-051', customer: 'Rocky Mountain Nutrition', amount: '$12,340', dueDate: '2026-02-15', status: 'Late 15', daysLate: '17 days', autoPayEnabled: 'No' },
        { invoice: 'INV-2026-055', customer: 'Frontier Health Co', amount: '$8,920', dueDate: '2026-03-15', status: 'Current', daysLate: '0 days', autoPayEnabled: 'No' },
        { invoice: 'INV-2026-056', customer: 'Mountain West Supplements', amount: '$4,847', dueDate: '2026-03-31', status: 'Current', daysLate: '0 days', autoPayEnabled: 'Yes' },
        { invoice: 'INV-2026-057', customer: 'Wasatch Wellness', amount: '$3,100', dueDate: '2026-03-31', status: 'Current', daysLate: '0 days', autoPayEnabled: 'Yes' },
      ],
      expandedFields: ['daysLate', 'autoPayEnabled'],
      chart: {
        type: 'bar',
        title: 'Payment Aging Distribution',
        xKey: 'bucket',
        dataKeys: ['amount'],
        colors: ['#2A9D8F'],
        data: [
          { bucket: 'Current', amount: 16867 },
          { bucket: '1-15 Days', amount: 0 },
          { bucket: '16-30 Days', amount: 12340 },
          { bucket: '31-60 Days', amount: 22470 },
          { bucket: '61+ Days', amount: 0 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Escalate Summit Retail Collections', description: 'SRD-005 owes $22,470 and is 32 days past due. This is above your 30-day threshold. Consider placing a hold on new orders until payment is received.', impact: 'Protect $22,470', action: 'Place Hold' },
        { priority: 'medium', title: 'Offer Early-Pay Discount to RMN', description: 'Rocky Mountain Nutrition has been consistently 15-17 days late. A 2% early-pay discount for payment within 10 days could shift their behavior.', impact: 'Improve DSO by 7 days', action: 'Send Offer' },
      ],
      actions: [
        { label: 'Generate Invoices', description: 'Create monthly invoices for all active customers' },
        { label: 'Send Payment Reminders', description: 'AI-drafted reminders to past-due accounts' },
      ],
    },
    {
      id: 'inventory',
      label: 'Inventory',
      kpis: [
        { label: 'Total Pallets', value: 342, change: 6, trend: 'up', icon: '\u{1F4E6}' },
        { label: 'Total SKUs', value: 116, change: 4, trend: 'up', icon: '\u{1F3F7}\u{FE0F}' },
        { label: 'Space Utilization', value: 78, suffix: '%', change: 3, trend: 'up', icon: '\u{1F3ED}' },
        { label: 'Items in QC', value: 4, change: -33, trend: 'up', icon: '\u{1F50D}' },
      ],
      columns: [
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'pallets', label: 'Pallets', sortable: true },
        { key: 'skus', label: 'SKUs', sortable: true },
        { key: 'units', label: 'Units', sortable: true },
        { key: 'zone', label: 'Zone', sortable: true },
      ],
      rows: [
        { customer: 'Mountain West Supplements', pallets: 47, skus: 16, units: 8240, zone: 'A/B', expiringWithin90: 2, holdItems: 0 },
        { customer: 'Rocky Mountain Nutrition', pallets: 82, skus: 24, units: 14200, zone: 'A/C', expiringWithin90: 4, holdItems: 1 },
        { customer: 'Peak Performance Labs', pallets: 18, skus: 8, units: 3100, zone: 'B', expiringWithin90: 0, holdItems: 0 },
        { customer: 'Frontier Health Co', pallets: 104, skus: 31, units: 18400, zone: 'A/B/C', expiringWithin90: 6, holdItems: 2 },
        { customer: 'Summit Retail Dist.', pallets: 38, skus: 12, units: 6800, zone: 'C', expiringWithin90: 1, holdItems: 0 },
        { customer: 'Wasatch Wellness', pallets: 34, skus: 19, units: 5900, zone: 'B', expiringWithin90: 3, holdItems: 0 },
        { customer: 'Alpine Supplements', pallets: 19, skus: 6, units: 3400, zone: 'A', expiringWithin90: 0, holdItems: 0 },
      ],
      expandedFields: ['expiringWithin90', 'holdItems'],
      chart: {
        type: 'area',
        title: 'Total Inventory Trend (12 Months)',
        xKey: 'month',
        dataKeys: ['pallets'],
        colors: ['#2A9D8F'],
        data: [
          { month: 'Apr', pallets: 280 },
          { month: 'May', pallets: 295 },
          { month: 'Jun', pallets: 288 },
          { month: 'Jul', pallets: 310 },
          { month: 'Aug', pallets: 325 },
          { month: 'Sep', pallets: 318 },
          { month: 'Oct', pallets: 332 },
          { month: 'Nov', pallets: 345 },
          { month: 'Dec', pallets: 360 },
          { month: 'Jan', pallets: 348 },
          { month: 'Feb', pallets: 335 },
          { month: 'Mar', pallets: 342 },
        ],
      },
      recommendations: [
        { priority: 'high', title: '16 Items Expiring Within 90 Days', description: 'Across all customers, 16 SKU/lot combinations expire within 90 days. Notify affected customers and recommend FIFO pick priority or disposal plans.', impact: 'Prevent $12K in spoilage', action: 'Send Alerts' },
        { priority: 'medium', title: 'Zone C Approaching Capacity', description: 'Zone C is at 92% utilization. Summit Retail and Frontier Health have the most pallets there. Consider rebalancing to Zone A which is at 64%.', impact: 'Prevent overflow fees', action: 'Rebalance Plan' },
      ],
      actions: [
        { label: 'Run Cycle Count', description: 'Schedule a cycle count for selected zones or customers' },
        { label: 'Expiration Report', description: 'Generate a full report of items expiring within 30/60/90 days' },
      ],
    },
  ],
});
