import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'cfo',
    name: 'CFO',
    icon: '\u{1F4B0}',
    dept: 'Finance',
    deptColor: '#059669',
    description: 'AI-powered financial oversight and cash flow optimization',
    valueProposition: 'See your complete financial picture and get AI recommendations to optimize cash flow',
    enabled: true,
    buildBatch: 1,
  },
  tabs: [
    {
      id: 'cash-flow',
      label: 'Cash Flow',
      kpis: [
        { label: 'Total Cash', value: 2400000, prefix: '$', change: 8, trend: 'up', icon: '\u{1F4B5}' },
        { label: 'AR Outstanding', value: 847000, prefix: '$', change: -12, trend: 'down', icon: '\u{1F4C9}' },
        { label: 'AP Due', value: 423000, prefix: '$', change: 0, trend: 'flat', icon: '\u{1F4CB}' },
        { label: 'Net 30-Day Flow', value: 124000, prefix: '+$', change: 14, trend: 'up', icon: '\u{1F4C8}' },
      ],
      columns: [
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'invoice', label: 'Invoice #', sortable: true },
        { key: 'amount', label: 'Amount', sortable: true },
        { key: 'daysOverdue', label: 'Days Overdue', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
        { key: 'lastContact', label: 'Last Contact', sortable: false },
      ],
      rows: [
        { customer: 'Apex Logistics', invoice: 'INV-2847', amount: 23400, daysOverdue: 45, status: 'Overdue', lastContact: 'Mar 12', invoiceHistory: '4 invoices, 2 late', paymentTerms: 'Net 30', contactInfo: 'james@apex.com', creditLimit: '$50,000' },
        { customer: 'Mountain West Supply', invoice: 'INV-2903', amount: 18700, daysOverdue: 0, status: 'Current', lastContact: 'Mar 18', invoiceHistory: '12 invoices, all on-time', paymentTerms: 'Net 45', contactInfo: 'billing@mws.com', creditLimit: '$75,000' },
        { customer: 'Redline Distribution', invoice: 'INV-2856', amount: 34200, daysOverdue: 32, status: '30', lastContact: 'Mar 5', invoiceHistory: '8 invoices, 3 late', paymentTerms: 'Net 30', contactInfo: 'ar@redline.io', creditLimit: '$60,000' },
        { customer: 'Summit Warehousing', invoice: 'INV-2921', amount: 12800, daysOverdue: 0, status: 'Current', lastContact: 'Mar 20', invoiceHistory: '6 invoices, all on-time', paymentTerms: 'Net 30', contactInfo: 'pay@summit.co', creditLimit: '$40,000' },
        { customer: 'Pacific Freight Co', invoice: 'INV-2789', amount: 67500, daysOverdue: 68, status: '60', lastContact: 'Feb 14', invoiceHistory: '15 invoices, 5 late', paymentTerms: 'Net 30', contactInfo: 'finance@pacfreight.com', creditLimit: '$100,000' },
        { customer: 'Cascade Materials', invoice: 'INV-2934', amount: 8900, daysOverdue: 12, status: 'Current', lastContact: 'Mar 15', invoiceHistory: '3 invoices, 0 late', paymentTerms: 'Net 30', contactInfo: 'ap@cascade.net', creditLimit: '$25,000' },
        { customer: 'Iron Ridge Metals', invoice: 'INV-2801', amount: 41300, daysOverdue: 94, status: '90+', lastContact: 'Jan 28', invoiceHistory: '10 invoices, 4 late', paymentTerms: 'Net 45', contactInfo: 'controller@ironridge.com', creditLimit: '$80,000' },
      ],
      expandedFields: ['invoiceHistory', 'paymentTerms', 'contactInfo', 'creditLimit'],
      chart: {
        type: 'area',
        title: '6-Month Cash Flow Trend',
        xKey: 'month',
        dataKeys: ['cash', 'ar', 'ap'],
        colors: ['#059669', '#F5920B', '#DC2626'],
        data: [
          { month: 'Jan', cash: 1800000, ar: 920000, ap: 380000 },
          { month: 'Feb', cash: 1950000, ar: 880000, ap: 410000 },
          { month: 'Mar', cash: 2100000, ar: 860000, ap: 440000 },
          { month: 'Apr', cash: 2050000, ar: 890000, ap: 400000 },
          { month: 'May', cash: 2300000, ar: 850000, ap: 430000 },
          { month: 'Jun', cash: 2400000, ar: 847000, ap: 423000 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Escalate Apex Logistics Collection', description: 'Apex Logistics is 45 days overdue on $23,400. Payment promise was broken twice. Recommend escalation to collections agency.', impact: '$23,400 recovery', action: 'Escalate Collection' },
        { priority: 'high', title: 'Capture Early Pay Discount', description: 'Vendor XYZ offers 2% discount for payment within 10 days. Discount expires Friday. Net savings after cost of capital.', impact: '$1,200 savings', action: 'Approve Early Payment' },
        { priority: 'medium', title: 'Defer Equipment Purchase', description: 'Cash reserves are below the 2-month operating threshold. Recommend deferring the $45K conveyor equipment purchase to Q3.', impact: 'Extends runway 3 weeks', action: 'Review Deferrals' },
        { priority: 'low', title: 'Consolidate Bank Accounts', description: 'Three operating accounts at different banks incur duplicate fees. Consolidating to one primary account saves $340/mo.', impact: '$4,080/yr savings', action: 'Start Consolidation' },
      ],
      actions: [
        { label: 'Generate Cash Flow Forecast', description: 'AI-powered 90-day cash flow projection using historical patterns and scheduled receivables' },
        { label: 'Export AR Report', description: 'Download a comprehensive aging report with customer risk scores and collection recommendations' },
        { label: 'Send Collection Emails', description: 'Auto-generate and send personalized collection emails to overdue accounts' },
        { label: 'Schedule Board Review', description: 'Prepare a board-ready financial summary with variance analysis and forecasts' },
      ],
    },
    {
      id: 'ar-aging',
      label: 'AR Aging',
      kpis: [
        { label: 'Current', value: 412000, prefix: '$', change: 5, trend: 'up', icon: '\u{2705}' },
        { label: '30-Day', value: 234000, prefix: '$', change: -8, trend: 'down', icon: '\u{1F7E1}' },
        { label: '60-Day', value: 142000, prefix: '$', change: 3, trend: 'up', icon: '\u{1F7E0}' },
        { label: '90+ Day', value: 59000, prefix: '$', change: -15, trend: 'down', icon: '\u{1F534}' },
      ],
      columns: [
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'current', label: 'Current', sortable: true },
        { key: 'thirty', label: '30 Day', sortable: true },
        { key: 'sixty', label: '60 Day', sortable: true },
        { key: 'ninety', label: '90+ Day', sortable: true },
        { key: 'total', label: 'Total', sortable: true },
      ],
      rows: [
        { customer: 'Apex Logistics', current: 0, thirty: 0, sixty: 0, ninety: 23400, total: 23400, riskScore: 'High', lastPayment: '62 days ago', collectionStatus: 'Escalated' },
        { customer: 'Redline Distribution', current: 8200, thirty: 34200, sixty: 0, ninety: 0, total: 42400, riskScore: 'Medium', lastPayment: '18 days ago', collectionStatus: 'In Progress' },
        { customer: 'Pacific Freight Co', current: 0, thirty: 0, sixty: 67500, ninety: 0, total: 67500, riskScore: 'High', lastPayment: '45 days ago', collectionStatus: 'Escalated' },
        { customer: 'Summit Warehousing', current: 12800, thirty: 0, sixty: 0, ninety: 0, total: 12800, riskScore: 'Low', lastPayment: '3 days ago', collectionStatus: 'Current' },
        { customer: 'Iron Ridge Metals', current: 0, thirty: 0, sixty: 0, ninety: 41300, total: 41300, riskScore: 'Critical', lastPayment: '94 days ago', collectionStatus: 'At Risk' },
        { customer: 'Mountain West Supply', current: 18700, thirty: 0, sixty: 0, ninety: 0, total: 18700, riskScore: 'Low', lastPayment: '5 days ago', collectionStatus: 'Current' },
        { customer: 'Cascade Materials', current: 8900, thirty: 0, sixty: 0, ninety: 0, total: 8900, riskScore: 'Low', lastPayment: '12 days ago', collectionStatus: 'Current' },
      ],
      expandedFields: ['riskScore', 'lastPayment', 'collectionStatus'],
      chart: {
        type: 'bar',
        title: 'AR Aging Distribution',
        xKey: 'bucket',
        dataKeys: ['amount'],
        colors: ['#059669'],
        data: [
          { bucket: 'Current', amount: 412000 },
          { bucket: '30 Day', amount: 234000 },
          { bucket: '60 Day', amount: 142000 },
          { bucket: '90+ Day', amount: 59000 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Iron Ridge Write-Off Risk', description: 'Iron Ridge Metals is 94 days overdue on $41,300. No response to last 3 contact attempts. Legal review recommended.', impact: '$41,300 at risk', action: 'Start Legal Review' },
        { priority: 'high', title: 'Pacific Freight Entering 90-Day', description: 'Pacific Freight $67,500 invoice crosses 90-day threshold in 22 days if no payment received.', impact: '$67,500 at risk', action: 'Schedule Call' },
        { priority: 'medium', title: 'Tighten Credit Terms', description: '3 customers with repeated late payments. Consider moving from Net 45 to Net 30 with late fees.', impact: 'Reduce aging 15%', action: 'Review Credit Policy' },
      ],
      actions: [
        { label: 'Generate Aging Report', description: 'Comprehensive AR aging report with risk scoring and trend analysis' },
        { label: 'Batch Collection Notices', description: 'Send automated collection notices to all overdue accounts' },
        { label: 'Update Credit Limits', description: 'AI-recommended credit limit adjustments based on payment history' },
      ],
    },
    {
      id: 'ap-overview',
      label: 'AP Overview',
      kpis: [
        { label: 'Total Payables', value: 423000, prefix: '$', change: 2, trend: 'up', icon: '\u{1F4E4}' },
        { label: 'Due This Week', value: 87000, prefix: '$', change: -5, trend: 'down', icon: '\u{1F4C5}' },
        { label: 'Discounts Available', value: 6200, prefix: '$', change: 12, trend: 'up', icon: '\u{1F3AF}' },
        { label: 'Overdue', value: 12000, prefix: '$', change: -22, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
      ],
      columns: [
        { key: 'vendor', label: 'Vendor', sortable: true },
        { key: 'invoice', label: 'Invoice', sortable: true },
        { key: 'amount', label: 'Amount', sortable: true },
        { key: 'dueDate', label: 'Due Date', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { vendor: 'DataFlow Systems', invoice: 'DF-4821', amount: 28400, dueDate: 'Mar 25', status: 'Pending', discount: '2% if paid by Mar 22', poMatch: 'Matched', approver: 'Steve M.' },
        { vendor: 'Acme Supply Co', invoice: 'AC-1147', amount: 14200, dueDate: 'Mar 28', status: 'Pending', discount: '1.5% if paid by Mar 24', poMatch: 'Matched', approver: 'Lisa R.' },
        { vendor: 'LogiParts Inc', invoice: 'LP-7834', amount: 42000, dueDate: 'Mar 22', status: 'Overdue', discount: 'None', poMatch: 'Partial match', approver: 'Needs review' },
        { vendor: 'TechServ Solutions', invoice: 'TS-2290', amount: 8700, dueDate: 'Apr 1', status: 'Scheduled', discount: 'None', poMatch: 'Matched', approver: 'Auto-approved' },
        { vendor: 'Warehouse Direct', invoice: 'WD-5563', amount: 19800, dueDate: 'Apr 5', status: 'Pending', discount: 'None', poMatch: 'Matched', approver: 'Steve M.' },
        { vendor: 'Quality Fasteners', invoice: 'QF-9012', amount: 6300, dueDate: 'Mar 20', status: 'Overdue', discount: 'Expired', poMatch: 'Matched', approver: 'Lisa R.' },
      ],
      expandedFields: ['discount', 'poMatch', 'approver'],
      chart: {
        type: 'stacked-bar',
        title: 'Upcoming Payments by Week',
        xKey: 'week',
        dataKeys: ['scheduled', 'pending', 'overdue'],
        colors: ['#059669', '#F5920B', '#DC2626'],
        data: [
          { week: 'This Week', scheduled: 42000, pending: 28400, overdue: 12000 },
          { week: 'Next Week', scheduled: 34000, pending: 19800, overdue: 0 },
          { week: 'Week 3', scheduled: 28000, pending: 8700, overdue: 0 },
          { week: 'Week 4', scheduled: 22000, pending: 14200, overdue: 0 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Resolve LogiParts PO Mismatch', description: 'Invoice LP-7834 for $42,000 only partially matches PO. $3,200 discrepancy needs vendor clarification before payment.', impact: 'Avoid $3,200 overpay', action: 'Contact Vendor' },
        { priority: 'medium', title: 'Capture Early Pay Discounts', description: 'Two invoices eligible for early payment discounts totaling $995. Payment deadlines within 5 days.', impact: '$995 savings', action: 'Schedule Early Payments' },
        { priority: 'low', title: 'Set Up Auto-Pay', description: 'TechServ Solutions has consistent monthly invoices under $10K. Auto-pay would save 2 hours/month of processing time.', impact: '24 hrs/yr saved', action: 'Configure Auto-Pay' },
      ],
      actions: [
        { label: 'Batch Approve Invoices', description: 'Review and approve multiple pending invoices in one workflow' },
        { label: 'Schedule Payments', description: 'Optimize payment timing to maximize cash position while meeting terms' },
        { label: 'Export AP Report', description: 'Download complete accounts payable report with aging and forecast' },
      ],
    },
    {
      id: 'ai-insights',
      label: 'AI Insights',
      kpis: [
        { label: 'Forecast Accuracy', value: 94, suffix: '%', change: 2, trend: 'up', icon: '\u{1F3AF}' },
        { label: 'Anomalies Detected', value: 3, change: -1, trend: 'down', icon: '\u{1F50D}' },
        { label: 'Savings Identified', value: 18400, prefix: '$', change: 24, trend: 'up', icon: '\u{1F4A1}' },
        { label: 'Reports Generated', value: 12, change: 8, trend: 'up', icon: '\u{1F4CA}' },
      ],
      columns: [
        { key: 'insight', label: 'Insight', sortable: true },
        { key: 'category', label: 'Category', sortable: true },
        { key: 'impact', label: 'Impact', sortable: true },
        { key: 'confidence', label: 'Confidence', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { insight: 'Cash flow dip predicted for April', category: 'Forecast', impact: '$84K shortfall', confidence: '92%', status: 'New', detail: 'Seasonal pattern plus 3 large invoices entering 60-day', recommendation: 'Accelerate collections on top 5 accounts', source: 'ML model v3.1' },
        { insight: 'Duplicate vendor payments detected', category: 'Anomaly', impact: '$2,100', confidence: '98%', status: 'Active', detail: 'DataFlow Systems billed twice for maintenance contract', recommendation: 'Issue credit memo request', source: 'Pattern matching' },
        { insight: 'Vendor consolidation opportunity', category: 'Savings', impact: '$6,400/yr', confidence: '85%', status: 'Open', detail: '4 vendors supply similar fastener products at varying prices', recommendation: 'Consolidate to Quality Fasteners for volume discount', source: 'Spend analysis' },
        { insight: 'Revenue recognition timing risk', category: 'Compliance', impact: 'Audit risk', confidence: '78%', status: 'Pending', detail: '2 projects with milestone billing may need revenue deferral', recommendation: 'Review with auditor before quarter close', source: 'Rule-based check' },
        { insight: 'Bank fee optimization available', category: 'Savings', impact: '$4,080/yr', confidence: '91%', status: 'Open', detail: 'Account consolidation and wire batch timing can reduce fees', recommendation: 'Switch to consolidated account structure', source: 'Fee analysis' },
      ],
      expandedFields: ['detail', 'recommendation', 'source'],
      chart: {
        type: 'pie',
        title: 'Savings by Category',
        dataKeys: ['value'],
        data: [
          { name: 'Vendor Consolidation', value: 6400 },
          { name: 'Early Pay Discounts', value: 4800 },
          { name: 'Bank Fee Reduction', value: 4080 },
          { name: 'Duplicate Prevention', value: 2100 },
          { name: 'Process Automation', value: 1020 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Act on April Cash Dip', description: 'Model predicts $84K cash shortfall in April with 92% confidence. Accelerate top 5 collections to bridge the gap.', impact: 'Prevent shortfall', action: 'Review Forecast' },
        { priority: 'high', title: 'Recover Duplicate Payment', description: 'DataFlow Systems billed $2,100 twice for the same maintenance contract. Request credit memo immediately.', impact: '$2,100 recovery', action: 'Issue Credit Request' },
        { priority: 'medium', title: 'Start Vendor Consolidation', description: 'Analysis shows 4 fastener vendors can be consolidated for volume pricing. Estimated annual savings of $6,400.', impact: '$6,400/yr savings', action: 'Begin RFP Process' },
      ],
      actions: [
        { label: 'Generate Financial Report', description: 'AI-compiled monthly financial summary with insights and action items' },
        { label: 'Run Anomaly Scan', description: 'Deep scan of transactions for duplicates, outliers, and compliance risks' },
        { label: 'Export Savings Plan', description: 'Download prioritized savings opportunities with implementation timeline' },
      ],
    },
  ],
});
