import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'collections',
    name: 'Collections',
    icon: '\u{1F4B3}',
    dept: 'Finance',
    deptColor: '#059669',
    description: 'AI-powered accounts receivable collection automation',
    valueProposition: 'Recover outstanding payments faster with AI-prioritized collection workflows',
    enabled: true,
    buildBatch: 1,
  },
  tabs: [
    {
      id: 'active-collections',
      label: 'Active Collections',
      kpis: [
        { label: 'Total Outstanding', value: 1200000, prefix: '$', change: -4, trend: 'down', icon: '\u{1F4B0}' },
        { label: 'Collection Rate', value: 87, suffix: '%', change: 3, trend: 'up', icon: '\u{1F4C8}' },
        { label: 'Avg Days to Pay', value: 34, change: -5, trend: 'down', icon: '\u{23F1}\u{FE0F}' },
        { label: 'Overdue Accounts', value: 23, change: -3, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
      ],
      columns: [
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'outstanding', label: 'Outstanding', sortable: true },
        { key: 'daysOverdue', label: 'Days Overdue', sortable: true },
        { key: 'lastContact', label: 'Last Contact', sortable: true },
        { key: 'nextAction', label: 'Next Action', sortable: false },
        { key: 'riskScore', label: 'Risk Score', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { customer: 'ABC Corporation', outstanding: 47200, daysOverdue: 92, lastContact: 'Feb 28', nextAction: 'Final notice', riskScore: 94, status: 'Critical', contactHistory: '6 calls, 2 emails, 1 letter', paymentPromise: 'Broken twice', escalationLog: 'Sent to collections mgr Mar 1' },
        { customer: 'XYZ Ltd', outstanding: 12400, daysOverdue: 67, lastContact: 'Mar 8', nextAction: 'Settlement offer', riskScore: 72, status: 'At Risk', contactHistory: '4 calls, 3 emails', paymentPromise: 'Promised Mar 15, missed', escalationLog: 'Tier 2 escalation' },
        { customer: 'Metro Systems', outstanding: 28900, daysOverdue: 34, lastContact: 'Mar 14', nextAction: 'Follow-up call', riskScore: 45, status: 'In Progress', contactHistory: '2 calls, 1 email', paymentPromise: 'Partial payment Mar 20', escalationLog: 'None' },
        { customer: 'Pinnacle Group', outstanding: 8700, daysOverdue: 18, lastContact: 'Mar 18', nextAction: 'Reminder email', riskScore: 22, status: 'Pending', contactHistory: '1 email', paymentPromise: 'None yet', escalationLog: 'None' },
        { customer: 'Vanguard Shipping', outstanding: 63400, daysOverdue: 55, lastContact: 'Mar 2', nextAction: 'Manager call', riskScore: 78, status: 'At Risk', contactHistory: '5 calls, 4 emails', paymentPromise: 'Dispute on 2 invoices', escalationLog: 'Dispute resolution in progress' },
        { customer: 'NorthStar Industries', outstanding: 19200, daysOverdue: 42, lastContact: 'Mar 10', nextAction: 'Payment plan', riskScore: 56, status: 'In Progress', contactHistory: '3 calls, 2 emails', paymentPromise: 'Requested 3-month plan', escalationLog: 'None' },
        { customer: 'Clearwater Logistics', outstanding: 5600, daysOverdue: 12, lastContact: 'Mar 19', nextAction: 'Auto-reminder', riskScore: 12, status: 'Pending', contactHistory: '1 auto-email', paymentPromise: 'N/A', escalationLog: 'None' },
      ],
      expandedFields: ['contactHistory', 'paymentPromise', 'escalationLog'],
      chart: {
        type: 'bar',
        title: 'Outstanding by Aging Bucket',
        xKey: 'bucket',
        dataKeys: ['amount'],
        colors: ['#059669'],
        data: [
          { bucket: 'Current', amount: 284000 },
          { bucket: '1-30 Days', amount: 312000 },
          { bucket: '31-60 Days', amount: 248000 },
          { bucket: '61-90 Days', amount: 198000 },
          { bucket: '90+ Days', amount: 158000 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Call ABC Corporation', description: 'ABC Corp owes $47,200 at 92 days. Two broken payment promises. Write-off risk is high without immediate escalation.', impact: '$47,200 at risk', action: 'Escalate to Legal' },
        { priority: 'high', title: 'Settlement Offer for XYZ Ltd', description: 'XYZ Ltd owes $12,400 at 67 days. Offering a 5% settlement discount could recover $11,780 this month.', impact: '$11,780 recovery', action: 'Send Settlement Offer' },
        { priority: 'medium', title: 'Auto-Schedule Follow-Ups', description: '8 accounts entering the 60-day bucket this week. Schedule automated follow-up sequences to prevent further aging.', impact: 'Prevent $124K aging', action: 'Schedule Follow-Ups' },
        { priority: 'low', title: 'Send Batch Reminders', description: '14 accounts at 25 days with no prior contact. Friendly reminder emails have 34% response rate at this stage.', impact: '5 expected payments', action: 'Send Reminders' },
      ],
      actions: [
        { label: 'Auto-Schedule Follow-Ups', description: 'Set up automated follow-up sequences based on AI-optimized timing' },
        { label: 'Generate Collection Letters', description: 'Create personalized collection letters with escalating urgency levels' },
        { label: 'Export Aging Report', description: 'Download complete aging report with risk scores and recommended actions' },
        { label: 'Batch Send Reminders', description: 'Send customized payment reminders to all accounts in a specific aging bucket' },
      ],
    },
    {
      id: 'aging-buckets',
      label: 'Aging Buckets',
      kpis: [
        { label: 'Current', value: 284000, prefix: '$', change: 12, trend: 'up', icon: '\u{2705}' },
        { label: '30-Day', value: 312000, prefix: '$', change: -6, trend: 'down', icon: '\u{1F7E1}' },
        { label: '60-Day', value: 248000, prefix: '$', change: -3, trend: 'down', icon: '\u{1F7E0}' },
        { label: '90+ Day', value: 158000, prefix: '$', change: -18, trend: 'down', icon: '\u{1F534}' },
      ],
      columns: [
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'bucket', label: 'Bucket', sortable: true },
        { key: 'amount', label: 'Amount', sortable: true },
        { key: 'invoiceCount', label: 'Invoices', sortable: true },
        { key: 'trend', label: 'Trend', sortable: true },
      ],
      rows: [
        { customer: 'ABC Corporation', bucket: '90+', amount: 47200, invoiceCount: 3, trend: 'Worsening', avgPayDays: 78, lastPayment: '$0 in 90 days' },
        { customer: 'Vanguard Shipping', bucket: '60', amount: 63400, invoiceCount: 4, trend: 'Stable', avgPayDays: 52, lastPayment: '$12K partial' },
        { customer: 'Metro Systems', bucket: '30', amount: 28900, invoiceCount: 2, trend: 'Improving', avgPayDays: 38, lastPayment: '$8K last week' },
        { customer: 'NorthStar Industries', bucket: '30', amount: 19200, invoiceCount: 1, trend: 'Stable', avgPayDays: 44, lastPayment: 'Payment plan requested' },
        { customer: 'XYZ Ltd', bucket: '60', amount: 12400, invoiceCount: 1, trend: 'Worsening', avgPayDays: 61, lastPayment: 'None' },
        { customer: 'Pinnacle Group', bucket: 'Current', amount: 8700, invoiceCount: 1, trend: 'New', avgPayDays: 18, lastPayment: 'First invoice' },
      ],
      expandedFields: ['avgPayDays', 'lastPayment'],
      chart: {
        type: 'stacked-bar',
        title: 'Aging Bucket Trend (6 Months)',
        xKey: 'month',
        dataKeys: ['current', 'thirty', 'sixty', 'ninety'],
        colors: ['#059669', '#F5920B', '#EA580C', '#DC2626'],
        data: [
          { month: 'Jan', current: 220000, thirty: 340000, sixty: 280000, ninety: 210000 },
          { month: 'Feb', current: 240000, thirty: 330000, sixty: 270000, ninety: 190000 },
          { month: 'Mar', current: 260000, thirty: 320000, sixty: 260000, ninety: 175000 },
          { month: 'Apr', current: 270000, thirty: 318000, sixty: 255000, ninety: 168000 },
          { month: 'May', current: 278000, thirty: 315000, sixty: 250000, ninety: 162000 },
          { month: 'Jun', current: 284000, thirty: 312000, sixty: 248000, ninety: 158000 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Aging Trend Improving', description: '90+ day bucket decreased 25% over 6 months. Continue aggressive collection on remaining accounts to maintain trajectory.', impact: 'Maintain $52K reduction', action: 'View Strategy' },
        { priority: 'medium', title: 'Watch 30-Day Growth', description: 'Current bucket grew 29% but 30-day bucket only shrank 8%. Some current accounts may age quickly.', impact: 'Prevent $28K aging', action: 'Set Alerts' },
      ],
      actions: [
        { label: 'Generate Trend Report', description: 'Historical aging analysis with predictive modeling for next quarter' },
        { label: 'Set Bucket Alerts', description: 'Automated alerts when accounts cross aging thresholds' },
        { label: 'Export Bucket Detail', description: 'Detailed breakdown of all accounts by aging bucket' },
      ],
    },
    {
      id: 'follow-up-queue',
      label: 'Follow-Up Queue',
      kpis: [
        { label: 'Overdue Follow-Ups', value: 8, change: -2, trend: 'down', icon: '\u{1F4DE}' },
        { label: 'Scheduled Today', value: 12, change: 4, trend: 'up', icon: '\u{1F4C5}' },
        { label: 'Completed This Week', value: 34, change: 8, trend: 'up', icon: '\u{2705}' },
        { label: 'Avg Response Rate', value: 42, suffix: '%', change: 6, trend: 'up', icon: '\u{1F4CA}' },
      ],
      columns: [
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'type', label: 'Type', sortable: true },
        { key: 'scheduledDate', label: 'Scheduled', sortable: true },
        { key: 'amount', label: 'Amount at Stake', sortable: true },
        { key: 'priority', label: 'Priority', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { customer: 'ABC Corporation', type: 'Phone Call', scheduledDate: 'Today 10AM', amount: 47200, priority: 'Critical', status: 'Overdue', assignee: 'Mike T.', notes: 'Final attempt before legal' },
        { customer: 'Vanguard Shipping', type: 'Email', scheduledDate: 'Today 2PM', amount: 63400, priority: 'High', status: 'Scheduled', assignee: 'Sarah L.', notes: 'Dispute resolution follow-up' },
        { customer: 'Metro Systems', type: 'Phone Call', scheduledDate: 'Tomorrow 9AM', amount: 28900, priority: 'Medium', status: 'Scheduled', assignee: 'Mike T.', notes: 'Confirm partial payment received' },
        { customer: 'NorthStar Industries', type: 'Email', scheduledDate: 'Today 4PM', amount: 19200, priority: 'Medium', status: 'Scheduled', assignee: 'Sarah L.', notes: 'Payment plan proposal' },
        { customer: 'XYZ Ltd', type: 'Phone Call', scheduledDate: 'Overdue', amount: 12400, priority: 'High', status: 'Overdue', assignee: 'Mike T.', notes: 'Settlement discussion' },
      ],
      expandedFields: ['assignee', 'notes'],
      chart: {
        type: 'area',
        title: 'Follow-Up Completion Rate',
        xKey: 'week',
        dataKeys: ['completed', 'scheduled'],
        colors: ['#059669', '#E5E7EB'],
        data: [
          { week: 'W1', completed: 22, scheduled: 28 },
          { week: 'W2', completed: 26, scheduled: 30 },
          { week: 'W3', completed: 30, scheduled: 32 },
          { week: 'W4', completed: 34, scheduled: 36 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Clear Overdue Follow-Ups', description: '8 follow-ups are past their scheduled date. Delays beyond 48 hours reduce collection probability by 23%.', impact: '+23% collection rate', action: 'Reschedule Now' },
        { priority: 'medium', title: 'Optimize Call Times', description: 'Data shows 62% higher answer rate for calls between 10-11AM Tuesday-Thursday. Shift scheduling accordingly.', impact: '+18% contact rate', action: 'Update Schedule' },
      ],
      actions: [
        { label: 'Auto-Reschedule Overdue', description: 'Move all overdue follow-ups to optimal time slots this week' },
        { label: 'Generate Call Scripts', description: 'AI-crafted scripts personalized to each account situation' },
        { label: 'Export Queue', description: 'Download prioritized follow-up queue for the team' },
      ],
    },
    {
      id: 'performance',
      label: 'Performance',
      kpis: [
        { label: 'Calls Made', value: 186, change: 12, trend: 'up', icon: '\u{1F4DE}' },
        { label: 'Promises to Pay', value: 23, change: 8, trend: 'up', icon: '\u{1F91D}' },
        { label: 'Dollars Recovered', value: 234000, prefix: '$', change: 18, trend: 'up', icon: '\u{1F4B0}' },
        { label: 'Recovery Rate', value: 87, suffix: '%', change: 3, trend: 'up', icon: '\u{1F3AF}' },
      ],
      columns: [
        { key: 'rep', label: 'Rep', sortable: true },
        { key: 'callsMade', label: 'Calls', sortable: true },
        { key: 'promises', label: 'Promises', sortable: true },
        { key: 'recovered', label: 'Recovered', sortable: true },
        { key: 'rate', label: 'Rate', sortable: true },
      ],
      rows: [
        { rep: 'Mike Thompson', callsMade: 98, promises: 14, recovered: 142000, rate: '91%', avgCallTime: '4.2 min', topAccount: 'Vanguard Shipping', improvement: '+12% vs last month' },
        { rep: 'Sarah Lin', callsMade: 88, promises: 9, recovered: 92000, rate: '83%', avgCallTime: '3.8 min', topAccount: 'Metro Systems', improvement: '+8% vs last month' },
      ],
      expandedFields: ['avgCallTime', 'topAccount', 'improvement'],
      chart: {
        type: 'line',
        title: 'Monthly Recovery Rate',
        xKey: 'month',
        dataKeys: ['rate'],
        colors: ['#059669'],
        data: [
          { month: 'Jan', rate: 78 },
          { month: 'Feb', rate: 81 },
          { month: 'Mar', rate: 83 },
          { month: 'Apr', rate: 84 },
          { month: 'May', rate: 85 },
          { month: 'Jun', rate: 87 },
        ],
      },
      recommendations: [
        { priority: 'high', title: "Replicate Mike's Approach", description: "Mike's recovery rate is 8 points above team average. His discovery call script has a 64% promise-to-pay conversion.", impact: '+8% team improvement', action: 'Share Best Practices' },
        { priority: 'medium', title: 'Increase Call Volume', description: 'Team averages 93 calls/rep/month vs 120 industry benchmark. Adding 27 calls could yield $48K in additional recovery.', impact: '$48K additional', action: 'Adjust Targets' },
      ],
      actions: [
        { label: 'Generate Performance Report', description: 'Detailed rep-by-rep analysis with benchmarks and improvement areas' },
        { label: 'Schedule Coaching', description: 'AI-recommended coaching sessions based on performance gaps' },
        { label: 'Export Metrics', description: 'Download all collection KPIs and performance data' },
      ],
    },
  ],
});
