import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'compliance',
    name: 'Compliance',
    icon: '\u{1F6E1}\u{FE0F}',
    dept: 'Legal',
    deptColor: '#7C3AED',
    description: 'AI-powered regulatory compliance monitoring and audit management',
    valueProposition: 'Stay ahead of regulations, automate audits, and maintain certifications effortlessly',
    enabled: true,
    buildBatch: 3,
  },
  tabs: [
    {
      id: 'dashboard',
      label: 'Compliance Dashboard',
      kpis: [
        { label: 'Overall Score', value: 87, suffix: '/100', change: 4, trend: 'up', icon: '\u{1F3AF}' },
        { label: 'Open Findings', value: 12, change: -5, trend: 'down', icon: '\u{1F50D}' },
        { label: 'Certifications', value: 6, change: 1, trend: 'up', icon: '\u{2705}' },
        { label: 'Next Audit', value: 0, suffix: '', change: 0, trend: 'flat', icon: '\u{1F4C5}' },
      ],
      columns: [
        { key: 'framework', label: 'Framework', sortable: true },
        { key: 'scope', label: 'Scope', sortable: true },
        { key: 'score', label: 'Score', sortable: true },
        { key: 'findings', label: 'Findings', sortable: true },
        { key: 'lastAudit', label: 'Last Audit', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { framework: 'SOC 2 Type II', scope: 'Platform & Data', score: '92/100', findings: 2, lastAudit: 'Dec 2025', status: 'Certified', nextAudit: 'Dec 2026', auditor: 'Deloitte', gaps: 'Access review frequency' },
        { framework: 'OSHA', scope: 'Warehouse Operations', score: '88/100', findings: 4, lastAudit: 'Jan 2026', status: 'Certified', nextAudit: 'Jul 2026', auditor: 'Internal + State', gaps: 'Zone C fire exit, forklift training docs' },
        { framework: 'GDPR', scope: 'EU Customer Data', score: '84/100', findings: 3, lastAudit: 'Nov 2025', status: 'Active', nextAudit: 'Nov 2026', auditor: 'PwC', gaps: 'Data deletion SLA, privacy notice update' },
        { framework: 'PCI DSS', scope: 'Payment Processing', score: '90/100', findings: 1, lastAudit: 'Feb 2026', status: 'Certified', nextAudit: 'Feb 2027', auditor: 'QSA Partner', gaps: 'Encryption key rotation schedule' },
        { framework: 'ISO 27001', scope: 'Information Security', score: '78/100', findings: 5, lastAudit: 'Oct 2025', status: 'In Progress', nextAudit: 'Apr 2026', auditor: 'BSI', gaps: 'ISMS documentation, incident playbooks' },
        { framework: 'DOT/FMCSA', scope: 'Fleet & Transport', score: '94/100', findings: 1, lastAudit: 'Mar 2026', status: 'Certified', nextAudit: 'Mar 2027', auditor: 'State DOT', gaps: 'Driver log formatting' },
      ],
      expandedFields: ['nextAudit', 'auditor', 'gaps'],
      chart: {
        type: 'bar',
        title: 'Compliance Score by Framework',
        xKey: 'framework',
        dataKeys: ['score'],
        colors: ['#7C3AED'],
        data: [
          { framework: 'DOT', score: 94 },
          { framework: 'SOC 2', score: 92 },
          { framework: 'PCI', score: 90 },
          { framework: 'OSHA', score: 88 },
          { framework: 'GDPR', score: 84 },
          { framework: 'ISO 27001', score: 78 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'ISO 27001 Audit in 30 Days', description: 'ISO 27001 certification audit is Apr 2026 and score is 78/100. 5 open findings need closure, especially ISMS documentation.', impact: 'Certification at risk', action: 'View Remediation Plan' },
        { priority: 'high', title: 'GDPR Deletion SLA Breach', description: 'Customer data deletion request exceeded 30-day SLA. This is a reportable violation. Implement automated deletion workflow.', impact: 'Regulatory exposure', action: 'Resolve Immediately' },
        { priority: 'medium', title: 'OSHA Zone C Remediation', description: 'Fire exit reroute in Zone C flagged during Jan audit. Construction scheduled but not completed.', impact: 'Safety compliance', action: 'Check Progress' },
      ],
      actions: [
        { label: 'Run Compliance Scan', description: 'AI-powered gap analysis across all active frameworks' },
        { label: 'Generate Board Report', description: 'Executive compliance summary with risk indicators and trends' },
        { label: 'Schedule Audit', description: 'Plan and prepare for upcoming internal or external audits' },
        { label: 'Export Compliance Matrix', description: 'Download cross-framework compliance status and control mapping' },
      ],
    },
    {
      id: 'findings',
      label: 'Findings',
      kpis: [
        { label: 'Open', value: 12, change: -5, trend: 'down', icon: '\u{1F534}' },
        { label: 'In Remediation', value: 8, change: 2, trend: 'up', icon: '\u{1F7E1}' },
        { label: 'Closed (Quarter)', value: 18, change: 8, trend: 'up', icon: '\u{2705}' },
        { label: 'Avg Close Time', value: 22, suffix: ' days', change: -14, trend: 'down', icon: '\u{23F1}\u{FE0F}' },
      ],
      columns: [
        { key: 'finding', label: 'Finding', sortable: true },
        { key: 'framework', label: 'Framework', sortable: true },
        { key: 'severity', label: 'Severity', sortable: true },
        { key: 'owner', label: 'Owner', sortable: true },
        { key: 'dueDate', label: 'Due', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { finding: 'ISMS policy documentation incomplete', framework: 'ISO 27001', severity: 'High', owner: 'CISO', dueDate: 'Mar 28', status: 'In Progress', rootCause: 'Rapid growth outpaced documentation', remediation: 'Draft 8 remaining policies' },
        { finding: 'Data deletion SLA exceeded', framework: 'GDPR', severity: 'Critical', owner: 'Engineering', dueDate: 'Overdue', status: 'Open', rootCause: 'Manual process, no automation', remediation: 'Build automated deletion pipeline' },
        { finding: 'Forklift training records gap', framework: 'OSHA', severity: 'Medium', owner: 'HR', dueDate: 'Apr 5', status: 'In Progress', rootCause: '2 new hires missing certification', remediation: 'Schedule training by Mar 28' },
        { finding: 'Encryption key rotation overdue', framework: 'PCI DSS', severity: 'Medium', owner: 'DevOps', dueDate: 'Mar 25', status: 'In Progress', rootCause: 'Annual rotation missed by 2 weeks', remediation: 'Rotate and automate schedule' },
        { finding: 'Access reviews not quarterly', framework: 'SOC 2', severity: 'Low', owner: 'IT Admin', dueDate: 'Apr 15', status: 'Open', rootCause: 'Process defined but not enforced', remediation: 'Set up automated review triggers' },
        { finding: 'Incident response playbook outdated', framework: 'ISO 27001', severity: 'High', owner: 'CISO', dueDate: 'Apr 1', status: 'Open', rootCause: 'Last updated 18 months ago', remediation: 'Update and run tabletop exercise' },
      ],
      expandedFields: ['rootCause', 'remediation'],
      chart: {
        type: 'stacked-bar',
        title: 'Findings Trend (6 Months)',
        xKey: 'month',
        dataKeys: ['opened', 'closed'],
        colors: ['#DC2626', '#059669'],
        data: [
          { month: 'Jan', opened: 6, closed: 4 },
          { month: 'Feb', opened: 4, closed: 5 },
          { month: 'Mar', opened: 3, closed: 6 },
          { month: 'Apr', opened: 5, closed: 7 },
          { month: 'May', opened: 2, closed: 5 },
          { month: 'Jun', opened: 3, closed: 4 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'GDPR Finding Overdue', description: 'Data deletion SLA finding is past due. This exposes the company to regulatory penalties. Prioritize engineering resources.', impact: 'Regulatory penalty risk', action: 'Escalate to CTO' },
        { priority: 'high', title: 'ISO Findings Before Audit', description: '5 ISO 27001 findings must be closed before April audit. 2 are high severity. Assign dedicated resources.', impact: 'Certification at risk', action: 'Create Sprint Plan' },
      ],
      actions: [
        { label: 'Create Finding', description: 'Document a new compliance finding with severity assessment' },
        { label: 'Assign Remediation', description: 'Route findings to owners with due dates and tracking' },
        { label: 'Export Findings', description: 'Download finding register with remediation status' },
      ],
    },
    {
      id: 'policies',
      label: 'Policies',
      kpis: [
        { label: 'Total Policies', value: 34, change: 4, trend: 'up', icon: '\u{1F4DA}' },
        { label: 'Current', value: 28, change: 6, trend: 'up', icon: '\u{2705}' },
        { label: 'Needs Review', value: 6, change: -2, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
        { label: 'Acknowledgment %', value: 86, suffix: '%', change: 8, trend: 'up', icon: '\u{1F4DD}' },
      ],
      columns: [
        { key: 'policy', label: 'Policy', sortable: true },
        { key: 'category', label: 'Category', sortable: true },
        { key: 'version', label: 'Version', sortable: true },
        { key: 'lastReview', label: 'Last Review', sortable: true },
        { key: 'acknowledged', label: 'Ack %', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { policy: 'Information Security Policy', category: 'Security', version: 'v3.2', lastReview: 'Feb 2026', acknowledged: '92%', status: 'Current', owner: 'CISO', nextReview: 'Aug 2026' },
        { policy: 'Acceptable Use Policy', category: 'IT', version: 'v2.1', lastReview: 'Jan 2026', acknowledged: '88%', status: 'Current', owner: 'IT Director', nextReview: 'Jul 2026' },
        { policy: 'Data Retention Policy', category: 'Privacy', version: 'v1.4', lastReview: 'Sep 2025', acknowledged: '76%', status: 'Review Due', owner: 'Legal', nextReview: 'Overdue' },
        { policy: 'Anti-Harassment Policy', category: 'HR', version: 'v4.0', lastReview: 'Dec 2025', acknowledged: '94%', status: 'Current', owner: 'HR Director', nextReview: 'Dec 2026' },
        { policy: 'Vendor Security Policy', category: 'Procurement', version: 'v1.0', lastReview: 'Never', acknowledged: '44%', status: 'Draft', owner: 'Legal', nextReview: 'New policy' },
      ],
      expandedFields: ['owner', 'nextReview'],
      chart: {
        type: 'bar',
        title: 'Policy Acknowledgment by Category',
        xKey: 'category',
        dataKeys: ['rate'],
        colors: ['#7C3AED'],
        data: [
          { category: 'HR', rate: 94 },
          { category: 'Security', rate: 92 },
          { category: 'IT', rate: 88 },
          { category: 'Privacy', rate: 76 },
          { category: 'Procurement', rate: 44 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Data Retention Policy Overdue', description: 'Data Retention Policy has not been reviewed since Sep 2025. GDPR requires annual review. Update immediately.', impact: 'GDPR compliance', action: 'Start Review' },
        { priority: 'medium', title: 'Vendor Security Policy Incomplete', description: 'New Vendor Security Policy is still in draft at 44% acknowledgment. Finalize and distribute to all procurement staff.', impact: 'Reduce vendor risk', action: 'Finalize Policy' },
      ],
      actions: [
        { label: 'Create Policy', description: 'Draft a new policy from AI-generated templates' },
        { label: 'Send Acknowledgments', description: 'Distribute policies requiring employee acknowledgment' },
        { label: 'Export Policy Register', description: 'Download all policies with review dates and acknowledgment rates' },
      ],
    },
    {
      id: 'training-compliance',
      label: 'Training',
      kpis: [
        { label: 'Completion Rate', value: 82, suffix: '%', change: 6, trend: 'up', icon: '\u{1F393}' },
        { label: 'Overdue', value: 14, change: -4, trend: 'down', icon: '\u{1F534}' },
        { label: 'Courses Active', value: 8, change: 2, trend: 'up', icon: '\u{1F4DA}' },
        { label: 'Avg Score', value: 88, suffix: '%', change: 3, trend: 'up', icon: '\u{1F3AF}' },
      ],
      columns: [
        { key: 'course', label: 'Course', sortable: true },
        { key: 'required', label: 'Required', sortable: true },
        { key: 'completed', label: 'Completed', sortable: true },
        { key: 'overdue', label: 'Overdue', sortable: true },
        { key: 'avgScore', label: 'Avg Score', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { course: 'Security Awareness', required: 127, completed: 112, overdue: 6, avgScore: '91%', status: 'Active', frequency: 'Annual', dueDate: 'Mar 31' },
        { course: 'OSHA Safety', required: 48, completed: 44, overdue: 4, avgScore: '87%', status: 'Active', frequency: 'Annual', dueDate: 'Apr 15' },
        { course: 'Anti-Harassment', required: 127, completed: 118, overdue: 2, avgScore: '94%', status: 'Active', frequency: 'Annual', dueDate: 'Dec 31' },
        { course: 'Data Privacy (GDPR)', required: 84, completed: 72, overdue: 3, avgScore: '82%', status: 'Active', frequency: 'Annual', dueDate: 'Apr 30' },
        { course: 'Forklift Certification', required: 24, completed: 22, overdue: 2, avgScore: '88%', status: 'Active', frequency: 'Biennial', dueDate: 'Varies' },
      ],
      expandedFields: ['frequency', 'dueDate'],
      chart: {
        type: 'line',
        title: 'Training Completion Trend',
        xKey: 'month',
        dataKeys: ['rate'],
        colors: ['#7C3AED'],
        data: [
          { month: 'Jan', rate: 68 },
          { month: 'Feb', rate: 72 },
          { month: 'Mar', rate: 76 },
          { month: 'Apr', rate: 78 },
          { month: 'May', rate: 80 },
          { month: 'Jun', rate: 82 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Security Training Due Mar 31', description: '15 employees have not completed required security awareness training. Deadline is 8 days away.', impact: 'SOC 2 compliance', action: 'Send Reminders' },
        { priority: 'medium', title: 'GDPR Training Low Score', description: 'Average score of 82% on GDPR training is below 85% target. Add supplemental module on data rights.', impact: 'Improve comprehension', action: 'Update Course' },
      ],
      actions: [
        { label: 'Send Reminders', description: 'Batch-send training reminders to employees with overdue courses' },
        { label: 'Generate Training Report', description: 'Compliance training status by department and course' },
        { label: 'Export Certifications', description: 'Download employee training records and certification dates' },
      ],
    },
  ],
});
