import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'finops',
    name: 'FinOps',
    icon: '💸',
    dept: 'Finance',
    deptColor: '#059669',
    description: 'AI-powered financial operations and spend optimization',
    valueProposition: 'Track every dollar, optimize vendor spend, and automate financial workflows',
    enabled: true,
    buildBatch: 2,
  },
  tabs: [
    {
      id: 'spend-overview',
      label: 'Spend Overview',
      kpis: [
        { label: 'Monthly Spend', value: 284000, prefix: '$', change: -4, trend: 'down', icon: '💰' },
        { label: 'Budget Variance', value: -3.2, suffix: '%', change: 2, trend: 'up', icon: '📊' },
        { label: 'Savings Found', value: 42000, prefix: '$', change: 18, trend: 'up', icon: '💡' },
        { label: 'Vendor Count', value: 87, change: -3, trend: 'down', icon: '📋' },
      ],
      columns: [
        { key: 'category', label: 'Category', sortable: true },
        { key: 'budget', label: 'Budget', sortable: true },
        { key: 'actual', label: 'Actual', sortable: true },
        { key: 'variance', label: 'Variance', sortable: true },
        { key: 'trend', label: 'Trend', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { category: 'Cloud Infrastructure', budget: 48000, actual: 52400, variance: '+9.2%', trend: 'Rising', status: 'Over', topVendor: 'AWS ($38K)', optimizationOpp: 'Right-size 12 idle instances' },
        { category: 'Software Licenses', budget: 34000, actual: 31200, variance: '-8.2%', trend: 'Stable', status: 'Under', topVendor: 'Salesforce ($12K)', optimizationOpp: 'Remove 8 unused seats' },
        { category: 'Logistics & Shipping', budget: 82000, actual: 79400, variance: '-3.2%', trend: 'Falling', status: 'On Track', topVendor: 'UPS ($42K)', optimizationOpp: 'Consolidate to 2 carriers' },
        { category: 'Equipment & Parts', budget: 45000, actual: 47800, variance: '+6.2%', trend: 'Rising', status: 'Over', topVendor: 'Grainger ($18K)', optimizationOpp: 'Bulk order Q3 parts now' },
        { category: 'Payroll & Benefits', budget: 156000, actual: 154200, variance: '-1.2%', trend: 'Stable', status: 'On Track', topVendor: 'ADP ($4.2K)', optimizationOpp: 'None identified' },
        { category: 'Facilities', budget: 28000, actual: 26800, variance: '-4.3%', trend: 'Stable', status: 'Under', topVendor: 'Utility Co ($8K)', optimizationOpp: 'LED retrofit saves $340/mo' },
      ],
      expandedFields: ['topVendor', 'optimizationOpp'],
      chart: {
        type: 'stacked-bar',
        title: 'Spend by Category (6 Months)',
        xKey: 'month',
        dataKeys: ['cloud', 'software', 'logistics', 'equipment', 'payroll', 'facilities'],
        colors: ['#059669', '#2A9D8F', '#F5920B', '#6366F1', '#DC2626', '#8B5CF6'],
        data: [
          { month: 'Jan', cloud: 46000, software: 32000, logistics: 78000, equipment: 42000, payroll: 152000, facilities: 27000 },
          { month: 'Feb', cloud: 48000, software: 33000, logistics: 80000, equipment: 44000, payroll: 153000, facilities: 27500 },
          { month: 'Mar', cloud: 50000, software: 32000, logistics: 81000, equipment: 46000, payroll: 153500, facilities: 27200 },
          { month: 'Apr', cloud: 51000, software: 31500, logistics: 80000, equipment: 47000, payroll: 154000, facilities: 27000 },
          { month: 'May', cloud: 52000, software: 31200, logistics: 79800, equipment: 47500, payroll: 154000, facilities: 26900 },
          { month: 'Jun', cloud: 52400, software: 31200, logistics: 79400, equipment: 47800, payroll: 154200, facilities: 26800 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Cloud Spend Over Budget', description: 'AWS spend exceeded budget by $4,400 (9.2%). 12 idle EC2 instances account for $3,800/mo. Terminate or downsize immediately.', impact: '$3,800/mo savings', action: 'Review Instances' },
        { priority: 'high', title: '8 Unused Software Seats', description: 'Salesforce has 8 seats with zero logins in 60 days. Reclaiming saves $960/mo.', impact: '$11,520/yr savings', action: 'Reclaim Seats' },
        { priority: 'medium', title: 'Carrier Consolidation', description: 'Using 5 shipping carriers creates rate inefficiency. Consolidating to 2 preferred carriers saves 12% on logistics.', impact: '$9,500/yr savings', action: 'Start RFP' },
        { priority: 'low', title: 'LED Retrofit ROI', description: 'Facilities LED retrofit costs $4,200 upfront, saves $340/month. 12.4 month payback.', impact: '$4,080/yr savings', action: 'Approve Project' },
      ],
      actions: [
        { label: 'Generate Spend Report', description: 'Detailed spend analysis with category breakdowns and trend analysis' },
        { label: 'Run Savings Scan', description: 'AI-powered scan for cost optimization opportunities across all categories' },
        { label: 'Export Budget vs Actual', description: 'Download budget variance report with department-level detail' },
        { label: 'Create Purchase Request', description: 'Submit a new purchase request with auto-routing for approval' },
      ],
    },
    {
      id: 'vendor-management',
      label: 'Vendor Management',
      kpis: [
        { label: 'Active Vendors', value: 87, change: -3, trend: 'down', icon: '👥' },
        { label: 'Contracts Expiring', value: 6, change: 2, trend: 'up', icon: '📅' },
        { label: 'Avg Payment Terms', value: 34, suffix: ' days', change: 0, trend: 'flat', icon: '⏳' },
        { label: 'Vendor Score', value: 78, suffix: '/100', change: 3, trend: 'up', icon: '⭐' },
      ],
      columns: [
        { key: 'vendor', label: 'Vendor', sortable: true },
        { key: 'category', label: 'Category', sortable: true },
        { key: 'annualSpend', label: 'Annual Spend', sortable: true },
        { key: 'contractEnd', label: 'Contract Ends', sortable: true },
        { key: 'score', label: 'Score', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { vendor: 'AWS', category: 'Cloud', annualSpend: 456000, contractEnd: 'Dec 2026', score: '82/100', status: 'Active', slaCompliance: '99.2%', lastReview: 'Feb 2026' },
        { vendor: 'Salesforce', category: 'CRM', annualSpend: 144000, contractEnd: 'Jul 2026', score: '74/100', status: 'Review', slaCompliance: '98.8%', lastReview: 'Jan 2026' },
        { vendor: 'UPS', category: 'Shipping', annualSpend: 504000, contractEnd: 'Sep 2026', score: '88/100', status: 'Active', slaCompliance: '96.4%', lastReview: 'Mar 2026' },
        { vendor: 'Grainger', category: 'Parts', annualSpend: 216000, contractEnd: 'Apr 2026', score: '72/100', status: 'Expiring', slaCompliance: '94.1%', lastReview: 'Dec 2025' },
        { vendor: 'ADP', category: 'Payroll', annualSpend: 50400, contractEnd: 'Nov 2026', score: '90/100', status: 'Active', slaCompliance: '99.9%', lastReview: 'Feb 2026' },
      ],
      expandedFields: ['slaCompliance', 'lastReview'],
      chart: {
        type: 'pie',
        title: 'Spend by Vendor Category',
        dataKeys: ['value'],
        data: [
          { name: 'Shipping', value: 504000 },
          { name: 'Cloud', value: 456000 },
          { name: 'Parts & Equipment', value: 216000 },
          { name: 'CRM & Software', value: 144000 },
          { name: 'Services', value: 96000 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Grainger Contract Expiring', description: 'Grainger contract expires April 2026. Score is 72/100. Begin RFP process now to negotiate better terms or switch vendors.', impact: 'Secure $216K/yr contract', action: 'Start RFP' },
        { priority: 'medium', title: 'Salesforce Review Needed', description: 'Salesforce score dropped to 74/100. Usage analytics show 62% feature adoption. Consider downgrade or alternative.', impact: 'Potential $48K savings', action: 'Schedule Review' },
      ],
      actions: [
        { label: 'Generate Vendor Scorecard', description: 'Comprehensive vendor performance report with SLA tracking' },
        { label: 'Start RFP Process', description: 'Create and distribute RFP for expiring or underperforming contracts' },
        { label: 'Export Vendor Data', description: 'Download complete vendor database with spend and performance metrics' },
      ],
    },
    {
      id: 'budgets',
      label: 'Budgets',
      kpis: [
        { label: 'Total Budget', value: 3400000, prefix: '$', change: 0, trend: 'flat', icon: '💰' },
        { label: 'YTD Spend', value: 1680000, prefix: '$', change: 2, trend: 'up', icon: '📊' },
        { label: 'Remaining', value: 1720000, prefix: '$', change: -2, trend: 'down', icon: '💵' },
        { label: 'Burn Rate', value: 280000, prefix: '$', change: 0, trend: 'flat', icon: '🔥' },
      ],
      columns: [
        { key: 'department', label: 'Department', sortable: true },
        { key: 'annual', label: 'Annual Budget', sortable: true },
        { key: 'ytdSpend', label: 'YTD Spend', sortable: true },
        { key: 'remaining', label: 'Remaining', sortable: true },
        { key: 'burnRate', label: 'Burn Rate', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { department: 'Operations', annual: 1200000, ytdSpend: 620000, remaining: 580000, burnRate: '103K/mo', status: 'On Track', forecast: 'Under by $24K', topExpense: 'Equipment maintenance' },
        { department: 'Engineering', annual: 780000, ytdSpend: 410000, remaining: 370000, burnRate: '68K/mo', status: 'Over', forecast: 'Over by $36K', topExpense: 'Cloud infrastructure' },
        { department: 'Sales', annual: 540000, ytdSpend: 260000, remaining: 280000, burnRate: '43K/mo', status: 'On Track', forecast: 'Under by $12K', topExpense: 'Travel & entertainment' },
        { department: 'People', annual: 420000, ytdSpend: 198000, remaining: 222000, burnRate: '33K/mo', status: 'Under', forecast: 'Under by $24K', topExpense: 'Recruiting fees' },
        { department: 'Finance', annual: 280000, ytdSpend: 132000, remaining: 148000, burnRate: '22K/mo', status: 'On Track', forecast: 'On target', topExpense: 'Audit & compliance' },
        { department: 'Support', annual: 180000, ytdSpend: 60000, remaining: 120000, burnRate: '14K/mo', status: 'Under', forecast: 'Under by $12K', topExpense: 'Tool subscriptions' },
      ],
      expandedFields: ['forecast', 'topExpense'],
      chart: {
        type: 'area',
        title: 'Budget Burn Rate',
        xKey: 'month',
        dataKeys: ['actual', 'planned'],
        colors: ['#059669', '#E5E7EB'],
        data: [
          { month: 'Jan', actual: 272000, planned: 283000 },
          { month: 'Feb', actual: 278000, planned: 283000 },
          { month: 'Mar', actual: 284000, planned: 283000 },
          { month: 'Apr', actual: 282000, planned: 283000 },
          { month: 'May', actual: 280000, planned: 283000 },
          { month: 'Jun', actual: 284000, planned: 283000 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Engineering Over Budget', description: 'Engineering is tracking $36K over annual budget. Cloud spend is the primary driver. Needs immediate review.', impact: 'Prevent $36K overrun', action: 'Schedule Review' },
        { priority: 'medium', title: 'Reallocate People Budget', description: 'People dept is $24K under budget. Shift funds to Engineering to cover cloud cost overrun.', impact: 'Balance budgets', action: 'Submit Transfer' },
      ],
      actions: [
        { label: 'Generate Budget Report', description: 'Comprehensive budget vs actual with department-level detail' },
        { label: 'Submit Budget Transfer', description: 'Request inter-department budget reallocation' },
        { label: 'Export Financials', description: 'Download complete budget data for board presentation' },
      ],
    },
    {
      id: 'automation',
      label: 'Automation',
      kpis: [
        { label: 'Active Workflows', value: 24, change: 4, trend: 'up', icon: '⚙️' },
        { label: 'Hours Saved/Mo', value: 186, change: 22, trend: 'up', icon: '⏱️' },
        { label: 'Error Rate', value: 0.8, suffix: '%', change: -34, trend: 'down', icon: '🎯' },
        { label: 'Auto-Processed', value: 342, change: 12, trend: 'up', icon: '📨' },
      ],
      columns: [
        { key: 'workflow', label: 'Workflow', sortable: true },
        { key: 'type', label: 'Type', sortable: true },
        { key: 'frequency', label: 'Frequency', sortable: true },
        { key: 'hoursSaved', label: 'Hrs Saved/Mo', sortable: true },
        { key: 'errorRate', label: 'Error %', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { workflow: 'Invoice Matching', type: 'AP Automation', frequency: 'Daily', hoursSaved: 48, errorRate: '0.4%', status: 'Active', lastRun: '2 hours ago', exceptions: 3 },
        { workflow: 'Expense Approval', type: 'Approval Chain', frequency: 'Real-time', hoursSaved: 32, errorRate: '0.2%', status: 'Active', lastRun: '34 min ago', exceptions: 0 },
        { workflow: 'Revenue Recognition', type: 'Accounting', frequency: 'Monthly', hoursSaved: 24, errorRate: '1.2%', status: 'Active', lastRun: 'Mar 1', exceptions: 2 },
        { workflow: 'Vendor Onboarding', type: 'Procurement', frequency: 'On-demand', hoursSaved: 16, errorRate: '0.8%', status: 'Active', lastRun: '3 days ago', exceptions: 1 },
        { workflow: 'Bank Reconciliation', type: 'Accounting', frequency: 'Daily', hoursSaved: 28, errorRate: '0.6%', status: 'Active', lastRun: 'Today 6AM', exceptions: 0 },
        { workflow: 'Budget Alerts', type: 'Monitoring', frequency: 'Real-time', hoursSaved: 12, errorRate: '0%', status: 'Active', lastRun: '1 hour ago', exceptions: 0 },
      ],
      expandedFields: ['lastRun', 'exceptions'],
      chart: {
        type: 'line',
        title: 'Hours Saved by Automation',
        xKey: 'month',
        dataKeys: ['hours'],
        colors: ['#059669'],
        data: [
          { month: 'Jan', hours: 124 },
          { month: 'Feb', hours: 138 },
          { month: 'Mar', hours: 152 },
          { month: 'Apr', hours: 164 },
          { month: 'May', hours: 178 },
          { month: 'Jun', hours: 186 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Automate PO Creation', description: 'Manual PO creation takes 18 hours/month. Auto-PO from approved requisitions could reduce to 2 hours.', impact: '16 hrs/mo saved', action: 'Create Workflow' },
        { priority: 'medium', title: 'Revenue Recognition Error', description: 'Rev rec workflow has 1.2% error rate, highest of all automations. Rule engine needs tuning for milestone billing.', impact: 'Reduce errors 60%', action: 'Review Rules' },
      ],
      actions: [
        { label: 'Create Workflow', description: 'Build a new automated workflow with AI-suggested triggers and actions' },
        { label: 'View Run History', description: 'Audit trail of all automation runs with exception details' },
        { label: 'Export Savings Report', description: 'Download automation ROI analysis with time and cost savings' },
      ],
    },
  ],
});
