import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'hr',
    name: 'HR',
    icon: '\u{1F465}',
    dept: 'People',
    deptColor: '#6366F1',
    description: 'AI-powered workforce management and people analytics',
    valueProposition: 'Track hiring, retention, and satisfaction with actionable AI insights',
    enabled: true,
    buildBatch: 1,
  },
  tabs: [
    {
      id: 'workforce',
      label: 'Workforce Overview',
      kpis: [
        { label: 'Headcount', value: 127, change: 4, trend: 'up', icon: '\u{1F465}' },
        { label: 'Open Positions', value: 8, change: -2, trend: 'down', icon: '\u{1F4CB}' },
        { label: 'Retention Rate', value: 91, suffix: '%', change: 2, trend: 'up', icon: '\u{1F4CA}' },
        { label: 'Avg Tenure', value: 2.4, suffix: ' yrs', change: 4, trend: 'up', icon: '\u{23F3}' },
      ],
      columns: [
        { key: 'position', label: 'Position', sortable: true },
        { key: 'department', label: 'Department', sortable: true },
        { key: 'applicants', label: 'Applicants', sortable: true },
        { key: 'interviews', label: 'Interviews', sortable: true },
        { key: 'daysOpen', label: 'Days Open', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { position: 'Warehouse Associate', department: 'Operations', applicants: 34, interviews: 8, daysOpen: 34, status: 'Open', hiringManager: 'Tom B.', compRange: '$42K-$52K', requirements: 'Forklift certified, 2+ years' },
        { position: 'Software Engineer', department: 'Engineering', applicants: 67, interviews: 12, daysOpen: 28, status: 'In Progress', hiringManager: 'Steve M.', compRange: '$95K-$130K', requirements: 'React/Node, 3+ years' },
        { position: 'Sales Representative', department: 'Sales', applicants: 28, interviews: 6, daysOpen: 21, status: 'Open', hiringManager: 'Sarah M.', compRange: '$65K + commission', requirements: 'B2B SaaS, 2+ years' },
        { position: 'Financial Analyst', department: 'Finance', applicants: 42, interviews: 5, daysOpen: 14, status: 'Pending', hiringManager: 'Lisa R.', compRange: '$70K-$85K', requirements: 'CPA preferred, Excel expert' },
        { position: 'HR Coordinator', department: 'People', applicants: 19, interviews: 3, daysOpen: 7, status: 'New', hiringManager: 'Amy J.', compRange: '$55K-$65K', requirements: 'SHRM-CP preferred' },
        { position: 'Logistics Manager', department: 'Operations', applicants: 22, interviews: 4, daysOpen: 42, status: 'Open', hiringManager: 'Tom B.', compRange: '$75K-$95K', requirements: 'Supply chain exp, WMS' },
        { position: 'Customer Success Mgr', department: 'Support', applicants: 31, interviews: 5, daysOpen: 18, status: 'In Progress', hiringManager: 'David K.', compRange: '$60K-$75K', requirements: 'SaaS CSM experience' },
      ],
      expandedFields: ['hiringManager', 'compRange', 'requirements'],
      chart: {
        type: 'line',
        title: 'Headcount Trend (12 Months)',
        xKey: 'month',
        dataKeys: ['headcount'],
        colors: ['#6366F1'],
        data: [
          { month: 'Jul', headcount: 108 },
          { month: 'Aug', headcount: 110 },
          { month: 'Sep', headcount: 112 },
          { month: 'Oct', headcount: 115 },
          { month: 'Nov', headcount: 118 },
          { month: 'Dec', headcount: 119 },
          { month: 'Jan', headcount: 121 },
          { month: 'Feb', headcount: 123 },
          { month: 'Mar', headcount: 125 },
          { month: 'Apr', headcount: 124 },
          { month: 'May', headcount: 126 },
          { month: 'Jun', headcount: 127 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Warehouse Associate Open 34 Days', description: 'This role has been open 34 days vs 21-day target. Expand to 3 additional job boards and increase comp range by 5%.', impact: 'Fill in 2 weeks', action: 'Expand Job Posting' },
        { priority: 'high', title: 'Engineering Turnover Risk', description: 'Engineering turnover hit 22% annually. Exit interviews cite compensation. Market analysis shows 12% below median.', impact: 'Retain 3 engineers', action: 'Run Comp Analysis' },
        { priority: 'medium', title: 'Anniversary Check-Ins', description: '5 employees hitting 1-year anniversary. Data shows 28% turnover risk at 12-month mark. Schedule retention check-ins.', impact: 'Prevent 1-2 exits', action: 'Schedule Check-Ins' },
      ],
      actions: [
        { label: 'Post Job Opening', description: 'Create and distribute a job posting across configured job boards' },
        { label: 'Generate Retention Report', description: 'Flight risk analysis with recommended retention actions by employee' },
        { label: 'Schedule Review Cycle', description: 'Set up performance review cycle with templates and timelines' },
        { label: 'Run Salary Benchmark', description: 'Compare compensation against market data for all roles' },
      ],
    },
    {
      id: 'hiring',
      label: 'Hiring Pipeline',
      kpis: [
        { label: 'Active Candidates', value: 84, change: 12, trend: 'up', icon: '\u{1F464}' },
        { label: 'Interviews/Week', value: 12, change: 4, trend: 'up', icon: '\u{1F4DE}' },
        { label: 'Offers Pending', value: 3, change: 1, trend: 'up', icon: '\u{1F4E8}' },
        { label: 'Time-to-Fill', value: 28, suffix: ' days', change: -4, trend: 'down', icon: '\u{23F1}\u{FE0F}' },
      ],
      columns: [
        { key: 'candidate', label: 'Candidate', sortable: true },
        { key: 'position', label: 'Position', sortable: true },
        { key: 'stage', label: 'Stage', sortable: true },
        { key: 'rating', label: 'Rating', sortable: true },
        { key: 'daysInStage', label: 'Days', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { candidate: 'Jordan Rivera', position: 'Software Engineer', stage: 'Final Interview', rating: '4.5/5', daysInStage: 3, status: 'Active', source: 'LinkedIn', interviewScore: '92/100' },
        { candidate: 'Priya Patel', position: 'Financial Analyst', stage: 'Offer Sent', rating: '4.8/5', daysInStage: 2, status: 'Pending', source: 'Referral', interviewScore: '95/100' },
        { candidate: 'Marcus Thompson', position: 'Warehouse Associate', stage: 'Phone Screen', rating: '3.8/5', daysInStage: 1, status: 'Active', source: 'Indeed', interviewScore: 'Pending' },
        { candidate: 'Emma Sandoval', position: 'Sales Representative', stage: 'In Progress', rating: '4.2/5', daysInStage: 5, status: 'Active', source: 'Recruiter', interviewScore: '88/100' },
        { candidate: 'Alex Chen', position: 'Customer Success Mgr', stage: 'Offer Sent', rating: '4.6/5', daysInStage: 4, status: 'Pending', source: 'LinkedIn', interviewScore: '91/100' },
      ],
      expandedFields: ['source', 'interviewScore'],
      chart: {
        type: 'bar',
        title: 'Hiring Funnel',
        xKey: 'stage',
        dataKeys: ['count'],
        colors: ['#6366F1'],
        data: [
          { stage: 'Applied', count: 243 },
          { stage: 'Screened', count: 69 },
          { stage: 'Interview', count: 38 },
          { stage: 'Final', count: 12 },
          { stage: 'Offer', count: 5 },
          { stage: 'Hired', count: 3 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Priya Patel Offer Expiring', description: 'Financial Analyst offer expires in 3 days. She has another offer. Consider adding sign-on bonus.', impact: 'Fill key role', action: 'Review Offer' },
        { priority: 'medium', title: 'Screening Bottleneck', description: '243 applications but only 69 screened. AI pre-screening could reduce manual review by 60%.', impact: 'Save 40 hrs/month', action: 'Enable AI Screen' },
      ],
      actions: [
        { label: 'Schedule Interviews', description: 'AI-optimized interview scheduling based on availability' },
        { label: 'Generate Offer Letter', description: 'Create customized offer letters with competitive comp packages' },
        { label: 'Export Pipeline', description: 'Download complete hiring pipeline with stage analytics' },
      ],
    },
    {
      id: 'retention',
      label: 'Retention',
      kpis: [
        { label: 'Annual Turnover', value: 14, suffix: '%', change: -2, trend: 'down', icon: '\u{1F4C9}' },
        { label: 'Flight Risk', value: 6, change: -1, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
        { label: 'Exit Score', value: 3.1, suffix: '/5', change: 4, trend: 'up', icon: '\u{1F4CB}' },
        { label: 'Regrettable Losses', value: 4, change: -2, trend: 'down', icon: '\u{1F614}' },
      ],
      columns: [
        { key: 'employee', label: 'Employee', sortable: true },
        { key: 'department', label: 'Dept', sortable: true },
        { key: 'tenure', label: 'Tenure', sortable: true },
        { key: 'riskScore', label: 'Flight Risk', sortable: true },
        { key: 'riskFactors', label: 'Risk Factors', sortable: false },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { employee: 'Tyler Brooks', department: 'Engineering', tenure: '1.8 yrs', riskScore: 'High', riskFactors: 'Below market comp, manager change', status: 'At Risk', lastReview: '3.8/5', actionPlan: 'Comp adjustment + mentorship' },
        { employee: 'Rachel Kim', department: 'Engineering', tenure: '2.1 yrs', riskScore: 'High', riskFactors: 'No promotion in 2 years', status: 'At Risk', lastReview: '4.2/5', actionPlan: 'Promotion fast-track' },
        { employee: 'Marcus Hall', department: 'Sales', tenure: '0.9 yrs', riskScore: 'Medium', riskFactors: 'Below quota 2 quarters', status: 'In Progress', lastReview: '3.2/5', actionPlan: 'Coaching plan active' },
        { employee: 'Jenny Nguyen', department: 'Operations', tenure: '3.4 yrs', riskScore: 'Medium', riskFactors: 'Passed over for promotion', status: 'In Progress', lastReview: '4.0/5', actionPlan: 'Career path discussion' },
        { employee: 'Chris Martinez', department: 'Support', tenure: '1.2 yrs', riskScore: 'Low', riskFactors: 'Remote work preference', status: 'Active', lastReview: '4.5/5', actionPlan: 'Hybrid arrangement approved' },
      ],
      expandedFields: ['lastReview', 'actionPlan'],
      chart: {
        type: 'line',
        title: 'Monthly Turnover Rate',
        xKey: 'month',
        dataKeys: ['turnover', 'industry'],
        colors: ['#6366F1', '#E5E7EB'],
        data: [
          { month: 'Jan', turnover: 18, industry: 22 },
          { month: 'Feb', turnover: 17, industry: 21 },
          { month: 'Mar', turnover: 16, industry: 21 },
          { month: 'Apr', turnover: 15, industry: 20 },
          { month: 'May', turnover: 15, industry: 20 },
          { month: 'Jun', turnover: 14, industry: 20 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Engineering Comp Crisis', description: 'Two high-performers are flight risks citing compensation. Market data shows 12-15% below median. Retention costs 3x replacement.', impact: 'Save $180K in turnover', action: 'Approve Adjustments' },
        { priority: 'medium', title: 'Promotion Pipeline Empty', description: 'No internal promotions in 6 months. Creating visible career paths reduces turnover by 34%.', impact: 'Retain 2 key employees', action: 'Create Career Paths' },
      ],
      actions: [
        { label: 'Generate Retention Report', description: 'AI-powered flight risk analysis with intervention recommendations' },
        { label: 'Run Stay Interviews', description: 'Schedule and template stay interviews for at-risk employees' },
        { label: 'Export Risk Assessment', description: 'Download flight risk scores and recommended actions' },
      ],
    },
    {
      id: 'satisfaction',
      label: 'Satisfaction',
      kpis: [
        { label: 'eNPS', value: 42, change: 6, trend: 'up', icon: '\u{1F4CA}' },
        { label: 'Response Rate', value: 78, suffix: '%', change: 4, trend: 'up', icon: '\u{1F4E9}' },
        { label: 'Top Concern', value: 0, change: 0, trend: 'flat', icon: '\u{1F4AC}' },
        { label: 'Satisfaction', value: 7.2, suffix: '/10', change: 3, trend: 'up', icon: '\u{2B50}' },
      ],
      columns: [
        { key: 'department', label: 'Department', sortable: true },
        { key: 'enps', label: 'eNPS', sortable: true },
        { key: 'satisfaction', label: 'Score', sortable: true },
        { key: 'responseRate', label: 'Response %', sortable: true },
        { key: 'topConcern', label: 'Top Concern', sortable: false },
        { key: 'trend', label: 'Trend', sortable: true },
      ],
      rows: [
        { department: 'Sales', enps: 52, satisfaction: '7.8/10', responseRate: '82%', topConcern: 'Quota targets', trend: 'Improving', detractors: '12%', promoters: '64%' },
        { department: 'Engineering', enps: 28, satisfaction: '6.4/10', responseRate: '74%', topConcern: 'Compensation', trend: 'Declining', detractors: '28%', promoters: '56%' },
        { department: 'Operations', enps: 44, satisfaction: '7.2/10', responseRate: '88%', topConcern: 'Scheduling', trend: 'Stable', detractors: '16%', promoters: '60%' },
        { department: 'Finance', enps: 48, satisfaction: '7.5/10', responseRate: '80%', topConcern: 'Career growth', trend: 'Improving', detractors: '14%', promoters: '62%' },
        { department: 'People', enps: 56, satisfaction: '8.1/10', responseRate: '92%', topConcern: 'Workload', trend: 'Stable', detractors: '8%', promoters: '64%' },
        { department: 'Support', enps: 38, satisfaction: '6.9/10', responseRate: '70%', topConcern: 'Burnout', trend: 'Declining', detractors: '22%', promoters: '60%' },
      ],
      expandedFields: ['detractors', 'promoters'],
      chart: {
        type: 'bar',
        title: 'eNPS by Department',
        xKey: 'department',
        dataKeys: ['enps'],
        colors: ['#6366F1'],
        data: [
          { department: 'People', enps: 56 },
          { department: 'Sales', enps: 52 },
          { department: 'Finance', enps: 48 },
          { department: 'Operations', enps: 44 },
          { department: 'Support', enps: 38 },
          { department: 'Engineering', enps: 28 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Engineering Satisfaction Declining', description: 'Engineering eNPS dropped from 38 to 28. Compensation and growth are top concerns. Immediate action needed.', impact: 'Prevent further decline', action: 'Plan Intervention' },
        { priority: 'medium', title: 'Support Team Burnout', description: 'Support eNPS declining with burnout as top concern. Ticket volume up 18% without headcount increase.', impact: 'Reduce burnout risk', action: 'Review Staffing' },
      ],
      actions: [
        { label: 'Launch Pulse Survey', description: 'Quick 5-question pulse survey to track engagement trends' },
        { label: 'Generate Insights Report', description: 'AI-analyzed survey results with theme extraction and recommendations' },
        { label: 'Schedule Town Halls', description: 'Department-specific town halls to address top concerns' },
      ],
    },
  ],
});
