import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'legal',
    name: 'Legal',
    icon: '\u{2696}\u{FE0F}',
    dept: 'Legal',
    deptColor: '#7C3AED',
    description: 'AI-powered contract management, risk analysis, and compliance tracking',
    valueProposition: 'Review contracts faster, track obligations, and reduce legal risk across the business',
    enabled: true,
    buildBatch: 3,
  },
  tabs: [
    {
      id: 'contracts',
      label: 'Contracts',
      kpis: [
        { label: 'Active Contracts', value: 94, change: 6, trend: 'up', icon: '\u{1F4C4}' },
        { label: 'Pending Review', value: 12, change: -3, trend: 'down', icon: '\u{23F3}' },
        { label: 'Expiring (90d)', value: 8, change: 2, trend: 'up', icon: '\u{26A0}\u{FE0F}' },
        { label: 'Avg Review Time', value: 3.2, suffix: ' days', change: -18, trend: 'down', icon: '\u{23F1}\u{FE0F}' },
      ],
      columns: [
        { key: 'contract', label: 'Contract', sortable: true },
        { key: 'counterparty', label: 'Counterparty', sortable: true },
        { key: 'type', label: 'Type', sortable: true },
        { key: 'value', label: 'Value', sortable: true },
        { key: 'expiration', label: 'Expires', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { contract: 'MSA-2024-041', counterparty: 'MegaCorp Inc', type: 'Master Service', value: 480000, expiration: 'Jun 30', status: 'Active', autoRenew: 'Yes - 30 day notice', keyTerms: 'Net 45, liability cap 2x', assignedAttorney: 'Karen W.' },
        { contract: 'VND-2025-018', counterparty: 'Grainger Industrial', type: 'Vendor', value: 216000, expiration: 'Apr 15', status: 'Expiring', autoRenew: 'No', keyTerms: 'Net 30, volume pricing tiers', assignedAttorney: 'Marcus T.' },
        { contract: 'NDA-2026-112', counterparty: 'Apex Fulfillment', type: 'NDA', value: 0, expiration: 'Dec 31', status: 'Active', autoRenew: 'Yes - annual', keyTerms: 'Mutual, 3-year term', assignedAttorney: 'Auto-generated' },
        { contract: 'SVC-2025-007', counterparty: 'TechFlow Solutions', type: 'SaaS', value: 78000, expiration: 'Jul 15', status: 'Review', autoRenew: 'Yes - 60 day notice', keyTerms: 'Annual prepay, 99.5% SLA', assignedAttorney: 'Karen W.' },
        { contract: 'LSE-2024-003', counterparty: 'Prologis', type: 'Lease', value: 420000, expiration: 'Dec 2027', status: 'Active', autoRenew: 'No - renegotiate', keyTerms: 'Triple net, 3% annual escalation', assignedAttorney: 'Marcus T.' },
        { contract: 'EMP-2026-089', counterparty: 'Jordan Rivera', type: 'Employment', value: 125000, expiration: 'N/A', status: 'Pending', autoRenew: 'N/A', keyTerms: 'At-will, 12-month non-compete', assignedAttorney: 'Karen W.' },
        { contract: 'MSA-2025-022', counterparty: 'Pacific Freight Co', type: 'Master Service', value: 340000, expiration: 'Sep 30', status: 'Active', autoRenew: 'Yes - 45 day notice', keyTerms: 'Net 30, indemnification clause', assignedAttorney: 'Marcus T.' },
      ],
      expandedFields: ['autoRenew', 'keyTerms', 'assignedAttorney'],
      chart: {
        type: 'pie',
        title: 'Contracts by Type',
        dataKeys: ['value'],
        data: [
          { name: 'Master Service', value: 28 },
          { name: 'Vendor', value: 22 },
          { name: 'NDA', value: 18 },
          { name: 'SaaS/License', value: 14 },
          { name: 'Employment', value: 8 },
          { name: 'Lease', value: 4 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Grainger Contract Expiring', description: 'Grainger vendor contract ($216K) expires Apr 15 with no auto-renew. Begin renegotiation now to avoid supply gap.', impact: '$216K contract at risk', action: 'Start Renewal' },
        { priority: 'high', title: 'TechFlow SLA Below Target', description: 'TechFlow SaaS contract guarantees 99.5% uptime but delivered 98.8% last quarter. Document for renegotiation leverage.', impact: 'Service credit eligible', action: 'Draft SLA Claim' },
        { priority: 'medium', title: 'Standardize NDA Template', description: '18 active NDAs use 4 different templates. Standardizing reduces review time by 60% for new NDAs.', impact: 'Save 8 hrs/month', action: 'Review Templates' },
      ],
      actions: [
        { label: 'Create Contract', description: 'Generate a new contract from AI-recommended templates' },
        { label: 'Run Clause Analysis', description: 'AI extraction of key terms, risks, and obligations from any contract' },
        { label: 'Export Contract Register', description: 'Download complete contract database with key dates and terms' },
        { label: 'Set Renewal Alerts', description: 'Configure automated alerts for upcoming expirations and renewals' },
      ],
    },
    {
      id: 'risk-register',
      label: 'Risk Register',
      kpis: [
        { label: 'Open Risks', value: 14, change: -2, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
        { label: 'High Severity', value: 3, change: -1, trend: 'down', icon: '\u{1F534}' },
        { label: 'Mitigated (Q)', value: 8, change: 4, trend: 'up', icon: '\u{2705}' },
        { label: 'Insurance Coverage', value: 94, suffix: '%', change: 2, trend: 'up', icon: '\u{1F6E1}\u{FE0F}' },
      ],
      columns: [
        { key: 'risk', label: 'Risk', sortable: true },
        { key: 'category', label: 'Category', sortable: true },
        { key: 'severity', label: 'Severity', sortable: true },
        { key: 'likelihood', label: 'Likelihood', sortable: true },
        { key: 'owner', label: 'Owner', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { risk: 'Data breach liability', category: 'Cybersecurity', severity: 'High', likelihood: 'Medium', owner: 'CISO', status: 'Mitigating', mitigation: 'Cyber insurance + SOC2 audit', exposure: '$2M estimated max', lastReview: 'Mar 1' },
        { risk: 'Worker comp claim escalation', category: 'Employment', severity: 'High', likelihood: 'Low', owner: 'HR Director', status: 'Monitoring', mitigation: 'Safety program + training', exposure: '$500K policy limit', lastReview: 'Feb 15' },
        { risk: 'IP infringement allegation', category: 'IP', severity: 'Medium', likelihood: 'Low', owner: 'Legal', status: 'Open', mitigation: 'Freedom-to-operate analysis', exposure: '$250K defense costs', lastReview: 'Jan 20' },
        { risk: 'Vendor bankruptcy impact', category: 'Supply Chain', severity: 'Medium', likelihood: 'Medium', owner: 'Procurement', status: 'Mitigating', mitigation: 'Dual-source strategy for top 5 vendors', exposure: '$180K supply disruption', lastReview: 'Mar 10' },
        { risk: 'Lease escalation dispute', category: 'Real Estate', severity: 'Low', likelihood: 'Medium', owner: 'CFO', status: 'Monitoring', mitigation: 'Document market comparables', exposure: '$36K annual delta', lastReview: 'Feb 28' },
      ],
      expandedFields: ['mitigation', 'exposure', 'lastReview'],
      chart: {
        type: 'bar',
        title: 'Risks by Category',
        xKey: 'category',
        dataKeys: ['count'],
        colors: ['#7C3AED'],
        data: [
          { category: 'Employment', count: 4 },
          { category: 'Cybersecurity', count: 3 },
          { category: 'Supply Chain', count: 3 },
          { category: 'IP', count: 2 },
          { category: 'Real Estate', count: 2 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Cyber Insurance Gap', description: 'Current cyber policy covers $2M but recent breach cost analysis suggests $3.5M exposure. Review coverage limits.', impact: 'Close $1.5M gap', action: 'Review Policy' },
        { priority: 'medium', title: 'Quarterly Risk Review Due', description: '6 risks have not been reviewed in 60+ days. Schedule quarterly risk review for all open items.', impact: 'Maintain compliance', action: 'Schedule Review' },
      ],
      actions: [
        { label: 'Add Risk', description: 'Document a new risk with AI-suggested severity and mitigation strategies' },
        { label: 'Generate Risk Report', description: 'Board-ready risk assessment with heat map and trend analysis' },
        { label: 'Export Register', description: 'Download complete risk register with mitigation plans' },
      ],
    },
    {
      id: 'obligations',
      label: 'Obligations',
      kpis: [
        { label: 'Active Obligations', value: 42, change: 3, trend: 'up', icon: '\u{1F4CB}' },
        { label: 'Due This Month', value: 6, change: 1, trend: 'up', icon: '\u{1F4C5}' },
        { label: 'Overdue', value: 2, change: -1, trend: 'down', icon: '\u{1F534}' },
        { label: 'Compliance Rate', value: 95, suffix: '%', change: 2, trend: 'up', icon: '\u{1F3AF}' },
      ],
      columns: [
        { key: 'obligation', label: 'Obligation', sortable: true },
        { key: 'contract', label: 'Contract', sortable: true },
        { key: 'dueDate', label: 'Due Date', sortable: true },
        { key: 'owner', label: 'Owner', sortable: true },
        { key: 'frequency', label: 'Frequency', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { obligation: 'SOC2 Audit Report', contract: 'MSA-2024-041', dueDate: 'Mar 31', owner: 'CISO', frequency: 'Annual', status: 'In Progress', penalty: 'Contract default', details: 'Provide to MegaCorp by Q1 end' },
        { obligation: 'Insurance Certificate', contract: 'LSE-2024-003', dueDate: 'Apr 1', owner: 'Finance', frequency: 'Annual', status: 'Pending', penalty: 'Lease violation', details: 'Updated COI to Prologis' },
        { obligation: 'Data Deletion Request', contract: 'SVC-2025-007', dueDate: 'Mar 22', owner: 'Engineering', frequency: 'On Request', status: 'Overdue', penalty: 'GDPR violation', details: 'Customer data deletion within 30 days' },
        { obligation: 'Quarterly Business Review', contract: 'MSA-2025-022', dueDate: 'Mar 30', owner: 'Account Mgr', frequency: 'Quarterly', status: 'Scheduled', penalty: 'None', details: 'Pacific Freight QBR presentation' },
        { obligation: 'License Renewal', contract: 'SVC-2025-007', dueDate: 'Overdue', owner: 'IT', frequency: 'Annual', status: 'Overdue', penalty: 'Service interruption', details: 'TechFlow license key expired Mar 15' },
      ],
      expandedFields: ['penalty', 'details'],
      chart: {
        type: 'area',
        title: 'Obligation Compliance Rate',
        xKey: 'month',
        dataKeys: ['rate'],
        colors: ['#7C3AED'],
        data: [
          { month: 'Jan', rate: 88 },
          { month: 'Feb', rate: 90 },
          { month: 'Mar', rate: 92 },
          { month: 'Apr', rate: 93 },
          { month: 'May', rate: 94 },
          { month: 'Jun', rate: 95 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: '2 Overdue Obligations', description: 'Data deletion request and license renewal are both past due. Data deletion has GDPR penalty exposure.', impact: 'Regulatory risk', action: 'Resolve Immediately' },
        { priority: 'medium', title: 'SOC2 Report Due Mar 31', description: 'MegaCorp contractually requires SOC2 report by Q1 end. Audit is 80% complete. Ensure delivery on time.', impact: 'Maintain $480K contract', action: 'Check Progress' },
      ],
      actions: [
        { label: 'Track Obligation', description: 'Add a new contractual obligation with automated reminders' },
        { label: 'Generate Compliance Report', description: 'Obligation fulfillment status across all active contracts' },
        { label: 'Export Calendar', description: 'Download obligation due dates for calendar integration' },
      ],
    },
    {
      id: 'matter-tracker',
      label: 'Matters',
      kpis: [
        { label: 'Open Matters', value: 7, change: -1, trend: 'down', icon: '\u{1F4C2}' },
        { label: 'External Spend', value: 48000, prefix: '$', change: -8, trend: 'down', icon: '\u{1F4B0}' },
        { label: 'Avg Resolution', value: 34, suffix: ' days', change: -12, trend: 'down', icon: '\u{23F3}' },
        { label: 'In Litigation', value: 1, change: 0, trend: 'flat', icon: '\u{2696}\u{FE0F}' },
      ],
      columns: [
        { key: 'matter', label: 'Matter', sortable: true },
        { key: 'type', label: 'Type', sortable: true },
        { key: 'counsel', label: 'Counsel', sortable: true },
        { key: 'spend', label: 'Spend', sortable: true },
        { key: 'opened', label: 'Opened', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { matter: 'Vendor Payment Dispute', type: 'Commercial', counsel: 'Internal', spend: 0, opened: 'Feb 12', status: 'Negotiating', exposure: '$42K disputed amount', nextAction: 'Mediation Mar 28' },
        { matter: 'Employee Non-Compete', type: 'Employment', counsel: 'Baker & Associates', spend: 12400, opened: 'Jan 8', status: 'Active', exposure: '$0 - defensive', nextAction: 'Deposition Apr 5' },
        { matter: 'Trademark Registration', type: 'IP', counsel: 'Internal', spend: 2800, opened: 'Mar 1', status: 'Filing', exposure: 'N/A', nextAction: 'USPTO filing Mar 25' },
        { matter: 'Slip-and-Fall Claim', type: 'Liability', counsel: 'Morrison LLP', spend: 18400, opened: 'Nov 15', status: 'Litigation', exposure: '$125K claim', nextAction: 'Summary judgment May 1' },
        { matter: 'Lease Amendment', type: 'Real Estate', counsel: 'Internal', spend: 0, opened: 'Mar 10', status: 'Drafting', exposure: 'N/A', nextAction: 'Draft to landlord Mar 22' },
      ],
      expandedFields: ['exposure', 'nextAction'],
      chart: {
        type: 'bar',
        title: 'Legal Spend by Type',
        xKey: 'type',
        dataKeys: ['spend'],
        colors: ['#7C3AED'],
        data: [
          { type: 'Liability', spend: 18400 },
          { type: 'Employment', spend: 12400 },
          { type: 'IP', spend: 2800 },
          { type: 'Commercial', spend: 0 },
          { type: 'Real Estate', spend: 0 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Slip-and-Fall Exposure', description: 'Morrison LLP recommends settling for $45K vs $125K trial exposure. Settlement saves $80K+ in potential judgment and legal fees.', impact: 'Save up to $80K', action: 'Review Settlement' },
        { priority: 'medium', title: 'External Spend Trending Down', description: 'Legal spend dropped 8% by handling more matters internally. Continue building internal capacity.', impact: 'Save $12K/quarter', action: 'View Analysis' },
      ],
      actions: [
        { label: 'Open Matter', description: 'Create a new legal matter with AI-suggested categorization and staffing' },
        { label: 'Generate Spend Report', description: 'Legal spend analysis by matter type, firm, and trend' },
        { label: 'Export Matter List', description: 'Download all open matters with status and next actions' },
      ],
    },
  ],
});
