import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'operations',
    name: 'Operations',
    icon: '⚙️',
    dept: 'Operations',
    deptColor: '#2A9D8F',
    description: 'AI-powered project management, resources, and equipment tracking',
    valueProposition: 'Keep every project on track, optimize resources, and prevent equipment failures',
    enabled: true,
    buildBatch: 1,
  },
  tabs: [
    {
      id: 'project-board',
      label: 'Project Board',
      kpis: [
        { label: 'Active Projects', value: 8, change: 2, trend: 'up', icon: '📋' },
        { label: 'Resource Utilization', value: 76, suffix: '%', change: 4, trend: 'up', icon: '📊' },
        { label: 'On-Time Delivery', value: 88, suffix: '%', change: -3, trend: 'down', icon: '⏰' },
        { label: 'Equipment Uptime', value: 94, suffix: '%', change: 1, trend: 'up', icon: '✅' },
      ],
      columns: [
        { key: 'project', label: 'Project', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
        { key: 'progress', label: 'Progress %', sortable: true },
        { key: 'dueDate', label: 'Due Date', sortable: true },
        { key: 'lead', label: 'Lead', sortable: true },
        { key: 'budgetUsed', label: 'Budget Used', sortable: true },
      ],
      rows: [
        { project: 'DC Expansion Phase 2', status: 'Behind', progress: 62, dueDate: 'Apr 15', lead: 'Tom Bradley', budgetUsed: '74%', milestones: 'Steel frame complete, electrical 40%', team: '12 crew members', blockers: 'Permit delay on sprinkler system' },
        { project: 'Conveyor Upgrade Line 3', status: 'On Track', progress: 78, dueDate: 'Mar 28', lead: 'Sarah Kim', budgetUsed: '68%', milestones: 'Motors installed, belt alignment next', team: '6 crew members', blockers: 'None' },
        { project: 'WMS Integration', status: 'On Track', progress: 45, dueDate: 'May 30', lead: 'Dev Team', budgetUsed: '42%', milestones: 'API connected, testing phase', team: '4 engineers', blockers: 'None' },
        { project: 'Safety Compliance Audit', status: 'At Risk', progress: 85, dueDate: 'Mar 22', lead: 'Amy Jones', budgetUsed: '92%', milestones: '6 of 7 zones cleared', team: '3 auditors', blockers: 'Zone C fire exit reroute needed' },
        { project: 'Forklift Fleet Refresh', status: 'On Track', progress: 30, dueDate: 'Jun 15', lead: 'Carlos Diaz', budgetUsed: '28%', milestones: 'Vendor selected, 4 of 8 ordered', team: '2 fleet managers', blockers: 'Lead time 8 weeks' },
        { project: 'Client Portal v2', status: 'On Track', progress: 55, dueDate: 'Apr 30', lead: 'Steve M.', budgetUsed: '52%', milestones: 'UI complete, API integration', team: '3 engineers', blockers: 'None' },
        { project: 'Dock Door Automation', status: 'Completed', progress: 100, dueDate: 'Mar 10', lead: 'Tom Bradley', budgetUsed: '96%', milestones: 'All 6 doors automated', team: '4 installers', blockers: 'None' },
        { project: 'Pick Module Reconfiguration', status: 'In Progress', progress: 22, dueDate: 'Jul 1', lead: 'Sarah Kim', budgetUsed: '18%', milestones: 'Design approved, materials ordered', team: '5 crew members', blockers: 'Steel delivery delayed 1 week' },
      ],
      expandedFields: ['milestones', 'team', 'blockers'],
      chart: {
        type: 'stacked-bar',
        title: 'Resource Utilization by Team',
        xKey: 'team',
        dataKeys: ['utilized', 'available'],
        colors: ['#2A9D8F', '#E5E7EB'],
        data: [
          { team: 'Installation', utilized: 88, available: 12 },
          { team: 'Engineering', utilized: 82, available: 18 },
          { team: 'Fleet Ops', utilized: 74, available: 26 },
          { team: 'Maintenance', utilized: 68, available: 32 },
          { team: 'Admin', utilized: 56, available: 44 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'DC Expansion 3 Days Behind', description: 'DC Expansion Phase 2 is 3 days behind due to permit delay. Reassign 2 installers from completed Dock Door project.', impact: 'Back on schedule', action: 'Reassign Resources' },
        { priority: 'high', title: 'Forklift #4 Maintenance Alert', description: 'Forklift #4 has triggered 3 sensor alerts this week. Running hours exceed maintenance interval by 120 hours.', impact: 'Prevent breakdown', action: 'Schedule Maintenance' },
        { priority: 'medium', title: 'Installation Team Above 90%', description: 'Installation team has been above 90% utilization for 3 weeks. Risk of burnout and quality issues.', impact: 'Reduce burnout risk', action: 'Review Workload' },
      ],
      actions: [
        { label: 'Create Project', description: 'Start a new project with AI-suggested milestones and resource allocation' },
        { label: 'Generate Status Report', description: 'Executive summary of all active projects with risk indicators' },
        { label: 'Schedule Maintenance', description: 'AI-optimized maintenance scheduling to minimize downtime' },
        { label: 'Reallocate Resources', description: 'Move team members between projects based on priority and skills' },
      ],
    },
    {
      id: 'resources',
      label: 'Resources',
      kpis: [
        { label: 'Team Size', value: 34, change: 2, trend: 'up', icon: '👥' },
        { label: 'Utilization', value: 76, suffix: '%', change: 4, trend: 'up', icon: '📊' },
        { label: 'Bench', value: 4, change: -1, trend: 'down', icon: '💤' },
        { label: 'Overtime Hours', value: 126, change: -8, trend: 'down', icon: '⏰' },
      ],
      columns: [
        { key: 'name', label: 'Name', sortable: true },
        { key: 'role', label: 'Role', sortable: true },
        { key: 'project', label: 'Current Project', sortable: true },
        { key: 'utilization', label: 'Utilization', sortable: true },
        { key: 'overtime', label: 'OT Hours', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { name: 'Tom Bradley', role: 'Sr. Installer', project: 'DC Expansion', utilization: '94%', overtime: 18, status: 'Active', certifications: 'Crane, Electrical, OSHA-30', availability: 'Booked through Apr 15' },
        { name: 'Sarah Kim', role: 'Project Engineer', project: 'Conveyor Upgrade', utilization: '86%', overtime: 8, status: 'Active', certifications: 'PMP, Six Sigma', availability: 'Available after Mar 28' },
        { name: 'Carlos Diaz', role: 'Fleet Manager', project: 'Forklift Refresh', utilization: '72%', overtime: 4, status: 'Active', certifications: 'ASE, Forklift Trainer', availability: 'Partially available' },
        { name: 'Mike Rodriguez', role: 'Installer', project: 'None', utilization: '0%', overtime: 0, status: 'Pending', certifications: 'OSHA-10, Forklift', availability: 'Fully available' },
        { name: 'Anna Lee', role: 'Maintenance Tech', project: 'Multiple', utilization: '68%', overtime: 12, status: 'Active', certifications: 'Electrical, HVAC', availability: 'Booked M-W, available Th-F' },
      ],
      expandedFields: ['certifications', 'availability'],
      chart: {
        type: 'bar',
        title: 'Utilization by Team',
        xKey: 'team',
        dataKeys: ['utilization'],
        colors: ['#2A9D8F'],
        data: [
          { team: 'Installation', utilization: 88 },
          { team: 'Engineering', utilization: 82 },
          { team: 'Fleet Ops', utilization: 74 },
          { team: 'Maintenance', utilization: 68 },
          { team: 'Admin', utilization: 56 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Mike Rodriguez Unassigned', description: 'Mike has been on bench for 5 days. DC Expansion needs 2 more installers. Assign immediately.', impact: 'Reduce bench cost', action: 'Assign to Project' },
        { priority: 'medium', title: 'Overtime Trending Down', description: 'Overtime dropped from 164 to 126 hours. Better resource planning is working. Continue current approach.', impact: 'Save $4,200/month', action: 'View Trend' },
      ],
      actions: [
        { label: 'View Availability', description: 'Team availability calendar with skill-based filtering' },
        { label: 'Generate Resource Report', description: 'Utilization and capacity analysis by team and role' },
        { label: 'Assign to Project', description: 'Match available team members to project needs by skill' },
      ],
    },
    {
      id: 'equipment',
      label: 'Equipment',
      kpis: [
        { label: 'Total Assets', value: 47, change: 3, trend: 'up', icon: '🛠️' },
        { label: 'Maintenance Due', value: 8, change: -2, trend: 'down', icon: '🔧' },
        { label: 'Downtime', value: 14, suffix: ' hrs', change: -22, trend: 'down', icon: '⚠️' },
        { label: 'Avg Age', value: 3.2, suffix: ' yrs', change: 0, trend: 'flat', icon: '📅' },
      ],
      columns: [
        { key: 'asset', label: 'Asset', sortable: true },
        { key: 'type', label: 'Type', sortable: true },
        { key: 'lastService', label: 'Last Service', sortable: true },
        { key: 'nextService', label: 'Next Service', sortable: true },
        { key: 'hours', label: 'Run Hours', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { asset: 'Forklift #1', type: 'Electric Forklift', lastService: 'Mar 5', nextService: 'Apr 5', hours: 2840, status: 'Active', condition: 'Good', alerts: 'None' },
        { asset: 'Forklift #4', type: 'Electric Forklift', lastService: 'Jan 28', nextService: 'Overdue', hours: 3120, status: 'At Risk', condition: 'Fair', alerts: '3 sensor alerts this week' },
        { asset: 'Conveyor Line 1', type: 'Belt Conveyor', lastService: 'Feb 15', nextService: 'May 15', hours: 8400, status: 'Active', condition: 'Good', alerts: 'None' },
        { asset: 'Dock Leveler #2', type: 'Hydraulic Leveler', lastService: 'Mar 12', nextService: 'Jun 12', hours: 1200, status: 'Active', condition: 'Excellent', alerts: 'None' },
        { asset: 'Pallet Wrapper', type: 'Stretch Wrapper', lastService: 'Feb 1', nextService: 'Apr 1', hours: 4600, status: 'Maintenance', condition: 'Fair', alerts: 'Film tension sensor drift' },
        { asset: 'Scissor Lift #2', type: 'Electric Lift', lastService: 'Mar 8', nextService: 'Jun 8', hours: 890, status: 'Active', condition: 'Good', alerts: 'None' },
      ],
      expandedFields: ['condition', 'alerts'],
      chart: {
        type: 'line',
        title: 'Equipment Uptime (12 Months)',
        xKey: 'month',
        dataKeys: ['uptime'],
        colors: ['#2A9D8F'],
        data: [
          { month: 'Jul', uptime: 88 },
          { month: 'Aug', uptime: 90 },
          { month: 'Sep', uptime: 89 },
          { month: 'Oct', uptime: 92 },
          { month: 'Nov', uptime: 91 },
          { month: 'Dec', uptime: 93 },
          { month: 'Jan', uptime: 92 },
          { month: 'Feb', uptime: 94 },
          { month: 'Mar', uptime: 94 },
          { month: 'Apr', uptime: 93 },
          { month: 'May', uptime: 95 },
          { month: 'Jun', uptime: 94 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Forklift #4 Overdue Service', description: 'Forklift #4 is 120 hours past service interval with 3 sensor alerts. Take offline for immediate inspection.', impact: 'Prevent breakdown', action: 'Schedule Now' },
        { priority: 'medium', title: 'Pallet Wrapper Sensor Drift', description: 'Film tension sensor showing drift pattern. Replace sensor during next scheduled maintenance to prevent wrap failures.', impact: 'Prevent 4hr downtime', action: 'Order Part' },
      ],
      actions: [
        { label: 'Schedule Maintenance', description: 'AI-optimized maintenance scheduling to minimize operational impact' },
        { label: 'Generate Asset Report', description: 'Complete equipment inventory with condition and maintenance history' },
        { label: 'Order Parts', description: 'Predictive parts ordering based on maintenance forecasts' },
      ],
    },
    {
      id: 'efficiency',
      label: 'Efficiency',
      kpis: [
        { label: 'Throughput Index', value: 87, change: 4, trend: 'up', icon: '📈' },
        { label: 'Cost Per Unit', value: 3.42, prefix: '$', change: -6, trend: 'down', icon: '💰' },
        { label: 'Cycle Time', value: 2.4, suffix: ' days', change: -8, trend: 'down', icon: '⏱️' },
        { label: 'Waste Rate', value: 2.1, suffix: '%', change: -12, trend: 'down', icon: '♻️' },
      ],
      columns: [
        { key: 'metric', label: 'Metric', sortable: true },
        { key: 'current', label: 'Current', sortable: true },
        { key: 'target', label: 'Target', sortable: true },
        { key: 'gap', label: 'Gap', sortable: true },
        { key: 'trend', label: 'Trend', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { metric: 'Orders Per Hour', current: 47, target: 50, gap: '-3', trend: 'Improving', status: 'Active', initiative: 'Pick route optimization', owner: 'Sarah Kim' },
        { metric: 'Pick Accuracy', current: '99.4%', target: '99.8%', gap: '-0.4%', trend: 'Stable', status: 'Active', initiative: 'Barcode verification', owner: 'Carlos Diaz' },
        { metric: 'Dock-to-Stock', current: '22 min', target: '18 min', gap: '-4 min', trend: 'Improving', status: 'In Progress', initiative: 'Receiving automation', owner: 'Tom Bradley' },
        { metric: 'On-Time Ship', current: '88%', target: '95%', gap: '-7%', trend: 'Declining', status: 'At Risk', initiative: 'Wave planning overhaul', owner: 'Steve M.' },
        { metric: 'Space Utilization', current: '78%', target: '85%', gap: '-7%', trend: 'Improving', status: 'Active', initiative: 'SKU slotting optimization', owner: 'Sarah Kim' },
      ],
      expandedFields: ['initiative', 'owner'],
      chart: {
        type: 'area',
        title: 'Efficiency Index Trend',
        xKey: 'month',
        dataKeys: ['index', 'target'],
        colors: ['#2A9D8F', '#E5E7EB'],
        data: [
          { month: 'Jan', index: 78, target: 90 },
          { month: 'Feb', index: 80, target: 90 },
          { month: 'Mar', index: 82, target: 90 },
          { month: 'Apr', index: 84, target: 90 },
          { month: 'May', index: 86, target: 90 },
          { month: 'Jun', index: 87, target: 90 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'On-Time Shipping Declining', description: 'On-time shipping dropped from 92% to 88%. Wave planning is not accounting for SLA mix. Overhaul needed.', impact: '+7% on-time rate', action: 'Review Wave Planning' },
        { priority: 'medium', title: 'Dock-to-Stock Improving', description: 'Receiving automation cut dock-to-stock from 28 to 22 min. Target of 18 min achievable by adding scan stations.', impact: '-4 min cycle time', action: 'Approve Scan Stations' },
      ],
      actions: [
        { label: 'Generate Efficiency Report', description: 'Comprehensive operational efficiency analysis with benchmarks' },
        { label: 'Run Cost Analysis', description: 'Unit economics breakdown by process and department' },
        { label: 'Export Metrics', description: 'Download all operational KPIs and trend data' },
      ],
    },
  ],
});
