import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'org-lead',
    name: 'Org Lead',
    icon: '\u{1F3E2}',
    dept: 'Strategy',
    deptColor: '#0EA5E9',
    description: 'AI-powered organizational leadership dashboard and strategic planning',
    valueProposition: 'See the whole business at a glance and make data-driven strategic decisions',
    enabled: true,
    buildBatch: 3,
  },
  tabs: [
    {
      id: 'executive-summary',
      label: 'Executive Summary',
      kpis: [
        { label: 'Revenue (MTD)', value: 842000, prefix: '$', change: 12, trend: 'up', icon: '\u{1F4B0}' },
        { label: 'EBITDA Margin', value: 18.4, suffix: '%', change: 2, trend: 'up', icon: '\u{1F4CA}' },
        { label: 'Headcount', value: 127, change: 4, trend: 'up', icon: '\u{1F465}' },
        { label: 'Customer NPS', value: 62, change: 6, trend: 'up', icon: '\u{2B50}' },
      ],
      columns: [
        { key: 'department', label: 'Department', sortable: true },
        { key: 'revenue', label: 'Revenue', sortable: true },
        { key: 'headcount', label: 'HC', sortable: true },
        { key: 'budget', label: 'Budget Status', sortable: true },
        { key: 'keyMetric', label: 'Key Metric', sortable: false },
        { key: 'status', label: 'Health', sortable: true },
      ],
      rows: [
        { department: 'Sales', revenue: 284000, headcount: 18, budget: 'On Track', keyMetric: '78% quota attainment', status: 'Healthy', topRisk: 'Q2 pipeline gap $340K', topWin: 'Velocity Logistics closed $64K' },
        { department: 'Operations', revenue: 0, headcount: 48, budget: 'On Track', keyMetric: '88% on-time delivery', status: 'At Risk', topRisk: 'DC Expansion 3 days behind', topWin: 'Dock automation completed' },
        { department: 'Engineering', revenue: 0, headcount: 22, budget: 'Over', keyMetric: '94% sprint velocity', status: 'At Risk', topRisk: 'Cloud spend +9.2% over budget', topWin: 'WoulfAI platform 96% complete' },
        { department: 'Finance', revenue: 0, headcount: 12, budget: 'On Track', keyMetric: '$42K savings found', status: 'Healthy', topRisk: 'Iron Ridge $41K write-off risk', topWin: 'Automation saving 186 hrs/mo' },
        { department: 'People', revenue: 0, headcount: 8, budget: 'Under', keyMetric: '91% retention', status: 'Healthy', topRisk: '2 engineering flight risks', topWin: 'eNPS up 6 points to 42' },
        { department: 'Support', revenue: 0, headcount: 6, budget: 'Under', keyMetric: '4.2/5 CSAT', status: 'Pending', topRisk: 'TechFlow CSAT dropped to 2.1', topWin: 'Response time below 2hr target' },
      ],
      expandedFields: ['topRisk', 'topWin'],
      chart: {
        type: 'area',
        title: 'Revenue & EBITDA (12 Months)',
        xKey: 'month',
        dataKeys: ['revenue', 'ebitda'],
        colors: ['#0EA5E9', '#059669'],
        data: [
          { month: 'Jul', revenue: 680000, ebitda: 112000 },
          { month: 'Aug', revenue: 710000, ebitda: 124000 },
          { month: 'Sep', revenue: 724000, ebitda: 128000 },
          { month: 'Oct', revenue: 756000, ebitda: 134000 },
          { month: 'Nov', revenue: 788000, ebitda: 140000 },
          { month: 'Dec', revenue: 794000, ebitda: 138000 },
          { month: 'Jan', revenue: 802000, ebitda: 142000 },
          { month: 'Feb', revenue: 818000, ebitda: 148000 },
          { month: 'Mar', revenue: 842000, ebitda: 155000 },
          { month: 'Apr', revenue: 0, ebitda: 0 },
          { month: 'May', revenue: 0, ebitda: 0 },
          { month: 'Jun', revenue: 0, ebitda: 0 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Engineering Comp Crisis', description: 'Two senior engineers flagged as flight risks citing below-market compensation. Losing both would delay WoulfAI launch by 3 months.', impact: '$180K replacement cost', action: 'Approve Comp Adjustments' },
        { priority: 'high', title: 'Q2 Revenue Gap', description: 'Q2 forecast is $340K short of target. Three deals in negotiation (TechFlow, Summit, GlobalShip) total $261K. Close aggressively.', impact: 'Close $340K gap', action: 'Review Pipeline' },
        { priority: 'high', title: 'DC Expansion Behind Schedule', description: 'Phase 2 is 3 days behind due to permit delay. Reassign resources from completed dock automation project.', impact: 'Back on schedule', action: 'Reassign Resources' },
        { priority: 'medium', title: 'TechFlow Account at Risk', description: 'Enterprise customer ($48K ARR) health score dropped to 42/100. 8 support tickets in 30 days. Schedule executive intervention.', impact: '$48K ARR at risk', action: 'Schedule Outreach' },
      ],
      actions: [
        { label: 'Generate Board Deck', description: 'AI-compiled board presentation with financials, ops, and strategic updates' },
        { label: 'Run Cross-Dept Analysis', description: 'Identify inter-department dependencies and bottlenecks' },
        { label: 'Schedule All-Hands', description: 'Prepare company-wide update with department highlights' },
        { label: 'Export Executive Summary', description: 'Download one-page executive summary with key metrics' },
      ],
    },
    {
      id: 'okrs',
      label: 'OKRs',
      kpis: [
        { label: 'Company OKRs', value: 5, change: 0, trend: 'flat', icon: '\u{1F3AF}' },
        { label: 'On Track', value: 3, change: 1, trend: 'up', icon: '\u{2705}' },
        { label: 'At Risk', value: 2, change: -1, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
        { label: 'Avg Progress', value: 62, suffix: '%', change: 8, trend: 'up', icon: '\u{1F4CA}' },
      ],
      columns: [
        { key: 'objective', label: 'Objective', sortable: true },
        { key: 'owner', label: 'Owner', sortable: true },
        { key: 'keyResults', label: 'Key Results', sortable: true },
        { key: 'progress', label: 'Progress', sortable: true },
        { key: 'dueDate', label: 'Due', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { objective: 'Launch WoulfAI Platform', owner: 'Steve M.', keyResults: '3/4 complete', progress: '75%', dueDate: 'Jun 30', status: 'On Track', kr1: 'Stripe live billing (Done)', kr2: '21 agent demos (Done)', kr3: 'First 10 paying customers (4/10)', kr4: '$50K MRR (tracking)' },
        { objective: 'Grow Revenue 25% YoY', owner: 'Sarah M.', keyResults: '2/3 complete', progress: '67%', dueDate: 'Dec 31', status: 'On Track', kr1: '$3.2M pipeline built (Done)', kr2: 'Win rate to 35% (at 32%)', kr3: 'Add 8 new logos (5/8)' },
        { objective: 'Operational Excellence', owner: 'Tom B.', keyResults: '1/3 complete', progress: '40%', dueDate: 'Jun 30', status: 'At Risk', kr1: '95% on-time delivery (at 88%)', kr2: 'Complete DC Phase 2 (62%)', kr3: '99.5% pick accuracy (at 99.4%)' },
        { objective: 'Build World-Class Team', owner: 'Amy J.', keyResults: '2/3 complete', progress: '67%', dueDate: 'Dec 31', status: 'On Track', kr1: 'eNPS above 40 (at 42, Done)', kr2: 'Retention above 90% (at 91%, Done)', kr3: 'Fill all open positions (5/8)' },
        { objective: 'Customer Success', owner: 'David K.', keyResults: '1/3 complete', progress: '45%', dueDate: 'Jun 30', status: 'At Risk', kr1: 'CSAT 4.5/5 (at 4.2)', kr2: 'Churn below 5% (at 6.2%)', kr3: 'NPS above 65 (at 62)' },
      ],
      expandedFields: ['kr1', 'kr2', 'kr3', 'kr4'],
      chart: {
        type: 'bar',
        title: 'OKR Progress by Objective',
        xKey: 'objective',
        dataKeys: ['progress'],
        colors: ['#0EA5E9'],
        data: [
          { objective: 'WoulfAI', progress: 75 },
          { objective: 'Revenue', progress: 67 },
          { objective: 'Team', progress: 67 },
          { objective: 'Customer', progress: 45 },
          { objective: 'Operations', progress: 40 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Operations OKR At Risk', description: 'On-time delivery at 88% vs 95% target. DC expansion delay is the primary blocker. Needs executive attention.', impact: 'OKR miss likely', action: 'Schedule War Room' },
        { priority: 'high', title: 'Customer Success OKR Slipping', description: 'Churn at 6.2% vs 5% target. TechFlow and Pacific Freight accounts driving the gap. Intervention needed.', impact: 'Churn target miss', action: 'Review At-Risk Accounts' },
      ],
      actions: [
        { label: 'Update OKRs', description: 'Refresh OKR progress with latest data from all departments' },
        { label: 'Generate OKR Report', description: 'Board-ready OKR status report with commentary' },
        { label: 'Schedule Check-In', description: 'Book cross-functional OKR review meeting' },
      ],
    },
    {
      id: 'strategic-initiatives',
      label: 'Initiatives',
      kpis: [
        { label: 'Active Initiatives', value: 6, change: 1, trend: 'up', icon: '\u{1F680}' },
        { label: 'On Schedule', value: 4, change: 0, trend: 'flat', icon: '\u{2705}' },
        { label: 'Total Investment', value: 1200000, prefix: '$', change: 0, trend: 'flat', icon: '\u{1F4B0}' },
        { label: 'Expected ROI', value: 340, suffix: '%', change: 12, trend: 'up', icon: '\u{1F4C8}' },
      ],
      columns: [
        { key: 'initiative', label: 'Initiative', sortable: true },
        { key: 'sponsor', label: 'Sponsor', sortable: true },
        { key: 'investment', label: 'Investment', sortable: true },
        { key: 'expectedRoi', label: 'ROI', sortable: true },
        { key: 'timeline', label: 'Timeline', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { initiative: 'WoulfAI SaaS Platform', sponsor: 'Steve M.', investment: 420000, expectedRoi: '680%', timeline: 'H1 2026', status: 'On Track', milestones: '21 agents live, Stripe billing active', risks: 'Engineering capacity, first customer acquisition' },
        { initiative: 'DC Expansion Phase 2', sponsor: 'Tom B.', investment: 340000, expectedRoi: '220%', timeline: 'Q2 2026', status: 'Behind', milestones: '62% complete, electrical in progress', risks: 'Permit delay, material costs' },
        { initiative: 'Fleet Modernization', sponsor: 'Carlos D.', investment: 180000, expectedRoi: '180%', timeline: 'Q2 2026', status: 'On Track', milestones: '4 of 8 forklifts ordered', risks: '8-week lead time' },
        { initiative: 'Market Expansion (West)', sponsor: 'Sarah M.', investment: 120000, expectedRoi: '340%', timeline: 'H2 2026', status: 'Planning', milestones: 'Market research complete', risks: 'Hiring in new markets' },
        { initiative: 'Client Portal v2', sponsor: 'Steve M.', investment: 85000, expectedRoi: '420%', timeline: 'Q2 2026', status: 'On Track', milestones: 'UI complete, API integration', risks: 'None significant' },
        { initiative: 'ISO 27001 Certification', sponsor: 'CISO', investment: 55000, expectedRoi: 'N/A', timeline: 'Q2 2026', status: 'At Risk', milestones: '5 findings open, audit Apr', risks: 'Documentation gaps' },
      ],
      expandedFields: ['milestones', 'risks'],
      chart: {
        type: 'stacked-bar',
        title: 'Investment by Initiative',
        xKey: 'initiative',
        dataKeys: ['spent', 'remaining'],
        colors: ['#0EA5E9', '#E5E7EB'],
        data: [
          { initiative: 'WoulfAI', spent: 280000, remaining: 140000 },
          { initiative: 'DC Phase 2', spent: 252000, remaining: 88000 },
          { initiative: 'Fleet', spent: 72000, remaining: 108000 },
          { initiative: 'Expansion', spent: 18000, remaining: 102000 },
          { initiative: 'Portal v2', spent: 44000, remaining: 41000 },
          { initiative: 'ISO 27001', spent: 32000, remaining: 23000 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'DC Phase 2 Budget Risk', description: 'At 74% budget used and 62% complete, DC expansion risks overrun. Material cost escalation adding 8%.', impact: '$27K potential overrun', action: 'Review Budget' },
        { priority: 'medium', title: 'WoulfAI ROI Tracking Strong', description: 'At 67% of investment spent and 75% OKR progress, WoulfAI is on track for 680% ROI. Maintain momentum.', impact: 'Validate investment', action: 'View ROI Model' },
      ],
      actions: [
        { label: 'Create Initiative', description: 'Propose a new strategic initiative with AI-assisted business case' },
        { label: 'Generate Portfolio Report', description: 'Strategic initiative portfolio status for board review' },
        { label: 'Run ROI Analysis', description: 'Updated return on investment projections for all initiatives' },
      ],
    },
    {
      id: 'team-health',
      label: 'Team Health',
      kpis: [
        { label: 'Overall Health', value: 78, suffix: '/100', change: 4, trend: 'up', icon: '\u{1F49A}' },
        { label: 'Engagement', value: 74, suffix: '%', change: 6, trend: 'up', icon: '\u{1F4CA}' },
        { label: 'Collaboration Score', value: 82, suffix: '/100', change: 3, trend: 'up', icon: '\u{1F91D}' },
        { label: 'Leadership NPS', value: 54, change: 8, trend: 'up', icon: '\u{2B50}' },
      ],
      columns: [
        { key: 'team', label: 'Team', sortable: true },
        { key: 'healthScore', label: 'Health', sortable: true },
        { key: 'engagement', label: 'Engagement', sortable: true },
        { key: 'velocity', label: 'Velocity', sortable: true },
        { key: 'blockers', label: 'Blockers', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { team: 'Sales', healthScore: 84, engagement: '82%', velocity: 'High', blockers: 0, status: 'Healthy', morale: 'Strong - recent wins', topIssue: 'Quota concerns for Q3' },
        { team: 'Engineering', healthScore: 62, engagement: '64%', velocity: 'Medium', blockers: 2, status: 'At Risk', morale: 'Low - comp frustration', topIssue: 'Compensation and career growth' },
        { team: 'Operations', healthScore: 76, engagement: '78%', velocity: 'High', blockers: 1, status: 'Healthy', morale: 'Good - proud of dock project', topIssue: 'Overtime fatigue' },
        { team: 'Finance', healthScore: 82, engagement: '76%', velocity: 'Medium', blockers: 0, status: 'Healthy', morale: 'Stable', topIssue: 'Quarter-end workload' },
        { team: 'Support', healthScore: 68, engagement: '70%', velocity: 'Medium', blockers: 1, status: 'Pending', morale: 'Mixed - burnout concerns', topIssue: 'Ticket volume without headcount' },
        { team: 'People', healthScore: 88, engagement: '86%', velocity: 'High', blockers: 0, status: 'Healthy', morale: 'Strong', topIssue: 'Hiring backlog' },
      ],
      expandedFields: ['morale', 'topIssue'],
      chart: {
        type: 'line',
        title: 'Team Health Trend',
        xKey: 'month',
        dataKeys: ['overall', 'engagement'],
        colors: ['#0EA5E9', '#059669'],
        data: [
          { month: 'Jan', overall: 68, engagement: 62 },
          { month: 'Feb', overall: 70, engagement: 66 },
          { month: 'Mar', overall: 72, engagement: 68 },
          { month: 'Apr', overall: 74, engagement: 70 },
          { month: 'May', overall: 76, engagement: 72 },
          { month: 'Jun', overall: 78, engagement: 74 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Engineering Team Intervention', description: 'Engineering health score at 62 is 16 points below company average. Comp adjustments and career paths needed immediately.', impact: 'Prevent team attrition', action: 'Plan Intervention' },
        { priority: 'medium', title: 'Support Headcount Needed', description: 'Support team burnout signals with ticket volume up 18%. Adding 1 agent improves health score by estimated 12 points.', impact: 'Reduce burnout', action: 'Approve Hire' },
      ],
      actions: [
        { label: 'Run Team Survey', description: 'Quick pulse survey to measure team health across all departments' },
        { label: 'Generate Health Report', description: 'Cross-department team health analysis with intervention recommendations' },
        { label: 'Schedule 1-on-1s', description: 'Book leadership check-ins with department heads' },
      ],
    },
  ],
});
