import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'payables',
    name: 'Payables',
    icon: '\u{1F9FE}',
    dept: 'Finance',
    deptColor: '#059669',
    description: 'AI-powered accounts payable automation and vendor management',
    valueProposition: 'Never miss a discount, eliminate duplicate charges, and automate AP workflows',
    enabled: true,
    buildBatch: 2,
  },
  tabs: [
    {
      id: 'pending-invoices',
      label: 'Pending Invoices',
      kpis: [
        { label: 'Total Payables', value: 423000, prefix: '$', change: 3, trend: 'up', icon: '\u{1F4B0}' },
        { label: 'Pending Approval', value: 12, change: -3, trend: 'down', icon: '\u{1F4CB}' },
        { label: 'Early-Pay Savings', value: 3400, prefix: '$', change: 18, trend: 'up', icon: '\u{1F4B5}' },
        { label: 'Past Due', value: 3, change: -1, trend: 'down', icon: '\u{1F534}' },
      ],
      columns: [
        { key: 'vendor', label: 'Vendor', sortable: true },
        { key: 'invoice', label: 'Invoice #', sortable: true },
        { key: 'amount', label: 'Amount', sortable: true },
        { key: 'dueDate', label: 'Due Date', sortable: true },
        { key: 'approvalStatus', label: 'Approval', sortable: true },
        { key: 'earlyDiscount', label: 'Early Discount', sortable: true },
        { key: 'savings', label: 'Savings', sortable: true },
      ],
      rows: [
        { vendor: 'Acme Supply Co', invoice: 'AC-1203', amount: 18400, dueDate: 'Mar 28', approvalStatus: 'Pending', earlyDiscount: '2.0%', savings: 368, lineItems: 'Fasteners $8.2K, Brackets $6.4K, Hardware $3.8K', poMatch: 'Matched', approvalChain: 'Lisa R. > Steve M.' },
        { vendor: 'LogiParts Inc', invoice: 'LP-8841', amount: 42600, dueDate: 'Mar 25', approvalStatus: 'Pending', earlyDiscount: '1.5%', savings: 639, lineItems: 'Conveyor parts $28K, Motors $14.6K', poMatch: 'Partial - $3,200 variance', approvalChain: 'Tom B. > Finance review' },
        { vendor: 'DataFlow Systems', invoice: 'DF-5102', amount: 8900, dueDate: 'Apr 2', approvalStatus: 'Scheduled', earlyDiscount: 'None', savings: 0, lineItems: 'Software license renewal', poMatch: 'Matched', approvalChain: 'Auto-approved' },
        { vendor: 'TechServ Solutions', invoice: 'TS-2447', amount: 14200, dueDate: 'Mar 22', approvalStatus: 'Overdue', earlyDiscount: 'Expired', savings: 0, lineItems: 'IT support retainer $10K, Hardware repair $4.2K', poMatch: 'Matched', approvalChain: 'Steve M. (pending)' },
        { vendor: 'Warehouse Direct', invoice: 'WD-6178', amount: 27300, dueDate: 'Apr 5', approvalStatus: 'Pending', earlyDiscount: '2.5%', savings: 683, lineItems: 'Racking $18K, Safety equipment $9.3K', poMatch: 'Matched', approvalChain: 'Tom B. > Lisa R.' },
        { vendor: 'Quality Fasteners', invoice: 'QF-9234', amount: 5800, dueDate: 'Mar 30', approvalStatus: 'Pending', earlyDiscount: '1.0%', savings: 58, lineItems: 'Specialty bolts $3.2K, Clamps $2.6K', poMatch: 'Matched', approvalChain: 'Auto-approved (under $10K)' },
        { vendor: 'SafeGuard Insurance', invoice: 'SG-0412', amount: 12400, dueDate: 'Apr 1', approvalStatus: 'Scheduled', earlyDiscount: 'None', savings: 0, lineItems: 'Workers comp premium Q2', poMatch: 'Recurring - matched', approvalChain: 'Auto-approved' },
      ],
      expandedFields: ['lineItems', 'poMatch', 'approvalChain'],
      chart: {
        type: 'bar',
        title: 'Payment Schedule (Next 30 Days)',
        xKey: 'week',
        dataKeys: ['amount'],
        colors: ['#059669'],
        data: [
          { week: 'Mar 20-26', amount: 67000 },
          { week: 'Mar 27-Apr 2', amount: 45600 },
          { week: 'Apr 3-9', amount: 39700 },
          { week: 'Apr 10-16', amount: 22400 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Pay Acme Supply Early', description: 'Acme Supply invoice AC-1203 qualifies for 2% early pay discount. Pay 10 days early to save $368. Deadline in 5 days.', impact: '$368 savings', action: 'Approve Early Payment' },
        { priority: 'medium', title: 'Batch LogiParts Invoices', description: '3 invoices from LogiParts can be batched into one payment, saving $45 in processing fees and reducing reconciliation work.', impact: '$45 + 2 hrs saved', action: 'Batch Payments' },
        { priority: 'medium', title: 'Duplicate Charge Detected', description: 'DataFlow Systems billed maintenance fee twice in consecutive months. $2,100 credit owed.', impact: '$2,100 recovery', action: 'Flag Duplicate' },
        { priority: 'low', title: 'Set Up Auto-Pay', description: '5 recurring vendors under $10K/mo could be auto-paid, saving 8 hours of monthly processing.', impact: '8 hrs/mo saved', action: 'Configure Auto-Pay' },
      ],
      actions: [
        { label: 'Batch Approve', description: 'Review and approve multiple pending invoices in a single workflow' },
        { label: 'Schedule Payments', description: 'Optimize payment timing to capture discounts and manage cash flow' },
        { label: 'Export AP Report', description: 'Download complete accounts payable report with aging analysis' },
        { label: 'Flag Duplicates', description: 'AI scan for duplicate invoices, charges, and billing errors' },
      ],
    },
    {
      id: 'payment-schedule',
      label: 'Payment Schedule',
      kpis: [
        { label: 'Due This Week', value: 67000, prefix: '$', change: -12, trend: 'down', icon: '\u{1F4C5}' },
        { label: 'Due This Month', value: 198000, prefix: '$', change: 4, trend: 'up', icon: '\u{1F4C6}' },
        { label: 'Scheduled', value: 156000, prefix: '$', change: 8, trend: 'up', icon: '\u{2705}' },
        { label: 'Unscheduled', value: 42000, prefix: '$', change: -14, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
      ],
      columns: [
        { key: 'vendor', label: 'Vendor', sortable: true },
        { key: 'amount', label: 'Amount', sortable: true },
        { key: 'dueDate', label: 'Due Date', sortable: true },
        { key: 'payDate', label: 'Pay Date', sortable: true },
        { key: 'method', label: 'Method', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { vendor: 'TechServ Solutions', amount: 14200, dueDate: 'Mar 22', payDate: 'Mar 22', method: 'ACH', status: 'Overdue', terms: 'Net 30', relationship: '2 years' },
        { vendor: 'LogiParts Inc', amount: 42600, dueDate: 'Mar 25', payDate: 'Pending', method: 'Wire', status: 'Pending', terms: 'Net 45', relationship: '4 years' },
        { vendor: 'Acme Supply Co', amount: 18400, dueDate: 'Mar 28', payDate: 'Mar 18', method: 'ACH', status: 'Scheduled', terms: 'Net 30', relationship: '3 years' },
        { vendor: 'Quality Fasteners', amount: 5800, dueDate: 'Mar 30', payDate: 'Mar 29', method: 'ACH', status: 'Scheduled', terms: 'Net 30', relationship: '1 year' },
        { vendor: 'SafeGuard Insurance', amount: 12400, dueDate: 'Apr 1', payDate: 'Apr 1', method: 'Auto-Pay', status: 'Scheduled', terms: 'Quarterly', relationship: '5 years' },
      ],
      expandedFields: ['terms', 'relationship'],
      chart: {
        type: 'stacked-bar',
        title: 'Payments by Week',
        xKey: 'week',
        dataKeys: ['scheduled', 'pending', 'overdue'],
        colors: ['#059669', '#F5920B', '#DC2626'],
        data: [
          { week: 'This Week', scheduled: 32400, pending: 42600, overdue: 14200 },
          { week: 'Next Week', scheduled: 24200, pending: 0, overdue: 0 },
          { week: 'Week 3', scheduled: 39700, pending: 0, overdue: 0 },
          { week: 'Week 4', scheduled: 22400, pending: 0, overdue: 0 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'TechServ Invoice Overdue', description: 'Invoice TS-2447 for $14,200 is past due. TechServ is a critical IT vendor. Pay immediately to maintain relationship.', impact: 'Preserve vendor relationship', action: 'Pay Now' },
        { priority: 'medium', title: 'Optimize Payment Timing', description: 'Paying LogiParts on Mar 25 instead of early preserves $42,600 in float for 7 additional days.', impact: '$42K float preserved', action: 'Schedule Optimally' },
      ],
      actions: [
        { label: 'Optimize Schedule', description: 'AI-optimized payment schedule balancing discounts, float, and relationships' },
        { label: 'Generate Calendar', description: 'Visual payment calendar with cash flow impact analysis' },
        { label: 'Export Schedule', description: 'Download payment schedule with all vendor details' },
      ],
    },
    {
      id: 'vendor-analytics',
      label: 'Vendor Analytics',
      kpis: [
        { label: 'Active Vendors', value: 47, change: 3, trend: 'up', icon: '\u{1F465}' },
        { label: 'Avg Terms', value: 32, suffix: ' days', change: 0, trend: 'flat', icon: '\u{1F4C5}' },
        { label: 'On-Time Payment', value: 94, suffix: '%', change: 2, trend: 'up', icon: '\u{2705}' },
        { label: 'Vendor Satisfaction', value: 4.1, suffix: '/5', change: 3, trend: 'up', icon: '\u{2B50}' },
      ],
      columns: [
        { key: 'vendor', label: 'Vendor', sortable: true },
        { key: 'annualSpend', label: 'Annual Spend', sortable: true },
        { key: 'invoiceCount', label: 'Invoices', sortable: true },
        { key: 'avgPayTime', label: 'Avg Pay Time', sortable: true },
        { key: 'discountsCaptured', label: 'Discounts Captured', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { vendor: 'LogiParts Inc', annualSpend: 480000, invoiceCount: 48, avgPayTime: '28 days', discountsCaptured: '$4,200', status: 'Active', category: 'Parts & Components', contractEnd: 'Dec 2025' },
        { vendor: 'Acme Supply Co', annualSpend: 220000, invoiceCount: 24, avgPayTime: '22 days', discountsCaptured: '$3,800', status: 'Active', category: 'Hardware & Supplies', contractEnd: 'Sep 2025' },
        { vendor: 'DataFlow Systems', annualSpend: 106000, invoiceCount: 12, avgPayTime: '30 days', discountsCaptured: '$0', status: 'Active', category: 'Software', contractEnd: 'Jun 2025' },
        { vendor: 'Warehouse Direct', annualSpend: 340000, invoiceCount: 36, avgPayTime: '26 days', discountsCaptured: '$6,400', status: 'Active', category: 'Racking & Equipment', contractEnd: 'Mar 2026' },
        { vendor: 'TechServ Solutions', annualSpend: 168000, invoiceCount: 12, avgPayTime: '34 days', discountsCaptured: '$0', status: 'Active', category: 'IT Services', contractEnd: 'Nov 2025' },
      ],
      expandedFields: ['category', 'contractEnd'],
      chart: {
        type: 'bar',
        title: 'Top Vendors by Annual Spend',
        xKey: 'vendor',
        dataKeys: ['spend'],
        colors: ['#059669'],
        data: [
          { vendor: 'LogiParts', spend: 480000 },
          { vendor: 'Warehouse Direct', spend: 340000 },
          { vendor: 'Acme Supply', spend: 220000 },
          { vendor: 'TechServ', spend: 168000 },
          { vendor: 'DataFlow', spend: 106000 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Negotiate Volume Discount', description: 'LogiParts and Warehouse Direct combined spend is $820K/yr. Negotiate volume discount for potential 3-5% savings.', impact: '$24K-$41K/yr savings', action: 'Start Negotiation' },
        { priority: 'medium', title: 'DataFlow Contract Renewal', description: 'DataFlow Systems contract expires Jun 2025. Begin renewal discussions now to lock in current pricing.', impact: 'Prevent price increase', action: 'Schedule Review' },
      ],
      actions: [
        { label: 'Generate Vendor Report', description: 'Comprehensive vendor performance and spend analysis' },
        { label: 'Run Spend Analysis', description: 'Category-level spend analysis with consolidation opportunities' },
        { label: 'Export Vendor Data', description: 'Download vendor master list with performance metrics' },
      ],
    },
    {
      id: 'discounts',
      label: 'Discounts',
      kpis: [
        { label: 'Available Discounts', value: 3400, prefix: '$', change: 14, trend: 'up', icon: '\u{1F4B5}' },
        { label: 'Captured YTD', value: 12000, prefix: '$', change: 22, trend: 'up', icon: '\u{2705}' },
        { label: 'Missed YTD', value: 4200, prefix: '$', change: -8, trend: 'down', icon: '\u{1F534}' },
        { label: 'Avg Discount', value: 2.1, suffix: '%', change: 0, trend: 'flat', icon: '\u{1F4CA}' },
      ],
      columns: [
        { key: 'vendor', label: 'Vendor', sortable: true },
        { key: 'invoice', label: 'Invoice', sortable: true },
        { key: 'amount', label: 'Invoice Amount', sortable: true },
        { key: 'discountPercent', label: 'Discount %', sortable: true },
        { key: 'savings', label: 'Savings', sortable: true },
        { key: 'deadline', label: 'Deadline', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { vendor: 'Warehouse Direct', invoice: 'WD-6178', amount: 27300, discountPercent: '2.5%', savings: 683, deadline: 'Mar 26', status: 'Open', daysLeft: 6, paymentMethod: 'ACH' },
        { vendor: 'Acme Supply Co', invoice: 'AC-1203', amount: 18400, discountPercent: '2.0%', savings: 368, deadline: 'Mar 23', status: 'Open', daysLeft: 3, paymentMethod: 'ACH' },
        { vendor: 'LogiParts Inc', invoice: 'LP-8841', amount: 42600, discountPercent: '1.5%', savings: 639, deadline: 'Mar 18', status: 'Pending', daysLeft: 0, paymentMethod: 'Wire' },
        { vendor: 'Quality Fasteners', invoice: 'QF-9234', amount: 5800, discountPercent: '1.0%', savings: 58, deadline: 'Mar 25', status: 'Open', daysLeft: 5, paymentMethod: 'ACH' },
      ],
      expandedFields: ['daysLeft', 'paymentMethod'],
      chart: {
        type: 'line',
        title: 'Discount Capture Rate (6 Months)',
        xKey: 'month',
        dataKeys: ['captured', 'missed'],
        colors: ['#059669', '#DC2626'],
        data: [
          { month: 'Jan', captured: 1400, missed: 1200 },
          { month: 'Feb', captured: 1800, missed: 800 },
          { month: 'Mar', captured: 2200, missed: 600 },
          { month: 'Apr', captured: 2400, missed: 500 },
          { month: 'May', captured: 2100, missed: 700 },
          { month: 'Jun', captured: 2100, missed: 400 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'LogiParts Discount Expiring Today', description: 'LogiParts discount of $639 on invoice LP-8841 expires today. Approve immediately or lose the saving.', impact: '$639 at risk', action: 'Approve Now' },
        { priority: 'high', title: 'Acme Discount in 3 Days', description: 'Acme Supply 2% discount worth $368 expires in 3 days. Approve and schedule early payment.', impact: '$368 savings', action: 'Schedule Payment' },
      ],
      actions: [
        { label: 'Capture All Discounts', description: 'Auto-approve and schedule all available early-pay discounts' },
        { label: 'Generate Discount Report', description: 'Track captured vs missed discounts with trend analysis' },
        { label: 'Set Discount Alerts', description: 'Automated alerts when discount deadlines approach' },
      ],
    },
  ],
});
