import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'research',
    name: 'Research',
    icon: '🔬',
    dept: 'Strategy',
    deptColor: '#0EA5E9',
    description: 'AI-powered market research, competitive intelligence, and trend analysis',
    valueProposition: 'Know your market, track competitors, and spot opportunities before anyone else',
    enabled: true,
    buildBatch: 3,
  },
  tabs: [
    {
      id: 'market-overview',
      label: 'Market Overview',
      kpis: [
        { label: 'TAM', value: 4200000000, prefix: '$', change: 8, trend: 'up', icon: '🌍' },
        { label: 'Market Growth', value: 12, suffix: '%', change: 2, trend: 'up', icon: '📈' },
        { label: 'Our Share', value: 0.3, suffix: '%', change: 18, trend: 'up', icon: '🎯' },
        { label: 'Competitors Tracked', value: 24, change: 3, trend: 'up', icon: '🔍' },
      ],
      columns: [
        { key: 'segment', label: 'Segment', sortable: true },
        { key: 'size', label: 'Market Size', sortable: true },
        { key: 'growth', label: 'Growth %', sortable: true },
        { key: 'ourPosition', label: 'Our Position', sortable: true },
        { key: 'topPlayer', label: 'Top Player', sortable: true },
        { key: 'opportunity', label: 'Opportunity', sortable: true },
      ],
      rows: [
        { segment: 'Warehouse Automation', size: '$1.8B', growth: '14%', ourPosition: 'Emerging', topPlayer: 'Dematic', opportunity: 'High', keyTrend: 'AMR adoption accelerating', entryBarrier: 'Moderate - partnerships available' },
        { segment: 'WMS Software', size: '$3.2B', growth: '11%', ourPosition: 'Niche', topPlayer: 'Manhattan Assoc.', opportunity: 'High', keyTrend: 'Cloud-native WMS demand', entryBarrier: 'Low - SaaS model accessible' },
        { segment: '3PL Services', size: '$1.1B', growth: '9%', ourPosition: 'Active', topPlayer: 'XPO Logistics', opportunity: 'Medium', keyTrend: 'E-commerce overflow demand', entryBarrier: 'Medium - capital intensive' },
        { segment: 'Systems Integration', size: '$680M', growth: '10%', ourPosition: 'Strong', topPlayer: 'Bastian Solutions', opportunity: 'High', keyTrend: 'Retrofit demand growing', entryBarrier: 'High - expertise required' },
        { segment: 'Conveyor Systems', size: '$2.4B', growth: '8%', ourPosition: 'Active', topPlayer: 'Hytrol', opportunity: 'Medium', keyTrend: 'Modular designs preferred', entryBarrier: 'Medium - certification needed' },
      ],
      expandedFields: ['keyTrend', 'entryBarrier'],
      chart: {
        type: 'bar',
        title: 'Market Size by Segment ($B)',
        xKey: 'segment',
        dataKeys: ['size'],
        colors: ['#0EA5E9'],
        data: [
          { segment: 'WMS', size: 3.2 },
          { segment: 'Conveyor', size: 2.4 },
          { segment: 'Automation', size: 1.8 },
          { segment: '3PL', size: 1.1 },
          { segment: 'Integration', size: 0.68 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'WMS Market Entry Window', description: 'Cloud-native WMS segment growing 11% with 60% of mid-market still on legacy systems. Low barrier to entry with SaaS model.', impact: 'Address $3.2B market', action: 'View Analysis' },
        { priority: 'medium', title: 'Retrofit Demand Spike', description: 'Systems integration retrofit requests up 34% YoY. Existing expertise positions Woulf Group well.', impact: 'Capture $12M pipeline', action: 'Build Service Package' },
      ],
      actions: [
        { label: 'Generate Market Report', description: 'Comprehensive market analysis with size, growth, and opportunity scoring' },
        { label: 'Run Competitor Scan', description: 'AI-powered competitive landscape analysis with positioning map' },
        { label: 'Export Research', description: 'Download market research data for strategy presentations' },
        { label: 'Set Market Alerts', description: 'Automated alerts on market moves, competitor actions, and trend shifts' },
      ],
    },
    {
      id: 'competitors',
      label: 'Competitors',
      kpis: [
        { label: 'Tracked', value: 24, change: 3, trend: 'up', icon: '🔍' },
        { label: 'Alerts This Week', value: 8, change: 2, trend: 'up', icon: '🔔' },
        { label: 'Win Rate vs Top 5', value: 38, suffix: '%', change: 6, trend: 'up', icon: '📊' },
        { label: 'Intel Reports', value: 12, change: 4, trend: 'up', icon: '📄' },
      ],
      columns: [
        { key: 'competitor', label: 'Competitor', sortable: true },
        { key: 'segment', label: 'Primary Segment', sortable: true },
        { key: 'estRevenue', label: 'Est. Revenue', sortable: true },
        { key: 'headcount', label: 'Headcount', sortable: true },
        { key: 'threat', label: 'Threat Level', sortable: true },
        { key: 'recentMove', label: 'Recent Move', sortable: true },
      ],
      rows: [
        { competitor: 'Bastian Solutions', segment: 'Integration', estRevenue: '$420M', headcount: 2800, threat: 'High', recentMove: 'Acquired robotics startup', strengths: 'Toyota backing, global reach', weaknesses: 'Slow on software innovation' },
        { competitor: 'Conveyco', segment: 'Integration', estRevenue: '$180M', headcount: 600, threat: 'High', recentMove: 'Launched AI warehouse planner', strengths: 'Strong mid-market presence', weaknesses: 'Limited geographic coverage' },
        { competitor: 'RivalCo Systems', segment: 'WMS', estRevenue: '$95M', headcount: 340, threat: 'Medium', recentMove: 'Series C funding $45M', strengths: 'Modern cloud platform', weaknesses: 'No hardware capability' },
        { competitor: 'Dematic', segment: 'Automation', estRevenue: '$3.8B', headcount: 12000, threat: 'Low', recentMove: 'New DC in Texas', strengths: 'Full-stack automation', weaknesses: 'Too large for mid-market' },
        { competitor: 'Numina Group', segment: 'Integration', estRevenue: '$45M', headcount: 120, threat: 'Medium', recentMove: 'Voice picking partnership', strengths: 'Niche expertise', weaknesses: 'Small team limits scale' },
      ],
      expandedFields: ['strengths', 'weaknesses'],
      chart: {
        type: 'bar',
        title: 'Win Rate vs Top Competitors',
        xKey: 'competitor',
        dataKeys: ['winRate'],
        colors: ['#0EA5E9'],
        data: [
          { competitor: 'Numina', winRate: 62 },
          { competitor: 'RivalCo', winRate: 48 },
          { competitor: 'Conveyco', winRate: 34 },
          { competitor: 'Bastian', winRate: 28 },
          { competitor: 'Dematic', winRate: 18 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Conveyco AI Launch', description: 'Conveyco launched an AI warehouse planning tool this month. Directly competes with WoulfAI positioning. Prepare battlecard.', impact: 'Competitive response needed', action: 'Create Battlecard' },
        { priority: 'medium', title: 'RivalCo Funding Alert', description: 'RivalCo raised $45M Series C for WMS expansion. Expect aggressive pricing in mid-market.', impact: 'Pricing pressure expected', action: 'Monitor Pricing' },
      ],
      actions: [
        { label: 'Generate Battlecard', description: 'AI-crafted competitive battlecard with talk tracks and objection handling' },
        { label: 'Run Win/Loss Analysis', description: 'Analyze deals won and lost against specific competitors' },
        { label: 'Export Intel Report', description: 'Download competitive intelligence briefing for sales team' },
      ],
    },
    {
      id: 'trends',
      label: 'Trends',
      kpis: [
        { label: 'Trends Tracked', value: 18, change: 4, trend: 'up', icon: '📈' },
        { label: 'Emerging', value: 5, change: 2, trend: 'up', icon: '🌟' },
        { label: 'Impact Score', value: 74, suffix: '/100', change: 6, trend: 'up', icon: '📊' },
        { label: 'Reports Generated', value: 8, change: 3, trend: 'up', icon: '📄' },
      ],
      columns: [
        { key: 'trend', label: 'Trend', sortable: true },
        { key: 'category', label: 'Category', sortable: true },
        { key: 'impact', label: 'Impact', sortable: true },
        { key: 'timeline', label: 'Timeline', sortable: true },
        { key: 'relevance', label: 'Relevance', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { trend: 'Autonomous Mobile Robots', category: 'Technology', impact: 'High', timeline: '12-24 months', relevance: 'Direct', status: 'Accelerating', description: 'AMR adoption in warehouses growing 40% YoY', actionRequired: 'Build AMR integration capability' },
        { trend: 'AI-Powered WMS', category: 'Software', impact: 'High', timeline: '6-12 months', relevance: 'Direct', status: 'Emerging', description: 'ML-driven slotting and wave planning', actionRequired: 'Core to WoulfAI platform' },
        { trend: 'Nearshoring Supply Chains', category: 'Market', impact: 'Medium', timeline: '12-36 months', relevance: 'Indirect', status: 'Growing', description: 'Companies moving warehouses closer to demand', actionRequired: 'Target nearshore DC buildouts' },
        { trend: 'Sustainability Requirements', category: 'Regulatory', impact: 'Medium', timeline: '24-36 months', relevance: 'Moderate', status: 'Growing', description: 'Carbon reporting for logistics operations', actionRequired: 'Add sustainability metrics to platform' },
        { trend: 'Labor Shortage', category: 'Workforce', impact: 'High', timeline: 'Now', relevance: 'Direct', status: 'Persistent', description: 'Warehouse labor gap widening, driving automation', actionRequired: 'Position automation as labor solution' },
      ],
      expandedFields: ['description', 'actionRequired'],
      chart: {
        type: 'area',
        title: 'Trend Impact Over Time',
        xKey: 'quarter',
        dataKeys: ['automation', 'ai', 'labor'],
        colors: ['#0EA5E9', '#059669', '#F5920B'],
        data: [
          { quarter: 'Q1', automation: 60, ai: 40, labor: 80 },
          { quarter: 'Q2', automation: 65, ai: 52, labor: 82 },
          { quarter: 'Q3', automation: 72, ai: 64, labor: 84 },
          { quarter: 'Q4', automation: 78, ai: 74, labor: 85 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'AMR Integration Capability', description: 'AMR adoption is accelerating. Clients are asking about AMR compatibility. Build integration partnerships now.', impact: 'New revenue stream', action: 'Identify Partners' },
        { priority: 'medium', title: 'Position for Nearshoring', description: 'Nearshoring trend creating demand for new DC buildouts. Target companies moving operations to Mexico/US border states.', impact: 'New market segment', action: 'Create Campaign' },
      ],
      actions: [
        { label: 'Generate Trend Report', description: 'Comprehensive trend analysis with business impact assessment' },
        { label: 'Set Trend Alerts', description: 'Automated monitoring for market shifts and emerging trends' },
        { label: 'Export Research', description: 'Download trend data for strategic planning sessions' },
      ],
    },
    {
      id: 'reports',
      label: 'Reports',
      kpis: [
        { label: 'Published', value: 24, change: 4, trend: 'up', icon: '📚' },
        { label: 'In Progress', value: 3, change: 1, trend: 'up', icon: '✍️' },
        { label: 'Avg Views', value: 34, change: 12, trend: 'up', icon: '👁️' },
        { label: 'Stakeholder NPS', value: 72, change: 8, trend: 'up', icon: '⭐' },
      ],
      columns: [
        { key: 'report', label: 'Report', sortable: true },
        { key: 'type', label: 'Type', sortable: true },
        { key: 'published', label: 'Published', sortable: true },
        { key: 'views', label: 'Views', sortable: true },
        { key: 'audience', label: 'Audience', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { report: 'Q1 Market Landscape', type: 'Quarterly', published: 'Mar 15', views: 48, audience: 'Leadership', status: 'Published', keyFinding: 'WMS market shift to cloud-native', downloadCount: 12 },
        { report: 'Competitor Battlecards', type: 'Ongoing', published: 'Mar 18', views: 62, audience: 'Sales', status: 'Published', keyFinding: 'Updated for Conveyco AI launch', downloadCount: 28 },
        { report: 'AMR Integration Brief', type: 'Ad-hoc', published: 'Mar 10', views: 34, audience: 'Engineering', status: 'Published', keyFinding: '3 AMR vendors compatible with our systems', downloadCount: 8 },
        { report: '2026 Strategic Outlook', type: 'Annual', published: 'In Progress', views: 0, audience: 'Board', status: 'Draft', keyFinding: 'Draft 60% complete', downloadCount: 0 },
        { report: 'Nearshoring Opportunity', type: 'Ad-hoc', published: 'In Progress', views: 0, audience: 'Sales', status: 'Draft', keyFinding: 'Researching 12 target companies', downloadCount: 0 },
      ],
      expandedFields: ['keyFinding', 'downloadCount'],
      chart: {
        type: 'line',
        title: 'Report Engagement',
        xKey: 'month',
        dataKeys: ['views', 'downloads'],
        colors: ['#0EA5E9', '#059669'],
        data: [
          { month: 'Jan', views: 84, downloads: 22 },
          { month: 'Feb', views: 96, downloads: 28 },
          { month: 'Mar', views: 144, downloads: 48 },
          { month: 'Apr', views: 120, downloads: 34 },
          { month: 'May', views: 132, downloads: 40 },
          { month: 'Jun', views: 156, downloads: 52 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Strategic Outlook Overdue', description: '2026 Strategic Outlook is 60% complete but was due Mar 1. Board meeting is Apr 15. Prioritize completion.', impact: 'Board readiness', action: 'Expedite Draft' },
        { priority: 'medium', title: 'High Battlecard Engagement', description: 'Competitor battlecards have highest download rate. Create dedicated Slack channel for real-time intel.', impact: 'Faster sales response', action: 'Create Channel' },
      ],
      actions: [
        { label: 'Create Report', description: 'AI-assisted research report generation from data and sources' },
        { label: 'Schedule Distribution', description: 'Set up automated report delivery to stakeholder groups' },
        { label: 'Export All Research', description: 'Download complete research library for offline access' },
      ],
    },
  ],
});
