import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'sales-intel',
    name: 'Sales Intel',
    icon: '\u{1F50D}',
    dept: 'Sales',
    deptColor: '#F5920B',
    description: 'AI-powered competitive intelligence and market research',
    valueProposition: 'Know your competitors, track market shifts, and find new opportunities before anyone else',
    enabled: true,
    buildBatch: 2,
  },
  tabs: [
    {
      id: 'competitor-tracker',
      label: 'Competitor Tracker',
      kpis: [
        { label: 'Tracked Competitors', value: 8, change: 1, trend: 'up', icon: '\u{1F3AF}' },
        { label: 'Intel Updates/Week', value: 24, change: 6, trend: 'up', icon: '\u{1F4F0}' },
        { label: 'Win Rate vs Top 3', value: 38, suffix: '%', change: 4, trend: 'up', icon: '\u{1F4CA}' },
        { label: 'Deals Lost to Comp', value: 3, change: -2, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
      ],
      columns: [
        { key: 'competitor', label: 'Competitor', sortable: true },
        { key: 'segment', label: 'Segment', sortable: true },
        { key: 'winRate', label: 'Our Win Rate', sortable: true },
        { key: 'recentActivity', label: 'Recent Activity', sortable: false },
        { key: 'threatLevel', label: 'Threat', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { competitor: 'RivalCo Systems', segment: 'Enterprise WMS', winRate: '32%', recentActivity: 'New pricing tier announced', threatLevel: 'High', status: 'Active', strengths: 'Brand recognition, large install base', weaknesses: 'Slow implementation, rigid customization', recentDeals: 'Lost MegaCorp deal ($120K)' },
        { competitor: 'FlexWare Inc', segment: 'Mid-Market WMS', winRate: '48%', recentActivity: 'Acquired a pick-to-light vendor', threatLevel: 'Medium', status: 'Active', strengths: 'Modern UI, fast deployment', weaknesses: 'Limited integrations, no 3PL support', recentDeals: 'Won 2 of last 5 head-to-heads' },
        { competitor: 'LogiStack', segment: 'SMB Warehouse', winRate: '55%', recentActivity: 'Launched free tier', threatLevel: 'Medium', status: 'Active', strengths: 'Low price, easy setup', weaknesses: 'No enterprise features, limited reporting', recentDeals: 'Lost 1 price-sensitive deal' },
        { competitor: 'WareBot AI', segment: 'AI-Native WMS', winRate: '22%', recentActivity: 'Series B funding $45M', threatLevel: 'High', status: 'Active', strengths: 'AI-first approach, investor buzz', weaknesses: 'Unproven at scale, startup risk', recentDeals: 'New entrant in 3 recent bids' },
        { competitor: 'OmniChain Pro', segment: 'Supply Chain Suite', winRate: '42%', recentActivity: 'Hired new CRO from SAP', threatLevel: 'Medium', status: 'Active', strengths: 'End-to-end supply chain', weaknesses: 'Overly complex, long sales cycle', recentDeals: 'Won Apex Fulfillment evaluation' },
      ],
      expandedFields: ['strengths', 'weaknesses', 'recentDeals'],
      chart: {
        type: 'bar',
        title: 'Win Rate vs Competitors',
        xKey: 'competitor',
        dataKeys: ['winRate'],
        colors: ['#F5920B'],
        data: [
          { competitor: 'LogiStack', winRate: 55 },
          { competitor: 'FlexWare', winRate: 48 },
          { competitor: 'OmniChain', winRate: 42 },
          { competitor: 'RivalCo', winRate: 32 },
          { competitor: 'WareBot AI', winRate: 22 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'WareBot AI Emerging Threat', description: 'WareBot AI closed $45M Series B and appeared in 3 recent bids. Our win rate against them is only 22%. Need competitive battle cards.', impact: 'Protect pipeline', action: 'Create Battle Card' },
        { priority: 'high', title: 'RivalCo Pricing Change', description: 'RivalCo announced new pricing 15% below ours for enterprise tier. Prepare value-based positioning for active deals.', impact: '4 deals affected', action: 'Update Positioning' },
        { priority: 'medium', title: 'FlexWare Acquisition Impact', description: 'FlexWare acquiring pick-to-light vendor fills a gap in their offering. Update competitive matrix.', impact: 'Update sales enablement', action: 'Update Matrix' },
      ],
      actions: [
        { label: 'Generate Battle Cards', description: 'AI-compiled competitive battle cards with objection handling' },
        { label: 'Set Competitor Alerts', description: 'Real-time alerts for competitor news, pricing changes, and hires' },
        { label: 'Export Intel Report', description: 'Download comprehensive competitive intelligence summary' },
        { label: 'Win/Loss Analysis', description: 'Deep analysis of recent wins and losses by competitor' },
      ],
    },
    {
      id: 'market-signals',
      label: 'Market Signals',
      kpis: [
        { label: 'Signals This Week', value: 18, change: 4, trend: 'up', icon: '\u{1F4E1}' },
        { label: 'Opportunities Found', value: 6, change: 2, trend: 'up', icon: '\u{1F4A1}' },
        { label: 'Industry Growth', value: 12, suffix: '%', change: 2, trend: 'up', icon: '\u{1F4C8}' },
        { label: 'Alert Accuracy', value: 88, suffix: '%', change: 4, trend: 'up', icon: '\u{1F3AF}' },
      ],
      columns: [
        { key: 'signal', label: 'Signal', sortable: true },
        { key: 'source', label: 'Source', sortable: true },
        { key: 'relevance', label: 'Relevance', sortable: true },
        { key: 'category', label: 'Category', sortable: true },
        { key: 'date', label: 'Date', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { signal: 'MegaCorp expanding to 3 new DCs', source: 'SEC Filing', relevance: 'High', category: 'Expansion', date: 'Mar 18', status: 'New', implication: 'Potential $340K multi-site deal', actionRequired: 'Alert Sarah M. immediately' },
        { signal: 'Warehouse labor shortage report', source: 'Industry Report', relevance: 'Medium', category: 'Trend', date: 'Mar 16', status: 'Active', implication: 'Automation demand increasing', actionRequired: 'Update marketing messaging' },
        { signal: 'New tariff on conveyor components', source: 'Trade News', relevance: 'High', category: 'Regulatory', date: 'Mar 14', status: 'Active', implication: '8-12% cost increase on equipment', actionRequired: 'Notify operations team' },
        { signal: 'Competitor layoffs at RivalCo', source: 'LinkedIn', relevance: 'Medium', category: 'Competitor', date: 'Mar 12', status: 'Active', implication: 'Possible service quality drop', actionRequired: 'Target their at-risk accounts' },
        { signal: 'New EPA warehouse standards', source: 'Federal Register', relevance: 'Low', category: 'Regulatory', date: 'Mar 10', status: 'Pending', implication: 'Compliance consulting opportunity', actionRequired: 'Add to solutions page' },
      ],
      expandedFields: ['implication', 'actionRequired'],
      chart: {
        type: 'pie',
        title: 'Signals by Category',
        dataKeys: ['value'],
        data: [
          { name: 'Expansion', value: 8 },
          { name: 'Competitor', value: 5 },
          { name: 'Regulatory', value: 3 },
          { name: 'Trend', value: 2 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'MegaCorp DC Expansion', description: 'MegaCorp filed for 3 new distribution centers. They are an active prospect. Alert sales immediately for multi-site opportunity.', impact: '$340K opportunity', action: 'Alert Sales Team' },
        { priority: 'high', title: 'Tariff Impact on Pricing', description: 'New tariffs will increase conveyor component costs 8-12%. Review pricing strategy and lock in current vendor quotes.', impact: 'Protect margins', action: 'Review Pricing' },
      ],
      actions: [
        { label: 'Configure Alerts', description: 'Set up AI-powered alerts for companies, industries, and topics' },
        { label: 'Generate Market Report', description: 'Weekly market intelligence summary with actionable insights' },
        { label: 'Export Signals', description: 'Download all market signals with analysis and recommendations' },
      ],
    },
    {
      id: 'prospect-intel',
      label: 'Prospect Intel',
      kpis: [
        { label: 'Enriched Prospects', value: 142, change: 18, trend: 'up', icon: '\u{1F464}' },
        { label: 'New Intent Signals', value: 9, change: 3, trend: 'up', icon: '\u{1F4E1}' },
        { label: 'Avg Fit Score', value: 72, suffix: '/100', change: 4, trend: 'up', icon: '\u{1F3AF}' },
        { label: 'Ready to Contact', value: 14, change: 5, trend: 'up', icon: '\u{1F4DE}' },
      ],
      columns: [
        { key: 'company', label: 'Company', sortable: true },
        { key: 'fitScore', label: 'Fit Score', sortable: true },
        { key: 'intentSignal', label: 'Intent Signal', sortable: false },
        { key: 'revenue', label: 'Est. Revenue', sortable: true },
        { key: 'employees', label: 'Employees', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { company: 'NovaTech Industries', fitScore: 92, intentSignal: 'Job posting for WMS admin', revenue: '$180M', employees: 1200, status: 'New', decisionMakers: 'VP Ops: Jane Chen, CTO: Mark Liu', techStack: 'SAP ERP, manual warehouse ops', painPoints: 'Scaling issues, manual processes' },
        { company: 'BlueRidge Supply', fitScore: 85, intentSignal: 'Visited pricing page 3x', revenue: '$45M', employees: 280, status: 'Active', decisionMakers: 'Owner: Tom Ridge', techStack: 'QuickBooks, spreadsheets', painPoints: 'Growing too fast for manual ops' },
        { company: 'Horizon Fulfillment', fitScore: 78, intentSignal: 'Downloaded warehouse guide', revenue: '$92M', employees: 540, status: 'New', decisionMakers: 'Dir. Ops: Lisa Park', techStack: 'Fishbowl, basic WMS', painPoints: 'Pick accuracy issues' },
        { company: 'Atlas Distribution', fitScore: 71, intentSignal: 'Competitor contract expiring', revenue: '$220M', employees: 1800, status: 'Active', decisionMakers: 'SVP Supply Chain: Robert Wu', techStack: 'RivalCo WMS (unhappy)', painPoints: 'Poor support, slow updates' },
        { company: 'Pinnacle Foods Co', fitScore: 64, intentSignal: 'Industry event attendee', revenue: '$340M', employees: 2400, status: 'Pending', decisionMakers: 'VP Logistics: Maria Santos', techStack: 'Oracle WMS', painPoints: 'Cost reduction initiative' },
      ],
      expandedFields: ['decisionMakers', 'techStack', 'painPoints'],
      chart: {
        type: 'bar',
        title: 'Prospects by Fit Score',
        xKey: 'range',
        dataKeys: ['count'],
        colors: ['#F5920B'],
        data: [
          { range: '90-100', count: 8 },
          { range: '80-89', count: 18 },
          { range: '70-79', count: 34 },
          { range: '60-69', count: 42 },
          { range: 'Below 60', count: 40 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'NovaTech Hiring WMS Admin', description: 'NovaTech (fit score 92) posted a WMS admin job. They have no WMS. This is a strong buying signal. Contact VP Ops Jane Chen now.', impact: '$180K opportunity', action: 'Create Outreach' },
        { priority: 'high', title: 'Atlas RivalCo Contract Expiring', description: 'Atlas Distribution uses RivalCo (unhappy) with contract expiring Q3. Perfect timing for displacement campaign.', impact: '$220K opportunity', action: 'Start Campaign' },
      ],
      actions: [
        { label: 'Enrich Prospects', description: 'AI-powered enrichment with firmographic, technographic, and intent data' },
        { label: 'Generate Outreach', description: 'Personalized outreach sequences based on prospect intelligence' },
        { label: 'Export Prospects', description: 'Download enriched prospect list with fit scores and signals' },
      ],
    },
    {
      id: 'win-loss',
      label: 'Win/Loss Analysis',
      kpis: [
        { label: 'Overall Win Rate', value: 34, suffix: '%', change: 3, trend: 'up', icon: '\u{1F3C6}' },
        { label: 'Deals Analyzed', value: 48, change: 8, trend: 'up', icon: '\u{1F4CA}' },
        { label: 'Top Loss Reason', value: 0, change: 0, trend: 'flat', icon: '\u{1F4AC}' },
        { label: 'Improvement YoY', value: 6, suffix: '%', change: 2, trend: 'up', icon: '\u{1F4C8}' },
      ],
      columns: [
        { key: 'deal', label: 'Deal', sortable: true },
        { key: 'outcome', label: 'Outcome', sortable: true },
        { key: 'competitor', label: 'Lost To', sortable: true },
        { key: 'value', label: 'Value', sortable: true },
        { key: 'primaryReason', label: 'Primary Reason', sortable: true },
        { key: 'stage', label: 'Lost Stage', sortable: true },
      ],
      rows: [
        { deal: 'GlobalTech WMS', outcome: 'Closed Won', competitor: 'FlexWare', value: 78000, primaryReason: 'Better integration story', stage: 'Negotiation', feedback: 'Customer valued ERP integration depth', lessonLearned: 'Integration demo wins deals' },
        { deal: 'MidWest Fulfillment', outcome: 'At Risk', competitor: 'RivalCo', value: 95000, primaryReason: 'Price objection', stage: 'Proposal', feedback: 'RivalCo undercut by 20%', lessonLearned: 'Need ROI calculator' },
        { deal: 'Pacific Coast DC', outcome: 'At Risk', competitor: 'WareBot AI', value: 64000, primaryReason: 'AI features', stage: 'Qualified', feedback: 'Wanted AI-native solution', lessonLearned: 'Highlight AI roadmap' },
        { deal: 'SteelWorks Project', outcome: 'Closed Won', competitor: 'None', value: 42000, primaryReason: 'Referral + fast deployment', stage: 'Closed', feedback: 'Valued speed over feature set', lessonLearned: 'Referral program effective' },
        { deal: 'FreshGoods Warehouse', outcome: 'At Risk', competitor: 'LogiStack', value: 28000, primaryReason: 'Budget constraints', stage: 'Proposal', feedback: 'Chose free tier competitor', lessonLearned: 'Need SMB entry pricing' },
      ],
      expandedFields: ['feedback', 'lessonLearned'],
      chart: {
        type: 'pie',
        title: 'Loss Reasons',
        dataKeys: ['value'],
        data: [
          { name: 'Price', value: 35 },
          { name: 'Features', value: 25 },
          { name: 'Integration', value: 18 },
          { name: 'Timing', value: 12 },
          { name: 'Relationship', value: 10 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Build ROI Calculator', description: 'Price is the top loss reason at 35%. An interactive ROI calculator would shift conversations from cost to value.', impact: '+8% win rate on price objections', action: 'Start Project' },
        { priority: 'medium', title: 'Strengthen AI Positioning', description: 'Lost 3 deals to AI-native competitors. Update messaging and demos to highlight AI capabilities and roadmap.', impact: 'Win 2 more deals/quarter', action: 'Update Messaging' },
      ],
      actions: [
        { label: 'Generate Win/Loss Report', description: 'Comprehensive analysis of win/loss patterns with recommendations' },
        { label: 'Schedule Debrief', description: 'Post-deal debrief sessions with structured feedback templates' },
        { label: 'Export Analysis', description: 'Download win/loss data with competitor insights' },
      ],
    },
  ],
});
