import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'sales',
    name: 'Sales Data',
    icon: '\u{1F4C8}',
    dept: 'Sales',
    deptColor: '#F5920B',
    description: 'AI-powered pipeline management and revenue forecasting',
    valueProposition: 'See every deal, predict revenue, and never miss a follow-up',
    enabled: true,
    buildBatch: 1,
  },
  tabs: [
    {
      id: 'pipeline',
      label: 'Pipeline Overview',
      kpis: [
        { label: 'Pipeline Value', value: 3200000, prefix: '$', change: 14, trend: 'up', icon: '\u{1F4B0}' },
        { label: 'Win Rate', value: 32, suffix: '%', change: 4, trend: 'up', icon: '\u{1F3AF}' },
        { label: 'Avg Deal Size', value: 47000, prefix: '$', change: 8, trend: 'up', icon: '\u{1F4CA}' },
        { label: 'Q2 Forecast', value: 890000, prefix: '$', change: 12, trend: 'up', icon: '\u{1F4C8}' },
      ],
      columns: [
        { key: 'company', label: 'Company', sortable: true },
        { key: 'deal', label: 'Deal', sortable: true },
        { key: 'stage', label: 'Stage', sortable: true },
        { key: 'value', label: 'Value', sortable: true },
        { key: 'probability', label: 'Prob %', sortable: true },
        { key: 'expectedClose', label: 'Close Date', sortable: true },
        { key: 'owner', label: 'Owner', sortable: true },
      ],
      rows: [
        { company: 'MegaCorp Inc', deal: 'Enterprise Warehouse Platform', stage: 'Proposal', value: 120000, probability: 45, expectedClose: 'Apr 15', owner: 'Sarah M.', activityTimeline: 'Demo completed Mar 5, proposal sent Mar 12', stakeholders: 'VP Ops, CTO, Procurement', competitiveIntel: 'Also evaluating RivalCo', nextSteps: 'Follow-up call Mar 22' },
        { company: 'TechFlow Solutions', deal: 'WMS Integration', stage: 'Negotiation', value: 78000, probability: 72, expectedClose: 'Mar 28', owner: 'James R.', activityTimeline: 'Contract redline received Mar 18', stakeholders: 'Director of IT', competitiveIntel: 'Single-source evaluation', nextSteps: 'Legal review of terms' },
        { company: 'Apex Fulfillment', deal: 'Multi-Site Rollout', stage: 'Qualified', value: 340000, probability: 25, expectedClose: 'Jun 30', owner: 'Sarah M.', activityTimeline: 'Discovery call Mar 10, site visit scheduled', stakeholders: 'CEO, VP Ops, CFO', competitiveIntel: '3 vendors in evaluation', nextSteps: 'Site visit Apr 2' },
        { company: 'Pacific Brands', deal: 'Inventory Optimization', stage: 'Prospect', value: 52000, probability: 15, expectedClose: 'Jul 15', owner: 'David K.', activityTimeline: 'Inbound from website Mar 14', stakeholders: 'Inventory Manager', competitiveIntel: 'Unknown', nextSteps: 'Discovery call Mar 25' },
        { company: 'Summit Retail', deal: 'Pick-Pack Automation', stage: 'Proposal', value: 95000, probability: 55, expectedClose: 'Apr 30', owner: 'James R.', activityTimeline: 'ROI analysis presented Mar 16', stakeholders: 'COO, Warehouse Dir.', competitiveIntel: 'Preferred vendor', nextSteps: 'Final pricing Mar 24' },
        { company: 'Velocity Logistics', deal: 'Real-Time Dashboard', stage: 'Closed Won', value: 64000, probability: 100, expectedClose: 'Mar 18', owner: 'Sarah M.', activityTimeline: 'Contract signed Mar 18', stakeholders: 'VP Technology', competitiveIntel: 'Won against 2 others', nextSteps: 'Kickoff meeting Mar 25' },
        { company: 'GlobalShip Partners', deal: 'Cross-Dock Solution', stage: 'Negotiation', value: 88000, probability: 65, expectedClose: 'Apr 8', owner: 'David K.', activityTimeline: 'Final demo Mar 14, pricing negotiation', stakeholders: 'Head of Logistics, CFO', competitiveIntel: 'Price-sensitive', nextSteps: 'Submit revised pricing Mar 21' },
      ],
      expandedFields: ['activityTimeline', 'stakeholders', 'competitiveIntel', 'nextSteps'],
      chart: {
        type: 'stacked-bar',
        title: 'Pipeline by Stage',
        xKey: 'stage',
        dataKeys: ['value'],
        colors: ['#F5920B'],
        data: [
          { stage: 'Prospect', value: 52000 },
          { stage: 'Qualified', value: 340000 },
          { stage: 'Proposal', value: 215000 },
          { stage: 'Negotiation', value: 166000 },
          { stage: 'Closed Won', value: 64000 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'MegaCorp Stalled 14 Days', description: 'MegaCorp Enterprise deal ($120K) has had no activity for 14 days since proposal. Contact VP Ops before they evaluate competitors.', impact: '$120K at risk', action: 'Schedule Follow-Up' },
        { priority: 'high', title: 'Q2 Forecast Gap', description: 'Q2 forecast is $340K short of target. Focus on 3 high-probability deals (TechFlow, Summit, GlobalShip) totaling $261K.', impact: 'Close $340K gap', action: 'View Priority Deals' },
        { priority: 'medium', title: "Replicate Sarah's Approach", description: 'Sarah closing at 2x team average. Her discovery call framework converts 60% to qualified. Roll out to team.', impact: '+15% team win rate', action: 'Share Playbook' },
      ],
      actions: [
        { label: 'Generate Forecast Report', description: 'AI-weighted revenue forecast with deal-by-deal probability analysis' },
        { label: 'Send Pipeline Summary', description: 'Weekly pipeline summary email to sales leadership with key changes' },
        { label: 'Create Deal', description: 'Add a new deal to the pipeline with AI-suggested next steps' },
        { label: 'Schedule Reviews', description: 'Set up deal review meetings with auto-generated prep materials' },
      ],
    },
    {
      id: 'deal-tracker',
      label: 'Deal Tracker',
      kpis: [
        { label: 'Deals in Motion', value: 24, change: 6, trend: 'up', icon: '\u{1F504}' },
        { label: 'Closing This Month', value: 6, change: 2, trend: 'up', icon: '\u{1F4C5}' },
        { label: 'Avg Cycle', value: 42, suffix: ' days', change: -4, trend: 'down', icon: '\u{23F1}\u{FE0F}' },
        { label: 'Stalled Deals', value: 5, change: -1, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
      ],
      columns: [
        { key: 'company', label: 'Company', sortable: true },
        { key: 'deal', label: 'Deal', sortable: true },
        { key: 'value', label: 'Value', sortable: true },
        { key: 'daysSinceActivity', label: 'Days Inactive', sortable: true },
        { key: 'stage', label: 'Stage', sortable: true },
        { key: 'status', label: 'Health', sortable: true },
      ],
      rows: [
        { company: 'MegaCorp Inc', deal: 'Enterprise Warehouse Platform', value: 120000, daysSinceActivity: 14, stage: 'Proposal', status: 'At Risk', lastActivity: 'Proposal sent', riskFactor: 'No engagement after proposal' },
        { company: 'TechFlow Solutions', deal: 'WMS Integration', value: 78000, daysSinceActivity: 2, stage: 'Negotiation', status: 'Active', lastActivity: 'Contract redline', riskFactor: 'None' },
        { company: 'Apex Fulfillment', deal: 'Multi-Site Rollout', value: 340000, daysSinceActivity: 8, stage: 'Qualified', status: 'Active', lastActivity: 'Site visit booked', riskFactor: 'Long sales cycle' },
        { company: 'Summit Retail', deal: 'Pick-Pack Automation', value: 95000, daysSinceActivity: 3, stage: 'Proposal', status: 'Active', lastActivity: 'ROI deck reviewed', riskFactor: 'Budget approval pending' },
        { company: 'GlobalShip Partners', deal: 'Cross-Dock Solution', value: 88000, daysSinceActivity: 5, stage: 'Negotiation', status: 'Active', lastActivity: 'Pricing discussion', riskFactor: 'Price-sensitive buyer' },
      ],
      expandedFields: ['lastActivity', 'riskFactor'],
      chart: {
        type: 'line',
        title: 'Deals Closed per Month',
        xKey: 'month',
        dataKeys: ['closed', 'target'],
        colors: ['#F5920B', '#E5E7EB'],
        data: [
          { month: 'Jan', closed: 4, target: 5 },
          { month: 'Feb', closed: 6, target: 5 },
          { month: 'Mar', closed: 5, target: 5 },
          { month: 'Apr', closed: 3, target: 5 },
          { month: 'May', closed: 7, target: 5 },
          { month: 'Jun', closed: 6, target: 5 },
        ],
      },
      recommendations: [
        { priority: 'high', title: '5 Stalled Deals Need Attention', description: 'Five deals have had no activity for 10+ days. AI recommends specific re-engagement actions for each.', impact: '$412K pipeline at risk', action: 'View Stalled Deals' },
        { priority: 'medium', title: 'Shorten Discovery Phase', description: 'Average time in discovery is 18 days vs 12-day benchmark. Pre-qualifying leads could cut 4 days.', impact: 'Close deals 4 days faster', action: 'View Recommendations' },
      ],
      actions: [
        { label: 'Flag Stalled Deals', description: 'Identify and alert on deals with no recent activity' },
        { label: 'Generate Activity Report', description: 'Deal-by-deal activity summary for sales reviews' },
        { label: 'Bulk Update Stages', description: 'Move multiple deals through pipeline stages' },
      ],
    },
    {
      id: 'forecast',
      label: 'Revenue Forecast',
      kpis: [
        { label: 'Q2 Committed', value: 550000, prefix: '$', change: 8, trend: 'up', icon: '\u{1F512}' },
        { label: 'Best Case', value: 890000, prefix: '$', change: 14, trend: 'up', icon: '\u{1F680}' },
        { label: 'Target', value: 780000, prefix: '$', change: 0, trend: 'flat', icon: '\u{1F3AF}' },
        { label: 'Coverage', value: 4.1, suffix: 'x', change: 10, trend: 'up', icon: '\u{1F4CA}' },
      ],
      columns: [
        { key: 'month', label: 'Month', sortable: true },
        { key: 'committed', label: 'Committed', sortable: true },
        { key: 'bestCase', label: 'Best Case', sortable: true },
        { key: 'target', label: 'Target', sortable: true },
        { key: 'gap', label: 'Gap', sortable: true },
      ],
      rows: [
        { month: 'April', committed: 180000, bestCase: 290000, target: 260000, gap: -80000, confidence: '72%', topDeal: 'TechFlow $78K' },
        { month: 'May', committed: 210000, bestCase: 320000, target: 260000, gap: -50000, confidence: '65%', topDeal: 'Summit $95K' },
        { month: 'June', committed: 160000, bestCase: 280000, target: 260000, gap: -100000, confidence: '58%', topDeal: 'Apex $340K (partial)' },
      ],
      expandedFields: ['confidence', 'topDeal'],
      chart: {
        type: 'area',
        title: 'Forecast vs Actual',
        xKey: 'month',
        dataKeys: ['actual', 'forecast', 'target'],
        colors: ['#F5920B', '#F5920B44', '#E5E7EB'],
        data: [
          { month: 'Jan', actual: 210000, forecast: 200000, target: 220000 },
          { month: 'Feb', actual: 245000, forecast: 230000, target: 220000 },
          { month: 'Mar', actual: 228000, forecast: 240000, target: 220000 },
          { month: 'Apr', actual: 0, forecast: 290000, target: 260000 },
          { month: 'May', actual: 0, forecast: 320000, target: 260000 },
          { month: 'Jun', actual: 0, forecast: 280000, target: 260000 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'April Gap is $80K', description: 'Need $80K more committed revenue for April target. Focus on TechFlow ($78K, 72% prob) and GlobalShip ($88K, 65% prob).', impact: 'Close April gap', action: 'View Priority Deals' },
        { priority: 'medium', title: 'Pipeline Coverage Healthy', description: 'At 4.1x coverage, pipeline is healthy but quality matters. 40% of pipeline is in early stages.', impact: 'Maintain 4x coverage', action: 'View Pipeline Health' },
      ],
      actions: [
        { label: 'Generate Forecast Report', description: 'Detailed monthly forecast with deal-level probability analysis' },
        { label: 'Run Scenarios', description: 'Model best-case, worst-case, and likely outcomes' },
        { label: 'Export to Finance', description: 'Share forecast data with finance team for planning' },
      ],
    },
    {
      id: 'leaderboard',
      label: 'Rep Leaderboard',
      kpis: [
        { label: 'Top Rep', value: 142, suffix: '% quota', change: 12, trend: 'up', icon: '\u{1F3C6}' },
        { label: 'Avg Attainment', value: 78, suffix: '%', change: 4, trend: 'up', icon: '\u{1F4CA}' },
        { label: 'Ramp Reps', value: 3, change: 0, trend: 'flat', icon: '\u{1F331}' },
        { label: 'Quota Coverage', value: 92, suffix: '%', change: 3, trend: 'up', icon: '\u{1F3AF}' },
      ],
      columns: [
        { key: 'rep', label: 'Rep', sortable: true },
        { key: 'quota', label: 'Quota', sortable: true },
        { key: 'actual', label: 'Actual', sortable: true },
        { key: 'attainment', label: 'Attainment', sortable: true },
        { key: 'winRate', label: 'Win Rate', sortable: true },
        { key: 'dealsClosed', label: 'Deals', sortable: true },
      ],
      rows: [
        { rep: 'Sarah Martinez', quota: 200000, actual: 284000, attainment: '142%', winRate: '41%', dealsClosed: 8, topDeal: 'Velocity Logistics $64K', pipeline: '$420K' },
        { rep: 'James Rodriguez', quota: 200000, actual: 178000, attainment: '89%', winRate: '32%', dealsClosed: 5, topDeal: 'TechFlow $78K (pending)', pipeline: '$310K' },
        { rep: 'David Kim', quota: 150000, actual: 96000, attainment: '64%', winRate: '24%', dealsClosed: 3, topDeal: 'GlobalShip $88K (pending)', pipeline: '$280K' },
        { rep: 'Lisa Chen', quota: 150000, actual: 112000, attainment: '75%', winRate: '28%', dealsClosed: 4, topDeal: 'SteelWorks $42K', pipeline: '$195K' },
      ],
      expandedFields: ['topDeal', 'pipeline'],
      chart: {
        type: 'bar',
        title: 'Quota Attainment by Rep',
        xKey: 'rep',
        dataKeys: ['attainment'],
        colors: ['#F5920B'],
        data: [
          { rep: 'Sarah M.', attainment: 142 },
          { rep: 'James R.', attainment: 89 },
          { rep: 'Lisa C.', attainment: 75 },
          { rep: 'David K.', attainment: 64 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'David Kim Needs Coaching', description: 'David is in month 4 of ramp but tracking 36% below expected curve. Discovery-to-qualified conversion is 18% vs 35% team avg.', impact: 'Accelerate ramp', action: 'Create Coaching Plan' },
        { priority: 'medium', title: "Study Sarah's Win Pattern", description: "Sarah's 41% win rate is 9 points above team average. She runs 2.3x more discovery calls per deal.", impact: '+9% team win rate', action: 'Analyze Pattern' },
      ],
      actions: [
        { label: 'Generate Team Report', description: 'Comprehensive rep performance analysis with benchmarks' },
        { label: 'Schedule 1-on-1s', description: 'Book coaching sessions with suggested talking points per rep' },
        { label: 'Export Leaderboard', description: 'Download rep rankings and performance metrics' },
      ],
    },
  ],
});
