import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'sales-coach',
    name: 'Sales Coach',
    icon: '\u{1F3C6}',
    dept: 'Sales',
    deptColor: '#F5920B',
    description: 'AI-powered sales coaching, call analysis, and skill development',
    valueProposition: 'Analyze every call, coach every rep, and build a world-class sales team',
    enabled: true,
    buildBatch: 2,
  },
  tabs: [
    {
      id: 'call-analysis',
      label: 'Call Analysis',
      kpis: [
        { label: 'Calls Analyzed', value: 148, change: 18, trend: 'up', icon: '\u{1F4DE}' },
        { label: 'Avg Talk Ratio', value: 42, suffix: '%', change: -4, trend: 'down', icon: '\u{1F4CA}' },
        { label: 'Avg Score', value: 74, suffix: '/100', change: 6, trend: 'up', icon: '\u{1F3AF}' },
        { label: 'Coaching Alerts', value: 6, change: -2, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
      ],
      columns: [
        { key: 'rep', label: 'Rep', sortable: true },
        { key: 'call', label: 'Call', sortable: true },
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'score', label: 'Score', sortable: true },
        { key: 'talkRatio', label: 'Talk %', sortable: true },
        { key: 'outcome', label: 'Outcome', sortable: true },
      ],
      rows: [
        { rep: 'Sarah Martinez', call: 'Discovery Call', customer: 'MegaCorp Inc', score: '92/100', talkRatio: '35%', outcome: 'Qualified', keyMoments: 'Strong discovery questions, identified 3 pain points', improvementAreas: 'Could probe budget earlier', duration: '28 min' },
        { rep: 'James Rodriguez', call: 'Demo', customer: 'TechFlow Solutions', score: '78/100', talkRatio: '52%', outcome: 'In Progress', keyMoments: 'Good feature demo, missed objection handling', improvementAreas: 'Talked too much, ask more questions', duration: '45 min' },
        { rep: 'David Kim', call: 'Discovery Call', customer: 'Pacific Brands', score: '54/100', talkRatio: '68%', outcome: 'Stalled', keyMoments: 'Pitched too early, dominated conversation', improvementAreas: 'Listen more, follow SPIN framework', duration: '22 min' },
        { rep: 'Lisa Chen', call: 'Follow-Up', customer: 'GlobalShip Partners', score: '81/100', talkRatio: '40%', outcome: 'Advancing', keyMoments: 'Good recap, clear next steps', improvementAreas: 'Could create more urgency', duration: '18 min' },
        { rep: 'Sarah Martinez', call: 'Negotiation', customer: 'Velocity Logistics', score: '88/100', talkRatio: '38%', outcome: 'Closed Won', keyMoments: 'Handled price objection with ROI data', improvementAreas: 'Minor: could summarize sooner', duration: '32 min' },
        { rep: 'David Kim', call: 'Cold Call', customer: 'NovaTech Industries', score: '62/100', talkRatio: '58%', outcome: 'Booked Meeting', keyMoments: 'Good hook, but rushed pitch', improvementAreas: 'Slow down, build rapport first', duration: '8 min' },
      ],
      expandedFields: ['keyMoments', 'improvementAreas', 'duration'],
      chart: {
        type: 'bar',
        title: 'Average Call Score by Rep',
        xKey: 'rep',
        dataKeys: ['score'],
        colors: ['#F5920B'],
        data: [
          { rep: 'Sarah M.', score: 90 },
          { rep: 'Lisa C.', score: 81 },
          { rep: 'James R.', score: 78 },
          { rep: 'David K.', score: 58 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'David Kim Needs Coaching', description: 'David averages 58/100 call score with 63% talk ratio. He pitches too early and dominates conversations. Pair with Sarah for shadowing.', impact: '+20pt score improvement', action: 'Create Coaching Plan' },
        { priority: 'high', title: 'James Talk Ratio High', description: 'James averages 52% talk ratio on demos. Best practice is under 45%. Train on asking discovery questions during demos.', impact: '+12pt demo score', action: 'Schedule Training' },
        { priority: 'medium', title: 'Sarah Best Practice Sharing', description: 'Sarah averages 90/100 with 35% talk ratio. Record her next 3 calls for the team library.', impact: 'Team-wide improvement', action: 'Record Calls' },
      ],
      actions: [
        { label: 'Generate Coaching Report', description: 'AI-analyzed call patterns with specific improvement recommendations per rep' },
        { label: 'Create Training Plan', description: 'Personalized skill development plan based on call analysis gaps' },
        { label: 'Export Call Insights', description: 'Download call scores, talk ratios, and key moments' },
        { label: 'Share Best Practices', description: 'Compile top-scoring call clips into a team learning library' },
      ],
    },
    {
      id: 'skill-gaps',
      label: 'Skill Gaps',
      kpis: [
        { label: 'Avg Discovery Score', value: 72, suffix: '/100', change: 8, trend: 'up', icon: '\u{1F50D}' },
        { label: 'Avg Objection Handling', value: 64, suffix: '/100', change: 4, trend: 'up', icon: '\u{1F6E1}\u{FE0F}' },
        { label: 'Avg Closing', value: 68, suffix: '/100', change: 6, trend: 'up', icon: '\u{1F91D}' },
        { label: 'Avg Rapport', value: 78, suffix: '/100', change: 2, trend: 'up', icon: '\u{1F4AC}' },
      ],
      columns: [
        { key: 'rep', label: 'Rep', sortable: true },
        { key: 'discovery', label: 'Discovery', sortable: true },
        { key: 'objectionHandling', label: 'Objections', sortable: true },
        { key: 'closing', label: 'Closing', sortable: true },
        { key: 'rapport', label: 'Rapport', sortable: true },
        { key: 'overallTrend', label: 'Trend', sortable: true },
      ],
      rows: [
        { rep: 'Sarah Martinez', discovery: '94/100', objectionHandling: '88/100', closing: '86/100', rapport: '92/100', overallTrend: 'Improving', biggestGap: 'None - top performer', recommendedAction: 'Mentor others' },
        { rep: 'James Rodriguez', discovery: '72/100', objectionHandling: '62/100', closing: '74/100', rapport: '80/100', overallTrend: 'Improving', biggestGap: 'Objection handling', recommendedAction: 'Objection role-play sessions' },
        { rep: 'Lisa Chen', discovery: '76/100', objectionHandling: '70/100', closing: '64/100', rapport: '78/100', overallTrend: 'Stable', biggestGap: 'Closing techniques', recommendedAction: 'Closing workshop' },
        { rep: 'David Kim', discovery: '48/100', objectionHandling: '38/100', closing: '52/100', rapport: '62/100', overallTrend: 'Declining', biggestGap: 'All areas - ramp rep', recommendedAction: 'Intensive coaching program' },
      ],
      expandedFields: ['biggestGap', 'recommendedAction'],
      chart: {
        type: 'grouped-bar',
        title: 'Skill Scores by Rep',
        xKey: 'rep',
        dataKeys: ['discovery', 'objections', 'closing', 'rapport'],
        colors: ['#F5920B', '#2A9D8F', '#6366F1', '#059669'],
        data: [
          { rep: 'Sarah M.', discovery: 94, objections: 88, closing: 86, rapport: 92 },
          { rep: 'James R.', discovery: 72, objections: 62, closing: 74, rapport: 80 },
          { rep: 'Lisa C.', discovery: 76, objections: 70, closing: 64, rapport: 78 },
          { rep: 'David K.', discovery: 48, objections: 38, closing: 52, rapport: 62 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Team Objection Handling Weak', description: 'Team average for objection handling is 64/100 - lowest skill area. Schedule team workshop with role-play exercises.', impact: '+15pt avg improvement', action: 'Schedule Workshop' },
        { priority: 'medium', title: 'Lisa Closing Gap', description: 'Lisa scores well in discovery but drops off in closing (64/100). Teach trial close techniques throughout the sales process.', impact: '+10pt closing score', action: 'Assign Training' },
      ],
      actions: [
        { label: 'Generate Gap Analysis', description: 'Detailed skill gap analysis with personalized development plans' },
        { label: 'Schedule Workshops', description: 'Team training sessions targeting the biggest collective skill gaps' },
        { label: 'Create Role-Play Scenarios', description: 'AI-generated practice scenarios based on real deal situations' },
      ],
    },
    {
      id: 'coaching-plans',
      label: 'Coaching Plans',
      kpis: [
        { label: 'Active Plans', value: 4, change: 0, trend: 'flat', icon: '\u{1F4CB}' },
        { label: 'Tasks Completed', value: 28, change: 6, trend: 'up', icon: '\u{2705}' },
        { label: 'Avg Improvement', value: 14, suffix: '%', change: 4, trend: 'up', icon: '\u{1F4C8}' },
        { label: 'Sessions/Week', value: 6, change: 1, trend: 'up', icon: '\u{1F4C5}' },
      ],
      columns: [
        { key: 'rep', label: 'Rep', sortable: true },
        { key: 'focusArea', label: 'Focus Area', sortable: true },
        { key: 'progress', label: 'Progress', sortable: true },
        { key: 'nextSession', label: 'Next Session', sortable: true },
        { key: 'improvement', label: 'Improvement', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { rep: 'David Kim', focusArea: 'Discovery & Listening', progress: '25%', nextSession: 'Mar 22', improvement: '+8pts', status: 'Active', tasks: 'Shadow 3 Sarah calls, complete SPIN module', weeksRemaining: 6, mentor: 'Sarah Martinez' },
        { rep: 'James Rodriguez', focusArea: 'Objection Handling', progress: '60%', nextSession: 'Mar 24', improvement: '+12pts', status: 'Active', tasks: 'Role-play 5 scenarios, review call recordings', weeksRemaining: 3, mentor: 'Sales Manager' },
        { rep: 'Lisa Chen', focusArea: 'Closing Techniques', progress: '40%', nextSession: 'Mar 23', improvement: '+6pts', status: 'Active', tasks: 'Trial close practice, review 3 won deals', weeksRemaining: 4, mentor: 'Sarah Martinez' },
        { rep: 'Sarah Martinez', focusArea: 'Mentorship Program', progress: '50%', nextSession: 'Mar 22', improvement: 'N/A', status: 'Active', tasks: 'Mentor David and Lisa, record 3 calls', weeksRemaining: 4, mentor: 'Self-directed' },
      ],
      expandedFields: ['tasks', 'weeksRemaining', 'mentor'],
      chart: {
        type: 'line',
        title: 'Coaching Impact Over Time',
        xKey: 'week',
        dataKeys: ['david', 'james', 'lisa'],
        colors: ['#DC2626', '#F5920B', '#6366F1'],
        data: [
          { week: 'W1', david: 54, james: 66, lisa: 64 },
          { week: 'W2', david: 56, james: 70, lisa: 66 },
          { week: 'W3', david: 58, james: 74, lisa: 68 },
          { week: 'W4', david: 62, james: 78, lisa: 70 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'David Making Progress', description: 'David improved 8 points in 4 weeks but still well below team average. Continue intensive coaching and add daily check-ins.', impact: 'Accelerate ramp', action: 'Intensify Coaching' },
        { priority: 'medium', title: 'James Ready to Graduate', description: 'James improved 12 points and is approaching team average. Consider graduating from formal coaching after 3 more weeks.', impact: 'Free coaching capacity', action: 'Review Progress' },
      ],
      actions: [
        { label: 'Create Coaching Plan', description: 'AI-generated coaching plan based on skill gaps and learning style' },
        { label: 'Schedule Sessions', description: 'Book coaching sessions with AI-suggested topics and exercises' },
        { label: 'Track Progress', description: 'Monitor improvement metrics and adjust plans accordingly' },
      ],
    },
    {
      id: 'playbooks',
      label: 'Playbooks',
      kpis: [
        { label: 'Active Playbooks', value: 8, change: 2, trend: 'up', icon: '\u{1F4D6}' },
        { label: 'Adoption Rate', value: 72, suffix: '%', change: 8, trend: 'up', icon: '\u{1F4CA}' },
        { label: 'Avg Win Rate Lift', value: 12, suffix: '%', change: 3, trend: 'up', icon: '\u{1F4C8}' },
        { label: 'Scripts Used', value: 42, change: 8, trend: 'up', icon: '\u{1F4DD}' },
      ],
      columns: [
        { key: 'playbook', label: 'Playbook', sortable: true },
        { key: 'type', label: 'Type', sortable: true },
        { key: 'adoptionRate', label: 'Adoption', sortable: true },
        { key: 'winRateLift', label: 'Win Rate Lift', sortable: true },
        { key: 'lastUpdated', label: 'Updated', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { playbook: 'Discovery Call Framework', type: 'Process', adoptionRate: '88%', winRateLift: '+18%', lastUpdated: 'Mar 15', status: 'Active', createdBy: 'Sarah Martinez', usageCount: 124, feedbackScore: '4.6/5' },
        { playbook: 'Enterprise Demo Script', type: 'Script', adoptionRate: '74%', winRateLift: '+14%', lastUpdated: 'Mar 8', status: 'Active', createdBy: 'Sales Ops', usageCount: 86, feedbackScore: '4.2/5' },
        { playbook: 'Objection Response Bank', type: 'Reference', adoptionRate: '82%', winRateLift: '+10%', lastUpdated: 'Mar 12', status: 'Active', createdBy: 'AI Generated', usageCount: 204, feedbackScore: '4.4/5' },
        { playbook: 'Competitor Battle Cards', type: 'Reference', adoptionRate: '68%', winRateLift: '+8%', lastUpdated: 'Mar 1', status: 'Stale', createdBy: 'Sales Intel', usageCount: 92, feedbackScore: '3.8/5' },
        { playbook: 'Closing Techniques Guide', type: 'Process', adoptionRate: '56%', winRateLift: '+6%', lastUpdated: 'Feb 20', status: 'Active', createdBy: 'Sales Manager', usageCount: 48, feedbackScore: '4.0/5' },
      ],
      expandedFields: ['createdBy', 'usageCount', 'feedbackScore'],
      chart: {
        type: 'bar',
        title: 'Playbook Adoption Rate',
        xKey: 'playbook',
        dataKeys: ['adoption'],
        colors: ['#F5920B'],
        data: [
          { playbook: 'Discovery', adoption: 88 },
          { playbook: 'Objections', adoption: 82 },
          { playbook: 'Demo Script', adoption: 74 },
          { playbook: 'Battle Cards', adoption: 68 },
          { playbook: 'Closing', adoption: 56 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Update Battle Cards', description: 'Competitor battle cards are stale (last updated Mar 1) with lowest feedback score. Update with recent RivalCo pricing and WareBot AI intel.', impact: 'Improve comp win rate', action: 'Update Now' },
        { priority: 'medium', title: 'Boost Closing Adoption', description: 'Closing techniques guide has only 56% adoption. Make it a required pre-call checklist in the CRM.', impact: '+6% closing rate', action: 'Enforce Adoption' },
      ],
      actions: [
        { label: 'Create Playbook', description: 'AI-assisted playbook creation from top performer patterns' },
        { label: 'Update Battle Cards', description: 'Refresh competitive battle cards with latest intelligence' },
        { label: 'Export Playbooks', description: 'Download all playbooks for offline reference' },
      ],
    },
  ],
});
