import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'seo',
    name: 'SEO',
    icon: '\u{1F310}',
    dept: 'Marketing',
    deptColor: '#EC4899',
    description: 'AI-powered search engine optimization and content strategy',
    valueProposition: 'Rank higher, drive organic traffic, and turn search into your best lead channel',
    enabled: true,
    buildBatch: 2,
  },
  tabs: [
    {
      id: 'rankings',
      label: 'Rankings',
      kpis: [
        { label: 'Keywords Tracked', value: 142, change: 12, trend: 'up', icon: '\u{1F50D}' },
        { label: 'Page 1 Rankings', value: 24, change: 4, trend: 'up', icon: '\u{1F3C6}' },
        { label: 'Organic Traffic', value: 8400, change: 18, trend: 'up', icon: '\u{1F4C8}' },
        { label: 'Domain Authority', value: 42, change: 3, trend: 'up', icon: '\u{1F4CA}' },
      ],
      columns: [
        { key: 'keyword', label: 'Keyword', sortable: true },
        { key: 'position', label: 'Position', sortable: true },
        { key: 'volume', label: 'Volume', sortable: true },
        { key: 'change', label: 'Change', sortable: true },
        { key: 'page', label: 'Ranking Page', sortable: false },
        { key: 'difficulty', label: 'Difficulty', sortable: true },
      ],
      rows: [
        { keyword: 'warehouse management system', position: 8, volume: 14800, change: '+3', page: '/solutions/wms', difficulty: 'High', ctr: '4.2%', clicks: 622, topCompetitor: 'RivalCo at #2' },
        { keyword: 'warehouse automation', position: 12, volume: 9200, change: '+5', page: '/blog/automation-guide', difficulty: 'High', ctr: '2.8%', clicks: 258, topCompetitor: 'WareBot at #4' },
        { keyword: 'pick pack fulfillment', position: 3, volume: 3400, change: '+1', page: '/solutions/pick-pack', difficulty: 'Medium', ctr: '8.4%', clicks: 286, topCompetitor: 'FlexWare at #5' },
        { keyword: 'warehouse ai employee', position: 1, volume: 720, change: '0', page: '/solutions', difficulty: 'Low', ctr: '28%', clicks: 202, topCompetitor: 'None relevant' },
        { keyword: '3pl warehouse software', position: 6, volume: 4800, change: '+2', page: '/solutions/3pl', difficulty: 'Medium', ctr: '5.6%', clicks: 269, topCompetitor: 'LogiStack at #1' },
        { keyword: 'warehouse operations optimization', position: 15, volume: 2400, change: '+8', page: '/blog/operations-guide', difficulty: 'Medium', ctr: '1.2%', clicks: 29, topCompetitor: 'OmniChain at #3' },
        { keyword: 'wms integration erp', position: 4, volume: 1800, change: '+2', page: '/solutions/integrations', difficulty: 'Medium', ctr: '7.2%', clicks: 130, topCompetitor: 'RivalCo at #1' },
      ],
      expandedFields: ['ctr', 'clicks', 'topCompetitor'],
      chart: {
        type: 'line',
        title: 'Organic Traffic Trend',
        xKey: 'month',
        dataKeys: ['traffic'],
        colors: ['#EC4899'],
        data: [
          { month: 'Jan', traffic: 5200 },
          { month: 'Feb', traffic: 5800 },
          { month: 'Mar', traffic: 6400 },
          { month: 'Apr', traffic: 7100 },
          { month: 'May', traffic: 7800 },
          { month: 'Jun', traffic: 8400 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Push WMS Keyword to Page 1', description: '"Warehouse management system" is at position 8 with 14,800 monthly searches. Adding 3 internal links and updating content could push to top 5.', impact: '+400 clicks/mo', action: 'Optimize Page' },
        { priority: 'high', title: 'Defend #1 for AI Employee', description: 'We own #1 for "warehouse ai employee" but competitors are creating content. Publish 2 supporting articles to maintain dominance.', impact: 'Protect 202 clicks/mo', action: 'Create Content' },
        { priority: 'medium', title: 'Target New Keywords', description: '12 high-value keywords have no existing content. Create pillar pages for "warehouse automation cost" and "wms comparison."', impact: '+1,200 clicks/mo', action: 'Plan Content' },
      ],
      actions: [
        { label: 'Run Site Audit', description: 'Comprehensive technical SEO audit with issue prioritization' },
        { label: 'Generate Content Plan', description: 'AI-recommended content topics based on keyword gaps and search trends' },
        { label: 'Track New Keywords', description: 'Add keywords to tracking with competitive position monitoring' },
        { label: 'Export Rankings', description: 'Download keyword rankings with historical position data' },
      ],
    },
    {
      id: 'technical-seo',
      label: 'Technical SEO',
      kpis: [
        { label: 'Health Score', value: 84, suffix: '/100', change: 6, trend: 'up', icon: '\u{2705}' },
        { label: 'Errors', value: 8, change: -4, trend: 'down', icon: '\u{1F534}' },
        { label: 'Warnings', value: 23, change: -8, trend: 'down', icon: '\u{1F7E1}' },
        { label: 'Page Speed', value: 82, suffix: '/100', change: 4, trend: 'up', icon: '\u{26A1}' },
      ],
      columns: [
        { key: 'issue', label: 'Issue', sortable: true },
        { key: 'type', label: 'Type', sortable: true },
        { key: 'pagesAffected', label: 'Pages', sortable: true },
        { key: 'impact', label: 'SEO Impact', sortable: true },
        { key: 'effort', label: 'Fix Effort', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { issue: 'Missing meta descriptions', type: 'Warning', pagesAffected: 12, impact: 'Medium', effort: 'Low', status: 'Open', affectedUrls: '/blog/* pages', recommendation: 'Add unique meta descriptions to each page' },
        { issue: 'Broken internal links', type: 'Error', pagesAffected: 4, impact: 'High', effort: 'Low', status: 'Open', affectedUrls: '/solutions/old-page, /blog/deleted-post', recommendation: 'Set up 301 redirects' },
        { issue: 'Large image files', type: 'Warning', pagesAffected: 18, impact: 'Medium', effort: 'Medium', status: 'In Progress', affectedUrls: 'Across site - case study images', recommendation: 'Compress and convert to WebP' },
        { issue: 'Duplicate title tags', type: 'Error', pagesAffected: 3, impact: 'High', effort: 'Low', status: 'Open', affectedUrls: '/solutions/* pages share titles', recommendation: 'Create unique title tags per page' },
        { issue: 'Missing alt text', type: 'Warning', pagesAffected: 28, impact: 'Low', effort: 'Low', status: 'Open', affectedUrls: 'Across site', recommendation: 'Add descriptive alt text to all images' },
        { issue: 'Slow LCP on mobile', type: 'Error', pagesAffected: 2, impact: 'High', effort: 'Medium', status: 'In Progress', affectedUrls: '/pricing, /solutions', recommendation: 'Optimize hero images and critical CSS' },
      ],
      expandedFields: ['affectedUrls', 'recommendation'],
      chart: {
        type: 'line',
        title: 'Site Health Score Trend',
        xKey: 'month',
        dataKeys: ['score'],
        colors: ['#EC4899'],
        data: [
          { month: 'Jan', score: 68 },
          { month: 'Feb', score: 72 },
          { month: 'Mar', score: 76 },
          { month: 'Apr', score: 78 },
          { month: 'May', score: 82 },
          { month: 'Jun', score: 84 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Fix Broken Links', description: '4 broken internal links are causing crawl errors and poor UX. Quick fix with 301 redirects.', impact: 'Fix 4 errors', action: 'Fix Now' },
        { priority: 'high', title: 'Fix Duplicate Titles', description: '3 solution pages share the same title tag. Each page needs a unique, keyword-rich title.', impact: 'Improve rankings', action: 'Update Titles' },
        { priority: 'medium', title: 'Compress Images', description: '18 pages have oversized images adding 2-4 seconds to load time. WebP conversion fixes this.', impact: '+4pt page speed', action: 'Start Compression' },
      ],
      actions: [
        { label: 'Run Full Audit', description: 'Deep technical SEO crawl with issue categorization' },
        { label: 'Fix Critical Issues', description: 'Auto-generate fix recommendations for high-impact issues' },
        { label: 'Export Audit Report', description: 'Download technical SEO audit with prioritized action items' },
      ],
    },
    {
      id: 'backlinks',
      label: 'Backlinks',
      kpis: [
        { label: 'Total Backlinks', value: 842, change: 12, trend: 'up', icon: '\u{1F517}' },
        { label: 'Referring Domains', value: 124, change: 8, trend: 'up', icon: '\u{1F310}' },
        { label: 'New This Month', value: 18, change: 4, trend: 'up', icon: '\u{1F195}' },
        { label: 'Lost This Month', value: 4, change: -2, trend: 'down', icon: '\u{1F534}' },
      ],
      columns: [
        { key: 'source', label: 'Source', sortable: true },
        { key: 'da', label: 'DA', sortable: true },
        { key: 'targetPage', label: 'Target', sortable: false },
        { key: 'anchorText', label: 'Anchor Text', sortable: false },
        { key: 'type', label: 'Type', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { source: 'SupplyChainDive.com', da: 72, targetPage: '/blog/automation-guide', anchorText: 'warehouse automation', type: 'Editorial', status: 'Active', dateAcquired: 'Mar 14', doFollow: 'Yes' },
        { source: 'LogisticsToday.com', da: 58, targetPage: '/solutions/wms', anchorText: 'WMS solutions', type: 'Guest Post', status: 'Active', dateAcquired: 'Mar 8', doFollow: 'Yes' },
        { source: 'TechCrunch.com', da: 94, targetPage: '/about', anchorText: 'WoulfAI', type: 'Mention', status: 'Active', dateAcquired: 'Feb 22', doFollow: 'No' },
        { source: 'SmallBizTech.org', da: 34, targetPage: '/case-studies', anchorText: 'case study', type: 'Directory', status: 'Active', dateAcquired: 'Feb 15', doFollow: 'Yes' },
        { source: 'WarehouseForum.net', da: 28, targetPage: '/blog/5-signs', anchorText: 'warehouse signs', type: 'Forum', status: 'Active', dateAcquired: 'Mar 2', doFollow: 'No' },
      ],
      expandedFields: ['dateAcquired', 'doFollow'],
      chart: {
        type: 'area',
        title: 'Backlink Growth',
        xKey: 'month',
        dataKeys: ['total', 'newLinks'],
        colors: ['#EC4899', '#F5920B'],
        data: [
          { month: 'Jan', total: 780, newLinks: 14 },
          { month: 'Feb', total: 800, newLinks: 20 },
          { month: 'Mar', total: 810, newLinks: 10 },
          { month: 'Apr', total: 822, newLinks: 12 },
          { month: 'May', total: 828, newLinks: 6 },
          { month: 'Jun', total: 842, newLinks: 14 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Pursue More DA 50+ Links', description: 'Only 18% of backlinks are from DA 50+ domains. Target 5 industry publications for guest posts and data studies.', impact: '+5 high-DA links', action: 'Start Outreach' },
        { priority: 'medium', title: 'Recover Lost Links', description: '4 backlinks lost this month due to page removals on linking sites. Reach out to recover or replace.', impact: 'Recover 4 links', action: 'Start Recovery' },
      ],
      actions: [
        { label: 'Find Opportunities', description: 'AI-identified backlink opportunities from competitor gap analysis' },
        { label: 'Start Outreach', description: 'Personalized outreach emails for link building campaigns' },
        { label: 'Export Backlink Report', description: 'Download backlink profile with DA, anchor text, and status' },
      ],
    },
    {
      id: 'competitors-seo',
      label: 'Competitor SEO',
      kpis: [
        { label: 'Keyword Overlap', value: 68, suffix: '%', change: 4, trend: 'up', icon: '\u{1F504}' },
        { label: 'We Outrank', value: 38, suffix: '%', change: 6, trend: 'up', icon: '\u{1F4C8}' },
        { label: 'Content Gap', value: 24, change: -4, trend: 'down', icon: '\u{1F4DD}' },
        { label: 'DA Gap', value: -12, change: 3, trend: 'up', icon: '\u{1F4CA}' },
      ],
      columns: [
        { key: 'competitor', label: 'Competitor', sortable: true },
        { key: 'da', label: 'DA', sortable: true },
        { key: 'organicTraffic', label: 'Traffic', sortable: true },
        { key: 'keywords', label: 'Keywords', sortable: true },
        { key: 'overlap', label: 'Overlap', sortable: true },
        { key: 'status', label: 'Threat', sortable: true },
      ],
      rows: [
        { competitor: 'RivalCo Systems', da: 62, organicTraffic: '24K/mo', keywords: 480, overlap: '72%', status: 'High', topKeyword: 'warehouse management system #2', contentGap: '12 topics we lack' },
        { competitor: 'FlexWare Inc', da: 48, organicTraffic: '12K/mo', keywords: 220, overlap: '58%', status: 'Medium', topKeyword: 'warehouse software #6', contentGap: '8 topics we lack' },
        { competitor: 'WareBot AI', da: 38, organicTraffic: '6K/mo', keywords: 140, overlap: '34%', status: 'Medium', topKeyword: 'ai warehouse management #1', contentGap: '6 AI-focused topics' },
        { competitor: 'LogiStack', da: 52, organicTraffic: '18K/mo', keywords: 340, overlap: '64%', status: 'High', topKeyword: '3pl warehouse software #1', contentGap: '10 topics we lack' },
      ],
      expandedFields: ['topKeyword', 'contentGap'],
      chart: {
        type: 'bar',
        title: 'Domain Authority Comparison',
        xKey: 'site',
        dataKeys: ['da'],
        colors: ['#EC4899'],
        data: [
          { site: 'RivalCo', da: 62 },
          { site: 'LogiStack', da: 52 },
          { site: 'FlexWare', da: 48 },
          { site: 'WoulfAI', da: 42 },
          { site: 'WareBot', da: 38 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Close Content Gap with RivalCo', description: 'RivalCo outranks us on 12 topics we have no content for. Creating pillar pages for top 5 could capture 2,400 clicks/mo.', impact: '+2,400 clicks/mo', action: 'Create Content Plan' },
        { priority: 'medium', title: 'Counter WareBot AI Content', description: 'WareBot ranks #1 for "ai warehouse management." Create comprehensive AI-focused content to compete.', impact: 'Capture AI search traffic', action: 'Plan AI Content' },
      ],
      actions: [
        { label: 'Run Gap Analysis', description: 'Comprehensive content and keyword gap analysis vs competitors' },
        { label: 'Generate Content Plan', description: 'AI-recommended topics to close competitive gaps' },
        { label: 'Export Competitor Data', description: 'Download competitor SEO profiles with ranking comparisons' },
      ],
    },
  ],
});
