import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'str',
    name: 'STR',
    icon: '🏠',
    dept: 'Real Estate',
    deptColor: '#D97706',
    description: 'AI-powered short-term rental management and revenue optimization',
    valueProposition: 'Maximize occupancy, optimize pricing, and automate guest management across all properties',
    enabled: true,
    buildBatch: 3,
  },
  tabs: [
    {
      id: 'portfolio',
      label: 'Portfolio Overview',
      kpis: [
        { label: 'Active Properties', value: 12, change: 2, trend: 'up', icon: '🏠' },
        { label: 'Avg Occupancy', value: 78, suffix: '%', change: 6, trend: 'up', icon: '📊' },
        { label: 'Revenue (MTD)', value: 48600, prefix: '$', change: 14, trend: 'up', icon: '💰' },
        { label: 'Avg Rating', value: 4.7, suffix: '/5', change: 2, trend: 'up', icon: '⭐' },
      ],
      columns: [
        { key: 'property', label: 'Property', sortable: true },
        { key: 'location', label: 'Location', sortable: true },
        { key: 'occupancy', label: 'Occupancy', sortable: true },
        { key: 'revpar', label: 'RevPAR', sortable: true },
        { key: 'rating', label: 'Rating', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { property: 'Mountain View Cabin', location: 'Park City, UT', occupancy: '92%', revpar: '$184', rating: '4.9/5', status: 'Active', nextGuest: 'Mar 22, 4 nights', avgNightlyRate: '$212', channels: 'Airbnb, VRBO, Direct' },
        { property: 'Downtown Loft', location: 'Salt Lake City, UT', occupancy: '84%', revpar: '$142', rating: '4.7/5', status: 'Active', nextGuest: 'Mar 21, 2 nights', avgNightlyRate: '$168', channels: 'Airbnb, Booking.com' },
        { property: 'Lake House Retreat', location: 'Bear Lake, UT', occupancy: '42%', revpar: '$88', rating: '4.8/5', status: 'Seasonal', nextGuest: 'May 15, 7 nights', avgNightlyRate: '$210', channels: 'VRBO, Direct' },
        { property: 'Red Rock Studio', location: 'St. George, UT', occupancy: '88%', revpar: '$124', rating: '4.6/5', status: 'Active', nextGuest: 'Tonight', avgNightlyRate: '$142', channels: 'Airbnb, VRBO' },
        { property: 'Canyon View Suite', location: 'Moab, UT', occupancy: '94%', revpar: '$198', rating: '4.9/5', status: 'Active', nextGuest: 'Occupied until Mar 24', avgNightlyRate: '$224', channels: 'Airbnb, VRBO, Direct' },
        { property: 'Ski Chalet', location: 'Brighton, UT', occupancy: '96%', revpar: '$268', rating: '4.8/5', status: 'Active', nextGuest: 'Occupied', avgNightlyRate: '$285', channels: 'Airbnb, VRBO, Direct' },
        { property: 'Desert Oasis', location: 'Zion, UT', occupancy: '82%', revpar: '$156', rating: '4.5/5', status: 'Active', nextGuest: 'Mar 23, 3 nights', avgNightlyRate: '$190', channels: 'Airbnb, Booking.com' },
        { property: 'Valley Townhome', location: 'Tooele, UT', occupancy: '68%', revpar: '$78', rating: '4.4/5', status: 'Active', nextGuest: 'Mar 26, 5 nights', avgNightlyRate: '$114', channels: 'Airbnb' },
      ],
      expandedFields: ['nextGuest', 'avgNightlyRate', 'channels'],
      chart: {
        type: 'bar',
        title: 'Revenue by Property (MTD)',
        xKey: 'property',
        dataKeys: ['revenue'],
        colors: ['#D97706'],
        data: [
          { property: 'Ski Chalet', revenue: 8420 },
          { property: 'Canyon View', revenue: 6340 },
          { property: 'Mountain Cabin', revenue: 5880 },
          { property: 'Downtown Loft', revenue: 4560 },
          { property: 'Desert Oasis', revenue: 4200 },
          { property: 'Red Rock', revenue: 3980 },
          { property: 'Valley Town', revenue: 2480 },
          { property: 'Lake House', revenue: 1760 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Lake House Pricing Drop', description: 'Bear Lake occupancy at 42% during shoulder season. Drop nightly rate 15% and enable last-minute discounts to fill gaps.', impact: '+$2,400/mo revenue', action: 'Adjust Pricing' },
        { priority: 'high', title: 'Valley Townhome Underperforming', description: 'Tooele property at 68% occupancy with lowest RevPAR. Consider refreshing photos and adding amenities.', impact: '+$1,800/mo revenue', action: 'Review Listing' },
        { priority: 'medium', title: 'Expand to Booking.com', description: '4 properties not listed on Booking.com. Adding this channel historically increases bookings 12-18%.', impact: '+$3,200/mo revenue', action: 'Add Channel' },
        { priority: 'low', title: 'Ski Season Ending', description: 'Brighton Ski Chalet rates should transition from peak ($285) to off-peak ($165) by April 15.', impact: 'Maintain occupancy', action: 'Schedule Rate Change' },
      ],
      actions: [
        { label: 'Optimize All Pricing', description: 'AI-powered dynamic pricing adjustment across all properties' },
        { label: 'Generate Revenue Report', description: 'Portfolio-wide revenue analysis with property-level detail' },
        { label: 'Sync Calendars', description: 'Force-sync availability across all booking channels' },
        { label: 'Add Property', description: 'Onboard a new property with AI-suggested pricing and listing copy' },
      ],
    },
    {
      id: 'bookings',
      label: 'Bookings',
      kpis: [
        { label: 'Upcoming', value: 34, change: 8, trend: 'up', icon: '📅' },
        { label: 'Check-ins Today', value: 3, change: 1, trend: 'up', icon: '🛎️' },
        { label: 'Avg Stay', value: 3.8, suffix: ' nights', change: 4, trend: 'up', icon: '🌙' },
        { label: 'Cancellation Rate', value: 4.2, suffix: '%', change: -12, trend: 'down', icon: '❌' },
      ],
      columns: [
        { key: 'guest', label: 'Guest', sortable: true },
        { key: 'property', label: 'Property', sortable: true },
        { key: 'checkIn', label: 'Check-In', sortable: true },
        { key: 'nights', label: 'Nights', sortable: true },
        { key: 'total', label: 'Total', sortable: true },
        { key: 'channel', label: 'Channel', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { guest: 'Michael & Sarah K.', property: 'Mountain View Cabin', checkIn: 'Mar 22', nights: 4, total: 848, channel: 'Airbnb', status: 'Confirmed', specialRequests: 'Early check-in, dog friendly', guestRating: '4.9 (12 reviews)' },
        { guest: 'Jennifer L.', property: 'Downtown Loft', checkIn: 'Mar 21', nights: 2, total: 336, channel: 'Direct', status: 'Confirmed', specialRequests: 'Late check-out', guestRating: 'New guest' },
        { guest: 'Robert & Amy T.', property: 'Desert Oasis', checkIn: 'Mar 23', nights: 3, total: 570, channel: 'VRBO', status: 'Confirmed', specialRequests: 'Pack-n-play for infant', guestRating: '4.7 (8 reviews)' },
        { guest: 'David M.', property: 'Red Rock Studio', checkIn: 'Tonight', nights: 2, total: 284, channel: 'Airbnb', status: 'Checking In', specialRequests: 'None', guestRating: '4.8 (22 reviews)' },
        { guest: 'Corporate Group', property: 'Valley Townhome', checkIn: 'Mar 26', nights: 5, total: 570, channel: 'Direct', status: 'Pending', specialRequests: 'Invoice for company', guestRating: 'Corporate booking' },
        { guest: 'Linda & Mark F.', property: 'Canyon View Suite', checkIn: 'Mar 25', nights: 6, total: 1344, channel: 'VRBO', status: 'Confirmed', specialRequests: 'Anniversary celebration', guestRating: '5.0 (4 reviews)' },
      ],
      expandedFields: ['specialRequests', 'guestRating'],
      chart: {
        type: 'area',
        title: 'Booking Volume (8 Weeks)',
        xKey: 'week',
        dataKeys: ['bookings'],
        colors: ['#D97706'],
        data: [
          { week: 'W1', bookings: 18 },
          { week: 'W2', bookings: 22 },
          { week: 'W3', bookings: 28 },
          { week: 'W4', bookings: 34 },
          { week: 'W5', bookings: 38 },
          { week: 'W6', bookings: 42 },
          { week: 'W7', bookings: 44 },
          { week: 'W8', bookings: 46 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Gap Night Alert', description: 'Mountain View Cabin has a 1-night gap between bookings on Mar 26. Enable orphan night pricing (50% discount) to fill it.', impact: '+$106 revenue', action: 'Enable Gap Pricing' },
        { priority: 'medium', title: 'Corporate Booking Pending', description: 'Valley Townhome corporate booking ($570) is unpaid after 48 hours. Send payment reminder before auto-cancellation.', impact: 'Secure $570 booking', action: 'Send Reminder' },
      ],
      actions: [
        { label: 'Create Booking', description: 'Manual booking entry for direct reservations' },
        { label: 'Send Guest Messages', description: 'Batch-send check-in instructions to upcoming guests' },
        { label: 'Export Calendar', description: 'Download booking calendar across all properties' },
      ],
    },
    {
      id: 'pricing',
      label: 'Dynamic Pricing',
      kpis: [
        { label: 'Avg Nightly Rate', value: 189, prefix: '$', change: 8, trend: 'up', icon: '💵' },
        { label: 'Rate Adjustments', value: 42, change: 12, trend: 'up', icon: '📊' },
        { label: 'Revenue Lift', value: 18, suffix: '%', change: 4, trend: 'up', icon: '📈' },
        { label: 'Comp Set Index', value: 108, change: 3, trend: 'up', icon: '🎯' },
      ],
      columns: [
        { key: 'property', label: 'Property', sortable: true },
        { key: 'currentRate', label: 'Current Rate', sortable: true },
        { key: 'suggestedRate', label: 'Suggested', sortable: true },
        { key: 'compAvg', label: 'Comp Avg', sortable: true },
        { key: 'demand', label: 'Demand', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { property: 'Ski Chalet', currentRate: '$285', suggestedRate: '$245', compAvg: '$260', demand: 'Declining', status: 'Adjust', reasoning: 'Ski season ending, transition to spring rates', lastAdjusted: '2 weeks ago' },
        { property: 'Canyon View Suite', currentRate: '$224', suggestedRate: '$248', compAvg: '$232', demand: 'High', status: 'Increase', reasoning: 'Spring break demand surge in Moab', lastAdjusted: '3 days ago' },
        { property: 'Lake House', currentRate: '$210', suggestedRate: '$158', compAvg: '$145', demand: 'Low', status: 'Decrease', reasoning: 'Shoulder season, need to compete for bookings', lastAdjusted: '1 month ago' },
        { property: 'Downtown Loft', currentRate: '$168', suggestedRate: '$178', compAvg: '$172', demand: 'Medium', status: 'Increase', reasoning: 'Convention weekend pricing opportunity', lastAdjusted: '5 days ago' },
        { property: 'Desert Oasis', currentRate: '$190', suggestedRate: '$210', compAvg: '$195', demand: 'High', status: 'Increase', reasoning: 'Zion spring season beginning', lastAdjusted: '1 week ago' },
        { property: 'Valley Townhome', currentRate: '$114', suggestedRate: '$98', compAvg: '$105', demand: 'Low', status: 'Decrease', reasoning: 'Below-market occupancy, price to fill', lastAdjusted: '2 weeks ago' },
      ],
      expandedFields: ['reasoning', 'lastAdjusted'],
      chart: {
        type: 'line',
        title: 'Average Rate vs Occupancy',
        xKey: 'month',
        dataKeys: ['rate', 'occupancy'],
        colors: ['#D97706', '#059669'],
        data: [
          { month: 'Jan', rate: 198, occupancy: 82 },
          { month: 'Feb', rate: 212, occupancy: 86 },
          { month: 'Mar', rate: 189, occupancy: 78 },
          { month: 'Apr', rate: 168, occupancy: 72 },
          { month: 'May', rate: 178, occupancy: 74 },
          { month: 'Jun', rate: 204, occupancy: 88 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Spring Break Surge', description: 'Moab and Zion properties should increase rates 10-15% for Mar 25-Apr 5. Demand signals are 40% above baseline.', impact: '+$4,200 revenue', action: 'Apply Surge Pricing' },
        { priority: 'medium', title: 'Ski Chalet Transition', description: 'Reduce Brighton rates from $285 to $245 now, then $165 by April 15. Gradual decrease maintains some premium.', impact: 'Maintain 80% occupancy', action: 'Schedule Rate Plan' },
      ],
      actions: [
        { label: 'Apply AI Pricing', description: 'One-click apply all AI-suggested rate changes across portfolio' },
        { label: 'Run Comp Analysis', description: 'Compare your rates against local competition on all channels' },
        { label: 'Export Rate Calendar', description: 'Download rate calendar with current and suggested rates' },
      ],
    },
    {
      id: 'guest-experience',
      label: 'Guest Experience',
      kpis: [
        { label: 'Overall Rating', value: 4.7, suffix: '/5', change: 2, trend: 'up', icon: '⭐' },
        { label: 'Reviews (30d)', value: 28, change: 6, trend: 'up', icon: '📝' },
        { label: 'Response Rate', value: 98, suffix: '%', change: 1, trend: 'up', icon: '💬' },
        { label: 'Repeat Guests', value: 22, suffix: '%', change: 4, trend: 'up', icon: '🔄' },
      ],
      columns: [
        { key: 'property', label: 'Property', sortable: true },
        { key: 'rating', label: 'Rating', sortable: true },
        { key: 'reviews', label: 'Reviews', sortable: true },
        { key: 'topCompliment', label: 'Top Compliment', sortable: false },
        { key: 'topComplaint', label: 'Top Complaint', sortable: false },
        { key: 'trend', label: 'Trend', sortable: true },
      ],
      rows: [
        { property: 'Canyon View Suite', rating: '4.9/5', reviews: 142, topCompliment: 'Stunning views', topComplaint: 'Road noise early AM', trend: 'Improving', responseTime: '< 30 min', repeatRate: '28%' },
        { property: 'Mountain View Cabin', rating: '4.9/5', reviews: 98, topCompliment: 'Cozy and clean', topComplaint: 'Steep driveway in snow', trend: 'Stable', responseTime: '< 15 min', repeatRate: '24%' },
        { property: 'Ski Chalet', rating: '4.8/5', reviews: 76, topCompliment: 'Ski-in/ski-out access', topComplaint: 'Parking limited', trend: 'Improving', responseTime: '< 20 min', repeatRate: '32%' },
        { property: 'Lake House', rating: '4.8/5', reviews: 64, topCompliment: 'Peaceful location', topComplaint: 'WiFi spotty', trend: 'Stable', responseTime: '< 45 min', repeatRate: '18%' },
        { property: 'Downtown Loft', rating: '4.7/5', reviews: 112, topCompliment: 'Great location', topComplaint: 'Street noise weekends', trend: 'Improving', responseTime: '< 20 min', repeatRate: '20%' },
        { property: 'Red Rock Studio', rating: '4.6/5', reviews: 54, topCompliment: 'Value for money', topComplaint: 'Small kitchen', trend: 'Stable', responseTime: '< 30 min', repeatRate: '16%' },
        { property: 'Desert Oasis', rating: '4.5/5', reviews: 38, topCompliment: 'Outdoor space', topComplaint: 'AC slow to cool', trend: 'Declining', responseTime: '< 1 hr', repeatRate: '12%' },
        { property: 'Valley Townhome', rating: '4.4/5', reviews: 28, topCompliment: 'Spacious layout', topComplaint: 'Dated fixtures', trend: 'Declining', responseTime: '< 30 min', repeatRate: '8%' },
      ],
      expandedFields: ['responseTime', 'repeatRate'],
      chart: {
        type: 'line',
        title: 'Portfolio Rating Trend',
        xKey: 'month',
        dataKeys: ['rating'],
        colors: ['#D97706'],
        data: [
          { month: 'Jan', rating: 4.5 },
          { month: 'Feb', rating: 4.6 },
          { month: 'Mar', rating: 4.6 },
          { month: 'Apr', rating: 4.6 },
          { month: 'May', rating: 4.7 },
          { month: 'Jun', rating: 4.7 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Desert Oasis AC Issue', description: 'Recurring AC complaint across 4 recent reviews. HVAC service call needed before summer season drives demand.', impact: 'Protect 4.5 rating', action: 'Schedule HVAC Service' },
        { priority: 'high', title: 'Valley Townhome Refresh', description: 'Lowest rating in portfolio (4.4) with "dated fixtures" as top complaint. Kitchen and bathroom refresh estimated at $8K.', impact: '+0.3 rating boost', action: 'Approve Renovation' },
        { priority: 'medium', title: 'Lake House WiFi Upgrade', description: 'WiFi complaints affecting 4.8 rating. Starlink installation ($600) would resolve and enable remote worker marketing.', impact: 'Attract new segment', action: 'Order Starlink' },
      ],
      actions: [
        { label: 'Generate Review Report', description: 'AI-analyzed review sentiment across all properties with action items' },
        { label: 'Auto-Reply to Reviews', description: 'AI-crafted personalized responses to recent guest reviews' },
        { label: 'Export Guest Data', description: 'Download guest satisfaction metrics and contact information' },
      ],
    },
  ],
});
