import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'supply-chain',
    name: 'Supply Chain',
    icon: '\u{1F6E3}\u{FE0F}',
    dept: 'Operations',
    deptColor: '#2A9D8F',
    description: 'AI-powered supply chain visibility and optimization',
    valueProposition: 'End-to-end supply chain visibility with AI-driven demand planning and risk alerts',
    enabled: true,
    buildBatch: 3,
  },
  tabs: [
    {
      id: 'overview',
      label: 'Supply Chain Overview',
      kpis: [
        { label: 'Active Suppliers', value: 34, change: 2, trend: 'up', icon: '\u{1F465}' },
        { label: 'On-Time Delivery', value: 91, suffix: '%', change: 3, trend: 'up', icon: '\u{2705}' },
        { label: 'Avg Lead Time', value: 14, suffix: ' days', change: -8, trend: 'down', icon: '\u{23F1}\u{FE0F}' },
        { label: 'Risk Alerts', value: 4, change: -2, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
      ],
      columns: [
        { key: 'supplier', label: 'Supplier', sortable: true },
        { key: 'category', label: 'Category', sortable: true },
        { key: 'leadTime', label: 'Lead Time', sortable: true },
        { key: 'onTimeRate', label: 'On-Time %', sortable: true },
        { key: 'qualityScore', label: 'Quality', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { supplier: 'LogiParts Inc', category: 'Components', leadTime: '12 days', onTimeRate: '94%', qualityScore: '4.2/5', status: 'Active', annualSpend: '$480K', alternateSupplier: 'PartsDirect Co', riskLevel: 'Low' },
        { supplier: 'SteelWorks Global', category: 'Raw Materials', leadTime: '21 days', onTimeRate: '82%', qualityScore: '3.8/5', status: 'At Risk', annualSpend: '$320K', alternateSupplier: 'MetalSource Ltd', riskLevel: 'Medium' },
        { supplier: 'TechComponent Ltd', category: 'Electronics', leadTime: '18 days', onTimeRate: '88%', qualityScore: '4.5/5', status: 'Active', annualSpend: '$210K', alternateSupplier: 'None identified', riskLevel: 'High' },
        { supplier: 'Acme Supply Co', category: 'Hardware', leadTime: '8 days', onTimeRate: '96%', qualityScore: '4.4/5', status: 'Active', annualSpend: '$220K', alternateSupplier: 'Quality Fasteners', riskLevel: 'Low' },
        { supplier: 'PackRight Industries', category: 'Packaging', leadTime: '5 days', onTimeRate: '98%', qualityScore: '4.6/5', status: 'Active', annualSpend: '$140K', alternateSupplier: 'WrapCo', riskLevel: 'Low' },
        { supplier: 'Shenzhen Motors', category: 'Motors', leadTime: '42 days', onTimeRate: '74%', qualityScore: '3.4/5', status: 'At Risk', annualSpend: '$180K', alternateSupplier: 'Evaluating 2 options', riskLevel: 'Critical' },
      ],
      expandedFields: ['annualSpend', 'alternateSupplier', 'riskLevel'],
      chart: {
        type: 'bar',
        title: 'Supplier On-Time Rate',
        xKey: 'supplier',
        dataKeys: ['onTimeRate'],
        colors: ['#2A9D8F'],
        data: [
          { supplier: 'PackRight', onTimeRate: 98 },
          { supplier: 'Acme', onTimeRate: 96 },
          { supplier: 'LogiParts', onTimeRate: 94 },
          { supplier: 'TechComp', onTimeRate: 88 },
          { supplier: 'SteelWorks', onTimeRate: 82 },
          { supplier: 'Shenzhen', onTimeRate: 74 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Shenzhen Motors Risk', description: 'Shenzhen Motors has 74% on-time rate and 42-day lead time. No backup supplier identified. Qualify an alternate immediately.', impact: 'Prevent line stoppage', action: 'Start RFQ' },
        { priority: 'high', title: 'TechComponent Single Source', description: 'TechComponent Ltd is the sole supplier for electronics. Any disruption halts production. Identify and qualify a backup.', impact: 'Reduce risk', action: 'Find Alternate' },
        { priority: 'medium', title: 'Negotiate SteelWorks Terms', description: 'SteelWorks delivery dropped to 82%. Negotiate improvement targets or shift 30% of volume to MetalSource.', impact: 'Improve to 90%', action: 'Schedule Review' },
      ],
      actions: [
        { label: 'Run Risk Assessment', description: 'AI-powered supply chain risk analysis across all suppliers' },
        { label: 'Generate Scorecard', description: 'Quarterly supplier performance scorecards' },
        { label: 'Start RFQ Process', description: 'Launch request for quote to qualify new suppliers' },
        { label: 'Export Supplier Data', description: 'Download supplier performance metrics and risk scores' },
      ],
    },
    {
      id: 'demand-planning',
      label: 'Demand Planning',
      kpis: [
        { label: 'Forecast Accuracy', value: 86, suffix: '%', change: 4, trend: 'up', icon: '\u{1F3AF}' },
        { label: 'SKUs Forecasted', value: 4218, change: 0, trend: 'flat', icon: '\u{1F4E6}' },
        { label: 'Stockout Risk', value: 14, change: -4, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
        { label: 'Overstock Risk', value: 47, change: -8, trend: 'down', icon: '\u{1F4A4}' },
      ],
      columns: [
        { key: 'sku', label: 'SKU', sortable: true },
        { key: 'product', label: 'Product', sortable: true },
        { key: 'forecastQty', label: 'Forecast (30d)', sortable: true },
        { key: 'onHand', label: 'On Hand', sortable: true },
        { key: 'daysOfSupply', label: 'Days Supply', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { sku: 'WH-1104', product: 'Barcode Scanner Holster', forecastQty: 280, onHand: 0, daysOfSupply: 0, status: 'Critical', reorderQty: 400, leadTimeDays: 14, seasonalFactor: 'None' },
        { sku: 'WH-2218', product: 'Pallet Jack Wheels', forecastQty: 60, onHand: 8, daysOfSupply: 4, status: 'Low', reorderQty: 100, leadTimeDays: 12, seasonalFactor: 'None' },
        { sku: 'WH-4421', product: 'Heavy-Duty Shelf Unit', forecastQty: 180, onHand: 342, daysOfSupply: 57, status: 'Healthy', reorderQty: 200, leadTimeDays: 18, seasonalFactor: 'Q2 spike +20%' },
        { sku: 'WH-8834', product: 'Stretch Wrap 18in', forecastQty: 320, onHand: 480, daysOfSupply: 45, status: 'Healthy', reorderQty: 300, leadTimeDays: 5, seasonalFactor: 'None' },
        { sku: 'WH-7790', product: 'Conveyor Belt 12ft', forecastQty: 12, onHand: 156, daysOfSupply: 390, status: 'Overstock', reorderQty: 20, leadTimeDays: 21, seasonalFactor: 'None' },
      ],
      expandedFields: ['reorderQty', 'leadTimeDays', 'seasonalFactor'],
      chart: {
        type: 'line',
        title: 'Forecast Accuracy Trend',
        xKey: 'month',
        dataKeys: ['accuracy', 'target'],
        colors: ['#2A9D8F', '#E5E7EB'],
        data: [
          { month: 'Jan', accuracy: 78, target: 90 },
          { month: 'Feb', accuracy: 80, target: 90 },
          { month: 'Mar', accuracy: 82, target: 90 },
          { month: 'Apr', accuracy: 84, target: 90 },
          { month: 'May', accuracy: 85, target: 90 },
          { month: 'Jun', accuracy: 86, target: 90 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Emergency Reorder WH-1104', description: 'Barcode Scanner Holsters have zero stock with 280 forecasted demand in 30 days. Emergency order with expedited shipping.', impact: 'Prevent 280 backorders', action: 'Emergency Reorder' },
        { priority: 'high', title: 'Liquidate Conveyor Overstock', description: 'WH-7790 has 390 days of supply. Offer a 15% volume discount to move 100 units and free $42K in working capital.', impact: 'Free $42K cash', action: 'Create Promotion' },
      ],
      actions: [
        { label: 'Run Demand Forecast', description: 'AI-powered demand forecast using historical data and market signals' },
        { label: 'Generate Reorder Plan', description: 'Optimal reorder quantities and timing for all SKUs' },
        { label: 'Export Forecast', description: 'Download demand forecast with confidence intervals' },
      ],
    },
    {
      id: 'shipments',
      label: 'Inbound Shipments',
      kpis: [
        { label: 'In Transit', value: 12, change: 2, trend: 'up', icon: '\u{1F69A}' },
        { label: 'Arriving Today', value: 3, change: 1, trend: 'up', icon: '\u{1F4C5}' },
        { label: 'Delayed', value: 2, change: -1, trend: 'down', icon: '\u{1F534}' },
        { label: 'Avg Transit Days', value: 8, change: -1, trend: 'down', icon: '\u{23F1}\u{FE0F}' },
      ],
      columns: [
        { key: 'shipment', label: 'Shipment', sortable: true },
        { key: 'supplier', label: 'Supplier', sortable: true },
        { key: 'items', label: 'Items', sortable: true },
        { key: 'eta', label: 'ETA', sortable: true },
        { key: 'origin', label: 'Origin', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { shipment: 'ISH-801', supplier: 'LogiParts Inc', items: 480, eta: 'Today', origin: 'Salt Lake City, UT', status: 'Arriving', carrier: 'FedEx Freight', tracking: '789012345', value: '$18,400' },
        { shipment: 'ISH-802', supplier: 'Shenzhen Motors', items: 24, eta: 'Apr 2', origin: 'Shenzhen, CN', status: 'In Transit', carrier: 'Ocean + Last Mile', tracking: 'MAEU123456', value: '$14,200' },
        { shipment: 'ISH-803', supplier: 'SteelWorks Global', items: 200, eta: 'Mar 24', origin: 'Pittsburgh, PA', status: 'Delayed', carrier: 'YRC Freight', tracking: 'YRC-88421', value: '$28,000' },
        { shipment: 'ISH-804', supplier: 'PackRight Industries', items: 1200, eta: 'Today', origin: 'Denver, CO', status: 'Arriving', carrier: 'UPS Ground', tracking: '1Z888CC3059', value: '$4,200' },
        { shipment: 'ISH-805', supplier: 'TechComponent Ltd', items: 48, eta: 'Mar 28', origin: 'Austin, TX', status: 'In Transit', carrier: 'FedEx Express', tracking: '456789012', value: '$22,800' },
      ],
      expandedFields: ['carrier', 'tracking', 'value'],
      chart: {
        type: 'area',
        title: 'Inbound Shipments (30 Days)',
        xKey: 'week',
        dataKeys: ['onTime', 'delayed'],
        colors: ['#059669', '#DC2626'],
        data: [
          { week: 'W1', onTime: 8, delayed: 2 },
          { week: 'W2', onTime: 10, delayed: 1 },
          { week: 'W3', onTime: 9, delayed: 3 },
          { week: 'W4', onTime: 11, delayed: 2 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'SteelWorks Shipment Delayed', description: 'ISH-803 from SteelWorks is delayed 2 days. Contains materials for DC Expansion project. Alert Tom Bradley.', impact: 'Project delay risk', action: 'Notify Team' },
        { priority: 'medium', title: 'Shenzhen Lead Time Creeping', description: 'Shenzhen Motors ocean shipments now averaging 42 days vs 35-day contract. Discuss with freight forwarder.', impact: 'Reduce lead time', action: 'Contact Forwarder' },
      ],
      actions: [
        { label: 'Track Shipments', description: 'Real-time tracking dashboard for all inbound shipments' },
        { label: 'Set Delay Alerts', description: 'Automated alerts when shipments miss ETA windows' },
        { label: 'Export Shipment Log', description: 'Download inbound shipment data with tracking and status' },
      ],
    },
    {
      id: 'procurement',
      label: 'Procurement',
      kpis: [
        { label: 'Open POs', value: 18, change: 2, trend: 'up', icon: '\u{1F4CB}' },
        { label: 'PO Value', value: 342000, prefix: '$', change: 8, trend: 'up', icon: '\u{1F4B0}' },
        { label: 'Savings This Quarter', value: 28000, prefix: '$', change: 14, trend: 'up', icon: '\u{1F4B5}' },
        { label: 'Pending Approvals', value: 3, change: -1, trend: 'down', icon: '\u{23F3}' },
      ],
      columns: [
        { key: 'po', label: 'PO #', sortable: true },
        { key: 'supplier', label: 'Supplier', sortable: true },
        { key: 'value', label: 'Value', sortable: true },
        { key: 'items', label: 'Items', sortable: true },
        { key: 'requestedBy', label: 'Requested By', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { po: 'PO-4430', supplier: 'LogiParts Inc', value: 42600, items: 12, requestedBy: 'Tom B.', status: 'Approved', category: 'Components', deliveryDate: 'Apr 8', budgetCode: 'OPS-2025-Q2' },
        { po: 'PO-4431', supplier: 'SteelWorks Global', value: 84000, items: 4, requestedBy: 'Sarah K.', status: 'Pending', category: 'Raw Materials', deliveryDate: 'Apr 22', budgetCode: 'PROJ-DCX-2' },
        { po: 'PO-4432', supplier: 'TechComponent Ltd', value: 22800, items: 48, requestedBy: 'Steve M.', status: 'Approved', category: 'Electronics', deliveryDate: 'Mar 28', budgetCode: 'ENG-2025' },
        { po: 'PO-4433', supplier: 'PackRight Industries', value: 8400, items: 2400, requestedBy: 'Carlos D.', status: 'Approved', category: 'Packaging', deliveryDate: 'Mar 25', budgetCode: 'OPS-2025-Q1' },
      ],
      expandedFields: ['category', 'deliveryDate', 'budgetCode'],
      chart: {
        type: 'pie',
        title: 'PO Value by Category',
        dataKeys: ['value'],
        data: [
          { name: 'Raw Materials', value: 84000 },
          { name: 'Components', value: 42600 },
          { name: 'Electronics', value: 22800 },
          { name: 'Packaging', value: 8400 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'SteelWorks PO Needs Approval', description: 'PO-4431 for $84,000 in raw materials is pending approval. DC Expansion project depends on this order shipping by Friday.', impact: 'Prevent project delay', action: 'Approve PO' },
        { priority: 'medium', title: 'Consolidate PackRight Orders', description: 'Three separate PackRight POs this month. Consolidating into monthly orders saves $1,200/yr in processing costs.', impact: '$1,200/yr savings', action: 'Set Up Blanket PO' },
      ],
      actions: [
        { label: 'Create PO', description: 'Generate purchase order with AI-suggested quantities and vendors' },
        { label: 'Approve Pending', description: 'Review and approve pending purchase orders' },
        { label: 'Export PO Report', description: 'Download procurement data with budget tracking' },
      ],
    },
  ],
});
