import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'support',
    name: 'Support',
    icon: '\u{1F3A7}',
    dept: 'People',
    deptColor: '#6366F1',
    description: 'AI-powered customer support and ticket management',
    valueProposition: 'Resolve tickets faster, predict escalations, and keep every customer happy',
    enabled: true,
    buildBatch: 1,
  },
  tabs: [
    {
      id: 'ticket-queue',
      label: 'Ticket Queue',
      kpis: [
        { label: 'Open Tickets', value: 47, change: -8, trend: 'down', icon: '\u{1F3AB}' },
        { label: 'Avg Response', value: 2.4, suffix: ' hrs', change: -18, trend: 'down', icon: '\u{23F1}\u{FE0F}' },
        { label: 'CSAT', value: 4.2, suffix: '/5', change: 7, trend: 'up', icon: '\u{2B50}' },
        { label: 'Resolution Rate', value: 89, suffix: '%', change: 4, trend: 'up', icon: '\u{2705}' },
      ],
      columns: [
        { key: 'ticketId', label: 'Ticket', sortable: true },
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'subject', label: 'Subject', sortable: false },
        { key: 'priority', label: 'Priority', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
        { key: 'assignee', label: 'Assigned', sortable: true },
        { key: 'age', label: 'Age', sortable: true },
      ],
      rows: [
        { ticketId: 'TK-4421', customer: 'TechFlow Inc', subject: 'Login errors after update', priority: 'Critical', status: 'Open', assignee: 'Rachel S.', age: '4 hrs', history: '3 messages, escalated once', customerArn: '$48K ARR', suggestedFix: 'Clear auth cache, reissue JWT tokens' },
        { ticketId: 'TK-4422', customer: 'Apex Fulfillment', subject: 'API rate limit too low', priority: 'High', status: 'In Progress', assignee: 'Mark T.', age: '1 day', history: '5 messages, API logs attached', customerArn: '$24K ARR', suggestedFix: 'Upgrade rate tier or implement batching' },
        { ticketId: 'TK-4423', customer: 'Metro Systems', subject: 'Report export blank', priority: 'Medium', status: 'Open', assignee: 'Unassigned', age: '2 hrs', history: '1 message, screenshot attached', customerArn: '$18K ARR', suggestedFix: 'Date range filter empty; reset defaults' },
        { ticketId: 'TK-4424', customer: 'Summit Retail', subject: 'Dashboard loading slow', priority: 'Medium', status: 'In Progress', assignee: 'Rachel S.', age: '6 hrs', history: '2 messages', customerArn: '$36K ARR', suggestedFix: 'Optimize query caching on dashboard endpoint' },
        { ticketId: 'TK-4425', customer: 'Velocity Logistics', subject: 'Webhook not firing', priority: 'High', status: 'Open', assignee: 'Mark T.', age: '3 hrs', history: '1 message, webhook config attached', customerArn: '$42K ARR', suggestedFix: 'Endpoint URL missing trailing slash' },
        { ticketId: 'TK-4426', customer: 'Cascade Materials', subject: 'Feature request: bulk import', priority: 'Low', status: 'Open', assignee: 'Unassigned', age: '2 days', history: '1 message', customerArn: '$12K ARR', suggestedFix: 'Add to product backlog, ETA Q3' },
        { ticketId: 'TK-4427', customer: 'Pacific Freight', subject: 'SSO integration broken', priority: 'Critical', status: 'In Progress', assignee: 'Rachel S.', age: '1 hr', history: '2 messages, urgent escalation', customerArn: '$64K ARR', suggestedFix: 'SAML cert expired; customer needs to re-upload' },
      ],
      expandedFields: ['history', 'customerArn', 'suggestedFix'],
      chart: {
        type: 'area',
        title: 'Ticket Volume (30 Days)',
        xKey: 'day',
        dataKeys: ['opened', 'resolved'],
        colors: ['#DC2626', '#059669'],
        data: [
          { day: 'W1', opened: 42, resolved: 38 },
          { day: 'W2', opened: 38, resolved: 40 },
          { day: 'W3', opened: 45, resolved: 42 },
          { day: 'W4', opened: 36, resolved: 39 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: '12 Login Error Tickets', description: '12 tickets this week report login errors after the latest update. Likely a systemic bug. Escalate to engineering.', impact: 'Affects 12 customers', action: 'Escalate to Engineering' },
        { priority: 'high', title: 'TechFlow CSAT Dropped to 2.1', description: 'TechFlow Inc (Enterprise, $48K ARR) CSAT dropped from 4.1 to 2.1. Schedule executive health check.', impact: '$48K ARR at risk', action: 'Schedule Health Check' },
        { priority: 'medium', title: 'P1 Response Time Above Target', description: 'P1 average response is 45 minutes vs 15-minute target. Staffing gap during 2-4PM window.', impact: 'Meet SLA target', action: 'Adjust Staffing' },
      ],
      actions: [
        { label: 'Create Ticket', description: 'Open a new support ticket with AI-suggested priority and routing' },
        { label: 'Generate CSAT Report', description: 'Customer satisfaction trends by segment and issue type' },
        { label: 'Update Knowledge Base', description: 'Auto-generate KB articles from resolved ticket patterns' },
        { label: 'Escalate to Engineering', description: 'Create engineering bug report from ticket cluster analysis' },
      ],
    },
    {
      id: 'performance',
      label: 'Performance',
      kpis: [
        { label: 'Tickets Resolved', value: 312, change: 8, trend: 'up', icon: '\u{2705}' },
        { label: 'First Response', value: 1.8, suffix: ' hrs', change: -12, trend: 'down', icon: '\u{23F1}\u{FE0F}' },
        { label: 'First Contact Resolution', value: 64, suffix: '%', change: 5, trend: 'up', icon: '\u{1F3AF}' },
        { label: 'Agent Utilization', value: 84, suffix: '%', change: 3, trend: 'up', icon: '\u{1F4CA}' },
      ],
      columns: [
        { key: 'agent', label: 'Agent', sortable: true },
        { key: 'resolved', label: 'Resolved', sortable: true },
        { key: 'avgResponse', label: 'Avg Response', sortable: true },
        { key: 'csat', label: 'CSAT', sortable: true },
        { key: 'fcr', label: 'FCR %', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { agent: 'Rachel Simmons', resolved: 142, avgResponse: '1.2 hrs', csat: '4.6/5', fcr: '72%', status: 'Active', specialization: 'Enterprise accounts', escalations: 3 },
        { agent: 'Mark Torres', resolved: 118, avgResponse: '2.1 hrs', csat: '4.0/5', fcr: '58%', status: 'Active', specialization: 'API/Technical', escalations: 8 },
        { agent: 'Jennifer Walsh', resolved: 52, avgResponse: '2.8 hrs', csat: '3.8/5', fcr: '52%', status: 'Active', specialization: 'Onboarding', escalations: 6 },
      ],
      expandedFields: ['specialization', 'escalations'],
      chart: {
        type: 'line',
        title: 'Response Time Trend',
        xKey: 'week',
        dataKeys: ['avgResponse', 'target'],
        colors: ['#6366F1', '#E5E7EB'],
        data: [
          { week: 'W1', avgResponse: 3.2, target: 2.0 },
          { week: 'W2', avgResponse: 2.8, target: 2.0 },
          { week: 'W3', avgResponse: 2.4, target: 2.0 },
          { week: 'W4', avgResponse: 1.8, target: 2.0 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Jennifer Needs Coaching', description: 'Jennifer has the lowest FCR at 52% and highest escalation rate. Her CSAT is 0.8 below team average.', impact: '+14% FCR', action: 'Create Training Plan' },
        { priority: 'medium', title: 'Response Time Improving', description: 'Team response time dropped from 3.2 to 1.8 hours over 4 weeks. Now below 2-hour target.', impact: 'Maintain trend', action: 'View Analysis' },
      ],
      actions: [
        { label: 'Generate Team Report', description: 'Agent-by-agent performance analysis with benchmarks' },
        { label: 'Schedule Training', description: 'AI-recommended training based on ticket pattern analysis' },
        { label: 'Export Metrics', description: 'Download support KPIs and SLA performance data' },
      ],
    },
    {
      id: 'customer-health',
      label: 'Customer Health',
      kpis: [
        { label: 'Healthy', value: 68, suffix: '%', change: 4, trend: 'up', icon: '\u{1F49A}' },
        { label: 'At Risk', value: 12, change: -2, trend: 'down', icon: '\u{1F7E1}' },
        { label: 'Critical', value: 4, change: -1, trend: 'down', icon: '\u{1F534}' },
        { label: 'Avg Health Score', value: 74, suffix: '/100', change: 3, trend: 'up', icon: '\u{1F4CA}' },
      ],
      columns: [
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'healthScore', label: 'Score', sortable: true },
        { key: 'tickets30d', label: 'Tickets (30d)', sortable: true },
        { key: 'csat', label: 'CSAT', sortable: true },
        { key: 'arr', label: 'ARR', sortable: true },
        { key: 'status', label: 'Health', sortable: true },
      ],
      rows: [
        { customer: 'TechFlow Inc', healthScore: 42, tickets30d: 8, csat: '2.1/5', arr: '$48K', status: 'Critical', lastContact: '2 days ago', renewalDate: 'Jun 15', churnRisk: '78%' },
        { customer: 'Pacific Freight', healthScore: 56, tickets30d: 5, csat: '3.2/5', arr: '$64K', status: 'At Risk', lastContact: 'Today', renewalDate: 'Aug 1', churnRisk: '45%' },
        { customer: 'Velocity Logistics', healthScore: 82, tickets30d: 1, csat: '4.5/5', arr: '$42K', status: 'Healthy', lastContact: '1 week ago', renewalDate: 'Sep 30', churnRisk: '8%' },
        { customer: 'Summit Retail', healthScore: 71, tickets30d: 3, csat: '3.8/5', arr: '$36K', status: 'Pending', lastContact: '3 days ago', renewalDate: 'Jul 15', churnRisk: '22%' },
        { customer: 'Apex Fulfillment', healthScore: 88, tickets30d: 2, csat: '4.2/5', arr: '$24K', status: 'Healthy', lastContact: '5 days ago', renewalDate: 'Dec 1', churnRisk: '5%' },
      ],
      expandedFields: ['lastContact', 'renewalDate', 'churnRisk'],
      chart: {
        type: 'bar',
        title: 'Health Score Distribution',
        xKey: 'range',
        dataKeys: ['count'],
        colors: ['#6366F1'],
        data: [
          { range: '0-25 Critical', count: 4 },
          { range: '26-50 Poor', count: 8 },
          { range: '51-75 Fair', count: 22 },
          { range: '76-100 Healthy', count: 48 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'TechFlow Churn Risk 78%', description: 'TechFlow (Enterprise, $48K ARR) health score dropped to 42. 8 tickets in 30 days, CSAT at 2.1. Renewal in 3 months.', impact: '$48K ARR at risk', action: 'Executive Outreach' },
        { priority: 'high', title: 'Pacific Freight Needs Attention', description: 'Pacific Freight ($64K ARR) health declining. SSO integration issues affecting daily usage.', impact: '$64K ARR at risk', action: 'Schedule Review' },
      ],
      actions: [
        { label: 'Generate Health Report', description: 'Customer health scores with trend analysis and churn prediction' },
        { label: 'Schedule QBRs', description: 'Quarterly business reviews for at-risk and critical accounts' },
        { label: 'Export Customer Data', description: 'Download health scores, tickets, and engagement metrics' },
      ],
    },
    {
      id: 'knowledge-base',
      label: 'Knowledge Base',
      kpis: [
        { label: 'Articles', value: 142, change: 8, trend: 'up', icon: '\u{1F4DA}' },
        { label: 'Weekly Views', value: 4200, change: 14, trend: 'up', icon: '\u{1F441}\u{FE0F}' },
        { label: 'Deflection Rate', value: 34, suffix: '%', change: 6, trend: 'up', icon: '\u{1F6E1}\u{FE0F}' },
        { label: 'Outdated', value: 12, change: -4, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
      ],
      columns: [
        { key: 'article', label: 'Article', sortable: true },
        { key: 'views', label: 'Views', sortable: true },
        { key: 'helpfulRate', label: 'Helpful %', sortable: true },
        { key: 'category', label: 'Category', sortable: true },
        { key: 'lastUpdated', label: 'Updated', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { article: 'Getting Started Guide', views: 892, helpfulRate: '94%', category: 'Onboarding', lastUpdated: 'Mar 12', status: 'Active', ticketsDeflected: 124, avgTimeOnPage: '4.2 min' },
        { article: 'API Authentication Setup', views: 654, helpfulRate: '82%', category: 'Technical', lastUpdated: 'Feb 28', status: 'Active', ticketsDeflected: 87, avgTimeOnPage: '6.1 min' },
        { article: 'SSO Configuration Guide', views: 312, helpfulRate: '68%', category: 'Technical', lastUpdated: 'Jan 15', status: 'Stale', ticketsDeflected: 34, avgTimeOnPage: '3.8 min' },
        { article: 'Billing FAQ', views: 478, helpfulRate: '88%', category: 'Account', lastUpdated: 'Mar 8', status: 'Active', ticketsDeflected: 56, avgTimeOnPage: '2.1 min' },
        { article: 'Dashboard Customization', views: 234, helpfulRate: '76%', category: 'Features', lastUpdated: 'Feb 14', status: 'Active', ticketsDeflected: 28, avgTimeOnPage: '5.4 min' },
      ],
      expandedFields: ['ticketsDeflected', 'avgTimeOnPage'],
      chart: {
        type: 'pie',
        title: 'Tickets by Category',
        dataKeys: ['value'],
        data: [
          { name: 'Technical', value: 34 },
          { name: 'Account', value: 22 },
          { name: 'Onboarding', value: 18 },
          { name: 'Features', value: 15 },
          { name: 'Billing', value: 11 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'SSO Guide Outdated', description: 'SSO Configuration Guide has 68% helpful rate and is 2 months old. 5 recent tickets reference incorrect steps.', impact: 'Deflect 15 tickets/mo', action: 'Update Article' },
        { priority: 'medium', title: 'Create Webhook Guide', description: 'No KB article for webhooks despite 8 tickets this month. Auto-generate from resolved ticket patterns.', impact: 'Deflect 8 tickets/mo', action: 'Generate Article' },
      ],
      actions: [
        { label: 'Auto-Generate Articles', description: 'Create KB articles from patterns in resolved tickets' },
        { label: 'Flag Outdated Content', description: 'Scan for articles with low helpful rates or old update dates' },
        { label: 'Export Analytics', description: 'Download KB performance metrics and deflection data' },
      ],
    },
  ],
});
