import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'training',
    name: 'Training',
    icon: '\u{1F393}',
    dept: 'People',
    deptColor: '#6366F1',
    description: 'AI-powered employee training, onboarding, and skill development',
    valueProposition: 'Onboard faster, track certifications, and build a skilled workforce with AI-guided learning',
    enabled: true,
    buildBatch: 3,
  },
  tabs: [
    {
      id: 'programs',
      label: 'Programs',
      kpis: [
        { label: 'Active Programs', value: 12, change: 2, trend: 'up', icon: '\u{1F4DA}' },
        { label: 'Enrolled', value: 94, change: 14, trend: 'up', icon: '\u{1F464}' },
        { label: 'Completion Rate', value: 78, suffix: '%', change: 6, trend: 'up', icon: '\u{2705}' },
        { label: 'Avg Score', value: 84, suffix: '%', change: 3, trend: 'up', icon: '\u{1F3AF}' },
      ],
      columns: [
        { key: 'program', label: 'Program', sortable: true },
        { key: 'category', label: 'Category', sortable: true },
        { key: 'enrolled', label: 'Enrolled', sortable: true },
        { key: 'completed', label: 'Completed', sortable: true },
        { key: 'avgScore', label: 'Avg Score', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { program: 'Forklift Certification', category: 'Safety', enrolled: 18, completed: 14, avgScore: '92%', status: 'Active', duration: '8 hours', expiresIn: 'Annual renewal', instructor: 'Carlos D.' },
        { program: 'WMS Software Training', category: 'Technical', enrolled: 24, completed: 16, avgScore: '86%', status: 'Active', duration: '12 hours', expiresIn: 'N/A', instructor: 'Self-paced' },
        { program: 'OSHA-30 Safety', category: 'Compliance', enrolled: 12, completed: 8, avgScore: '88%', status: 'Active', duration: '30 hours', expiresIn: '5 years', instructor: 'External vendor' },
        { program: 'New Hire Onboarding', category: 'Onboarding', enrolled: 8, completed: 5, avgScore: '78%', status: 'Active', duration: '16 hours', expiresIn: 'N/A', instructor: 'Amy J.' },
        { program: 'Leadership Development', category: 'Management', enrolled: 6, completed: 2, avgScore: '82%', status: 'Active', duration: '24 hours', expiresIn: 'N/A', instructor: 'External coach' },
        { program: 'Hazmat Handling', category: 'Safety', enrolled: 8, completed: 8, avgScore: '94%', status: 'Completed', duration: '4 hours', expiresIn: '2 years', instructor: 'Carlos D.' },
      ],
      expandedFields: ['duration', 'expiresIn', 'instructor'],
      chart: {
        type: 'bar',
        title: 'Completion Rate by Category',
        xKey: 'category',
        dataKeys: ['rate'],
        colors: ['#6366F1'],
        data: [
          { category: 'Safety', rate: 88 },
          { category: 'Compliance', rate: 82 },
          { category: 'Technical', rate: 76 },
          { category: 'Onboarding', rate: 72 },
          { category: 'Management', rate: 68 },
        ],
      },
      recommendations: [
        { priority: 'high', title: '4 Forklift Certs Expiring', description: 'Four employees have forklift certifications expiring within 30 days. Schedule recertification immediately.', impact: 'Maintain compliance', action: 'Schedule Recertification' },
        { priority: 'medium', title: 'WMS Training Behind Schedule', description: '8 of 24 enrolled employees have not started WMS training. Send reminders and set completion deadline.', impact: 'Full team trained', action: 'Send Reminders' },
      ],
      actions: [
        { label: 'Create Program', description: 'AI-designed training program based on role and skill requirements' },
        { label: 'Enroll Employees', description: 'Batch enroll team members in training programs' },
        { label: 'Generate Compliance Report', description: 'Certification status and expiration tracking' },
        { label: 'Export Training Data', description: 'Download enrollment, completion, and score data' },
      ],
    },
    {
      id: 'certifications',
      label: 'Certifications',
      kpis: [
        { label: 'Active Certs', value: 142, change: 8, trend: 'up', icon: '\u{1F4DC}' },
        { label: 'Expiring 30d', value: 8, change: -2, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
        { label: 'Expired', value: 2, change: -1, trend: 'down', icon: '\u{1F534}' },
        { label: 'Compliance %', value: 96, suffix: '%', change: 2, trend: 'up', icon: '\u{2705}' },
      ],
      columns: [
        { key: 'employee', label: 'Employee', sortable: true },
        { key: 'certification', label: 'Certification', sortable: true },
        { key: 'issued', label: 'Issued', sortable: true },
        { key: 'expires', label: 'Expires', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { employee: 'Mike Rodriguez', certification: 'Forklift Operator', issued: 'Apr 2024', expires: 'Apr 2025', status: 'Expiring', renewalCost: '$250', renewalTime: '4 hours' },
        { employee: 'Anna Lee', certification: 'Electrical Safety', issued: 'Mar 2023', expires: 'Mar 2025', status: 'Expired', renewalCost: '$400', renewalTime: '8 hours' },
        { employee: 'Carlos Diaz', certification: 'OSHA-30', issued: 'Jun 2022', expires: 'Jun 2027', status: 'Active', renewalCost: '$600', renewalTime: '30 hours' },
        { employee: 'Tom Bradley', certification: 'Crane Operator', issued: 'Nov 2024', expires: 'Nov 2026', status: 'Active', renewalCost: '$500', renewalTime: '16 hours' },
        { employee: 'Sarah Kim', certification: 'PMP', issued: 'Jan 2024', expires: 'Jan 2027', status: 'Active', renewalCost: '$555', renewalTime: '60 PDUs' },
      ],
      expandedFields: ['renewalCost', 'renewalTime'],
      chart: {
        type: 'pie',
        title: 'Certification Status',
        dataKeys: ['value'],
        data: [
          { name: 'Active', value: 132 },
          { name: 'Expiring (30d)', value: 8 },
          { name: 'Expired', value: 2 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Anna Lee Cert Expired', description: 'Anna Lee Electrical Safety certification expired. She cannot perform electrical work until recertified. Schedule immediately.', impact: 'Compliance risk', action: 'Schedule Renewal' },
        { priority: 'high', title: 'Batch Forklift Renewals', description: '4 forklift certs expiring in April. Schedule a group recertification session to save $200 in training costs.', impact: '$200 savings', action: 'Schedule Group Session' },
      ],
      actions: [
        { label: 'Set Renewal Alerts', description: 'Automated alerts 60, 30, and 7 days before certification expiry' },
        { label: 'Generate Compliance Report', description: 'Full certification compliance report for audits' },
        { label: 'Export Cert Data', description: 'Download all certification records with expiry tracking' },
      ],
    },
    {
      id: 'onboarding',
      label: 'Onboarding',
      kpis: [
        { label: 'Active Onboards', value: 5, change: 2, trend: 'up', icon: '\u{1F195}' },
        { label: 'Avg Time-to-Productive', value: 18, suffix: ' days', change: -4, trend: 'down', icon: '\u{23F1}\u{FE0F}' },
        { label: 'Satisfaction', value: 4.4, suffix: '/5', change: 3, trend: 'up', icon: '\u{2B50}' },
        { label: 'Tasks Completed', value: 82, suffix: '%', change: 8, trend: 'up', icon: '\u{1F4CA}' },
      ],
      columns: [
        { key: 'employee', label: 'New Hire', sortable: true },
        { key: 'role', label: 'Role', sortable: true },
        { key: 'startDate', label: 'Start Date', sortable: true },
        { key: 'progress', label: 'Progress', sortable: true },
        { key: 'buddy', label: 'Buddy', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { employee: 'Jordan Rivera', role: 'Software Engineer', startDate: 'Mar 18', progress: '35%', buddy: 'Tyler Brooks', status: 'Active', completedTasks: '7 of 20', nextMilestone: 'Dev environment setup', weeklyCheckIn: 'Mar 22' },
        { employee: 'Priya Patel', role: 'Financial Analyst', startDate: 'Mar 25', progress: '0%', buddy: 'Lisa R.', status: 'Pending', completedTasks: '0 of 18', nextMilestone: 'System access setup', weeklyCheckIn: 'Apr 1' },
        { employee: 'Marcus Thompson', role: 'Warehouse Associate', startDate: 'Mar 11', progress: '62%', buddy: 'Mike R.', status: 'Active', completedTasks: '10 of 16', nextMilestone: 'Forklift certification', weeklyCheckIn: 'Mar 22' },
      ],
      expandedFields: ['completedTasks', 'nextMilestone', 'weeklyCheckIn'],
      chart: {
        type: 'line',
        title: 'Time-to-Productive Trend',
        xKey: 'quarter',
        dataKeys: ['days', 'target'],
        colors: ['#6366F1', '#E5E7EB'],
        data: [
          { quarter: 'Q3 2024', days: 28, target: 21 },
          { quarter: 'Q4 2024', days: 24, target: 21 },
          { quarter: 'Q1 2025', days: 22, target: 21 },
          { quarter: 'Q2 2025', days: 18, target: 21 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Jordan Missing Dev Setup', description: 'Jordan Rivera has not completed dev environment setup (Day 3 task) on Day 5. Check if blocked on access permissions.', impact: 'Prevent ramp delay', action: 'Check Status' },
        { priority: 'medium', title: 'Pre-Board Priya Patel', description: 'Priya starts Mar 25. Pre-provision accounts and send welcome materials to accelerate first week.', impact: 'Faster ramp', action: 'Start Pre-Boarding' },
      ],
      actions: [
        { label: 'Create Onboard Plan', description: 'AI-generated onboarding checklist tailored to role and department' },
        { label: 'Assign Buddy', description: 'Match new hires with onboarding buddies based on role and team' },
        { label: 'Export Progress', description: 'Download onboarding progress for all active new hires' },
      ],
    },
    {
      id: 'skills-matrix',
      label: 'Skills Matrix',
      kpis: [
        { label: 'Skills Tracked', value: 48, change: 4, trend: 'up', icon: '\u{1F4CA}' },
        { label: 'Avg Proficiency', value: 3.4, suffix: '/5', change: 2, trend: 'up', icon: '\u{1F3AF}' },
        { label: 'Skill Gaps', value: 12, change: -3, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
        { label: 'Cross-Trained', value: 34, suffix: '%', change: 6, trend: 'up', icon: '\u{1F504}' },
      ],
      columns: [
        { key: 'employee', label: 'Employee', sortable: true },
        { key: 'department', label: 'Dept', sortable: true },
        { key: 'primarySkill', label: 'Primary Skill', sortable: true },
        { key: 'proficiency', label: 'Proficiency', sortable: true },
        { key: 'crossTrained', label: 'Cross-Trained', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { employee: 'Tom Bradley', department: 'Operations', primarySkill: 'Installation', proficiency: '4.8/5', crossTrained: 'Electrical, Crane', status: 'Expert', gap: 'None', developmentPlan: 'Mentor junior installers' },
        { employee: 'Sarah Kim', department: 'Engineering', primarySkill: 'Project Mgmt', proficiency: '4.5/5', crossTrained: 'Lean Six Sigma', status: 'Expert', gap: 'None', developmentPlan: 'PMP renewal' },
        { employee: 'Mike Rodriguez', department: 'Operations', primarySkill: 'Warehouse Ops', proficiency: '3.2/5', crossTrained: 'Forklift only', status: 'Developing', gap: 'WMS system, inventory mgmt', developmentPlan: 'Enroll in WMS training' },
        { employee: 'Anna Lee', department: 'Maintenance', primarySkill: 'Electrical', proficiency: '4.2/5', crossTrained: 'HVAC, Plumbing', status: 'Advanced', gap: 'PLC programming', developmentPlan: 'PLC course Q3' },
      ],
      expandedFields: ['gap', 'developmentPlan'],
      chart: {
        type: 'bar',
        title: 'Cross-Training Coverage by Dept',
        xKey: 'department',
        dataKeys: ['coverage'],
        colors: ['#6366F1'],
        data: [
          { department: 'Maintenance', coverage: 48 },
          { department: 'Engineering', coverage: 42 },
          { department: 'Operations', coverage: 34 },
          { department: 'Sales', coverage: 22 },
          { department: 'Support', coverage: 18 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'WMS Skill Gap Critical', description: 'Only 16 of 24 warehouse staff are WMS-trained. New system features require 100% proficiency. Enroll remaining 8.', impact: 'Full team capable', action: 'Enroll Staff' },
        { priority: 'medium', title: 'Cross-Train Operations', description: 'Operations cross-training at 34% vs 48% for Maintenance. Start a rotation program for warehouse associates.', impact: 'Reduce single-point risk', action: 'Plan Rotations' },
      ],
      actions: [
        { label: 'Generate Skills Report', description: 'Team skill matrix with gap analysis and development recommendations' },
        { label: 'Create Development Plan', description: 'AI-personalized learning paths based on role and career goals' },
        { label: 'Export Matrix', description: 'Download skills matrix with proficiency ratings and gaps' },
      ],
    },
  ],
});
