import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'video-editor',
    name: 'Video Editor',
    icon: '\u{1F3AC}',
    dept: 'Operations',
    deptColor: '#7C3AED',
    description: 'AI-powered video editing: quote extraction, marketing clips, and professional cleanup',
    valueProposition: 'Turn raw video into polished clips, social content, and clean footage in minutes instead of hours',
    enabled: true,
    buildBatch: 3,
  },
  tabs: [
    {
      id: 'overview',
      label: 'Overview',
      kpis: [
        { label: 'Videos Processed', value: 47, change: 12, trend: 'up', icon: '\u{1F3AC}' },
        { label: 'Clips Generated', value: 312, change: 28, trend: 'up', icon: '\u{2702}\u{FE0F}' },
        { label: 'Avg Processing', value: 2.4, suffix: ' min', change: -18, trend: 'up', icon: '\u{23F1}\u{FE0F}' },
        { label: 'Hours Saved', value: 94, change: 15, trend: 'up', icon: '\u{1F4B0}' },
      ],
      columns: [
        { key: 'filename', label: 'File', sortable: true },
        { key: 'mode', label: 'Mode', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
        { key: 'clips', label: 'Clips', sortable: true },
        { key: 'duration', label: 'Duration', sortable: true },
        { key: 'date', label: 'Date', sortable: true },
      ],
      rows: [
        { filename: 'customer-testimonial-jcpenney.mp4', mode: 'Quote Clips', status: 'Complete', clips: 6, duration: '22:14', date: '2026-02-28', matchedQuotes: '6 of 6 found', confidence: '94% avg', outputSize: '148 MB' },
        { filename: 'warehouse-webinar-feb.mp4', mode: 'Power Clips', status: 'Complete', clips: 8, duration: '45:30', date: '2026-02-27', matchedQuotes: 'N/A', confidence: 'Top 8 scored', outputSize: '312 MB' },
        { filename: 'tradeshow-booth-walk.mov', mode: 'Cleanup', status: 'Complete', clips: 1, duration: '3:42', date: '2026-02-26', matchedQuotes: 'N/A', confidence: 'N/A', outputSize: '89 MB' },
        { filename: 'q4-sales-kickoff.mp4', mode: 'Power Clips', status: 'Complete', clips: 5, duration: '32:10', date: '2026-02-25', matchedQuotes: 'N/A', confidence: 'Top 5 scored', outputSize: '205 MB' },
        { filename: 'ceo-interview-raw.mov', mode: 'Quote Clips', status: 'Complete', clips: 4, duration: '18:55', date: '2026-02-24', matchedQuotes: '4 of 5 found', confidence: '89% avg', outputSize: '112 MB' },
        { filename: 'product-demo-v3.mp4', mode: 'Cleanup', status: 'Complete', clips: 1, duration: '8:20', date: '2026-02-23', matchedQuotes: 'N/A', confidence: 'N/A', outputSize: '67 MB' },
        { filename: 'client-call-recording.mp4', mode: 'Quote Clips', status: 'Complete', clips: 3, duration: '14:08', date: '2026-02-22', matchedQuotes: '3 of 3 found', confidence: '97% avg', outputSize: '78 MB' },
      ],
      expandedFields: ['matchedQuotes', 'confidence', 'outputSize'],
      chart: {
        type: 'bar',
        title: 'Videos Processed by Mode',
        xKey: 'week',
        dataKeys: ['quote', 'power', 'cleanup'],
        colors: ['#2A9D8F', '#F5920B', '#7C3AED'],
        data: [
          { week: 'Week 1', quote: 4, power: 3, cleanup: 2 },
          { week: 'Week 2', quote: 6, power: 5, cleanup: 3 },
          { week: 'Week 3', quote: 8, power: 6, cleanup: 4 },
          { week: 'Week 4', quote: 7, power: 8, cleanup: 5 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Upload a Testimonial Video to Extract Client Quotes', description: 'Quote Clips mode finds exact timestamps for any quote you paste, then extracts clean clips in seconds. Perfect for pulling sound bites from customer interviews.', impact: 'Save 2+ hours per testimonial', action: 'Try Quote Clips' },
        { priority: 'high', title: 'Turn Your 30-Min Webinar Into 8 Social Media Clips', description: 'Power Clips auto-detects the most engaging moments, burns in captions, and exports for Reels, TikTok, and LinkedIn. One upload creates a week of social content.', impact: '15 ready-to-post assets from one video', action: 'Try Power Clips' },
        { priority: 'medium', title: 'Clean Up Trade Show Footage for the Website', description: 'Video Cleanup normalizes audio, corrects color, stabilizes shaky footage, and removes dead air automatically. Turn raw phone video into professional content.', impact: 'Professional-quality video in minutes', action: 'Try Cleanup' },
        { priority: 'low', title: 'Batch Process Last Quarter Sales Recordings', description: 'Upload your sales call recordings and extract the best customer quotes for case studies, testimonials, and marketing collateral.', impact: 'Build testimonial library', action: 'Start Batch' },
      ],
      actions: [
        { label: 'Upload Video', description: 'Upload a video file to start processing with any mode' },
        { label: 'Extract Quote Clips', description: 'Paste quotes and get timestamped clips of each one' },
        { label: 'Generate Power Clips', description: 'AI auto-detects the best marketing moments with captions' },
        { label: 'Clean Up Video', description: 'Normalize audio, correct color, stabilize, and remove dead air' },
      ],
    },
    {
      id: 'quote-clips',
      label: 'Quote Clips',
      kpis: [
        { label: 'Quotes Found', value: 89, suffix: '%', change: 4, trend: 'up', icon: '\u{1F4AC}' },
        { label: 'Avg Confidence', value: 93, suffix: '%', change: 2, trend: 'up', icon: '\u{1F3AF}' },
        { label: 'Clips Extracted', value: 186, change: 24, trend: 'up', icon: '\u{2702}\u{FE0F}' },
        { label: 'Compilations', value: 12, change: 3, trend: 'up', icon: '\u{1F4F9}' },
      ],
      columns: [
        { key: 'quote', label: 'Quote', sortable: false },
        { key: 'source', label: 'Source Video', sortable: true },
        { key: 'confidence', label: 'Confidence', sortable: true },
        { key: 'timestamp', label: 'Timestamp', sortable: true },
        { key: 'duration', label: 'Clip Length', sortable: true },
      ],
      rows: [
        { quote: 'This system saved us over 200 hours per month', source: 'customer-testimonial-jcpenney.mp4', confidence: '97%', timestamp: '4:32', duration: '8s', speaker: 'VP Operations', usedIn: 'Website hero' },
        { quote: 'We saw ROI within the first 30 days', source: 'customer-testimonial-jcpenney.mp4', confidence: '94%', timestamp: '8:15', duration: '6s', speaker: 'Director of Logistics', usedIn: 'Case study' },
        { quote: 'The AI handles what used to take our whole team', source: 'ceo-interview-raw.mov', confidence: '91%', timestamp: '12:40', duration: '10s', speaker: 'CEO', usedIn: 'LinkedIn post' },
        { quote: 'Our error rate dropped to nearly zero', source: 'ceo-interview-raw.mov', confidence: '88%', timestamp: '15:22', duration: '7s', speaker: 'CEO', usedIn: 'Sales deck' },
        { quote: 'Best investment we made all year', source: 'client-call-recording.mp4', confidence: '96%', timestamp: '6:55', duration: '5s', speaker: 'Client', usedIn: 'Email campaign' },
      ],
      expandedFields: ['speaker', 'usedIn'],
      chart: {
        type: 'bar',
        title: 'Quote Match Confidence Distribution',
        xKey: 'range',
        dataKeys: ['count'],
        colors: ['#2A9D8F'],
        data: [
          { range: '95-100%', count: 42 },
          { range: '90-94%', count: 38 },
          { range: '85-89%', count: 24 },
          { range: '80-84%', count: 12 },
          { range: '70-79%', count: 6 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Re-process CEO Interview with Expanded Quotes', description: 'One quote from the CEO interview scored below 80% confidence. Try rephrasing or expanding the quote text for a better match.', impact: 'Recover 1 missed clip', action: 'Retry Quote' },
        { priority: 'medium', title: 'Create Compilation from Top Customer Quotes', description: 'You have 6 high-confidence clips from JCPenney. Stitch them into a 45-second compilation for the website.', impact: 'Ready-to-use testimonial reel', action: 'Stitch Clips' },
      ],
      actions: [
        { label: 'Upload & Transcribe', description: 'Upload a new video and get a full transcript to search' },
        { label: 'Stitch Compilation', description: 'Combine multiple clips into one seamless video' },
      ],
    },
    {
      id: 'power-clips',
      label: 'Power Clips',
      kpis: [
        { label: 'Clips Generated', value: 126, change: 18, trend: 'up', icon: '\u{26A1}' },
        { label: 'Formats Exported', value: 378, change: 54, trend: 'up', icon: '\u{1F4F1}' },
        { label: 'Captions Burned', value: 98, suffix: '%', change: 0, trend: 'flat', icon: '\u{1F4DD}' },
        { label: 'Avg Engagement Score', value: 8.4, suffix: '/10', change: 0.6, trend: 'up', icon: '\u{1F4CA}' },
      ],
      columns: [
        { key: 'clip', label: 'Clip', sortable: true },
        { key: 'source', label: 'Source', sortable: true },
        { key: 'score', label: 'Score', sortable: true },
        { key: 'duration', label: 'Duration', sortable: true },
        { key: 'formats', label: 'Formats', sortable: false },
      ],
      rows: [
        { clip: 'Power Clip #1', source: 'warehouse-webinar-feb.mp4', score: '9.2/10', duration: '18s', formats: '16:9, 9:16, 1:1', keyPhrase: 'We reduced errors by 94 percent', platform: 'TikTok, Reels' },
        { clip: 'Power Clip #2', source: 'warehouse-webinar-feb.mp4', score: '8.8/10', duration: '22s', formats: '16:9, 9:16', keyPhrase: 'ROI within 30 days guaranteed', platform: 'LinkedIn, YouTube' },
        { clip: 'Power Clip #3', source: 'q4-sales-kickoff.mp4', score: '8.5/10', duration: '15s', formats: '9:16, 1:1', keyPhrase: 'Three million in new revenue', platform: 'Reels, Instagram' },
        { clip: 'Power Clip #4', source: 'q4-sales-kickoff.mp4', score: '8.1/10', duration: '25s', formats: '16:9', keyPhrase: 'The future of warehouse operations', platform: 'YouTube, LinkedIn' },
        { clip: 'Power Clip #5', source: 'warehouse-webinar-feb.mp4', score: '7.9/10', duration: '20s', formats: '16:9, 9:16, 1:1', keyPhrase: 'What would you do with 200 extra hours', platform: 'All platforms' },
      ],
      expandedFields: ['keyPhrase', 'platform'],
      chart: {
        type: 'bar',
        title: 'Clips by Platform Format',
        xKey: 'format',
        dataKeys: ['clips'],
        colors: ['#F5920B'],
        data: [
          { format: '16:9 YouTube', clips: 42 },
          { format: '9:16 Reels', clips: 38 },
          { format: '9:16 TikTok', clips: 35 },
          { format: '1:1 Instagram', clips: 28 },
          { format: '16:9 LinkedIn', clips: 22 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Schedule This Week of Social Content', description: 'You have 8 new power clips from the webinar. Export the 9:16 versions and schedule across TikTok, Reels, and Shorts.', impact: '7 days of content ready', action: 'Export All' },
        { priority: 'medium', title: 'Re-run With Longer Clip Range', description: 'Try setting clip range to 15-45 seconds for LinkedIn. Longer clips perform better on professional platforms.', impact: '+30% LinkedIn engagement', action: 'Adjust Settings' },
      ],
      actions: [
        { label: 'Generate New Clips', description: 'Upload a video and auto-detect the best marketing moments' },
        { label: 'Download All Formats', description: 'Bulk download clips in all exported formats' },
      ],
    },
  ],
});
