import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'warehouse',
    name: 'Warehouse',
    icon: '🏭',
    dept: 'Operations',
    deptColor: '#2A9D8F',
    description: 'AI-powered warehouse floor management and optimization',
    valueProposition: 'Optimize picks, manage space, and hit every SLA with AI-powered operations',
    enabled: true,
    buildBatch: 1,
  },
  tabs: [
    {
      id: 'floor-dashboard',
      label: 'Floor Dashboard',
      kpis: [
        { label: 'Orders Today', value: 342, change: 8, trend: 'up', icon: '📦' },
        { label: 'Pick Accuracy', value: 99.4, suffix: '%', change: 0.2, trend: 'up', icon: '🎯' },
        { label: 'Units Shipped', value: 2847, change: 12, trend: 'up', icon: '🚚' },
        { label: 'Space Utilization', value: 78, suffix: '%', change: 3, trend: 'up', icon: '📊' },
      ],
      columns: [
        { key: 'order', label: 'Order #', sortable: true },
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'items', label: 'Items', sortable: true },
        { key: 'pickStatus', label: 'Status', sortable: true },
        { key: 'shipMethod', label: 'Ship Method', sortable: true },
        { key: 'zone', label: 'Zone', sortable: true },
        { key: 'slaStatus', label: 'SLA', sortable: true },
      ],
      rows: [
        { order: 'ORD-8847', customer: 'Redline Distribution', items: 24, pickStatus: 'Picking', shipMethod: 'Ground', zone: 'A-North', slaStatus: 'On Track', pickList: '12 SKUs across 3 aisles', weight: '84 lbs', picker: 'Mike R.', tracking: 'Pending' },
        { order: 'ORD-8848', customer: 'Summit Retail', items: 8, pickStatus: 'Packed', shipMethod: 'Express', zone: 'B-East', slaStatus: 'Completed', pickList: '8 SKUs, single aisle', weight: '32 lbs', picker: 'Anna L.', tracking: '1Z999AA10392847' },
        { order: 'ORD-8849', customer: 'Pacific Brands', items: 47, pickStatus: 'Picking', shipMethod: 'Freight', zone: 'C-South', slaStatus: 'At Risk', pickList: '22 SKUs across 5 aisles', weight: '210 lbs', picker: 'Carlos D.', tracking: 'Pending' },
        { order: 'ORD-8850', customer: 'Apex Fulfillment', items: 3, pickStatus: 'Shipped', shipMethod: 'Next Day', zone: 'A-North', slaStatus: 'Completed', pickList: '3 SKUs, single bin', weight: '12 lbs', picker: 'Mike R.', tracking: '1Z888BB20481930' },
        { order: 'ORD-8851', customer: 'Metro Systems', items: 15, pickStatus: 'Picking', shipMethod: 'Ground', zone: 'B-East', slaStatus: 'On Track', pickList: '9 SKUs across 2 aisles', weight: '56 lbs', picker: 'Anna L.', tracking: 'Pending' },
        { order: 'ORD-8852', customer: 'Iron Ridge Metals', items: 62, pickStatus: 'Queued', shipMethod: 'LTL', zone: 'C-South', slaStatus: 'Pending', pickList: '28 SKUs across 6 aisles', weight: '340 lbs', picker: 'Unassigned', tracking: 'Pending' },
        { order: 'ORD-8853', customer: 'Clearwater Logistics', items: 11, pickStatus: 'Packed', shipMethod: 'Ground', zone: 'A-South', slaStatus: 'On Track', pickList: '7 SKUs across 2 aisles', weight: '44 lbs', picker: 'Carlos D.', tracking: '1Z777CC30592018' },
      ],
      expandedFields: ['pickList', 'weight', 'picker', 'tracking'],
      chart: {
        type: 'bar',
        title: 'Hourly Throughput',
        xKey: 'hour',
        dataKeys: ['orders', 'target'],
        colors: ['#2A9D8F', '#E5E7EB'],
        data: [
          { hour: '8AM', orders: 28, target: 40 },
          { hour: '9AM', orders: 42, target: 40 },
          { hour: '10AM', orders: 48, target: 40 },
          { hour: '11AM', orders: 44, target: 40 },
          { hour: '12PM', orders: 22, target: 40 },
          { hour: '1PM', orders: 38, target: 40 },
          { hour: '2PM', orders: 46, target: 40 },
          { hour: '3PM', orders: 41, target: 40 },
          { hour: '4PM', orders: 33, target: 40 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Zone C at 94% Capacity', description: 'Zone C-South is nearly full. Redistribute 200 slow-moving SKUs to Zone A (67% utilized) to prevent picking bottlenecks.', impact: 'Prevent 2hr delay', action: 'Optimize Zones' },
        { priority: 'high', title: '3 Orders Behind SLA', description: 'Orders ORD-8849 and ORD-8852 are at risk of missing their shipping SLA. Escalate to available pickers immediately.', impact: '3 SLA saves', action: 'Escalate Orders' },
        { priority: 'medium', title: 'Retrain Picker in Zone B', description: 'One picker is 15% slower than team average in Zone B with 2.1% error rate vs 0.6% team average.', impact: '+15% zone efficiency', action: 'Schedule Training' },
        { priority: 'low', title: 'Dock 3 Idle Since 10AM', description: 'Dock 3 has been unused for 2 hours. Reassign to outbound staging to clear the shipping backlog.', impact: '+8 shipments/hr', action: 'Reassign Dock' },
      ],
      actions: [
        { label: 'Optimize Zone Layout', description: 'AI-recommended SKU placement to minimize pick travel time' },
        { label: 'Generate Pick Routes', description: 'Optimized pick paths for each active order to reduce walk time' },
        { label: 'Export Inventory Report', description: 'Complete SKU-level inventory with location and velocity data' },
        { label: 'Create Emergency Restock', description: 'Trigger priority replenishment for fast-moving bins running low' },
      ],
    },
    {
      id: 'inventory',
      label: 'Inventory',
      kpis: [
        { label: 'Total SKUs', value: 4218, change: 3, trend: 'up', icon: '📦' },
        { label: 'Low Stock', value: 14, change: -4, trend: 'down', icon: '⚠️' },
        { label: 'Dead Stock', value: 47, change: -8, trend: 'down', icon: '💤' },
        { label: 'Inventory Value', value: 1800000, prefix: '$', change: 5, trend: 'up', icon: '💰' },
      ],
      columns: [
        { key: 'sku', label: 'SKU', sortable: true },
        { key: 'product', label: 'Product', sortable: true },
        { key: 'onHand', label: 'On Hand', sortable: true },
        { key: 'velocity', label: 'Velocity', sortable: true },
        { key: 'category', label: 'Category', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { sku: 'WH-4421', product: 'Heavy-Duty Shelf Unit', onHand: 342, velocity: 'High', category: 'Racking', status: 'Active', reorderPoint: 100, daysOfSupply: 28 },
        { sku: 'WH-2218', product: 'Pallet Jack Wheels', onHand: 8, velocity: 'Medium', category: 'Parts', status: 'Low', reorderPoint: 20, daysOfSupply: 4 },
        { sku: 'WH-7790', product: 'Conveyor Belt Section 12ft', onHand: 156, velocity: 'Low', category: 'Conveyor', status: 'Active', reorderPoint: 40, daysOfSupply: 92 },
        { sku: 'WH-1104', product: 'Barcode Scanner Holster', onHand: 0, velocity: 'High', category: 'Tech', status: 'Critical', reorderPoint: 50, daysOfSupply: 0 },
        { sku: 'WH-5567', product: 'Safety Harness Kit', onHand: 24, velocity: 'Medium', category: 'Safety', status: 'Active', reorderPoint: 15, daysOfSupply: 18 },
        { sku: 'WH-8834', product: 'Stretch Wrap 18in Roll', onHand: 480, velocity: 'High', category: 'Packaging', status: 'Active', reorderPoint: 200, daysOfSupply: 14 },
      ],
      expandedFields: ['reorderPoint', 'daysOfSupply'],
      chart: {
        type: 'pie',
        title: 'Inventory by Category',
        dataKeys: ['value'],
        data: [
          { name: 'Racking', value: 620000 },
          { name: 'Conveyor', value: 410000 },
          { name: 'Parts', value: 280000 },
          { name: 'Packaging', value: 220000 },
          { name: 'Safety', value: 150000 },
          { name: 'Tech', value: 120000 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Scanner Holsters Out of Stock', description: 'SKU WH-1104 has zero on-hand with 12 pending orders. Emergency reorder needed immediately.', impact: '12 orders blocked', action: 'Emergency Reorder' },
        { priority: 'high', title: 'Pallet Jack Wheels Low', description: 'Only 4 days of supply remaining. Reorder before stockout causes line stoppage.', impact: 'Prevent line stoppage', action: 'Reorder Now' },
        { priority: 'medium', title: 'Dead Stock Clearance', description: '47 SKUs with zero movement in 90 days occupy 8% of warehouse space. Liquidation frees 3,200 sq ft.', impact: 'Free 3,200 sq ft', action: 'Review Dead Stock' },
      ],
      actions: [
        { label: 'Run Cycle Count', description: 'AI-prioritized cycle count targeting high-value and high-discrepancy SKUs' },
        { label: 'Generate Reorder Report', description: 'Automated reorder recommendations based on velocity and lead times' },
        { label: 'Export Inventory', description: 'Full inventory export with values, velocities, and locations' },
      ],
    },
    {
      id: 'orders',
      label: 'Orders',
      kpis: [
        { label: 'Open Orders', value: 89, change: -6, trend: 'down', icon: '📋' },
        { label: 'Shipped Today', value: 253, change: 14, trend: 'up', icon: '🚚' },
        { label: 'Late Orders', value: 3, change: -2, trend: 'down', icon: '🔴' },
        { label: 'Avg Pick Time', value: 4.2, suffix: ' min', change: -8, trend: 'down', icon: '⏱️' },
      ],
      columns: [
        { key: 'order', label: 'Order', sortable: true },
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'items', label: 'Items', sortable: true },
        { key: 'priority', label: 'Priority', sortable: true },
        { key: 'shipBy', label: 'Ship By', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { order: 'ORD-8860', customer: 'NorthStar Industries', items: 18, priority: 'High', shipBy: 'Today 3PM', status: 'Picking', waveId: 'W-442', assignedPicker: 'Mike R.' },
        { order: 'ORD-8861', customer: 'Cascade Materials', items: 6, priority: 'Medium', shipBy: 'Tomorrow', status: 'Queued', waveId: 'W-443', assignedPicker: 'Unassigned' },
        { order: 'ORD-8862', customer: 'Velocity Logistics', items: 34, priority: 'High', shipBy: 'Today 5PM', status: 'Picking', waveId: 'W-442', assignedPicker: 'Anna L.' },
        { order: 'ORD-8863', customer: 'Pacific Brands', items: 12, priority: 'Critical', shipBy: 'Today 1PM', status: 'At Risk', waveId: 'W-441', assignedPicker: 'Carlos D.' },
        { order: 'ORD-8864', customer: 'Summit Retail', items: 4, priority: 'Low', shipBy: 'Mar 25', status: 'Queued', waveId: 'W-444', assignedPicker: 'Unassigned' },
      ],
      expandedFields: ['waveId', 'assignedPicker'],
      chart: {
        type: 'area',
        title: 'Daily Order Volume',
        xKey: 'day',
        dataKeys: ['orders'],
        colors: ['#2A9D8F'],
        data: [
          { day: 'Mon', orders: 312 },
          { day: 'Tue', orders: 342 },
          { day: 'Wed', orders: 298 },
          { day: 'Thu', orders: 367 },
          { day: 'Fri', orders: 385 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'ORD-8863 SLA at Risk', description: 'Pacific Brands order ships by 1PM today. Only 4 of 12 items picked. Assign second picker immediately.', impact: 'Save SLA', action: 'Assign Picker' },
        { priority: 'medium', title: 'Wave W-443 Unassigned', description: '6 orders in Wave 443 have no assigned pickers. Auto-assign based on zone proximity.', impact: 'Start 6 orders', action: 'Auto-Assign' },
      ],
      actions: [
        { label: 'Create Pick Wave', description: 'Group orders into optimized pick waves by zone' },
        { label: 'Reassign Pickers', description: 'Move pickers between zones based on real-time demand' },
        { label: 'Export Order Report', description: 'Download order status and SLA performance data' },
      ],
    },
    {
      id: 'zones',
      label: 'Zone Performance',
      kpis: [
        { label: 'Zones Active', value: 6, change: 0, trend: 'flat', icon: '🏗️' },
        { label: 'Best Zone', value: 48, suffix: ' picks/hr', change: 6, trend: 'up', icon: '🏆' },
        { label: 'Avg Picks/Hr', value: 38, change: 4, trend: 'up', icon: '📊' },
        { label: 'Utilization', value: 78, suffix: '%', change: 3, trend: 'up', icon: '📊' },
      ],
      columns: [
        { key: 'zone', label: 'Zone', sortable: true },
        { key: 'utilization', label: 'Util %', sortable: true },
        { key: 'picksPerHour', label: 'Picks/Hr', sortable: true },
        { key: 'accuracy', label: 'Accuracy', sortable: true },
        { key: 'pickers', label: 'Pickers', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { zone: 'A-North', utilization: 67, picksPerHour: 48, accuracy: '99.8%', pickers: 3, status: 'Active', topSku: 'WH-4421 Heavy Shelf', bottleneck: 'None' },
        { zone: 'A-South', utilization: 72, picksPerHour: 42, accuracy: '99.5%', pickers: 2, status: 'Active', topSku: 'WH-8834 Stretch Wrap', bottleneck: 'Replenishment delay' },
        { zone: 'B-East', utilization: 81, picksPerHour: 38, accuracy: '99.2%', pickers: 3, status: 'Active', topSku: 'WH-5567 Safety Kit', bottleneck: 'Narrow aisle congestion' },
        { zone: 'B-West', utilization: 74, picksPerHour: 36, accuracy: '99.6%', pickers: 2, status: 'Active', topSku: 'WH-2218 PJ Wheels', bottleneck: 'None' },
        { zone: 'C-South', utilization: 94, picksPerHour: 32, accuracy: '98.8%', pickers: 4, status: 'At Risk', topSku: 'WH-7790 Conveyor Belt', bottleneck: 'Over capacity' },
        { zone: 'D-Bulk', utilization: 58, picksPerHour: 22, accuracy: '99.9%', pickers: 1, status: 'Active', topSku: 'Pallet-level picks', bottleneck: 'Forklift availability' },
      ],
      expandedFields: ['topSku', 'bottleneck'],
      chart: {
        type: 'bar',
        title: 'Picks Per Hour by Zone',
        xKey: 'zone',
        dataKeys: ['picksPerHour'],
        colors: ['#2A9D8F'],
        data: [
          { zone: 'A-North', picksPerHour: 48 },
          { zone: 'A-South', picksPerHour: 42 },
          { zone: 'B-East', picksPerHour: 38 },
          { zone: 'B-West', picksPerHour: 36 },
          { zone: 'C-South', picksPerHour: 32 },
          { zone: 'D-Bulk', picksPerHour: 22 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Rebalance Zone C', description: 'Zone C-South is at 94% with the lowest picks/hr. Move 200 slow-movers to A-North (67%) or D-Bulk (58%).', impact: '+40% C throughput', action: 'Run Rebalance' },
        { priority: 'high', title: 'Zone B-East Congestion', description: 'Narrow aisle congestion reducing throughput. Split into B-East-1 and B-East-2 during peak hours.', impact: '+6 picks/hr', action: 'View Plan' },
      ],
      actions: [
        { label: 'Optimize Zone Layout', description: 'AI-recommended zone rebalancing based on velocity and proximity' },
        { label: 'Generate Zone Report', description: 'Detailed zone performance with bottleneck analysis' },
        { label: 'Reassign Pickers', description: 'Move pickers to zones with highest current demand' },
      ],
    },
  ],
});
