import { registerAgent } from '@/lib/demo-registry';

registerAgent({
  meta: {
    slug: 'wms',
    name: 'WMS',
    icon: '\u{1F4E6}',
    dept: 'Operations',
    deptColor: '#2A9D8F',
    description: 'AI-powered warehouse management system with real-time optimization',
    valueProposition: 'Run your entire warehouse from one intelligent dashboard with AI-driven decisions',
    enabled: true,
    buildBatch: 2,
  },
  tabs: [
    {
      id: 'live-operations',
      label: 'Live Operations',
      kpis: [
        { label: 'Active Picks', value: 48, change: 6, trend: 'up', icon: '\u{1F3C3}' },
        { label: 'Throughput/Hr', value: 312, change: 8, trend: 'up', icon: '\u{1F4CA}' },
        { label: 'On-Time Rate', value: 96.2, suffix: '%', change: 1.4, trend: 'up', icon: '\u{2705}' },
        { label: 'Error Rate', value: 0.4, suffix: '%', change: -0.2, trend: 'down', icon: '\u{1F3AF}' },
      ],
      columns: [
        { key: 'wave', label: 'Wave', sortable: true },
        { key: 'orders', label: 'Orders', sortable: true },
        { key: 'lines', label: 'Lines', sortable: true },
        { key: 'progress', label: 'Progress', sortable: true },
        { key: 'pickers', label: 'Pickers', sortable: true },
        { key: 'eta', label: 'ETA', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { wave: 'W-501', orders: 24, lines: 142, progress: '78%', pickers: 4, eta: '11:30 AM', status: 'Active', zone: 'A-North, B-East', priority: 'Express', completedLines: 111 },
        { wave: 'W-502', orders: 18, lines: 96, progress: '45%', pickers: 3, eta: '12:15 PM', status: 'Active', zone: 'C-South', priority: 'Standard', completedLines: 43 },
        { wave: 'W-503', orders: 32, lines: 218, progress: '12%', pickers: 5, eta: '2:00 PM', status: 'Active', zone: 'All zones', priority: 'Mixed', completedLines: 26 },
        { wave: 'W-504', orders: 8, lines: 34, progress: '0%', pickers: 0, eta: '3:30 PM', status: 'Queued', zone: 'B-West', priority: 'Low', completedLines: 0 },
        { wave: 'W-500', orders: 22, lines: 128, progress: '100%', pickers: 0, eta: 'Complete', status: 'Completed', zone: 'A-North, A-South', priority: 'Express', completedLines: 128 },
      ],
      expandedFields: ['zone', 'priority', 'completedLines'],
      chart: {
        type: 'area',
        title: 'Throughput Today (Units/Hr)',
        xKey: 'hour',
        dataKeys: ['actual', 'target'],
        colors: ['#2A9D8F', '#E5E7EB'],
        data: [
          { hour: '7AM', actual: 180, target: 300 },
          { hour: '8AM', actual: 280, target: 300 },
          { hour: '9AM', actual: 342, target: 300 },
          { hour: '10AM', actual: 318, target: 300 },
          { hour: '11AM', actual: 312, target: 300 },
          { hour: '12PM', actual: 0, target: 300 },
          { hour: '1PM', actual: 0, target: 300 },
        ],
      },
      recommendations: [
        { priority: 'critical', title: 'Wave W-503 Under-Staffed', description: 'Wave W-503 has 218 lines but only 5 pickers. At current rate, ETA slips to 3:00 PM (1 hour late). Add 2 pickers from completed W-500.', impact: 'Save SLA', action: 'Reassign Pickers' },
        { priority: 'high', title: 'Zone C Congestion Alert', description: 'Zone C-South has 3 pickers in the same aisle. Stagger pick assignments to reduce wait time by 22%.', impact: '+22% zone efficiency', action: 'Optimize Routes' },
        { priority: 'medium', title: 'Replenishment Needed Aisle B-4', description: 'Aisle B-4 bins are at 15% capacity for 3 high-velocity SKUs. Trigger replenishment before next wave starts.', impact: 'Prevent pick delay', action: 'Trigger Replenishment' },
      ],
      actions: [
        { label: 'Create Wave', description: 'AI-optimized wave planning based on SLA priorities and zone capacity' },
        { label: 'Reassign Pickers', description: 'Real-time picker rebalancing across zones and waves' },
        { label: 'Trigger Replenishment', description: 'Emergency bin replenishment for low-stock pick locations' },
        { label: 'Export Operations Log', description: 'Download wave completion data with performance metrics' },
      ],
    },
    {
      id: 'receiving',
      label: 'Receiving',
      kpis: [
        { label: 'Inbound Today', value: 6, change: 2, trend: 'up', icon: '\u{1F69B}' },
        { label: 'Dock-to-Stock', value: 18, suffix: ' min', change: -12, trend: 'down', icon: '\u{23F1}\u{FE0F}' },
        { label: 'Receiving Accuracy', value: 99.2, suffix: '%', change: 0.4, trend: 'up', icon: '\u{1F3AF}' },
        { label: 'PO Discrepancies', value: 2, change: -1, trend: 'down', icon: '\u{26A0}\u{FE0F}' },
      ],
      columns: [
        { key: 'po', label: 'PO #', sortable: true },
        { key: 'vendor', label: 'Vendor', sortable: true },
        { key: 'expectedUnits', label: 'Expected', sortable: true },
        { key: 'receivedUnits', label: 'Received', sortable: true },
        { key: 'dock', label: 'Dock', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { po: 'PO-4421', vendor: 'LogiParts Inc', expectedUnits: 480, receivedUnits: 480, dock: 'Dock 1', status: 'Completed', arrivalTime: '7:15 AM', putawayComplete: '7:48 AM', discrepancy: 'None' },
        { po: 'PO-4422', vendor: 'Acme Supply Co', expectedUnits: 240, receivedUnits: 234, dock: 'Dock 2', status: 'In Progress', arrivalTime: '8:30 AM', putawayComplete: 'In progress', discrepancy: '6 units short' },
        { po: 'PO-4423', vendor: 'Warehouse Direct', expectedUnits: 120, receivedUnits: 0, dock: 'Dock 3', status: 'Scheduled', arrivalTime: 'ETA 11:00 AM', putawayComplete: 'Pending', discrepancy: 'N/A' },
        { po: 'PO-4424', vendor: 'Quality Fasteners', expectedUnits: 800, receivedUnits: 0, dock: 'Dock 1', status: 'Scheduled', arrivalTime: 'ETA 1:30 PM', putawayComplete: 'Pending', discrepancy: 'N/A' },
        { po: 'PO-4425', vendor: 'TechServ Solutions', expectedUnits: 24, receivedUnits: 24, dock: 'Dock 4', status: 'Completed', arrivalTime: '6:45 AM', putawayComplete: '7:02 AM', discrepancy: 'None' },
      ],
      expandedFields: ['arrivalTime', 'putawayComplete', 'discrepancy'],
      chart: {
        type: 'bar',
        title: 'Dock-to-Stock Time (Last 7 Days)',
        xKey: 'day',
        dataKeys: ['minutes', 'target'],
        colors: ['#2A9D8F', '#E5E7EB'],
        data: [
          { day: 'Mon', minutes: 24, target: 20 },
          { day: 'Tue', minutes: 22, target: 20 },
          { day: 'Wed', minutes: 19, target: 20 },
          { day: 'Thu', minutes: 18, target: 20 },
          { day: 'Fri', minutes: 16, target: 20 },
          { day: 'Sat', minutes: 18, target: 20 },
          { day: 'Today', minutes: 18, target: 20 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Acme Shipment Short', description: 'PO-4422 from Acme Supply is 6 units short. Create a discrepancy report and notify AP to hold payment until resolved.', impact: 'Prevent overpayment', action: 'Create Report' },
        { priority: 'medium', title: 'Schedule Dock Assignments', description: 'PO-4423 and PO-4424 both targeting Dock 1 and Dock 3. Pre-assign docks to prevent wait times.', impact: 'Save 30 min', action: 'Assign Docks' },
      ],
      actions: [
        { label: 'Schedule Receiving', description: 'Dock appointment scheduling with vendor coordination' },
        { label: 'Report Discrepancy', description: 'File discrepancy report for short shipments or damages' },
        { label: 'Export Receiving Log', description: 'Download receiving data with discrepancy tracking' },
      ],
    },
    {
      id: 'slotting',
      label: 'Slotting',
      kpis: [
        { label: 'Optimized Slots', value: 82, suffix: '%', change: 6, trend: 'up', icon: '\u{1F4CA}' },
        { label: 'Avg Pick Distance', value: 42, suffix: ' ft', change: -14, trend: 'down', icon: '\u{1F3C3}' },
        { label: 'Hot Zone Items', value: 48, change: 4, trend: 'up', icon: '\u{1F525}' },
        { label: 'Reslot Needed', value: 14, change: -6, trend: 'down', icon: '\u{1F504}' },
      ],
      columns: [
        { key: 'sku', label: 'SKU', sortable: true },
        { key: 'product', label: 'Product', sortable: true },
        { key: 'currentSlot', label: 'Current Slot', sortable: true },
        { key: 'optimalSlot', label: 'Optimal Slot', sortable: true },
        { key: 'pickFrequency', label: 'Picks/Day', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { sku: 'WH-4421', product: 'Heavy-Duty Shelf Unit', currentSlot: 'A-12-3', optimalSlot: 'A-01-1', pickFrequency: 34, status: 'Pending', travelReduction: '-68 ft/pick', annualSavings: '$2,400/yr in labor' },
        { sku: 'WH-8834', product: 'Stretch Wrap 18in', currentSlot: 'C-08-2', optimalSlot: 'A-02-1', pickFrequency: 28, status: 'Pending', travelReduction: '-52 ft/pick', annualSavings: '$1,800/yr in labor' },
        { sku: 'WH-1104', product: 'Barcode Scanner Holster', currentSlot: 'B-14-4', optimalSlot: 'A-03-2', pickFrequency: 22, status: 'Pending', travelReduction: '-44 ft/pick', annualSavings: '$1,200/yr in labor' },
        { sku: 'WH-5567', product: 'Safety Harness Kit', currentSlot: 'A-04-1', optimalSlot: 'A-04-1', pickFrequency: 18, status: 'Optimized', travelReduction: '0 ft', annualSavings: 'Already optimal' },
        { sku: 'WH-7790', product: 'Conveyor Belt 12ft', currentSlot: 'D-01-1', optimalSlot: 'D-01-1', pickFrequency: 2, status: 'Optimized', travelReduction: '0 ft', annualSavings: 'Already optimal' },
      ],
      expandedFields: ['travelReduction', 'annualSavings'],
      chart: {
        type: 'bar',
        title: 'Pick Distance Reduction Potential',
        xKey: 'sku',
        dataKeys: ['current', 'optimal'],
        colors: ['#DC2626', '#059669'],
        data: [
          { sku: 'WH-4421', current: 82, optimal: 14 },
          { sku: 'WH-8834', current: 68, optimal: 16 },
          { sku: 'WH-1104', current: 58, optimal: 14 },
          { sku: 'WH-5567', current: 18, optimal: 18 },
          { sku: 'WH-7790', current: 8, optimal: 8 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Reslot Top 3 SKUs', description: 'Moving 3 high-velocity SKUs to Zone A would reduce average pick travel by 55 feet per pick. Annual labor savings of $5,400.', impact: '$5,400/yr savings', action: 'Start Reslotting' },
        { priority: 'medium', title: 'Seasonal Reslot Needed', description: 'Summer seasonal products should move to forward pick areas. Begin transition 2 weeks before peak.', impact: 'Prepare for peak', action: 'Plan Seasonal Moves' },
      ],
      actions: [
        { label: 'Run Slotting Analysis', description: 'AI-optimized slotting recommendations based on pick frequency and adjacency' },
        { label: 'Execute Reslot', description: 'Generate move list and assign team for slotting changes' },
        { label: 'Export Slotting Plan', description: 'Download slotting optimization plan with projected savings' },
      ],
    },
    {
      id: 'shipping',
      label: 'Shipping',
      kpis: [
        { label: 'Shipped Today', value: 184, change: 12, trend: 'up', icon: '\u{1F69A}' },
        { label: 'Ready to Ship', value: 28, change: -4, trend: 'down', icon: '\u{1F4E6}' },
        { label: 'Carrier On-Time', value: 94, suffix: '%', change: 2, trend: 'up', icon: '\u{2705}' },
        { label: 'Avg Ship Cost', value: 8.40, prefix: '$', change: -4, trend: 'down', icon: '\u{1F4B0}' },
      ],
      columns: [
        { key: 'shipment', label: 'Shipment', sortable: true },
        { key: 'customer', label: 'Customer', sortable: true },
        { key: 'carrier', label: 'Carrier', sortable: true },
        { key: 'packages', label: 'Packages', sortable: true },
        { key: 'cost', label: 'Cost', sortable: true },
        { key: 'status', label: 'Status', sortable: true },
      ],
      rows: [
        { shipment: 'SHP-2201', customer: 'Summit Retail', carrier: 'FedEx Ground', packages: 4, cost: 34.20, status: 'Shipped', tracking: '7489201847201', deliveryEta: 'Mar 25' },
        { shipment: 'SHP-2202', customer: 'Pacific Brands', carrier: 'UPS Freight', packages: 12, cost: 284.00, status: 'Shipped', tracking: '1Z999AA10002', deliveryEta: 'Mar 24' },
        { shipment: 'SHP-2203', customer: 'Metro Systems', carrier: 'FedEx Express', packages: 2, cost: 48.60, status: 'Packed', tracking: 'Pending', deliveryEta: 'Mar 22' },
        { shipment: 'SHP-2204', customer: 'Clearwater Logistics', carrier: 'USPS Priority', packages: 1, cost: 12.80, status: 'Packed', tracking: 'Pending', deliveryEta: 'Mar 24' },
        { shipment: 'SHP-2205', customer: 'Iron Ridge Metals', carrier: 'LTL - Estes', packages: 6, cost: 420.00, status: 'Scheduled', tracking: 'Pending', deliveryEta: 'Mar 26' },
      ],
      expandedFields: ['tracking', 'deliveryEta'],
      chart: {
        type: 'pie',
        title: 'Shipments by Carrier',
        dataKeys: ['value'],
        data: [
          { name: 'FedEx Ground', value: 42 },
          { name: 'UPS', value: 28 },
          { name: 'USPS', value: 18 },
          { name: 'LTL Carriers', value: 8 },
          { name: 'FedEx Express', value: 4 },
        ],
      },
      recommendations: [
        { priority: 'high', title: 'Rate Shop SHP-2205', description: 'Iron Ridge LTL shipment quoted at $420 via Estes. Rate shopping shows SAIA offers $368 for same lane and transit time.', impact: '$52 savings', action: 'Switch Carrier' },
        { priority: 'medium', title: 'Consolidate Small Parcels', description: '8 small parcels shipping to same zip code today. Consolidating into 2 shipments saves $24 in shipping.', impact: '$24 savings', action: 'Consolidate' },
      ],
      actions: [
        { label: 'Rate Shop', description: 'Compare carrier rates for pending shipments' },
        { label: 'Generate Labels', description: 'Batch print shipping labels for packed orders' },
        { label: 'Export Shipping Log', description: 'Download shipping data with costs and tracking numbers' },
      ],
    },
  ],
});
