-- ============================================================
-- WoulfAI — Onboarding Sessions Migration
-- Generated by install-onboarding.js
-- ============================================================
-- Fixed from Gemini's version:
--   ✓ Added company_id (was missing — broke multi-tenant)
--   ✓ Changed FK from auth.users to profiles
--   ✓ Added unique constraint for upsert
--   ✓ Added indexes for performance

CREATE TABLE IF NOT EXISTS onboarding_sessions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id),
  company_id UUID,
  agent_id TEXT NOT NULL,
  current_step INTEGER DEFAULT 1,
  data_payload JSONB DEFAULT '{}',
  is_complete BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(agent_id, company_id)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_onboarding_agent ON onboarding_sessions(agent_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_company ON onboarding_sessions(company_id);
CREATE INDEX IF NOT EXISTS idx_onboarding_complete ON onboarding_sessions(is_complete);

-- RLS: Users can only see/edit their own sessions
ALTER TABLE onboarding_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users manage own onboarding"
ON onboarding_sessions FOR ALL
USING (
  user_id = auth.uid()
  OR company_id IN (
    SELECT company_id FROM company_members WHERE user_id = auth.uid()
  )
);

-- View for admin: onboarding completion rates
CREATE OR REPLACE VIEW onboarding_analytics AS
SELECT
  agent_id,
  COUNT(*) AS total_sessions,
  COUNT(*) FILTER (WHERE is_complete) AS completed,
  ROUND(
    COUNT(*) FILTER (WHERE is_complete)::numeric / NULLIF(COUNT(*), 0) * 100, 1
  ) AS completion_rate_pct,
  AVG(current_step) AS avg_step_reached,
  MAX(updated_at) AS last_activity
FROM onboarding_sessions
GROUP BY agent_id
ORDER BY completion_rate_pct DESC;
