/**
 * Batch 3 Fix — Rewrites sales + portal pages cleanly
 * (The patching approach broke brace matching)
 *
 * Run: node batch3-fix.js && npm run build && vercel --prod
 */
const fs = require('fs');
const path = require('path');
const ROOT = process.cwd();
const AP = fs.existsSync(path.join(ROOT, 'src/app')) ? 'src/' : '';

function write(fp, content) {
  const full = path.join(ROOT, fp);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content, 'utf8');
  console.log('  \u2713 ' + fp);
}

console.log('  Batch 3 Fix: Rewriting sales + portal pages...');

// ── SALES PAGE (clean rewrite) ──
write(AP + 'app/agents/sales/page.tsx', [
"'use client';",
"import { useState } from 'react';",
"import { useTenant } from '@/lib/providers/tenant-provider';",
"import { getSales } from '@/lib/tenant-data';",
"",
"const TABS = [",
"  { id: 'pipeline', name: 'Pipeline', icon: '\\uD83C\\uDFAF' },",
"  { id: 'contacts', name: 'Contacts', icon: '\\uD83D\\uDC64' },",
"  { id: 'intel', name: 'Intelligence', icon: '\\uD83E\\uDDE0' },",
"  { id: 'activity', name: 'Activity', icon: '\\uD83D\\uDCDD' },",
"  { id: 'battlecards', name: 'Battle Cards', icon: '\\u2694\\uFE0F' },",
"  { id: 'forecasts', name: 'Forecasts', icon: '\\uD83D\\uDCC8' },",
"];",
"",
"const ACTIVITIES = [",
"  { type: 'Call', contact: 'Contact 1', summary: 'Discussed timeline', time: '2h ago', icon: '\\uD83D\\uDCDE' },",
"  { type: 'Email', contact: 'Contact 2', summary: 'Sent revised proposal', time: '5h ago', icon: '\\uD83D\\uDCE7' },",
"  { type: 'Meeting', contact: 'Contact 3', summary: 'Product demo went well', time: '1d ago', icon: '\\uD83D\\uDCC5' },",
"];",
"",
"const BATTLECARDS = [",
"  { competitor: 'Legacy ERP Co', weakness: 'Slow implementation (6-12 months)', ourEdge: 'Live in 10 minutes with AI', winRate: '73%' },",
"  { competitor: 'CloudOps Platform', weakness: 'No AI agent architecture', ourEdge: '14 specialized AI agents', winRate: '68%' },",
"  { competitor: 'DataForce Suite', weakness: 'Expensive per-seat pricing', ourEdge: 'Flat tier pricing, 20+ integrations', winRate: '81%' },",
"];",
"",
"export default function SalesAgentPage() {",
"  const { currentCompany, isLoading } = useTenant();",
"  const [activeTab, setActiveTab] = useState('pipeline');",
"  const sd = getSales(currentCompany?.name);",
"",
"  const fmtK = (n: number) => '$' + (n / 1000).toFixed(0) + 'K';",
"",
"  return (",
"    <div className=\"max-w-7xl mx-auto p-6 space-y-6\">",
"      <div className=\"flex justify-between items-start\">",
"        <div className=\"flex items-center gap-4\">",
"          <div className=\"text-4xl\">{'\\uD83C\\uDFAF'}</div>",
"          <div>",
"            <h1 className=\"text-2xl font-bold\">Sales Agent</h1>",
"            <p className=\"text-sm text-gray-400\">{isLoading ? 'Loading...' : currentCompany?.name || 'Select a company'}</p>",
"          </div>",
"        </div>",
"        <div className=\"flex gap-2\">",
"          <button className=\"px-4 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-500\">+ New Deal</button>",
"          <button className=\"px-4 py-2 bg-white/5 text-gray-300 rounded-lg text-sm hover:bg-white/10\">Export</button>",
"        </div>",
"      </div>",
"",
"      <div className=\"grid grid-cols-5 gap-3\">",
"        {[",
"          { l: 'Pipeline Value', v: fmtK(sd.pipelineValue), c: '' },",
"          { l: 'Won This Month', v: fmtK(sd.wonThisMonth), c: 'text-emerald-400' },",
"          { l: 'Active Deals', v: String(sd.activeDeals), c: '' },",
"          { l: 'Win Rate', v: sd.winRate + '%', c: '' },",
"          { l: 'Avg Deal Size', v: fmtK(sd.avgDealSize), c: '' },",
"        ].map(k => (",
"          <div key={k.l} className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-4\">",
"            <div className=\"text-[9px] text-gray-500 uppercase\">{k.l}</div>",
"            <div className={'text-xl font-mono font-bold mt-1 ' + k.c}>{k.v}</div>",
"          </div>",
"        ))}",
"      </div>",
"",
"      <div className=\"flex gap-2 border-b border-white/5 pb-3\">",
"        {TABS.map(tab => (",
"          <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={'flex items-center gap-2 px-4 py-2 rounded-lg text-sm transition ' + (activeTab === tab.id ? 'bg-blue-600 text-white' : 'bg-white/5 text-gray-400 hover:bg-white/10')}>",
"            <span>{tab.icon}</span> {tab.name}",
"          </button>",
"        ))}",
"      </div>",
"",
"      {activeTab === 'pipeline' && (",
"        <div className=\"grid grid-cols-4 gap-4\">",
"          {sd.stages.map(stage => (",
"            <div key={stage.name} className=\"space-y-2\">",
"              <div className=\"flex justify-between items-center px-1\">",
"                <h3 className=\"text-xs font-semibold text-gray-400\">{stage.name}</h3>",
"                <span className=\"text-[10px] text-gray-600\">{stage.deals.length} deals</span>",
"              </div>",
"              {stage.deals.map((deal, i) => (",
"                <div key={i} className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-4 hover:border-blue-500/30 transition cursor-pointer\">",
"                  <div className=\"font-medium text-sm text-white\">{deal.company}</div>",
"                  <div className=\"text-lg font-mono font-bold text-blue-400 mt-1\">{fmtK(deal.value)}</div>",
"                  <div className=\"flex justify-between mt-2 text-[10px]\">",
"                    <span className=\"text-gray-500\">{deal.owner}</span>",
"                    <span className=\"text-gray-600\">{deal.age}</span>",
"                  </div>",
"                  <span className={'text-[9px] px-1.5 py-0.5 rounded mt-1 inline-block ' + (deal.risk === 'high' ? 'bg-red-500/10 text-red-400' : deal.risk === 'medium' ? 'bg-amber-500/10 text-amber-400' : 'bg-emerald-500/10 text-emerald-400')}>{deal.risk} risk</span>",
"                </div>",
"              ))}",
"            </div>",
"          ))}",
"        </div>",
"      )}",
"",
"      {activeTab === 'contacts' && (",
"        <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl overflow-hidden\">",
"          <table className=\"w-full\"><thead><tr className=\"border-b border-white/5\">",
"            <th className=\"text-left px-4 py-3 text-xs text-gray-500\">Contact</th>",
"            <th className=\"text-left px-4 py-3 text-xs text-gray-500\">Company</th>",
"            <th className=\"text-left px-4 py-3 text-xs text-gray-500\">Role</th>",
"            <th className=\"text-left px-4 py-3 text-xs text-gray-500\">Sentiment</th>",
"            <th className=\"text-left px-4 py-3 text-xs text-gray-500\">Last Contact</th>",
"          </tr></thead><tbody>",
"            {sd.contacts.map((c, i) => (",
"              <tr key={i} className=\"border-b border-white/[0.03] hover:bg-white/[0.02]\">",
"                <td className=\"px-4 py-3 text-sm text-white\">{c.name}</td>",
"                <td className=\"px-4 py-3 text-sm text-gray-300\">{c.company}</td>",
"                <td className=\"px-4 py-3 text-sm text-gray-400\">{c.role}</td>",
"                <td className=\"px-4 py-3\"><span className={'text-[10px] px-2 py-0.5 rounded ' + (c.sentiment === 'Positive' ? 'bg-emerald-500/10 text-emerald-400' : c.sentiment === 'Cautious' ? 'bg-amber-500/10 text-amber-400' : 'bg-gray-500/10 text-gray-400')}>{c.sentiment}</span></td>",
"                <td className=\"px-4 py-3 text-xs text-gray-500\">{c.lastContact}</td>",
"              </tr>",
"            ))}",
"          </tbody></table>",
"        </div>",
"      )}",
"",
"      {activeTab === 'intel' && (",
"        <div className=\"bg-gradient-to-br from-blue-500/5 to-cyan-500/5 border border-blue-500/10 rounded-xl p-6\">",
"          <h3 className=\"text-sm font-semibold mb-3\">{'\\uD83E\\uDDE0'} AI Insights</h3>",
"          <div className=\"space-y-3 text-sm text-gray-300\">",
"            {sd.stages.filter(s => s.name === 'Negotiation').flatMap(s => s.deals).map((d, i) => (",
"              <div key={i} className=\"flex items-start gap-2\"><span className=\"text-amber-400\">{'\\u26A0\\uFE0F'}</span> {d.company} deal ({fmtK(d.value)}) in Negotiation for {d.age}. Risk: {d.risk}.</div>",
"            ))}",
"            <div className=\"flex items-start gap-2\"><span className=\"text-blue-400\">{'\\uD83D\\uDCA1'}</span> Win rate: {sd.winRate}%. Avg deal: {fmtK(sd.avgDealSize)}.</div>",
"          </div>",
"        </div>",
"      )}",
"",
"      {activeTab === 'activity' && (",
"        <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-5\">",
"          {ACTIVITIES.map((a, i) => (",
"            <div key={i} className=\"flex items-start gap-4 py-3 border-b border-white/[0.03] last:border-0\">",
"              <div className=\"text-2xl\">{a.icon}</div>",
"              <div className=\"flex-1\">",
"                <div className=\"flex justify-between\">",
"                  <div className=\"text-sm text-white font-medium\">{a.type} with {a.contact}</div>",
"                  <div className=\"text-[10px] text-gray-600\">{a.time}</div>",
"                </div>",
"                <div className=\"text-xs text-gray-400 mt-1\">{a.summary}</div>",
"              </div>",
"            </div>",
"          ))}",
"        </div>",
"      )}",
"",
"      {activeTab === 'battlecards' && (",
"        <div className=\"grid grid-cols-3 gap-4\">",
"          {BATTLECARDS.map((bc, i) => (",
"            <div key={i} className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-5 space-y-3\">",
"              <h3 className=\"text-sm font-semibold text-white\">vs {bc.competitor}</h3>",
"              <div><div className=\"text-[10px] text-red-400 uppercase font-medium\">Their Weakness</div><div className=\"text-xs text-gray-400 mt-1\">{bc.weakness}</div></div>",
"              <div><div className=\"text-[10px] text-emerald-400 uppercase font-medium\">Our Edge</div><div className=\"text-xs text-gray-300 mt-1\">{bc.ourEdge}</div></div>",
"              <div className=\"flex items-center gap-2\"><span className=\"text-[10px] text-gray-500\">Win Rate:</span><span className=\"text-sm font-bold text-emerald-400\">{bc.winRate}</span></div>",
"            </div>",
"          ))}",
"        </div>",
"      )}",
"",
"      {activeTab === 'forecasts' && (",
"        <div className=\"grid grid-cols-3 gap-4\">",
"          <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-5\"><div className=\"text-[9px] text-gray-500 uppercase\">Weighted Pipeline</div><div className=\"text-2xl font-mono font-bold mt-1\">{fmtK(Math.round(sd.pipelineValue * 0.6))}</div></div>",
"          <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-5\"><div className=\"text-[9px] text-gray-500 uppercase\">Best Case</div><div className=\"text-2xl font-mono font-bold mt-1 text-emerald-400\">{fmtK(sd.pipelineValue)}</div></div>",
"          <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-5\"><div className=\"text-[9px] text-gray-500 uppercase\">Most Likely</div><div className=\"text-2xl font-mono font-bold mt-1 text-blue-400\">{fmtK(Math.round(sd.pipelineValue * 0.66))}</div></div>",
"        </div>",
"      )}",
"    </div>",
"  );",
"}",
].join('\n'));

// ── PORTAL PAGE (clean rewrite with tenant data) ──
write(AP + 'app/portal/page.tsx', [
"'use client';",
"import { useState } from 'react';",
"import { useTenant } from '@/lib/providers/tenant-provider';",
"import { getPortal } from '@/lib/tenant-data';",
"",
"const TABS = [",
"  { id: 'overview', name: 'Overview', icon: '\\uD83D\\uDCCA' },",
"  { id: 'inventory', name: 'Inventory', icon: '\\uD83D\\uDCE6' },",
"  { id: 'shipments', name: 'Shipments', icon: '\\uD83D\\uDE9A' },",
"  { id: 'bol', name: 'Bill of Lading', icon: '\\uD83D\\uDCC4' },",
"  { id: 'po', name: 'Purchase Orders', icon: '\\uD83D\\uDED2' },",
"  { id: 'billing', name: 'Billing', icon: '\\uD83D\\uDCB3' },",
"  { id: 'support', name: 'Support', icon: '\\uD83D\\uDCAC' },",
"];",
"",
"const FREIGHT_CLASSES = ['50','55','60','65','70','77.5','85','92.5','100','110','125','150','175','200','250','300','400','500'];",
"const UNIT_TYPES = ['Pallet', 'Case', 'Box', 'Weight'];",
"const MEASUREMENTS = ['Standard (lbs/in)', 'Metric (kg/cm)'];",
"",
"interface BOLItem { sku: string; lotNumber: string; expDate: string; description: string; qty: number; unitType: string; weight: number; freightClass: string; }",
"",
"export default function CustomerPortal() {",
"  const { currentCompany, isLoading } = useTenant();",
"  const portal = getPortal(currentCompany?.name);",
"  const [activeTab, setActiveTab] = useState('overview');",
"  const [bolItems, setBolItems] = useState<BOLItem[]>([]);",
"  const [measurement, setMeasurement] = useState('Standard (lbs/in)');",
"  const [shipTo, setShipTo] = useState({ name: '', address: '', city: '', state: '', zip: '' });",
"  const [shipFrom, setShipFrom] = useState({ name: currentCompany?.name || '', address: '', city: 'Grantsville', state: 'UT', zip: '84029' });",
"  const [carrier, setCarrier] = useState('');",
"  const [unitType, setUnitType] = useState('Pallet');",
"  const [showNewPO, setShowNewPO] = useState(false);",
"",
"  const addToBOL = (inv: typeof portal.inventory[0], qty: number) => {",
"    const existing = bolItems.findIndex(b => b.sku === inv.sku && b.lotNumber === inv.lot);",
"    if (existing >= 0) { const u = [...bolItems]; u[existing].qty += qty; setBolItems(u); }",
"    else { setBolItems([...bolItems, { sku: inv.sku, lotNumber: inv.lot, expDate: inv.exp, description: inv.name, qty, unitType, weight: inv.weight * qty, freightClass: inv.freightClass }]); }",
"  };",
"  const removeBOLItem = (i: number) => setBolItems(bolItems.filter((_, idx) => idx !== i));",
"  const totalWeight = bolItems.reduce((sum, b) => sum + b.weight, 0);",
"  const weightUnit = measurement.includes('lbs') ? 'lbs' : 'kg';",
"",
"  return (",
"    <div className=\"max-w-6xl mx-auto p-6 space-y-6\">",
"      <div><h1 className=\"text-2xl font-bold\">Customer Portal</h1><p className=\"text-sm text-gray-400 mt-1\">{isLoading ? 'Loading...' : currentCompany?.name || 'Select a company'}</p></div>",
"",
"      <div className=\"flex gap-2 border-b border-white/5 pb-3 overflow-x-auto\">",
"        {TABS.map(tab => (<button key={tab.id} onClick={() => setActiveTab(tab.id)} className={'flex items-center gap-2 px-4 py-2 rounded-lg text-sm transition whitespace-nowrap ' + (activeTab === tab.id ? 'bg-blue-600 text-white' : 'bg-white/5 text-gray-400 hover:bg-white/10')}><span>{tab.icon}</span> {tab.name}</button>))}",
"      </div>",
"",
"      {activeTab === 'overview' && (",
"        <div className=\"grid grid-cols-4 gap-4\">",
"          <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-4\"><div className=\"text-[9px] text-gray-500 uppercase\">Total SKUs</div><div className=\"text-2xl font-bold mt-1\">{portal.totalSkus.toLocaleString()}</div></div>",
"          <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-4\"><div className=\"text-[9px] text-gray-500 uppercase\">Low Stock</div><div className=\"text-2xl font-bold mt-1 text-amber-400\">{portal.lowStock}</div></div>",
"          <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-4\"><div className=\"text-[9px] text-gray-500 uppercase\">Pending ASNs</div><div className=\"text-2xl font-bold mt-1 text-blue-400\">{portal.pendingAsns}</div></div>",
"          <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-4\"><div className=\"text-[9px] text-gray-500 uppercase\">Open BOLs</div><div className=\"text-2xl font-bold mt-1\">{bolItems.length > 0 ? 1 : 0}</div></div>",
"        </div>",
"      )}",
"",
"      {activeTab === 'inventory' && (",
"        <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl overflow-hidden\">",
"          <table className=\"w-full\"><thead><tr className=\"border-b border-white/5\">",
"            <th className=\"text-left px-4 py-3 text-xs text-gray-500\">SKU</th>",
"            <th className=\"text-left px-4 py-3 text-xs text-gray-500\">Name</th>",
"            <th className=\"text-left px-4 py-3 text-xs text-gray-500\">Lot #</th>",
"            <th className=\"text-left px-4 py-3 text-xs text-gray-500\">Exp Date</th>",
"            <th className=\"text-right px-4 py-3 text-xs text-gray-500\">Qty</th>",
"            <th className=\"text-left px-4 py-3 text-xs text-gray-500\">Location</th>",
"            <th className=\"text-right px-4 py-3 text-xs text-gray-500\">Ship</th>",
"          </tr></thead><tbody>",
"            {portal.inventory.map((item, i) => (",
"              <tr key={i} className=\"border-b border-white/[0.03] hover:bg-white/[0.02]\">",
"                <td className=\"px-4 py-3 text-sm font-mono text-blue-400\">{item.sku}</td>",
"                <td className=\"px-4 py-3 text-sm text-white\">{item.name}</td>",
"                <td className=\"px-4 py-3 text-sm font-mono text-gray-400\">{item.lot}</td>",
"                <td className=\"px-4 py-3 text-sm text-gray-400\">{item.exp}</td>",
"                <td className=\"px-4 py-3 text-sm text-right font-mono\">{item.qty}</td>",
"                <td className=\"px-4 py-3 text-sm text-gray-500\">{item.location}</td>",
"                <td className=\"px-4 py-3 text-right\">{item.qty > 0 && <button onClick={() => { addToBOL(item, 1); setActiveTab('bol'); }} className=\"text-[10px] px-2 py-1 bg-blue-600 text-white rounded hover:bg-blue-500\">+ BOL</button>}</td>",
"              </tr>",
"            ))}",
"            {portal.inventory.length === 0 && <tr><td colSpan={7} className=\"px-4 py-8 text-center text-sm text-gray-500\">No inventory for this company.</td></tr>}",
"          </tbody></table>",
"        </div>",
"      )}",
"",
"      {activeTab === 'shipments' && (",
"        portal.shipments.length > 0 ? (",
"          <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl overflow-hidden\">",
"            <table className=\"w-full\"><thead><tr className=\"border-b border-white/5\">",
"              <th className=\"text-left px-4 py-3 text-xs text-gray-500\">ID</th>",
"              <th className=\"text-left px-4 py-3 text-xs text-gray-500\">Type</th>",
"              <th className=\"text-right px-4 py-3 text-xs text-gray-500\">Items</th>",
"              <th className=\"text-left px-4 py-3 text-xs text-gray-500\">Carrier</th>",
"              <th className=\"text-left px-4 py-3 text-xs text-gray-500\">Status</th>",
"            </tr></thead><tbody>",
"              {portal.shipments.map(s => (",
"                <tr key={s.id} className=\"border-b border-white/[0.03]\">",
"                  <td className=\"px-4 py-3 text-sm font-mono text-blue-400\">{s.id}</td>",
"                  <td className=\"px-4 py-3 text-sm text-gray-300\">{s.type}</td>",
"                  <td className=\"px-4 py-3 text-sm text-right\">{s.items}</td>",
"                  <td className=\"px-4 py-3 text-sm text-gray-400\">{s.carrier}</td>",
"                  <td className=\"px-4 py-3\"><span className=\"text-[10px] px-2 py-0.5 rounded bg-blue-500/10 text-blue-400\">{s.status}</span></td>",
"                </tr>",
"              ))}",
"            </tbody></table>",
"          </div>",
"        ) : (",
"          <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-5 text-center text-gray-500 text-sm\">",
"            <div className=\"text-3xl mb-3\">{'\\uD83D\\uDE9A'}</div><p>No shipments for this company.</p>",
"          </div>",
"        )",
"      )}",
"",
"      {activeTab === 'bol' && (",
"        <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-6 space-y-4\">",
"          <div className=\"flex justify-between items-center\"><h2 className=\"text-lg font-bold\">STRAIGHT BILL OF LADING</h2><div className=\"text-[10px] text-gray-500\">DOT Compliant</div></div>",
"          <div className=\"grid grid-cols-2 gap-6\">",
"            <div><h3 className=\"text-xs text-gray-400 uppercase font-semibold mb-2\">Ship From</h3>",
"              <input value={shipFrom.name} onChange={e => setShipFrom({...shipFrom, name: e.target.value})} placeholder=\"Company\" className=\"w-full mb-1 px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\" />",
"              <input value={shipFrom.address} onChange={e => setShipFrom({...shipFrom, address: e.target.value})} placeholder=\"Address\" className=\"w-full mb-1 px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\" />",
"              <div className=\"grid grid-cols-3 gap-1\"><input value={shipFrom.city} onChange={e => setShipFrom({...shipFrom, city: e.target.value})} placeholder=\"City\" className=\"px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\" /><input value={shipFrom.state} onChange={e => setShipFrom({...shipFrom, state: e.target.value})} placeholder=\"ST\" className=\"px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\" /><input value={shipFrom.zip} onChange={e => setShipFrom({...shipFrom, zip: e.target.value})} placeholder=\"ZIP\" className=\"px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\" /></div>",
"            </div>",
"            <div><h3 className=\"text-xs text-gray-400 uppercase font-semibold mb-2\">Ship To</h3>",
"              <input value={shipTo.name} onChange={e => setShipTo({...shipTo, name: e.target.value})} placeholder=\"Company\" className=\"w-full mb-1 px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\" />",
"              <input value={shipTo.address} onChange={e => setShipTo({...shipTo, address: e.target.value})} placeholder=\"Address\" className=\"w-full mb-1 px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\" />",
"              <div className=\"grid grid-cols-3 gap-1\"><input value={shipTo.city} onChange={e => setShipTo({...shipTo, city: e.target.value})} placeholder=\"City\" className=\"px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\" /><input value={shipTo.state} onChange={e => setShipTo({...shipTo, state: e.target.value})} placeholder=\"ST\" className=\"px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\" /><input value={shipTo.zip} onChange={e => setShipTo({...shipTo, zip: e.target.value})} placeholder=\"ZIP\" className=\"px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\" /></div>",
"            </div>",
"          </div>",
"          <div className=\"grid grid-cols-3 gap-4\">",
"            <div><label className=\"text-xs text-gray-400 mb-1 block\">Carrier</label><input value={carrier} onChange={e => setCarrier(e.target.value)} placeholder=\"Carrier\" className=\"w-full px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\" /></div>",
"            <div><label className=\"text-xs text-gray-400 mb-1 block\">Unit Type</label><select value={unitType} onChange={e => setUnitType(e.target.value)} className=\"w-full px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\">{UNIT_TYPES.map(u => <option key={u} value={u}>{u}</option>)}</select></div>",
"            <div><label className=\"text-xs text-gray-400 mb-1 block\">Measurement</label><select value={measurement} onChange={e => setMeasurement(e.target.value)} className=\"w-full px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\">{MEASUREMENTS.map(m => <option key={m} value={m}>{m}</option>)}</select></div>",
"          </div>",
"          <div className=\"border border-white/10 rounded-lg overflow-hidden\">",
"            <table className=\"w-full\"><thead><tr className=\"bg-white/5 border-b border-white/10\">",
"              <th className=\"text-left px-3 py-2 text-[10px] text-gray-400\">SKU</th><th className=\"text-left px-3 py-2 text-[10px] text-gray-400\">Description</th><th className=\"text-left px-3 py-2 text-[10px] text-gray-400\">Lot #</th><th className=\"text-left px-3 py-2 text-[10px] text-gray-400\">Exp</th><th className=\"text-right px-3 py-2 text-[10px] text-gray-400\">Qty</th><th className=\"text-left px-3 py-2 text-[10px] text-gray-400\">Unit</th><th className=\"text-right px-3 py-2 text-[10px] text-gray-400\">Weight</th><th className=\"text-left px-3 py-2 text-[10px] text-gray-400\">Class</th><th className=\"px-3 py-2\"></th>",
"            </tr></thead><tbody>",
"              {bolItems.length === 0 ? (",
"                <tr><td colSpan={9} className=\"px-3 py-6 text-center text-xs text-gray-600\">No items. Go to Inventory tab and click + BOL.</td></tr>",
"              ) : bolItems.map((item, i) => (",
"                <tr key={i} className=\"border-b border-white/[0.03]\">",
"                  <td className=\"px-3 py-2 text-xs font-mono text-blue-400\">{item.sku}</td>",
"                  <td className=\"px-3 py-2 text-xs text-white\">{item.description}</td>",
"                  <td className=\"px-3 py-2 text-xs font-mono text-gray-400\">{item.lotNumber}</td>",
"                  <td className=\"px-3 py-2 text-xs text-gray-400\">{item.expDate}</td>",
"                  <td className=\"px-3 py-2 text-xs text-right\"><input type=\"number\" value={item.qty} min={1} onChange={e => { const u = [...bolItems]; u[i].qty = Number(e.target.value); u[i].weight = Number(e.target.value) * (portal.inventory.find(m => m.sku === item.sku)?.weight || 1); setBolItems(u); }} className=\"w-16 text-right px-1 py-0.5 bg-white/5 border border-white/10 rounded text-xs text-white\" /></td>",
"                  <td className=\"px-3 py-2 text-xs text-gray-400\">{unitType}</td>",
"                  <td className=\"px-3 py-2 text-xs text-right font-mono\">{item.weight.toFixed(1)}</td>",
"                  <td className=\"px-3 py-2 text-xs\"><select value={item.freightClass} onChange={e => { const u = [...bolItems]; u[i].freightClass = e.target.value; setBolItems(u); }} className=\"px-1 py-0.5 bg-white/5 border border-white/10 rounded text-xs text-white\">{FREIGHT_CLASSES.map(fc => <option key={fc} value={fc}>{fc}</option>)}</select></td>",
"                  <td className=\"px-3 py-2\"><button onClick={() => removeBOLItem(i)} className=\"text-red-400 text-xs\">X</button></td>",
"                </tr>",
"              ))}",
"            </tbody></table>",
"          </div>",
"          {bolItems.length > 0 && <div className=\"flex justify-between items-center bg-white/5 rounded-lg px-4 py-3\"><span className=\"text-sm text-gray-400\">{bolItems.length} items</span><span className=\"text-sm text-white font-bold\">{totalWeight.toFixed(1)} {weightUnit}</span></div>}",
"          <div className=\"flex gap-3\">",
"            <button onClick={() => setActiveTab('inventory')} className=\"px-4 py-2 bg-white/5 text-gray-300 rounded-lg text-sm hover:bg-white/10\">+ Add Items</button>",
"            {bolItems.length > 0 && <><button className=\"px-4 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-500\">Generate BOL PDF</button><button className=\"px-4 py-2 bg-emerald-600 text-white rounded-lg text-sm hover:bg-emerald-500\">Submit BOL</button></>}",
"          </div>",
"        </div>",
"      )}",
"",
"      {activeTab === 'po' && (",
"        <div className=\"space-y-4\">",
"          <div className=\"flex justify-between items-center\"><h2 className=\"text-lg font-semibold\">Purchase Orders</h2><button onClick={() => setShowNewPO(!showNewPO)} className=\"px-4 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-500\">{showNewPO ? 'Cancel' : '+ New PO'}</button></div>",
"          {showNewPO && <div className=\"bg-[#0A0E15] border border-blue-500/20 rounded-xl p-6\"><h3 className=\"text-sm font-semibold mb-3\">Create Purchase Order</h3><div className=\"grid grid-cols-2 gap-4 mb-3\"><div><label className=\"text-xs text-gray-400 mb-1 block\">Vendor</label><input placeholder=\"Vendor\" className=\"w-full px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\" /></div><div><label className=\"text-xs text-gray-400 mb-1 block\">Delivery Date</label><input type=\"date\" className=\"w-full px-3 py-2 bg-white/5 border border-white/10 rounded text-sm text-white\" /></div></div><button className=\"px-6 py-2.5 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-500\">Submit PO</button></div>}",
"        </div>",
"      )}",
"",
"      {activeTab === 'billing' && (",
"        <div className=\"grid grid-cols-3 gap-4\">",
"          <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-4\"><div className=\"text-[9px] text-gray-500 uppercase\">Balance</div><div className=\"text-2xl font-bold mt-1\">{'$' + portal.balance.toLocaleString()}</div></div>",
"          <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-4\"><div className=\"text-[9px] text-gray-500 uppercase\">Storage/mo</div><div className=\"text-2xl font-bold mt-1\">{'$' + portal.storageFee.toLocaleString()}</div></div>",
"          <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-4\"><div className=\"text-[9px] text-gray-500 uppercase\">Last Payment</div><div className=\"text-2xl font-bold mt-1 text-emerald-400\">{'$' + portal.lastPayment.toLocaleString()}</div></div>",
"        </div>",
"      )}",
"",
"      {activeTab === 'support' && (",
"        <div className=\"bg-[#0A0E15] border border-white/5 rounded-xl p-6 text-center\">",
"          <div className=\"text-3xl mb-3\">{'\\uD83D\\uDCAC'}</div><h3 className=\"text-lg font-semibold mb-2\">Need Help?</h3>",
"          <p className=\"text-sm text-gray-400 mb-4\">Monday-Friday, 8am-6pm MST</p>",
"          <div className=\"flex justify-center gap-3\"><a href=\"mailto:support@woulfgroup.com\" className=\"px-4 py-2 bg-blue-600 text-white rounded-lg text-sm hover:bg-blue-500\">Email Support</a><a href=\"tel:+18015551234\" className=\"px-4 py-2 bg-white/5 text-gray-300 rounded-lg text-sm hover:bg-white/10\">Call Us</a></div>",
"        </div>",
"      )}",
"    </div>",
"  );",
"}",
].join('\n'));

console.log('');
console.log('  Done! Now run: npm run build && vercel --prod');
