export const dynamic = 'force-dynamic';
// ============================================================
// GET /api/tenant/companies — List user's companies
// Generated by deploy-5-agents.js
// ============================================================

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabase = () => createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  );

export async function GET(request: NextRequest) {
  try {
    // Get user from auth header or session
    const authHeader = request.headers.get('authorization');
    
    // For now, return all companies the user has access to
    // TODO: Filter by user membership once auth is wired
    const { data: companies, error } = await supabase()
      .from('companies')
      .select('id, name, slug, logo_url')
      .order('name');

    if (error) throw error;

    return NextResponse.json({
      companies: (companies || []).map(c => ({
        id: c.id,
        name: c.name,
        slug: c.slug,
        logo: c.logo_url,
      })),
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
