'use client';
// ============================================================
// Marketing Agent — Live Agent Page
// Generated by deploy-5-agents.js
// ============================================================

import React, { useState, useEffect, useCallback } from 'react';
import AgentDashboardShell from '@/components/agents/agent-dashboard-shell';
import { getAgent } from '@/lib/agents/agent-registry';
import { useTenant } from '@/lib/providers/tenant-provider';

const agentDef = getAgent('marketing')!;

// ── KPI Formatting ──
function formatValue(value: number | null, format: string): string {
  if (value === null || value === undefined) return '—';
  switch (format) {
    case 'currency': return '$' + value.toLocaleString();
    case 'percent': return value.toFixed(1) + '%';
    default: return value.toLocaleString();
  }
}

// ── Tab definitions ──
const TABS = ["Campaigns","Calendar","Analytics","Content"];

export default function MarketingAgentPage() {
  const { companyId } = useTenant();
  const [activeTab, setActiveTab] = useState(TABS[0]);
  const [kpis, setKpis] = useState<Record<string, number | null>>({});
  const [data, setData] = useState<any[]>([]);
  const [hasData, setHasData] = useState(false);
  const [isEditing, setIsEditing] = useState(false);

  // ── Fetch agent data when company changes ──
  const fetchData = useCallback(async () => {
    if (!companyId) return;
    try {
      const res = await fetch(`/api/agents/marketing?companyId=${companyId}`);
      if (res.ok) {
        const json = await res.json();
        setKpis(json.kpis || {});
        setData(json.data || []);
        setHasData((json.data?.length || 0) > 0 || Object.keys(json.kpis || {}).length > 0);
      }
    } catch (err) {
      console.error('Failed to fetch marketing data:', err);
    }
  }, [companyId]);

  useEffect(() => { fetchData(); }, [fetchData]);

  // ── Action handlers ──
  const handleSubmit = async () => {
    await fetch(`/api/agents/marketing`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ companyId, data }),
    });
    await fetchData();
  };

  const handleDownload = async () => {
    const res = await fetch(`/api/agents/marketing/export?companyId=${companyId}`);
    if (res.ok) {
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `marketing-report-${new Date().toISOString().slice(0,10)}.csv`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  return (
    <AgentDashboardShell
      agent={agentDef}
      hasData={hasData}
      onSubmit={handleSubmit}
      onEdit={() => setIsEditing(!isEditing)}
      onDownload={handleDownload}
    >
      {/* ── KPI Cards ── */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        {[{"label":"Campaign ROI","key":"roi","format":"percent"},{"label":"Leads Generated","key":"leads","format":"number"},{"label":"Ad Spend","key":"spend","format":"currency"},{"label":"Conversion Rate","key":"conversion","format":"percent"}].map((kpi: any) => (
          <div key={kpi.key} className="bg-white rounded-xl border p-4">
            <p className="text-sm text-gray-500">{kpi.label}</p>
            <p className="text-2xl font-bold text-gray-900 mt-1">
              {formatValue(kpis[kpi.key] ?? null, kpi.format)}
            </p>
          </div>
        ))}
      </div>

      {/* ── Tabs ── */}
      <div className="bg-white rounded-xl border">
        <div className="flex border-b">
          {TABS.map((tab: string) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-6 py-3 text-sm font-medium transition border-b-2 ${
                activeTab === tab
                  ? 'border-blue-600 text-blue-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700'
              }`}
            >
              {tab}
            </button>
          ))}
        </div>

        {/* ── Tab Content ── */}
        <div className="p-6">
          {data.length > 0 ? (
            <div className="space-y-3">
              {data.map((item: any, i: number) => (
                <div key={i} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                  <div>
                    <p className="font-medium text-gray-900">{item.name || item.title || `Item ${i + 1}`}</p>
                    <p className="text-sm text-gray-500">{item.description || item.status || ''}</p>
                  </div>
                  {isEditing && (
                    <button className="text-sm text-blue-600 hover:text-blue-800">Edit</button>
                  )}
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-12 text-gray-400">
              <p className="text-lg">No {activeTab.toLowerCase()} data for this company yet.</p>
              <p className="text-sm mt-1">Use the Submit button to add data, or connect an integration.</p>
            </div>
          )}
        </div>
      </div>
    </AgentDashboardShell>
  );
}
