// ============================================================
// GET /api/agents/[slug]/export — CSV Export
// Generated by deploy-5-agents.js
// ============================================================

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const AGENT_TABLES: Record<string, string> = {
  'org-lead': 'agent_org_lead_data',
  'seo': 'agent_seo_data',
  'marketing': 'agent_marketing_data',
  'wms': 'agent_wms_data',
  'hr': 'agent_hr_data',
};

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;
  const companyId = request.nextUrl.searchParams.get('companyId');
  const table = AGENT_TABLES[slug];

  if (!companyId || !table) {
    return NextResponse.json({ error: 'Missing params' }, { status: 400 });
  }

  const { data: rows } = await supabase
    .from(table)
    .select('*')
    .eq('company_id', companyId);

  // Convert to CSV
  if (!rows || rows.length === 0) {
    return new NextResponse('No data', { status: 204 });
  }

  const headers = Object.keys(rows[0]);
  const csv = [
    headers.join(','),
    ...rows.map(row => headers.map(h => JSON.stringify(row[h] ?? '')).join(','))
  ].join('\n');

  return new NextResponse(csv, {
    headers: {
      'Content-Type': 'text/csv',
      'Content-Disposition': `attachment; filename=${slug}-export.csv`,
    },
  });
}
