// ============================================================
// POST /api/admin/comp-agent — Admin Comp Logic
// Generated by deploy-5-agents.js
// ============================================================
// Grants agent access to a company without Stripe payment.
// Super Admin only.

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { companyId, agentSlug, compAll, adminUserId } = body;

    if (!companyId) {
      return NextResponse.json({ error: 'companyId required' }, { status: 400 });
    }

    // Verify caller is super_admin
    if (adminUserId) {
      const { data: profile } = await supabase
        .from('profiles')
        .select('role')
        .eq('id', adminUserId)
        .single();

      if (profile?.role !== 'super_admin' && profile?.role !== 'admin') {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 403 });
      }
    }

    if (compAll) {
      // Comp ALL agents for this company
      const { data: agents } = await supabase
        .from('agents')
        .select('slug')
        .eq('status', 'live');

      if (agents) {
        const records = agents.map(a => ({
          company_id: companyId,
          agent_slug: a.slug,
          access_type: 'comp',
          status: 'active',
          granted_at: new Date().toISOString(),
        }));

        const { error } = await supabase
          .from('company_agent_access')
          .upsert(records, { onConflict: 'company_id,agent_slug' });

        if (error) throw error;

        return NextResponse.json({
          success: true,
          message: `Comped ${agents.length} agents for company ${companyId}`,
          agents: agents.map(a => a.slug),
        });
      }
    } else if (agentSlug) {
      // Comp single agent
      const { error } = await supabase
        .from('company_agent_access')
        .upsert({
          company_id: companyId,
          agent_slug: agentSlug,
          access_type: 'comp',
          status: 'active',
          granted_at: new Date().toISOString(),
        }, { onConflict: 'company_id,agent_slug' });

      if (error) throw error;

      return NextResponse.json({
        success: true,
        message: `Comped ${agentSlug} for company ${companyId}`,
      });
    }

    return NextResponse.json({ error: 'Provide agentSlug or compAll: true' }, { status: 400 });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
