'use client';
// ============================================================
// WoulfAI Sidebar Navigation
// Generated by deploy-5-agents.js
// ============================================================
// Auto-builds from agent-registry.ts. Groups by category.
// Shows Business Switcher dropdown at top.

import React, { useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useTenant } from '@/lib/providers/tenant-provider';
import { AGENTS, CATEGORY_LABELS, CATEGORY_ORDER, type AgentCategory } from '@/lib/agents/agent-registry';

export default function SidebarNav() {
  const pathname = usePathname();
  const { currentCompany, companies, switchCompany, isLoading } = useTenant();
  const [switcherOpen, setSwitcherOpen] = useState(false);

  // Group agents by category
  const grouped = CATEGORY_ORDER.reduce((acc, cat) => {
    const agents = AGENTS.filter(a => a.category === cat && a.status === 'live');
    if (agents.length > 0) acc[cat] = agents;
    return acc;
  }, {} as Record<AgentCategory, typeof AGENTS>);

  return (
    <aside className="w-64 bg-gray-900 text-gray-100 min-h-screen flex flex-col">
      {/* ── Logo ── */}
      <div className="px-4 py-5 border-b border-gray-800">
        <Link href="/" className="text-xl font-bold text-white tracking-tight">
          Woulf<span className="text-blue-400">AI</span>
        </Link>
      </div>

      {/* ── Business Switcher ── */}
      <div className="px-3 py-3 border-b border-gray-800 relative">
        <button
          onClick={() => setSwitcherOpen(!switcherOpen)}
          className="w-full flex items-center justify-between px-3 py-2 bg-gray-800 rounded-lg hover:bg-gray-700 transition text-sm"
        >
          <span className="truncate">
            {isLoading ? 'Loading...' : currentCompany?.name || 'Select Company'}
          </span>
          <svg className="w-4 h-4 flex-shrink-0 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </button>

        {switcherOpen && companies.length > 0 && (
          <div className="absolute left-3 right-3 top-full mt-1 bg-gray-800 rounded-lg shadow-xl border border-gray-700 z-50 max-h-60 overflow-y-auto">
            {companies.map((company) => (
              <button
                key={company.id}
                onClick={() => {
                  switchCompany(company.id);
                  setSwitcherOpen(false);
                }}
                className={`w-full text-left px-3 py-2 text-sm hover:bg-gray-700 transition ${
                  company.id === currentCompany?.id ? 'bg-gray-700 text-blue-400' : 'text-gray-300'
                }`}
              >
                {company.name}
              </button>
            ))}
          </div>
        )}
      </div>

      {/* ── Agent Navigation ── */}
      <nav className="flex-1 overflow-y-auto px-3 py-4 space-y-6">
        {Object.entries(grouped).map(([category, agents]) => (
          <div key={category}>
            <h3 className="px-3 text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">
              {CATEGORY_LABELS[category as AgentCategory]}
            </h3>
            <ul className="space-y-1">
              {agents.map((agent) => {
                const isActive = pathname?.startsWith(agent.liveRoute);
                return (
                  <li key={agent.slug}>
                    <Link
                      href={agent.liveRoute}
                      className={`flex items-center gap-3 px-3 py-2 rounded-lg text-sm transition ${
                        isActive
                          ? 'bg-blue-600 text-white'
                          : 'text-gray-400 hover:bg-gray-800 hover:text-gray-200'
                      }`}
                    >
                      <span className="text-lg">{agent.icon}</span>
                      <span className="truncate">{agent.name}</span>
                      <span className={`ml-auto px-1.5 py-0.5 text-[10px] rounded-full font-medium ${
                        agent.status === 'live'
                          ? 'bg-green-500/20 text-green-400'
                          : 'bg-amber-500/20 text-amber-400'
                      }`}>
                        {agent.status.toUpperCase()}
                      </span>
                    </Link>
                  </li>
                );
              })}
            </ul>
          </div>
        ))}
      </nav>

      {/* ── Admin Link ── */}
      <div className="px-3 py-4 border-t border-gray-800">
        <Link
          href="/admin"
          className="flex items-center gap-3 px-3 py-2 rounded-lg text-sm text-gray-400 hover:bg-gray-800 hover:text-gray-200 transition"
        >
          <span className="text-lg">⚡</span>
          <span>Admin Dashboard</span>
        </Link>
      </div>
    </aside>
  );
}
