'use client';
// ============================================================
// WoulfAI Tenant Provider — Global Business Switcher
// Generated by deploy-5-agents.js
// ============================================================
// Wraps the app. When user switches company, ALL agent data reloads.

import React, { createContext, useContext, useState, useEffect, useCallback, ReactNode } from 'react';
import { useRouter } from 'next/navigation';

interface Company {
  id: string;
  name: string;
  slug: string;
  logo?: string;
}

interface TenantContextType {
  currentCompany: Company | null;
  companies: Company[];
  switchCompany: (companyId: string) => Promise<void>;
  isLoading: boolean;
  companyId: string | null;
}

const TenantContext = createContext<TenantContextType>({
  currentCompany: null,
  companies: [],
  switchCompany: async () => {},
  isLoading: true,
  companyId: null,
});

export function useTenant() {
  return useContext(TenantContext);
}

interface Props {
  children: ReactNode;
  initialCompanyId?: string;
}

export function TenantProvider({ children, initialCompanyId }: Props) {
  const router = useRouter();
  const [companies, setCompanies] = useState<Company[]>([]);
  const [currentCompany, setCurrentCompany] = useState<Company | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  // Load companies on mount
  useEffect(() => {
    async function load() {
      try {
        const res = await fetch('/api/tenant/companies');
        if (res.ok) {
          const data = await res.json();
          setCompanies(data.companies || []);
          
          // Set initial company
          const initial = initialCompanyId
            ? data.companies?.find((c: Company) => c.id === initialCompanyId)
            : data.companies?.[0];
          
          if (initial) {
            setCurrentCompany(initial);
          }
        }
      } catch (err) {
        console.error('Failed to load companies:', err);
      } finally {
        setIsLoading(false);
      }
    }
    load();
  }, [initialCompanyId]);

  // Switch company — calls API, sets cookie, triggers full refresh
  const switchCompany = useCallback(async (companyId: string) => {
    setIsLoading(true);
    try {
      const res = await fetch('/api/tenant/switch', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ companyId }),
      });

      if (res.ok) {
        const target = companies.find(c => c.id === companyId);
        if (target) {
          setCurrentCompany(target);
        }
        // Force all server components to re-fetch with new companyId
        router.refresh();
      }
    } catch (err) {
      console.error('Failed to switch company:', err);
    } finally {
      setIsLoading(false);
    }
  }, [companies, router]);

  return (
    <TenantContext.Provider
      value={{
        currentCompany,
        companies,
        switchCompany,
        isLoading,
        companyId: currentCompany?.id || null,
      }}
    >
      {children}
    </TenantContext.Provider>
  );
}
