// ============================================================
// WoulfAI Agent Registry — Single Source of Truth
// Generated by deploy-5-agents.js
// ============================================================

export type AgentStatus = 'live' | 'demo' | 'dev' | 'locked';
export type AgentCategory = 'finance' | 'sales' | 'operations' | 'compliance' | 'portal';

export interface AgentDefinition {
  slug: string;
  name: string;
  description: string;
  icon: string;
  status: AgentStatus;
  category: AgentCategory;
  completionPct: number;
  liveRoute: string;
  demoRoute: string;
  portal: 'woulf' | 'clutch' | 'shared';
  features: string[];
  odooModel?: string;
  emptyStateMessage: string;
}

export const AGENTS: AgentDefinition[] = [
  // ── FINANCE ──────────────────────────────────────────────
  {
    slug: 'cfo',
    name: 'CFO Agent',
    description: 'AI-powered financial intelligence and cash flow management',
    icon: '💰',
    status: 'live',
    category: 'finance',
    completionPct: 92,
    liveRoute: '/agents/cfo/console',
    demoRoute: '/demo/cfo',
    portal: 'woulf',
    features: ['Invoice CRUD', 'Financial Health Score', 'Cashflow Forecast', 'Refinance Alert'],
    odooModel: 'account.move',
    emptyStateMessage: 'Connect your accounting system to unlock financial intelligence.',
  },
  {
    slug: 'finops',
    name: 'FinOps Agent',
    description: 'AP management, debt tracking, labor analysis, and forecasting',
    icon: '📊',
    status: 'live',
    category: 'finance',
    completionPct: 88,
    liveRoute: '/agents/cfo/finops',
    demoRoute: '/demo/finops',
    portal: 'woulf',
    features: ['AP Dashboard', 'Debt Tracker', 'Labor Analysis', 'Sandbox'],
    odooModel: 'account.move.line',
    emptyStateMessage: 'Connect your ERP to start analyzing financial operations.',
  },
  {
    slug: 'payables',
    name: 'Payables Agent',
    description: 'Invoice intake, approval workflows, payment processing',
    icon: '🧾',
    status: 'live',
    category: 'finance',
    completionPct: 85,
    liveRoute: '/agents/cfo/payables',
    demoRoute: '/demo/payables',
    portal: 'woulf',
    features: ['Invoice Intake', 'Approval Queue', 'Payment Processing', 'Reconciliation'],
    odooModel: 'account.payment',
    emptyStateMessage: 'Upload invoices or connect your AP system to get started.',
  },
  {
    slug: 'collections',
    name: 'Collections Agent',
    description: '4-tier AI collections with behavioral intelligence',
    icon: '📞',
    status: 'live',
    category: 'finance',
    completionPct: 80,
    liveRoute: '/agents/cfo/console',
    demoRoute: '/demo/collections',
    portal: 'woulf',
    features: ['Aging Analysis', 'Auto-Escalation', 'Payment Plans', 'Risk Scoring'],
    emptyStateMessage: 'Connect receivables data to activate collections intelligence.',
  },

  // ── SALES ────────────────────────────────────────────────
  {
    slug: 'sales',
    name: 'Sales Agent',
    description: 'CRM pipeline, behavioral profiles, and battle cards',
    icon: '🎯',
    status: 'live',
    category: 'sales',
    completionPct: 95,
    liveRoute: '/agents/sales/intel',
    demoRoute: '/demo/sales',
    portal: 'woulf',
    features: ['Pipeline Kanban', 'Contact Intel', 'Battle Cards', 'Activity Tracking'],
    odooModel: 'crm.lead',
    emptyStateMessage: 'Connect your CRM to load your pipeline and contacts.',
  },

  // ── THE 5 NEW AGENTS (ALL LIVE) ──────────────────────────
  {
    slug: 'org-lead',
    name: 'Organization Lead',
    description: 'Command center for org-wide KPIs, team management, and strategic oversight',
    icon: '🏢',
    status: 'live',
    category: 'operations',
    completionPct: 95,
    liveRoute: '/agents/org-lead',
    demoRoute: '/demo/org-lead',
    portal: 'shared',
    features: ['KPI Dashboard', 'Team Overview', 'Strategic Planning', 'Cross-Agent Reports'],
    emptyStateMessage: 'Set up your organization to see your command center.',
  },
  {
    slug: 'seo',
    name: 'SEO Agent',
    description: 'Search rankings, keyword tracking, technical audits, and content optimization',
    icon: '🔍',
    status: 'live',
    category: 'sales',
    completionPct: 95,
    liveRoute: '/agents/seo',
    demoRoute: '/demo/seo',
    portal: 'clutch',
    features: ['Rank Tracker', 'Keyword Research', 'Technical Audit', 'Content Grader'],
    emptyStateMessage: 'Enter your website URL to start tracking SEO performance.',
  },
  {
    slug: 'marketing',
    name: 'Marketing Agent',
    description: 'Campaign management, content calendar, ad performance, and analytics',
    icon: '📣',
    status: 'live',
    category: 'sales',
    completionPct: 95,
    liveRoute: '/agents/marketing',
    demoRoute: '/demo/marketing',
    portal: 'clutch',
    features: ['Campaign Builder', 'Content Calendar', 'Ad Analytics', 'ROI Tracker'],
    emptyStateMessage: 'Connect Google Analytics or your ad accounts to see campaign data.',
  },
  {
    slug: 'wms',
    name: 'WMS Agent',
    description: 'Warehouse inventory, receiving, shipping, and location management',
    icon: '📦',
    status: 'live',
    category: 'operations',
    completionPct: 95,
    liveRoute: '/agents/wms',
    demoRoute: '/demo/wms',
    portal: 'woulf',
    features: ['Inventory Dashboard', 'Receiving', 'Pick/Pack/Ship', 'Location Manager'],
    odooModel: 'stock.quant',
    emptyStateMessage: 'Connect your warehouse system or upload inventory to get started.',
  },
  {
    slug: 'hr',
    name: 'HR Agent',
    description: 'Employee directory, PTO tracking, onboarding, and performance reviews',
    icon: '👥',
    status: 'live',
    category: 'operations',
    completionPct: 95,
    liveRoute: '/agents/hr',
    demoRoute: '/demo/hr',
    portal: 'woulf',
    features: ['Employee Directory', 'PTO Manager', 'Onboarding Checklists', 'Reviews'],
    odooModel: 'hr.employee',
    emptyStateMessage: 'Upload your employee roster or connect your payroll system.',
  },

  // ── REMAINING AGENTS (from Phase B/C) ────────────────────
  {
    slug: 'operations',
    name: 'Operations Agent',
    description: 'Project tracking, crew scheduling, and resource management',
    icon: '⚙️',
    status: 'live',
    category: 'operations',
    completionPct: 95,
    liveRoute: '/agents/operations',
    demoRoute: '/demo/operations',
    portal: 'woulf',
    features: ['Project Tracker', 'Crew Scheduler', 'Resource Manager', 'Timeline'],
    emptyStateMessage: 'Create your first project to see the operations command center.',
  },
  {
    slug: 'legal',
    name: 'Legal Agent',
    description: 'Contract analysis, risk assessment, and compliance tracking',
    icon: '⚖️',
    status: 'live',
    category: 'compliance',
    completionPct: 95,
    liveRoute: '/agents/legal',
    demoRoute: '/demo/legal',
    portal: 'shared',
    features: ['Contract Scanner', 'Risk Assessment', 'Renewal Calendar', 'Clause Library'],
    emptyStateMessage: 'Upload a contract PDF to see AI-powered legal analysis.',
  },
  {
    slug: 'compliance',
    name: 'Compliance Agent',
    description: 'Regulatory tracking, audit preparation, and policy management',
    icon: '🛡️',
    status: 'live',
    category: 'compliance',
    completionPct: 95,
    liveRoute: '/agents/compliance',
    demoRoute: '/demo/compliance',
    portal: 'shared',
    features: ['Regulation Tracker', 'Audit Prep', 'Policy Library', 'Training Log'],
    emptyStateMessage: 'Set up your compliance requirements to start tracking.',
  },
  {
    slug: 'supply-chain',
    name: 'Supply Chain Agent',
    description: 'Vendor management, procurement, and logistics optimization',
    icon: '🚛',
    status: 'live',
    category: 'operations',
    completionPct: 95,
    liveRoute: '/agents/supply-chain',
    demoRoute: '/demo/supply-chain',
    portal: 'woulf',
    features: ['Vendor Scorecards', 'PO Management', 'Logistics Tracker', 'Cost Optimizer'],
    odooModel: 'purchase.order',
    emptyStateMessage: 'Connect your procurement system to see supply chain intelligence.',
  },
];

// ── Helpers ──────────────────────────────────────────────────
export function getAgent(slug: string): AgentDefinition | undefined {
  return AGENTS.find(a => a.slug === slug);
}

export function getAgentsByCategory(category: AgentCategory): AgentDefinition[] {
  return AGENTS.filter(a => a.category === category);
}

export function getLiveAgents(): AgentDefinition[] {
  return AGENTS.filter(a => a.status === 'live');
}

export function getAgentsByPortal(portal: 'woulf' | 'clutch' | 'shared'): AgentDefinition[] {
  return AGENTS.filter(a => a.portal === portal);
}

// Category labels for sidebar grouping
export const CATEGORY_LABELS: Record<AgentCategory, string> = {
  finance: 'Finance & Accounting',
  sales: 'Sales & Marketing',
  operations: 'Operations & Logistics',
  compliance: 'Legal & Compliance',
  portal: 'Customer Portal',
};

// Category sort order
export const CATEGORY_ORDER: AgentCategory[] = [
  'finance',
  'sales',
  'operations',
  'compliance',
  'portal',
];
