'use client';
// ============================================================
// /onboarding/[agentId] — Adaptive Multi-Step Wizard
// Generated by install-onboarding.js
// ============================================================
// Progressive Disclosure: Shows one step at a time.
// State saved to DB on every step (resume if they leave).
// Ends with the agent's "Aha Moment."

import React, { useState, useEffect, useCallback, use } from 'react';
import { useRouter } from 'next/navigation';
import { getOnboardingConfig, type OnboardingStep } from '@/lib/onboarding/agent-steps';

interface Props {
  params: Promise<{ agentId: string }>;
}

export default function OnboardingWizardPage({ params }: Props) {
  const { agentId } = use(params);
  const router = useRouter();
  const config = getOnboardingConfig(agentId);

  const [currentStep, setCurrentStep] = useState(0);
  const [formData, setFormData] = useState<Record<string, any>>({});
  const [isProcessing, setIsProcessing] = useState(false);
  const [verifyProgress, setVerifyProgress] = useState(0);

  // Load saved progress
  useEffect(() => {
    async function loadProgress() {
      try {
        const res = await fetch(`/api/onboarding/progress?agentId=${agentId}`);
        if (res.ok) {
          const data = await res.json();
          if (data.currentStep > 0) {
            setCurrentStep(data.currentStep);
            setFormData(data.dataPayload || {});
          }
        }
      } catch {}
    }
    loadProgress();
  }, [agentId]);

  // Save progress on each step change
  const saveProgress = useCallback(async (step: number, data: Record<string, any>) => {
    try {
      await fetch('/api/onboarding/progress', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          agentId,
          currentStep: step,
          dataPayload: data,
          isComplete: false,
        }),
      });
    } catch {}
  }, [agentId]);

  if (!config) {
    return (
      <div className="min-h-screen bg-gray-950 flex items-center justify-center text-white">
        <div className="text-center">
          <p className="text-2xl mb-2">Agent not found</p>
          <a href="/onboarding" className="text-blue-400 hover:underline">Back to agent selection</a>
        </div>
      </div>
    );
  }

  const step = config.steps[currentStep];
  const totalSteps = config.steps.length;
  const progressPct = ((currentStep + 1) / totalSteps) * 100;

  // Advance to next step
  const handleNext = async () => {
    const nextStep = currentStep + 1;
    const nextStepDef = config.steps[nextStep];

    // Save progress
    await saveProgress(nextStep, formData);

    // If next step is 'verify', simulate AI processing
    if (nextStepDef?.type === 'verify') {
      setCurrentStep(nextStep);
      setIsProcessing(true);
      setVerifyProgress(0);

      // Simulate verification progress
      const interval = setInterval(() => {
        setVerifyProgress(prev => {
          if (prev >= 100) {
            clearInterval(interval);
            setIsProcessing(false);
            // Auto-advance past verify step after completion
            setTimeout(() => {
              setCurrentStep(nextStep + 1);
              saveProgress(nextStep + 1, formData);
            }, 800);
            return 100;
          }
          return prev + Math.random() * 15 + 5;
        });
      }, 400);
      return;
    }

    // If this is the last step (success), mark complete
    if (nextStep >= totalSteps) {
      await fetch('/api/onboarding/progress', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          agentId,
          currentStep: totalSteps,
          dataPayload: formData,
          isComplete: true,
        }),
      });

      // Get the live route from registry
      const registryRes = await fetch(`/api/agents?slug=${agentId}`);
      const registryData = registryRes.ok ? await registryRes.json() : null;
      const liveRoute = registryData?.liveRoute || `/agents/${agentId}`;
      router.push(liveRoute);
      return;
    }

    setCurrentStep(nextStep);
  };

  const handleFieldChange = (name: string, value: any) => {
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-950 via-gray-900 to-gray-950 text-white">
      <div className="max-w-2xl mx-auto px-6 py-12">

        {/* ── Header ── */}
        <div className="flex items-center gap-3 mb-8">
          <a href="/onboarding" className="text-gray-500 hover:text-white transition">←</a>
          <span className="text-2xl">{config.icon}</span>
          <div>
            <h1 className="text-xl font-bold">{config.agentName}</h1>
            <p className="text-xs text-gray-500">~{config.estimatedMinutes} min setup</p>
          </div>
        </div>

        {/* ── Progress Bar ── */}
        <div className="mb-8">
          <div className="flex justify-between text-xs text-gray-500 mb-1">
            <span>Step {Math.min(currentStep + 1, totalSteps)} of {totalSteps}</span>
            <span>{Math.round(progressPct)}%</span>
          </div>
          <div className="h-1.5 bg-gray-800 rounded-full overflow-hidden">
            <div
              className="h-full bg-gradient-to-r from-blue-500 to-blue-400 rounded-full transition-all duration-500"
              style={{ width: `${progressPct}%` }}
            />
          </div>
        </div>

        {/* ── Step Content ── */}
        <div className="bg-white/5 border border-white/10 rounded-2xl p-8">
          {step.type === 'form' && (
            <FormStep step={step} formData={formData} onChange={handleFieldChange} onNext={handleNext} />
          )}

          {step.type === 'integration' && (
            <IntegrationStep step={step} onNext={handleNext} />
          )}

          {step.type === 'upload' && (
            <UploadStep step={step} onNext={handleNext} />
          )}

          {step.type === 'verify' && (
            <VerifyStep step={step} progress={Math.min(verifyProgress, 100)} />
          )}

          {step.type === 'success' && (
            <SuccessStep step={step} agentName={config.agentName} onFinish={handleNext} />
          )}
        </div>
      </div>
    </div>
  );
}

// ── Step Components ─────────────────────────────────────────

function FormStep({ step, formData, onChange, onNext }: {
  step: OnboardingStep; formData: Record<string, any>;
  onChange: (name: string, value: any) => void; onNext: () => void;
}) {
  return (
    <>
      <h2 className="text-2xl font-bold mb-2">{step.title}</h2>
      <p className="text-gray-400 mb-6">{step.description}</p>
      <div className="space-y-4">
        {step.fields?.map((field) => (
          <div key={field.name}>
            <label className="block text-sm font-medium text-gray-300 mb-1">{field.label}</label>
            {field.type === 'select' ? (
              <select
                value={formData[field.name] || ''}
                onChange={(e) => onChange(field.name, e.target.value)}
                className="w-full px-4 py-2.5 bg-gray-800 border border-gray-700 rounded-lg text-white focus:border-blue-500 focus:ring-1 focus:ring-blue-500 outline-none"
              >
                <option value="">{field.placeholder || 'Select...'}</option>
                <option value={field.placeholder}>{field.placeholder}</option>
              </select>
            ) : field.type === 'checkbox' ? (
              <label className="flex items-center gap-2">
                <input
                  type="checkbox"
                  checked={formData[field.name] || false}
                  onChange={(e) => onChange(field.name, e.target.checked)}
                  className="rounded border-gray-700 bg-gray-800 text-blue-500"
                />
                <span className="text-sm text-gray-300">{field.label}</span>
              </label>
            ) : (
              <input
                type={field.type}
                value={formData[field.name] || ''}
                onChange={(e) => onChange(field.name, e.target.value)}
                placeholder={field.placeholder}
                className="w-full px-4 py-2.5 bg-gray-800 border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:border-blue-500 focus:ring-1 focus:ring-blue-500 outline-none"
              />
            )}
          </div>
        ))}
      </div>
      <button
        onClick={onNext}
        className="mt-6 w-full py-3 bg-blue-600 hover:bg-blue-500 text-white font-semibold rounded-xl transition"
      >
        Continue
      </button>
    </>
  );
}

function IntegrationStep({ step, onNext }: { step: OnboardingStep; onNext: () => void }) {
  const integrations: Record<string, { name: string; icon: string; color: string }> = {
    odoo: { name: 'Odoo ERP', icon: '🟣', color: 'purple' },
    hubspot: { name: 'HubSpot CRM', icon: '🟠', color: 'orange' },
    google: { name: 'Google', icon: '🔵', color: 'blue' },
  };
  const integration = integrations[step.integrationKey || ''] || integrations.odoo;

  return (
    <>
      <h2 className="text-2xl font-bold mb-2">{step.title}</h2>
      <p className="text-gray-400 mb-6">{step.description}</p>

      <button
        onClick={onNext}
        className="w-full p-4 bg-gray-800 border border-gray-700 rounded-xl hover:border-blue-500 transition flex items-center gap-4"
      >
        <span className="text-2xl">{integration.icon}</span>
        <div className="text-left">
          <p className="font-semibold text-white">Connect {integration.name}</p>
          <p className="text-xs text-gray-500">OAuth · Secure · Read-only access</p>
        </div>
      </button>

      <button
        onClick={onNext}
        className="mt-3 w-full py-2 text-sm text-gray-500 hover:text-gray-300 transition"
      >
        Skip for now →
      </button>
    </>
  );
}

function UploadStep({ step, onNext }: { step: OnboardingStep; onNext: () => void }) {
  const [fileName, setFileName] = useState('');

  return (
    <>
      <h2 className="text-2xl font-bold mb-2">{step.title}</h2>
      <p className="text-gray-400 mb-6">{step.description}</p>

      <label className="block w-full p-8 border-2 border-dashed border-gray-700 rounded-xl text-center hover:border-blue-500 transition cursor-pointer">
        <input
          type="file"
          accept=".csv,.xlsx,.xls,.pdf"
          className="hidden"
          onChange={(e) => {
            const file = e.target.files?.[0];
            if (file) setFileName(file.name);
          }}
        />
        {fileName ? (
          <div>
            <p className="text-green-400 text-lg mb-1">✓ {fileName}</p>
            <p className="text-xs text-gray-500">Click to change file</p>
          </div>
        ) : (
          <div>
            <p className="text-gray-400 text-lg mb-1">Drop file here or click to browse</p>
            <p className="text-xs text-gray-500">Supports CSV, XLSX, PDF</p>
          </div>
        )}
      </label>

      <button
        onClick={onNext}
        disabled={!fileName}
        className="mt-6 w-full py-3 bg-blue-600 hover:bg-blue-500 disabled:opacity-40 disabled:cursor-not-allowed text-white font-semibold rounded-xl transition"
      >
        Upload & Continue
      </button>

      <button onClick={onNext} className="mt-2 w-full py-2 text-sm text-gray-500 hover:text-gray-300 transition">
        Skip for now →
      </button>
    </>
  );
}

function VerifyStep({ step, progress }: { step: OnboardingStep; progress: number }) {
  return (
    <div className="text-center py-8">
      <div className="text-4xl mb-4 animate-pulse">🤖</div>
      <h2 className="text-2xl font-bold mb-2">{step.title}</h2>
      <p className="text-gray-400 mb-6">{step.description}</p>
      <div className="max-w-xs mx-auto">
        <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
          <div
            className="h-full bg-gradient-to-r from-blue-500 via-purple-500 to-blue-400 rounded-full transition-all duration-300"
            style={{ width: `${progress}%` }}
          />
        </div>
        <p className="text-xs text-gray-500 mt-2">{Math.round(progress)}% complete</p>
      </div>
    </div>
  );
}

function SuccessStep({ step, agentName, onFinish }: {
  step: OnboardingStep; agentName: string; onFinish: () => void;
}) {
  return (
    <div className="text-center py-4">
      <div className="text-5xl mb-4">🎉</div>
      <h2 className="text-2xl font-bold mb-3">{agentName} is Ready</h2>
      <div className="bg-blue-500/10 border border-blue-500/30 rounded-xl p-4 mb-6">
        <p className="text-blue-300 text-sm leading-relaxed">{step.ahaMessage}</p>
      </div>
      <button
        onClick={onFinish}
        className="w-full py-3 bg-gradient-to-r from-blue-600 to-blue-500 hover:from-blue-500 hover:to-blue-400 text-white font-semibold rounded-xl transition shadow-lg shadow-blue-500/20"
      >
        Enter Live Dashboard →
      </button>
    </div>
  );
}
