'use client';
// ============================================================
// /onboarding — Agent Selection Entry Hall
// Generated by install-onboarding.js
// ============================================================
// Shows all available agents as cards. User clicks one to begin
// the adaptive wizard for that specific agent.

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import { ONBOARDING_CONFIGS, type AgentOnboardingConfig } from '@/lib/onboarding/agent-steps';

export default function OnboardingEntryPage() {
  const searchParams = useSearchParams();
  const preselected = searchParams?.get('agent');

  // If ?agent=cfo is in URL, redirect to that wizard directly
  useEffect(() => {
    if (preselected && ONBOARDING_CONFIGS[preselected]) {
      window.location.href = `/onboarding/${preselected}`;
    }
  }, [preselected]);

  const saasAgents = Object.values(ONBOARDING_CONFIGS).filter(a => a.category === 'saas');
  const threePlAgents = Object.values(ONBOARDING_CONFIGS).filter(a => a.category === '3pl');

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-950 via-gray-900 to-gray-950 text-white">
      <div className="max-w-5xl mx-auto px-6 py-16">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold mb-3">
            Welcome to Woulf<span className="text-blue-400">AI</span>
          </h1>
          <p className="text-gray-400 text-lg max-w-2xl mx-auto">
            Select the agent you want to activate. Each wizard takes under 10 minutes
            and ends with real AI-powered insights from your data.
          </p>
        </div>

        {/* SaaS Agents */}
        <div className="mb-12">
          <h2 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4 px-1">
            Business Agents
          </h2>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            {saasAgents.map((agent) => (
              <AgentCard key={agent.agentId} agent={agent} />
            ))}
          </div>
        </div>

        {/* 3PL Agents */}
        {threePlAgents.length > 0 && (
          <div>
            <h2 className="text-sm font-bold text-gray-500 uppercase tracking-wider mb-4 px-1">
              Warehouse / 3PL
            </h2>
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
              {threePlAgents.map((agent) => (
                <AgentCard key={agent.agentId} agent={agent} />
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function AgentCard({ agent }: { agent: AgentOnboardingConfig }) {
  return (
    <Link
      href={`/onboarding/${agent.agentId}`}
      className="group p-5 bg-white/5 border border-white/10 rounded-2xl hover:bg-white/10 hover:border-blue-500/40 transition-all"
    >
      <div className="text-3xl mb-3">{agent.icon}</div>
      <h3 className="font-semibold text-white group-hover:text-blue-400 transition">
        {agent.agentName}
      </h3>
      <p className="text-xs text-gray-500 mt-1">
        {agent.steps.length} steps · ~{agent.estimatedMinutes} min
      </p>
    </Link>
  );
}
