'use client';
// ============================================================
// TenantSwitcher — Header Quick Switch Component
// Generated by install-onboarding.js
// ============================================================
// Rewired from Gemini's version to use the useTenant() hook
// from tenant-provider.tsx instead of window.dispatchEvent.

import React, { useState } from 'react';
import { useTenant } from '@/lib/providers/tenant-provider';

export default function TenantSwitcher() {
  const { currentCompany, companies, switchCompany, isLoading } = useTenant();
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="relative inline-block text-left z-50">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex items-center gap-3 px-4 py-2 bg-white/5 border border-white/10 rounded-xl hover:bg-white/10 transition-all text-white"
      >
        <div className="w-8 h-8 rounded-lg flex items-center justify-center bg-gradient-to-br from-blue-500 to-indigo-600 text-white text-sm font-bold">
          {currentCompany?.name?.charAt(0) || 'W'}
        </div>
        <div className="text-left hidden md:block">
          <p className="text-[10px] text-gray-400 uppercase font-bold tracking-wider leading-none mb-1">
            Active Business
          </p>
          <p className="text-sm font-semibold leading-none">
            {isLoading ? 'Loading...' : currentCompany?.name || 'Select Company'}
          </p>
        </div>
        <svg
          className={`w-4 h-4 text-gray-400 transition-transform ${isOpen ? 'rotate-180' : ''}`}
          fill="none" stroke="currentColor" viewBox="0 0 24 24"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>

      {isOpen && (
        <>
          <div className="fixed inset-0" onClick={() => setIsOpen(false)} />
          <div className="absolute left-0 mt-2 w-64 bg-gray-900 border border-white/10 rounded-2xl shadow-2xl overflow-hidden z-50">
            <div className="p-2 space-y-1">
              {companies.map((company) => (
                <button
                  key={company.id}
                  onClick={() => {
                    switchCompany(company.id);
                    setIsOpen(false);
                  }}
                  className={`w-full flex items-center justify-between p-3 rounded-xl transition-all ${
                    company.id === currentCompany?.id
                      ? 'bg-blue-500/10 text-blue-400'
                      : 'hover:bg-white/5 text-gray-400 hover:text-white'
                  }`}
                >
                  <span className="text-sm font-medium">{company.name}</span>
                  {company.id === currentCompany?.id && (
                    <span className="text-blue-400">✓</span>
                  )}
                </button>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}
