'use client';
// ============================================================
// MagicMapper — AI-Powered CSV Column Mapper
// Generated by install-onboarding.js
// ============================================================
// Replaces Gemini's placeholder with functional mapping UI.
// Accepts CSV upload, detects columns, lets user confirm mapping.

import React, { useState, useCallback } from 'react';

interface ColumnMapping {
  sourceColumn: string;
  targetField: string;
  confidence: number; // 0-100
}

interface Props {
  targetFields: { key: string; label: string; required?: boolean }[];
  onComplete: (mappedData: Record<string, any>[]) => void;
  agentType?: string; // 'wms' | 'hr' etc
}

// AI guessing logic — maps common column names to our schema
const FIELD_ALIASES: Record<string, string[]> = {
  sku: ['sku', 'item', 'item_number', 'part', 'part_number', 'product_code', 'upc', 'barcode'],
  name: ['name', 'product', 'product_name', 'description', 'item_name', 'title', 'first_name', 'employee_name', 'full_name'],
  quantity: ['qty', 'quantity', 'count', 'on_hand', 'stock', 'available', 'units'],
  location: ['location', 'bin', 'zone', 'warehouse', 'aisle', 'rack', 'shelf', 'bay'],
  email: ['email', 'email_address', 'e_mail', 'contact_email'],
  phone: ['phone', 'telephone', 'mobile', 'cell', 'contact_phone'],
  department: ['department', 'dept', 'division', 'team', 'group'],
  role: ['role', 'title', 'job_title', 'position', 'designation'],
  startDate: ['start_date', 'hire_date', 'join_date', 'date_hired', 'employment_date'],
  weight: ['weight', 'wt', 'lbs', 'kg', 'mass'],
  price: ['price', 'cost', 'unit_price', 'rate', 'amount'],
};

function guessMapping(header: string, targetFields: { key: string }[]): { field: string; confidence: number } {
  const normalized = header.toLowerCase().replace(/[^a-z0-9]/g, '_').trim();

  for (const [targetKey, aliases] of Object.entries(FIELD_ALIASES)) {
    if (targetFields.some(f => f.key === targetKey)) {
      if (aliases.includes(normalized)) {
        return { field: targetKey, confidence: 95 };
      }
      if (aliases.some(a => normalized.includes(a) || a.includes(normalized))) {
        return { field: targetKey, confidence: 75 };
      }
    }
  }

  return { field: '', confidence: 0 };
}

export default function MagicMapper({ targetFields, onComplete, agentType }: Props) {
  const [rawData, setRawData] = useState<string[][]>([]);
  const [headers, setHeaders] = useState<string[]>([]);
  const [mappings, setMappings] = useState<ColumnMapping[]>([]);
  const [fileName, setFileName] = useState('');
  const [step, setStep] = useState<'upload' | 'map' | 'confirm'>('upload');

  const parseCSV = useCallback((text: string) => {
    const rows = text.split('\n').filter(r => r.trim());
    const headerRow = rows[0].split(',').map(h => h.trim().replace(/"/g, ''));
    const dataRows = rows.slice(1).map(r => r.split(',').map(c => c.trim().replace(/"/g, '')));

    setHeaders(headerRow);
    setRawData(dataRows);

    // Auto-guess mappings
    const autoMappings = headerRow.map(h => {
      const guess = guessMapping(h, targetFields);
      return {
        sourceColumn: h,
        targetField: guess.field,
        confidence: guess.confidence,
      };
    });

    setMappings(autoMappings);
    setStep('map');
  }, [targetFields]);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setFileName(file.name);

    const reader = new FileReader();
    reader.onload = (evt) => {
      const text = evt.target?.result as string;
      parseCSV(text);
    };
    reader.readAsText(file);
  };

  const handleMappingChange = (sourceCol: string, targetField: string) => {
    setMappings(prev => prev.map(m =>
      m.sourceColumn === sourceCol ? { ...m, targetField, confidence: 100 } : m
    ));
  };

  const handleConfirm = () => {
    // Transform raw data using mappings
    const mapped = rawData.map(row => {
      const obj: Record<string, any> = {};
      mappings.forEach((mapping, i) => {
        if (mapping.targetField && i < row.length) {
          obj[mapping.targetField] = row[i];
        }
      });
      return obj;
    }).filter(obj => Object.keys(obj).length > 0);

    onComplete(mapped);
  };

  // ── Upload Step ──
  if (step === 'upload') {
    return (
      <label className="block w-full p-8 border-2 border-dashed border-gray-700 rounded-xl text-center hover:border-blue-500 transition cursor-pointer">
        <input type="file" accept=".csv" className="hidden" onChange={handleFileUpload} />
        <p className="text-gray-400 text-lg mb-1">Drop CSV file or click to browse</p>
        <p className="text-xs text-gray-600">We'll automatically detect your columns</p>
      </label>
    );
  }

  // ── Mapping Step ──
  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <div>
          <h3 className="font-semibold text-white">Column Mapping</h3>
          <p className="text-xs text-gray-500">{fileName} · {rawData.length} rows detected</p>
        </div>
        <div className="text-xs text-green-400">
          {mappings.filter(m => m.confidence >= 75).length}/{targetFields.length} auto-mapped
        </div>
      </div>

      <div className="space-y-2 max-h-64 overflow-y-auto">
        {mappings.map((mapping) => (
          <div key={mapping.sourceColumn} className="flex items-center gap-3 p-2 bg-gray-800/50 rounded-lg">
            <span className="text-sm text-gray-400 w-32 truncate font-mono">{mapping.sourceColumn}</span>
            <span className="text-gray-600">→</span>
            <select
              value={mapping.targetField}
              onChange={(e) => handleMappingChange(mapping.sourceColumn, e.target.value)}
              className="flex-1 px-3 py-1.5 bg-gray-800 border border-gray-700 rounded text-sm text-white"
            >
              <option value="">Skip this column</option>
              {targetFields.map(f => (
                <option key={f.key} value={f.key}>{f.label}{f.required ? ' *' : ''}</option>
              ))}
            </select>
            {mapping.confidence >= 75 && (
              <span className="text-green-400 text-xs">AI ✓</span>
            )}
          </div>
        ))}
      </div>

      {/* Preview */}
      {rawData.length > 0 && (
        <div className="mt-4 p-3 bg-gray-900 rounded-lg overflow-x-auto">
          <p className="text-xs text-gray-500 mb-2">Preview (first 3 rows):</p>
          <table className="text-xs text-gray-400">
            <thead>
              <tr>
                {mappings.filter(m => m.targetField).map(m => (
                  <th key={m.targetField} className="pr-4 text-left text-blue-400">{m.targetField}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rawData.slice(0, 3).map((row, i) => (
                <tr key={i}>
                  {mappings.filter(m => m.targetField).map((m) => {
                    const colIdx = headers.indexOf(m.sourceColumn);
                    return <td key={m.targetField} className="pr-4">{row[colIdx] || '—'}</td>;
                  })}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      <button
        onClick={handleConfirm}
        className="mt-4 w-full py-3 bg-blue-600 hover:bg-blue-500 text-white font-semibold rounded-xl transition"
      >
        Confirm Mapping & Import {rawData.length} rows
      </button>
    </div>
  );
}
