// ============================================================
// WoulfAI — Per-Agent Onboarding Step Configurations
// Generated by install-onboarding.js
// ============================================================
// Each agent defines its own onboarding "sprint" — the minimum
// steps to get real data flowing and deliver the "Aha Moment."

export interface OnboardingStep {
  id: string;
  title: string;
  description: string;
  type: 'form' | 'integration' | 'upload' | 'verify' | 'success';
  fields?: { name: string; label: string; type: string; required?: boolean; placeholder?: string }[];
  integrationKey?: string; // 'odoo' | 'hubspot' | 'google' | 'csv'
  ahaMessage?: string;
}

export interface AgentOnboardingConfig {
  agentId: string;
  agentName: string;
  icon: string;
  category: 'saas' | '3pl';
  estimatedMinutes: number;
  steps: OnboardingStep[];
}

export const ONBOARDING_CONFIGS: Record<string, AgentOnboardingConfig> = {
  // ── FINANCE ──────────────────────────────────────────────
  cfo: {
    agentId: 'cfo',
    agentName: 'CFO Agent',
    icon: '💰',
    category: 'saas',
    estimatedMinutes: 8,
    steps: [
      {
        id: 'company-info',
        title: 'Company Financials',
        description: 'Tell us about your fiscal setup so the AI can calibrate.',
        type: 'form',
        fields: [
          { name: 'fiscalYearStart', label: 'Fiscal Year Start', type: 'select', required: true, placeholder: 'January' },
          { name: 'currency', label: 'Primary Currency', type: 'select', required: true, placeholder: 'USD' },
          { name: 'taxId', label: 'Tax ID / EIN', type: 'text', placeholder: 'XX-XXXXXXX' },
        ],
      },
      {
        id: 'connect-erp',
        title: 'Connect Your Books',
        description: 'Link your accounting system so the CFO Agent sees real numbers.',
        type: 'integration',
        integrationKey: 'odoo',
      },
      {
        id: 'verify-data',
        title: 'Verifying Connection',
        description: 'AI is scanning your financial data...',
        type: 'verify',
      },
      {
        id: 'aha-moment',
        title: 'Your First Insight',
        description: '',
        type: 'success',
        ahaMessage: "We\'ve identified overdue payments in your receivables. Click \'Send Reminders\' to collect.",
      },
    ],
  },

  finops: {
    agentId: 'finops',
    agentName: 'FinOps Agent',
    icon: '📊',
    category: 'saas',
    estimatedMinutes: 6,
    steps: [
      {
        id: 'connect-erp',
        title: 'Connect Your ERP',
        description: 'Link to your accounting system for AP/AR analysis.',
        type: 'integration',
        integrationKey: 'odoo',
      },
      {
        id: 'verify-data',
        title: 'Scanning Financial Operations',
        description: 'AI is analyzing AP, debt, and labor patterns...',
        type: 'verify',
      },
      {
        id: 'aha-moment',
        title: 'Operations Snapshot',
        description: '',
        type: 'success',
        ahaMessage: "Your AP aging shows 3 vendors past 60 days. FinOps has drafted payment priority recommendations.",
      },
    ],
  },

  payables: {
    agentId: 'payables',
    agentName: 'Payables Agent',
    icon: '🧾',
    category: 'saas',
    estimatedMinutes: 5,
    steps: [
      {
        id: 'connect-erp',
        title: 'Connect AP System',
        description: 'Link to Odoo or upload recent invoices.',
        type: 'integration',
        integrationKey: 'odoo',
      },
      {
        id: 'aha-moment',
        title: 'Invoice Intelligence',
        description: '',
        type: 'success',
        ahaMessage: "Payables Agent found duplicate invoices and flagged 2 for review. Your approval queue is ready.",
      },
    ],
  },

  collections: {
    agentId: 'collections',
    agentName: 'Collections Agent',
    icon: '📞',
    category: 'saas',
    estimatedMinutes: 5,
    steps: [
      {
        id: 'connect-erp',
        title: 'Connect Receivables',
        description: 'Link your AR data to activate AI collections.',
        type: 'integration',
        integrationKey: 'odoo',
      },
      {
        id: 'aha-moment',
        title: 'Collections Ready',
        description: '',
        type: 'success',
        ahaMessage: "4-tier escalation engine activated. 5 accounts identified for immediate outreach.",
      },
    ],
  },

  // ── SALES & MARKETING ───────────────────────────────────
  sales: {
    agentId: 'sales',
    agentName: 'Sales Agent',
    icon: '🎯',
    category: 'saas',
    estimatedMinutes: 7,
    steps: [
      {
        id: 'crm-type',
        title: 'Your CRM',
        description: 'Which CRM does your team use?',
        type: 'form',
        fields: [
          { name: 'crmType', label: 'CRM Platform', type: 'select', required: true, placeholder: 'HubSpot' },
        ],
      },
      {
        id: 'connect-crm',
        title: 'Connect Your Pipeline',
        description: 'Sync your deals, contacts, and activities.',
        type: 'integration',
        integrationKey: 'hubspot',
      },
      {
        id: 'verify-data',
        title: 'Importing Pipeline',
        description: 'AI is analyzing your deals and building behavioral profiles...',
        type: 'verify',
      },
      {
        id: 'aha-moment',
        title: 'Pipeline Intelligence',
        description: '',
        type: 'success',
        ahaMessage: "Your pipeline is synced. 3 deals flagged as \'High Risk\' based on behavioral analysis. View your Battle Cards now.",
      },
    ],
  },

  seo: {
    agentId: 'seo',
    agentName: 'SEO Agent',
    icon: '🔍',
    category: 'saas',
    estimatedMinutes: 5,
    steps: [
      {
        id: 'website-url',
        title: 'Your Website',
        description: 'Enter your URL and we\'ll start crawling immediately.',
        type: 'form',
        fields: [
          { name: 'websiteUrl', label: 'Website URL', type: 'url', required: true, placeholder: 'https://yoursite.com' },
          { name: 'targetRegion', label: 'Target Region', type: 'select', placeholder: 'United States' },
        ],
      },
      {
        id: 'connect-gsc',
        title: 'Google Search Console',
        description: 'Optional: Connect GSC for real ranking data.',
        type: 'integration',
        integrationKey: 'google',
      },
      {
        id: 'aha-moment',
        title: 'SEO Snapshot',
        description: '',
        type: 'success',
        ahaMessage: "We found 12 high-intent keywords you\'re not ranking for. Click \'Publish\' to generate optimized content.",
      },
    ],
  },

  marketing: {
    agentId: 'marketing',
    agentName: 'Marketing Agent',
    icon: '📣',
    category: 'saas',
    estimatedMinutes: 6,
    steps: [
      {
        id: 'marketing-setup',
        title: 'Marketing Channels',
        description: 'Tell us about your marketing stack.',
        type: 'form',
        fields: [
          { name: 'websiteUrl', label: 'Website URL', type: 'url', required: true, placeholder: 'https://yoursite.com' },
          { name: 'monthlyBudget', label: 'Monthly Ad Budget', type: 'number', placeholder: '5000' },
        ],
      },
      {
        id: 'connect-analytics',
        title: 'Connect Analytics',
        description: 'Link Google Analytics or your ad accounts.',
        type: 'integration',
        integrationKey: 'google',
      },
      {
        id: 'aha-moment',
        title: 'Marketing Intelligence',
        description: '',
        type: 'success',
        ahaMessage: "Campaign analysis complete. Shifting budget to Google Search could increase ROI by 3x. View recommendations.",
      },
    ],
  },

  // ── OPERATIONS ──────────────────────────────────────────
  'org-lead': {
    agentId: 'org-lead',
    agentName: 'Organization Lead',
    icon: '🏢',
    category: 'saas',
    estimatedMinutes: 5,
    steps: [
      {
        id: 'org-setup',
        title: 'Your Organization',
        description: 'Set up your command center.',
        type: 'form',
        fields: [
          { name: 'orgName', label: 'Organization Name', type: 'text', required: true },
          { name: 'teamSize', label: 'Team Size', type: 'number', placeholder: '25' },
          { name: 'industry', label: 'Industry', type: 'select', placeholder: 'Logistics' },
        ],
      },
      {
        id: 'aha-moment',
        title: 'Command Center Ready',
        description: '',
        type: 'success',
        ahaMessage: "Your Organization Lead dashboard is live. As you activate more agents, KPIs will flow here automatically.",
      },
    ],
  },

  wms: {
    agentId: 'wms',
    agentName: 'WMS Agent',
    icon: '📦',
    category: 'saas',
    estimatedMinutes: 10,
    steps: [
      {
        id: 'warehouse-setup',
        title: 'Warehouse Profile',
        description: 'Tell us about your facility.',
        type: 'form',
        fields: [
          { name: 'warehouseName', label: 'Warehouse Name', type: 'text', required: true },
          { name: 'zones', label: 'Number of Zones', type: 'number', placeholder: '4' },
          { name: 'wmsSystem', label: 'Current WMS', type: 'select', placeholder: 'None / Manual' },
        ],
      },
      {
        id: 'upload-inventory',
        title: 'Upload Inventory',
        description: 'Drop your inventory file and AI will map the columns.',
        type: 'upload',
        integrationKey: 'csv',
      },
      {
        id: 'verify-data',
        title: 'Processing Inventory',
        description: 'AI is mapping SKUs, quantities, and locations...',
        type: 'verify',
      },
      {
        id: 'aha-moment',
        title: 'Warehouse Live',
        description: '',
        type: 'success',
        ahaMessage: "Inventory imported. SKU-A102 is below reorder point. Draft a PO now?",
      },
    ],
  },

  hr: {
    agentId: 'hr',
    agentName: 'HR Agent',
    icon: '👥',
    category: 'saas',
    estimatedMinutes: 7,
    steps: [
      {
        id: 'hr-setup',
        title: 'HR Basics',
        description: 'Configure your HR profile.',
        type: 'form',
        fields: [
          { name: 'payrollSystem', label: 'Payroll System', type: 'select', placeholder: 'Gusto' },
          { name: 'ptoPolicy', label: 'PTO Days/Year', type: 'number', placeholder: '15' },
        ],
      },
      {
        id: 'upload-roster',
        title: 'Employee Roster',
        description: 'Upload your team list (CSV) or connect your payroll.',
        type: 'upload',
        integrationKey: 'csv',
      },
      {
        id: 'aha-moment',
        title: 'HR Intelligence Active',
        description: '',
        type: 'success',
        ahaMessage: "Employee roster imported. 2 new hires need onboarding checklists — I\'ve drafted them for you.",
      },
    ],
  },

  operations: {
    agentId: 'operations',
    agentName: 'Operations Agent',
    icon: '⚙️',
    category: 'saas',
    estimatedMinutes: 6,
    steps: [
      {
        id: 'ops-setup',
        title: 'Active Projects',
        description: 'What projects is your team running?',
        type: 'form',
        fields: [
          { name: 'projectName', label: 'First Project Name', type: 'text', required: true, placeholder: 'Warehouse Install - Building C' },
          { name: 'crewSize', label: 'Crew Size', type: 'number', placeholder: '8' },
          { name: 'targetDate', label: 'Target Completion', type: 'date' },
        ],
      },
      {
        id: 'aha-moment',
        title: 'Operations Tracking Live',
        description: '',
        type: 'success',
        ahaMessage: "Project created. Your Operations Command Center is tracking timelines, crew, and resources.",
      },
    ],
  },

  legal: {
    agentId: 'legal',
    agentName: 'Legal Agent',
    icon: '⚖️',
    category: 'saas',
    estimatedMinutes: 5,
    steps: [
      {
        id: 'upload-contracts',
        title: 'Upload Contracts',
        description: 'Drop your top 3-5 contracts (PDF). AI will scan for key terms.',
        type: 'upload',
        integrationKey: 'csv',
      },
      {
        id: 'verify-data',
        title: 'Analyzing Contracts',
        description: 'AI is extracting dates, terms, renewal windows, and risk clauses...',
        type: 'verify',
      },
      {
        id: 'aha-moment',
        title: 'Contract Intelligence',
        description: '',
        type: 'success',
        ahaMessage: "5 contracts analyzed. Warning: One subcontractor agreement has an unfavorable indemnification clause. Review now.",
      },
    ],
  },

  compliance: {
    agentId: 'compliance',
    agentName: 'Compliance Agent',
    icon: '🛡️',
    category: 'saas',
    estimatedMinutes: 5,
    steps: [
      {
        id: 'compliance-setup',
        title: 'Regulatory Framework',
        description: 'Which regulations apply to your business?',
        type: 'form',
        fields: [
          { name: 'industry', label: 'Industry', type: 'select', required: true, placeholder: 'Logistics' },
          { name: 'regulations', label: 'Key Regulations', type: 'text', placeholder: 'OSHA, DOT, FDA' },
        ],
      },
      {
        id: 'aha-moment',
        title: 'Compliance Calendar Active',
        description: '',
        type: 'success',
        ahaMessage: "Compliance calendar initialized. 2 certification renewals due within 30 days. Training links drafted.",
      },
    ],
  },

  'supply-chain': {
    agentId: 'supply-chain',
    agentName: 'Supply Chain Agent',
    icon: '🚛',
    category: 'saas',
    estimatedMinutes: 6,
    steps: [
      {
        id: 'connect-procurement',
        title: 'Connect Procurement',
        description: 'Link your purchasing system for vendor intelligence.',
        type: 'integration',
        integrationKey: 'odoo',
      },
      {
        id: 'aha-moment',
        title: 'Supply Chain Intelligence',
        description: '',
        type: 'success',
        ahaMessage: "Vendor scorecards generated. 2 suppliers flagged for late delivery patterns. View optimization recommendations.",
      },
    ],
  },

  // ── 3PL CUSTOMER PORTAL ─────────────────────────────────
  'customer-portal': {
    agentId: 'customer-portal',
    agentName: 'Customer Portal',
    icon: '🏭',
    category: '3pl',
    estimatedMinutes: 15,
    steps: [
      {
        id: 'rate-card',
        title: 'Rate Card Agreement',
        description: 'Review and digitally sign your rate card.',
        type: 'form',
        fields: [
          { name: 'companyName', label: 'Company Name', type: 'text', required: true },
          { name: 'contactName', label: 'Primary Contact', type: 'text', required: true },
          { name: 'contactEmail', label: 'Contact Email', type: 'email', required: true },
          { name: 'rateCardAccepted', label: 'I accept the rate card terms', type: 'checkbox', required: true },
        ],
      },
      {
        id: 'upload-item-master',
        title: 'Item Master Upload',
        description: 'Upload your SKU list. AI will map columns automatically.',
        type: 'upload',
        integrationKey: 'csv',
      },
      {
        id: 'first-asn',
        title: 'Schedule First Shipment',
        description: 'Create your first Advance Shipping Notice (ASN).',
        type: 'form',
        fields: [
          { name: 'carrierName', label: 'Carrier', type: 'text', required: true, placeholder: 'FedEx Freight' },
          { name: 'estimatedArrival', label: 'Expected Arrival', type: 'date', required: true },
          { name: 'palletCount', label: 'Pallet Count', type: 'number', required: true },
        ],
      },
      {
        id: 'aha-moment',
        title: 'Portal Activated',
        description: '',
        type: 'success',
        ahaMessage: "Your portal is live. First inbound shipment is scheduled. Track inventory, orders, and billing in real time.",
      },
    ],
  },
};

export function getOnboardingConfig(agentId: string): AgentOnboardingConfig | undefined {
  return ONBOARDING_CONFIGS[agentId];
}

export function getAllAgentIds(): string[] {
  return Object.keys(ONBOARDING_CONFIGS);
}
