// ============================================================
// GET/POST /api/agents/[slug] — Generic Agent Data API
// Generated by deploy-5-agents.js
// ============================================================
// Reads/writes agent-specific data filtered by companyId.
// Works for ALL agents via the slug parameter.

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// Table mapping per agent slug
const AGENT_TABLES: Record<string, string> = {
  'org-lead': 'agent_org_lead_data',
  'seo': 'agent_seo_data',
  'marketing': 'agent_marketing_data',
  'wms': 'agent_wms_data',
  'hr': 'agent_hr_data',
  'cfo': 'agent_cfo_data',
  'sales': 'agent_sales_data',
  'operations': 'agent_operations_data',
  'legal': 'agent_legal_data',
  'compliance': 'agent_compliance_data',
  'supply-chain': 'agent_supply_chain_data',
  'finops': 'agent_finops_data',
  'payables': 'agent_payables_data',
  'collections': 'agent_collections_data',
};

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;
  const companyId = request.nextUrl.searchParams.get('companyId');

  if (!companyId) {
    return NextResponse.json({ error: 'companyId required' }, { status: 400 });
  }

  const table = AGENT_TABLES[slug];
  if (!table) {
    return NextResponse.json({ error: `Unknown agent: ${slug}` }, { status: 404 });
  }

  try {
    // Fetch KPIs
    const { data: kpiRows } = await supabase
      .from(`${table}_kpis`)
      .select('*')
      .eq('company_id', companyId)
      .order('created_at', { ascending: false })
      .limit(1);

    // Fetch data rows
    const { data: dataRows } = await supabase
      .from(table)
      .select('*')
      .eq('company_id', companyId)
      .order('created_at', { ascending: false })
      .limit(100);

    return NextResponse.json({
      kpis: kpiRows?.[0]?.data || {},
      data: dataRows || [],
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;
  const body = await request.json();
  const { companyId, data } = body;

  if (!companyId) {
    return NextResponse.json({ error: 'companyId required' }, { status: 400 });
  }

  const table = AGENT_TABLES[slug];
  if (!table) {
    return NextResponse.json({ error: `Unknown agent: ${slug}` }, { status: 404 });
  }

  try {
    const { error } = await supabase
      .from(table)
      .insert({
        company_id: companyId,
        data: data,
        created_at: new Date().toISOString(),
      });

    if (error) throw error;

    return NextResponse.json({ success: true });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
