'use client';
// ============================================================
// WoulfAI Agent Dashboard Shell
// Generated by deploy-5-agents.js
// ============================================================
// Wraps every agent page with:
//   - Header (agent name, status badge)
//   - Action bar (Submit, Edit, Download buttons)
//   - Empty state when no data
//   - Locked state when agent not purchased
//   - Company-aware data context

import React, { ReactNode, useState } from 'react';
import { useTenant } from '@/lib/providers/tenant-provider';
import type { AgentDefinition } from '@/lib/hooks/useAgents';

interface Props {
  agent: AgentDefinition;
  children: ReactNode;
  hasData?: boolean;
  onSubmit?: () => Promise<void>;
  onEdit?: () => void;
  onDownload?: () => Promise<void>;
  isLocked?: boolean;
}

export default function AgentDashboardShell({
  agent,
  children,
  hasData = true,
  onSubmit,
  onEdit,
  onDownload,
  isLocked = false,
}: Props) {
  const { currentCompany } = useTenant();
  const [actionLoading, setActionLoading] = useState<string | null>(null);

  const handleAction = async (action: string, fn?: () => Promise<void>) => {
    if (!fn) return;
    setActionLoading(action);
    try {
      await fn();
    } catch (err) {
      console.error(`${action} failed:`, err);
    } finally {
      setActionLoading(null);
    }
  };

  // ── Locked State ──
  if (isLocked) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-8">
        <div className="max-w-md text-center">
          <div className="text-6xl mb-4">{agent.icon}</div>
          <h2 className="text-2xl font-bold text-gray-900 mb-2">{agent.name}</h2>
          <p className="text-gray-600 mb-6">{agent.description}</p>
          <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 mb-6">
            <p className="text-amber-800 text-sm">
              This agent requires an active subscription. Contact your admin or upgrade your plan.
            </p>
          </div>
          <a
            href="/pricing"
            className="inline-flex items-center px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
          >
            View Plans
          </a>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* ── Header ── */}
      <div className="bg-white border-b px-6 py-4">
        <div className="flex items-center justify-between max-w-7xl mx-auto">
          <div className="flex items-center gap-3">
            <span className="text-3xl">{agent.icon}</span>
            <div>
              <h1 className="text-xl font-bold text-gray-900">{agent.name}</h1>
              <p className="text-sm text-gray-500">
                {currentCompany ? currentCompany.name : 'No company selected'}
              </p>
            </div>
            <span className="ml-2 px-2 py-0.5 text-xs font-medium rounded-full bg-green-100 text-green-800">
              LIVE
            </span>
          </div>

          {/* ── Action Buttons ── */}
          <div className="flex items-center gap-2">
            {onSubmit && (
              <button
                onClick={() => handleAction('submit', onSubmit)}
                disabled={actionLoading === 'submit'}
                className="px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg hover:bg-blue-700 disabled:opacity-50 transition"
              >
                {actionLoading === 'submit' ? 'Saving...' : 'Submit'}
              </button>
            )}
            {onEdit && (
              <button
                onClick={onEdit}
                className="px-4 py-2 bg-white border border-gray-300 text-gray-700 text-sm font-medium rounded-lg hover:bg-gray-50 transition"
              >
                Edit
              </button>
            )}
            {onDownload && (
              <button
                onClick={() => handleAction('download', onDownload)}
                disabled={actionLoading === 'download'}
                className="px-4 py-2 bg-white border border-gray-300 text-gray-700 text-sm font-medium rounded-lg hover:bg-gray-50 transition"
              >
                {actionLoading === 'download' ? 'Exporting...' : 'Download'}
              </button>
            )}
          </div>
        </div>
      </div>

      {/* ── Content ── */}
      <div className="max-w-7xl mx-auto px-6 py-6">
        {hasData ? (
          children
        ) : (
          /* ── Empty State ── */
          <div className="flex flex-col items-center justify-center py-24 text-center">
            <div className="text-6xl mb-4 opacity-40">{agent.icon}</div>
            <h3 className="text-lg font-semibold text-gray-700 mb-2">
              No data yet
            </h3>
            <p className="text-gray-500 max-w-sm mb-6">
              {agent.emptyStateMessage}
            </p>
            <button
              onClick={onEdit}
              className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
            >
              Get Started
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
