// ============================================================
// GET/POST /api/onboarding/progress — Save & Resume Wizard
// Generated by install-onboarding.js
// ============================================================

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { cookies } from 'next/headers';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function GET(request: NextRequest) {
  const agentId = request.nextUrl.searchParams.get('agentId');
  const cookieStore = await cookies();
  const companyId = cookieStore.get('companyId')?.value;

  if (!agentId) {
    return NextResponse.json({ error: 'agentId required' }, { status: 400 });
  }

  try {
    const query = supabase
      .from('onboarding_sessions')
      .select('*')
      .eq('agent_id', agentId)
      .eq('is_complete', false)
      .order('updated_at', { ascending: false })
      .limit(1);

    if (companyId) {
      query.eq('company_id', companyId);
    }

    const { data } = await query;

    if (data && data.length > 0) {
      return NextResponse.json({
        currentStep: data[0].current_step,
        dataPayload: data[0].data_payload,
        isComplete: data[0].is_complete,
      });
    }

    return NextResponse.json({ currentStep: 0, dataPayload: {}, isComplete: false });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function POST(request: NextRequest) {
  const body = await request.json();
  const { agentId, currentStep, dataPayload, isComplete } = body;
  const cookieStore = await cookies();
  const companyId = cookieStore.get('companyId')?.value;

  if (!agentId) {
    return NextResponse.json({ error: 'agentId required' }, { status: 400 });
  }

  try {
    const { error } = await supabase
      .from('onboarding_sessions')
      .upsert({
        agent_id: agentId,
        company_id: companyId || null,
        current_step: currentStep,
        data_payload: dataPayload,
        is_complete: isComplete || false,
        updated_at: new Date().toISOString(),
      }, {
        onConflict: 'agent_id,company_id',
      });

    if (error) throw error;

    // If complete, also insert into user_agents for portal gating
    if (isComplete) {
      await supabase.from('user_agents').upsert({
        agent_slug: agentId,
        onboarded_at: new Date().toISOString(),
        config: dataPayload,
      }, {
        onConflict: 'agent_slug',
      });
    }

    return NextResponse.json({ success: true });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
