export const dynamic = 'force-dynamic';
// ============================================================
// POST /api/admin/comp-agent — Admin Comp Logic
// Generated by deploy-5-agents.js
// ============================================================
// Grants agent access to a company without Stripe payment.
// Super Admin only.

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

// Lazy init — do NOT create at module scope or build will crash
// when env vars aren't available during `next build` page collection.
let _supabase: ReturnType<typeof createClient> | null = null;
function getSupabase() {
  if (!_supabase) {
    _supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );
  }
  return _supabase;
}


// Auth guard - verify admin access
async function verifyAdmin(req: NextRequest) {
  const token = req.headers.get('authorization')?.replace('Bearer ', '') || '';
  if (!token) return null;
  const sb = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { autoRefreshToken: false, persistSession: false } }
  );
  const { data: { user }, error } = await sb.auth.getUser(token);
  if (error || !user) return null;
  const { data: profile } = await sb.from('profiles').select('role').eq('id', user.id).single();
  if (!profile || !['super_admin', 'admin'].includes(profile.role)) return null;
  return user;
}

export async function POST(req: NextRequest) {
  const adminUser = await verifyAdmin(req);
  if (!adminUser) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  try {
    const body = await req.json();
    const { companyId, agentSlug, compAll, adminUserId } = body;

    if (!companyId) {
      return NextResponse.json({ error: 'companyId required' }, { status: 400 });
    }

    // Verify caller is super_admin
    if (adminUserId) {
      const { data: profile } = await getSupabase()
        .from('profiles')
        .select('role')
        .eq('id', adminUserId)
        .single() as { data: { role: string } | null };

      if (profile?.role !== 'super_admin' && profile?.role !== 'admin') {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 403 });
      }
    }

    if (compAll) {
      // Comp ALL agents for this company
      const { data: agents } = await getSupabase()
        .from('agents')
        .select('slug')
        .eq('status', 'live') as { data: { slug: string }[] | null };

      if (agents) {
        const records = agents.map(a => ({
          company_id: companyId,
          agent_slug: a.slug,
          access_type: 'comp',
          status: 'active',
          granted_at: new Date().toISOString(),
        }));

        const { error } = await getSupabase()
          .from('company_agent_access')
          .upsert(records as any, { onConflict: 'company_id,agent_slug' });

        if (error) throw error;

        return NextResponse.json({
          success: true,
          message: `Comped ${agents.length} agents for company ${companyId}`,
          agents: agents.map(a => a.slug),
        });
      }
    } else if (agentSlug) {
      // Comp single agent
      const { error } = await getSupabase()
        .from('company_agent_access')
        .upsert({
          company_id: companyId,
          agent_slug: agentSlug,
          access_type: 'comp',
          status: 'active',
          granted_at: new Date().toISOString(),
        } as any, { onConflict: 'company_id,agent_slug' });

      if (error) throw error;

      return NextResponse.json({
        success: true,
        message: `Comped ${agentSlug} for company ${companyId}`,
      });
    }

    return NextResponse.json({ error: 'Provide agentSlug or compAll: true' }, { status: 400 });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
