'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { 
  Cpu, ArrowLeft, Play, Download, Code, Database, FileJson,
  Sparkles, Shield, Zap, CheckCircle2, AlertCircle, Loader2,
  ChevronDown, ChevronRight, Copy, Check, Lock
} from 'lucide-react'

// Types
interface AgentManifest {
  agent_id: string
  agent_name: string
  version: string
  created_at: string
  deployment_status: string
  confidence_score: number
  persona: any
  ecosystem_integration: any
  workflow_logic: any[]
  guardrails: any[]
  tool_manifest: any[]
  reliability: any
  verification_suite: any[]
  parsed_steps: any[]
  parsed_entities: any[]
  database_tables: any[]
  api_routes: any[]
  generated_code: string
}

// Mock build function (in production, this would call your backend API)
async function buildAgent(
  name: string,
  domain: string,
  requirements: string,
  sopContent: string,
  constraints: string[]
): Promise<AgentManifest> {
  // Simulate build phases
  await new Promise(r => setTimeout(r, 2000))
  
  const agentSlug = name.toLowerCase().replace(/\s+/g, '_')
  
  // Parse SOP content
  const parsedSteps = sopContent.split('\n')
    .filter(line => line.trim().match(/^\d+[\.\)]|^-|^\*/))
    .map((line, i) => ({
      order: i + 1,
      description: line.replace(/^\d+[\.\)]\s*|^[-\*]\s*/, '').trim(),
      action: 'process'
    }))
  
  // Extract entities
  const entityWords = ['customer', 'order', 'item', 'product', 'user', 'task', 'booking', 'payment', 'invoice']
  const parsedEntities = entityWords
    .filter(word => (requirements + sopContent).toLowerCase().includes(word))
    .map(word => ({
      name: word,
      fields: ['id', 'name', 'status', 'created_at', 'properties'],
      table_name: `${word}s`
    }))
  
  // Generate tables
  const databaseTables = parsedEntities.map(entity => ({
    name: `${agentSlug}_${entity.name}s`,
    columns: [
      'id UUID PRIMARY KEY DEFAULT gen_random_uuid()',
      'created_at TIMESTAMPTZ DEFAULT NOW()',
      'updated_at TIMESTAMPTZ',
      'name VARCHAR(255)',
      'status VARCHAR(50) DEFAULT \'ACTIVE\'',
      'properties JSONB DEFAULT \'{}\''
    ],
    indexes: [`ix_${agentSlug}_${entity.name}s_status`]
  }))
  
  // Generate routes
  const apiRoutes = parsedEntities.flatMap(entity => [
    { method: 'GET', path: `/api/${agentSlug}/${entity.name}s`, description: `List all ${entity.name}s` },
    { method: 'POST', path: `/api/${agentSlug}/${entity.name}s`, description: `Create ${entity.name}` },
    { method: 'GET', path: `/api/${agentSlug}/${entity.name}s/{id}`, description: `Get ${entity.name} by ID` },
    { method: 'PUT', path: `/api/${agentSlug}/${entity.name}s/{id}`, description: `Update ${entity.name}` },
    { method: 'DELETE', path: `/api/${agentSlug}/${entity.name}s/{id}`, description: `Delete ${entity.name}` }
  ])
  
  // Generate code
  const generatedCode = `"""
===============================================================================
${name.toUpperCase()} - AUTO-GENERATED AGENT
===============================================================================
Generated by ACA Master Architect
Version: 1.0.0
Created: ${new Date().toISOString()}
===============================================================================
"""

from datetime import datetime
from typing import Optional, List
from uuid import uuid4
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import text
from sqlalchemy.orm import Session
from packages.core.database import get_db
import json

router = APIRouter(prefix="/api/${agentSlug}", tags=["${agentSlug}"])

# ============================================================================
# DASHBOARD
# ============================================================================

@router.get("/dashboard")
def dashboard(db: Session = Depends(get_db)):
    """Agent dashboard with metrics"""
    return {"agent": "${name}", "status": "active"}

# ============================================================================
# CRUD ENDPOINTS
# ============================================================================
${parsedEntities.map(entity => `
@router.get("/${entity.name}s")
def list_${entity.name}s(status: Optional[str] = None, db: Session = Depends(get_db)):
    """List all ${entity.name}s"""
    query = "SELECT * FROM ${agentSlug}_${entity.name}s WHERE 1=1"
    params = {}
    if status:
        query += " AND status = :status"
        params["status"] = status
    query += " ORDER BY created_at DESC"
    result = db.execute(text(query), params)
    return {"${entity.name}s": [dict(r._mapping) for r in result.fetchall()]}

@router.post("/${entity.name}s")
def create_${entity.name}(name: str, db: Session = Depends(get_db)):
    """Create new ${entity.name}"""
    ${entity.name}_id = str(uuid4())
    db.execute(text("""
        INSERT INTO ${agentSlug}_${entity.name}s (id, name, status)
        VALUES (:id, :name, 'ACTIVE')
    """), {"id": ${entity.name}_id, "name": name})
    db.commit()
    return {"id": ${entity.name}_id, "status": "created"}
`).join('\n')}
`

  // Calculate confidence
  let confidence = 0.5
  if (parsedSteps.length >= 3) confidence += 0.15
  if (parsedEntities.length >= 1) confidence += 0.15
  if (constraints.length >= 1) confidence += 0.1
  if (sopContent.length > 100) confidence += 0.1
  
  return {
    agent_id: crypto.randomUUID(),
    agent_name: name,
    version: '1.0.0',
    created_at: new Date().toISOString(),
    deployment_status: confidence > 0.8 ? 'production_ready' : confidence > 0.6 ? 'simulation_ready' : 'draft',
    confidence_score: Math.min(confidence, 1),
    persona: {
      name,
      role: `${domain.charAt(0).toUpperCase() + domain.slice(1)} Agent`,
      authority_level: 'read_write',
      domain,
      scope_boundaries: [requirements],
      non_goals: ['Tasks outside specified domain'],
      escalation_rules: [{ condition: 'Unknown request', target: 'human_operator' }]
    },
    ecosystem_integration: {
      reads_from: ['supabase'],
      writes_to: ['supabase'],
      event_triggers: [{ type: 'api_call', endpoint: `/api/${agentSlug}/webhook` }],
      data_contracts: { input: { type: 'json' }, output: { type: 'json' } }
    },
    workflow_logic: parsedSteps.map((step, i) => ({
      order: i + 1,
      action: step.action,
      description: step.description,
      inputs: ['request_data'],
      outputs: ['result'],
      error_handling: 'retry_then_escalate'
    })),
    guardrails: [
      { rule_id: 'G001', description: 'Prevent unauthorized access', severity: 'block' },
      { rule_id: 'G002', description: 'Rate limit enforcement', severity: 'warning' },
      { rule_id: 'G003', description: 'Data validation', severity: 'block' },
      { rule_id: 'G004', description: 'PII protection', severity: 'block' }
    ],
    tool_manifest: [
      { name: 'supabase_api', api_endpoint: 'https://api.supabase.com', auth_method: 'api_key', verified: true }
    ],
    reliability: {
      self_correction_rules: [
        { rule_id: 'SC001', check_type: 'input_validation', condition: 'invalid JSON', correction_action: 'reject' },
        { rule_id: 'SC002', check_type: 'output_validation', condition: 'schema mismatch', correction_action: 'regenerate' },
        { rule_id: 'SC003', check_type: 'security_scan', condition: 'PII detected', correction_action: 'redact' },
        { rule_id: 'SC004', check_type: 'rate_limit_check', condition: 'limit approaching', correction_action: 'queue' }
      ],
      failure_simulations: [
        { scenario: 'api_timeout', expected_behavior: 'Return cached data' },
        { scenario: 'rate_limit_exceeded', expected_behavior: 'Queue request' },
        { scenario: 'auth_failure', expected_behavior: 'Refresh token' }
      ],
      idempotency_strategy: 'request_id_deduplication'
    },
    verification_suite: [
      { test_id: 'T001', test_type: 'unit', description: 'Test input validation', passed: false },
      { test_id: 'T002', test_type: 'integration', description: 'Test database', passed: false },
      { test_id: 'T003', test_type: 'negative', description: 'Test unauthorized', passed: false }
    ],
    parsed_steps: parsedSteps,
    parsed_entities: parsedEntities,
    database_tables: databaseTables,
    api_routes: apiRoutes,
    generated_code: generatedCode
  }
}

export default function AgentCreatorPage() {
  const router = useRouter()
  const [isAdmin, setIsAdmin] = useState(false)
  const [isLoading, setIsLoading] = useState(true)
  const [user, setUser] = useState<any>(null)
  
  // Form state
  const [name, setName] = useState('')
  const [domain, setDomain] = useState('')
  const [requirements, setRequirements] = useState('')
  const [sopContent, setSopContent] = useState('')
  const [constraints, setConstraints] = useState('')
  
  // Build state
  const [isBuilding, setIsBuilding] = useState(false)
  const [buildPhase, setBuildPhase] = useState('')
  const [manifest, setManifest] = useState<AgentManifest | null>(null)
  const [activeTab, setActiveTab] = useState<'manifest' | 'code' | 'sql'>('manifest')
  const [copied, setCopied] = useState(false)
  
  // Expandable sections
  const [expanded, setExpanded] = useState<Record<string, boolean>>({
    persona: true,
    ecosystem: false,
    workflow: false,
    guardrails: false,
    reliability: false
  })

  useEffect(() => {
    // Check if user is admin
    const checkAuth = () => {
      const sessionStr = localStorage.getItem('woulfai_session')
      if (!sessionStr) {
        router.push('/login')
        return
      }
      
      try {
        const session = JSON.parse(sessionStr)
        setUser(session.user)
        
        // Check if admin
        if (session.user?.role === 'super_admin' || session.user?.role === 'admin' || session.user?.email === 'admin') {
          setIsAdmin(true)
        } else {
          // Not admin - redirect to dashboard
          router.push('/dashboard')
        }
      } catch {
        router.push('/login')
      }
      
      setIsLoading(false)
    }
    
    checkAuth()
  }, [router])

  const handleBuild = async () => {
    if (!name || !domain || !requirements) return
    
    setIsBuilding(true)
    setManifest(null)
    
    const phases = [
      'Phase 1/8: Identity Construction...',
      'Phase 2/8: SOP Parsing...',
      'Phase 3/8: Ecosystem Integration...',
      'Phase 4/8: Logic & Guardrails...',
      'Phase 5/8: Tool Manifest...',
      'Phase 6/8: Code Generation...',
      'Phase 7/8: Reliability Layer...',
      'Phase 8/8: Verification Suite...'
    ]
    
    for (const phase of phases) {
      setBuildPhase(phase)
      await new Promise(r => setTimeout(r, 500))
    }
    
    const constraintList = constraints.split(',').map(c => c.trim()).filter(Boolean)
    const result = await buildAgent(name, domain, requirements, sopContent, constraintList)
    
    setManifest(result)
    setIsBuilding(false)
    setBuildPhase('')
  }

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const generateSQL = () => {
    if (!manifest) return ''
    return manifest.database_tables.map((table: any) => 
      `CREATE TABLE IF NOT EXISTS ${table.name} (\n${table.columns.map((c: string) => `    ${c}`).join(',\n')}\n);\n\nCREATE INDEX IF NOT EXISTS ${table.indexes[0]} ON ${table.name}(status);`
    ).join('\n\n')
  }

  const downloadFile = (content: string, filename: string) => {
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  if (isLoading) {
    return (
      <div className="min-h-screen bg-[#F4F5F7] flex items-center justify-center">
        <Loader2 className="w-8 h-8 text-purple-500 animate-spin" />
      </div>
    )
  }

  if (!isAdmin) {
    return (
      <div className="min-h-screen bg-[#F4F5F7] flex items-center justify-center">
        <div className="text-center">
          <Lock className="w-16 h-16 text-red-500 mx-auto mb-4" />
          <h1 className="text-2xl font-bold text-white mb-2">Access Denied</h1>
          <p className="text-[#6B7280] mb-4">This page is only available to administrators.</p>
          <Link href="/dashboard" className="text-purple-600 hover:text-purple-300">
            Return to Dashboard
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-[#F4F5F7] text-white">
      {/* Header */}
      <div className="border-b border-[#E5E7EB] bg-[#F4F5F7]/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link href="/dashboard" className="p-2 hover:bg-gray-100 rounded-lg transition-colors">
                <ArrowLeft className="w-5 h-5" />
              </Link>
              <div className="flex items-center gap-3">
                <div className="p-2 bg-gradient-to-br from-purple-500 to-pink-500 rounded-xl">
                  <Cpu className="w-6 h-6" />
                </div>
                <div>
                  <h1 className="text-xl font-bold">ACA Master Architect</h1>
                  <p className="text-sm text-[#6B7280]">Employee Creator · Admin Only</p>
                </div>
              </div>
            </div>
            <div className="flex items-center gap-2 px-3 py-1.5 bg-purple-500/20 rounded-full border border-purple-500/30">
              <Shield className="w-4 h-4 text-purple-600" />
              <span className="text-sm text-purple-300">Admin Access</span>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Left: Input Form */}
          <div className="space-y-6">
            <div className="bg-white shadow-sm rounded-2xl border border-[#E5E7EB] p-6">
              <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-purple-600" />
                Build New Agent
              </h2>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-[#6B7280] mb-1">Agent Name *</label>
                  <input
                    type="text"
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="e.g., Inventory Agent"
                    className="w-full px-4 py-3 bg-white border border-[#E5E7EB] shadow-sm rounded-xl focus:outline-none focus:border-purple-500"
                  />
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-[#6B7280] mb-1">Domain *</label>
                  <select
                    value={domain}
                    onChange={(e) => setDomain(e.target.value)}
                    className="w-full px-4 py-3 bg-white border border-[#E5E7EB] shadow-sm rounded-xl focus:outline-none focus:border-purple-500"
                  >
                    <option value="">Select domain...</option>
                    <option value="inventory">Inventory</option>
                    <option value="billing">Billing</option>
                    <option value="sales">Sales</option>
                    <option value="support">Support</option>
                    <option value="finance">Finance</option>
                    <option value="marketing">Marketing</option>
                    <option value="operations">Operations</option>
                    <option value="hr">HR</option>
                    <option value="other">Other</option>
                  </select>
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-[#6B7280] mb-1">Requirements *</label>
                  <textarea
                    value={requirements}
                    onChange={(e) => setRequirements(e.target.value)}
                    placeholder="Describe what this agent should do..."
                    rows={3}
                    className="w-full px-4 py-3 bg-white border border-[#E5E7EB] shadow-sm rounded-xl focus:outline-none focus:border-purple-500 resize-none"
                  />
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-[#6B7280] mb-1">SOP Content (Optional)</label>
                  <textarea
                    value={sopContent}
                    onChange={(e) => setSopContent(e.target.value)}
                    placeholder="Paste your SOP here. Steps will be extracted automatically.&#10;&#10;Example:&#10;1. Receive order request&#10;2. Validate customer info&#10;3. Check inventory&#10;4. Process payment&#10;5. Send confirmation"
                    rows={8}
                    className="w-full px-4 py-3 bg-white border border-[#E5E7EB] shadow-sm rounded-xl focus:outline-none focus:border-purple-500 resize-none font-mono text-sm"
                  />
                </div>
                
                <div>
                  <label className="block text-sm font-medium text-[#6B7280] mb-1">Constraints (Optional)</label>
                  <input
                    type="text"
                    value={constraints}
                    onChange={(e) => setConstraints(e.target.value)}
                    placeholder="Comma-separated: No direct DB writes, Rate limit 100/min"
                    className="w-full px-4 py-3 bg-white border border-[#E5E7EB] shadow-sm rounded-xl focus:outline-none focus:border-purple-500"
                  />
                </div>
                
                <button
                  onClick={handleBuild}
                  disabled={isBuilding || !name || !domain || !requirements}
                  className="w-full py-3 bg-gradient-to-r from-purple-500 to-pink-500 rounded-xl font-semibold flex items-center justify-center gap-2 hover:opacity-90 transition-opacity disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {isBuilding ? (
                    <>
                      <Loader2 className="w-5 h-5 animate-spin" />
                      {buildPhase}
                    </>
                  ) : (
                    <>
                      <Play className="w-5 h-5" />
                      Build Agent
                    </>
                  )}
                </button>
              </div>
            </div>
            
            {/* Info Cards */}
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-white shadow-sm rounded-xl border border-[#E5E7EB] p-4">
                <Zap className="w-8 h-8 text-yellow-600 mb-2" />
                <h3 className="font-semibold mb-1">8-Phase Protocol</h3>
                <p className="text-sm text-[#6B7280]">Genius-Stack methodology for production-grade agents</p>
              </div>
              <div className="bg-white shadow-sm rounded-xl border border-[#E5E7EB] p-4">
                <Code className="w-8 h-8 text-green-600 mb-2" />
                <h3 className="font-semibold mb-1">Auto-Generated</h3>
                <p className="text-sm text-[#6B7280]">Python code, SQL schemas, API routes</p>
              </div>
            </div>
          </div>

          {/* Right: Output */}
          <div className="space-y-6">
            {manifest ? (
              <div className="bg-white shadow-sm rounded-2xl border border-[#E5E7EB] overflow-hidden">
                {/* Status Header */}
                <div className="p-4 border-b border-[#E5E7EB] flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className={`p-2 rounded-lg ${
                      manifest.deployment_status === 'production_ready' ? 'bg-green-500/20' :
                      manifest.deployment_status === 'simulation_ready' ? 'bg-yellow-500/20' :
                      'bg-gray-500/20'
                    }`}>
                      {manifest.deployment_status === 'production_ready' ? (
                        <CheckCircle2 className="w-5 h-5 text-green-600" />
                      ) : manifest.deployment_status === 'simulation_ready' ? (
                        <AlertCircle className="w-5 h-5 text-yellow-600" />
                      ) : (
                        <AlertCircle className="w-5 h-5 text-[#6B7280]" />
                      )}
                    </div>
                    <div>
                      <h3 className="font-semibold">{manifest.agent_name}</h3>
                      <p className="text-sm text-[#6B7280]">
                        {manifest.deployment_status.replace('_', ' ')} · {(manifest.confidence_score * 100).toFixed(0)}% confidence
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => copyToClipboard(JSON.stringify(manifest, null, 2))}
                      className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
                      title="Copy JSON"
                    >
                      {copied ? <Check className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}
                    </button>
                    <button
                      onClick={() => downloadFile(JSON.stringify(manifest, null, 2), 'manifest.json')}
                      className="p-2 hover:bg-gray-100 rounded-lg transition-colors"
                      title="Download"
                    >
                      <Download className="w-4 h-4" />
                    </button>
                  </div>
                </div>

                {/* Tabs */}
                <div className="flex border-b border-[#E5E7EB]">
                  <button
                    onClick={() => setActiveTab('manifest')}
                    className={`flex-1 px-4 py-3 text-sm font-medium flex items-center justify-center gap-2 ${
                      activeTab === 'manifest' ? 'bg-white shadow-sm text-white border-b-2 border-purple-500' : 'text-[#6B7280] hover:text-[#1B2A4A]'
                    }`}
                  >
                    <FileJson className="w-4 h-4" />
                    Manifest
                  </button>
                  <button
                    onClick={() => setActiveTab('code')}
                    className={`flex-1 px-4 py-3 text-sm font-medium flex items-center justify-center gap-2 ${
                      activeTab === 'code' ? 'bg-white shadow-sm text-white border-b-2 border-purple-500' : 'text-[#6B7280] hover:text-[#1B2A4A]'
                    }`}
                  >
                    <Code className="w-4 h-4" />
                    Python
                  </button>
                  <button
                    onClick={() => setActiveTab('sql')}
                    className={`flex-1 px-4 py-3 text-sm font-medium flex items-center justify-center gap-2 ${
                      activeTab === 'sql' ? 'bg-white shadow-sm text-white border-b-2 border-purple-500' : 'text-[#6B7280] hover:text-[#1B2A4A]'
                    }`}
                  >
                    <Database className="w-4 h-4" />
                    SQL
                  </button>
                </div>

                {/* Content */}
                <div className="p-4 max-h-[600px] overflow-auto">
                  {activeTab === 'manifest' && (
                    <div className="space-y-3">
                      {/* Persona */}
                      <div className="border border-[#E5E7EB] rounded-lg overflow-hidden">
                        <button
                          onClick={() => setExpanded({ ...expanded, persona: !expanded.persona })}
                          className="w-full px-4 py-3 flex items-center justify-between hover:bg-white shadow-sm"
                        >
                          <span className="font-medium">Persona</span>
                          {expanded.persona ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
                        </button>
                        {expanded.persona && (
                          <div className="px-4 pb-3 text-sm">
                            <pre className="text-[#4B5563] overflow-auto">{JSON.stringify(manifest.persona, null, 2)}</pre>
                          </div>
                        )}
                      </div>

                      {/* Workflow */}
                      <div className="border border-[#E5E7EB] rounded-lg overflow-hidden">
                        <button
                          onClick={() => setExpanded({ ...expanded, workflow: !expanded.workflow })}
                          className="w-full px-4 py-3 flex items-center justify-between hover:bg-white shadow-sm"
                        >
                          <span className="font-medium">Workflow ({manifest.workflow_logic.length} steps)</span>
                          {expanded.workflow ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
                        </button>
                        {expanded.workflow && (
                          <div className="px-4 pb-3 text-sm">
                            <pre className="text-[#4B5563] overflow-auto">{JSON.stringify(manifest.workflow_logic, null, 2)}</pre>
                          </div>
                        )}
                      </div>

                      {/* Guardrails */}
                      <div className="border border-[#E5E7EB] rounded-lg overflow-hidden">
                        <button
                          onClick={() => setExpanded({ ...expanded, guardrails: !expanded.guardrails })}
                          className="w-full px-4 py-3 flex items-center justify-between hover:bg-white shadow-sm"
                        >
                          <span className="font-medium">Guardrails ({manifest.guardrails.length} rules)</span>
                          {expanded.guardrails ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
                        </button>
                        {expanded.guardrails && (
                          <div className="px-4 pb-3 text-sm">
                            <pre className="text-[#4B5563] overflow-auto">{JSON.stringify(manifest.guardrails, null, 2)}</pre>
                          </div>
                        )}
                      </div>

                      {/* Reliability */}
                      <div className="border border-[#E5E7EB] rounded-lg overflow-hidden">
                        <button
                          onClick={() => setExpanded({ ...expanded, reliability: !expanded.reliability })}
                          className="w-full px-4 py-3 flex items-center justify-between hover:bg-white shadow-sm"
                        >
                          <span className="font-medium">Reliability Layer</span>
                          {expanded.reliability ? <ChevronDown className="w-4 h-4" /> : <ChevronRight className="w-4 h-4" />}
                        </button>
                        {expanded.reliability && (
                          <div className="px-4 pb-3 text-sm">
                            <pre className="text-[#4B5563] overflow-auto">{JSON.stringify(manifest.reliability, null, 2)}</pre>
                          </div>
                        )}
                      </div>

                      {/* API Routes */}
                      <div className="border border-[#E5E7EB] rounded-lg p-4">
                        <h4 className="font-medium mb-2">API Routes ({manifest.api_routes.length})</h4>
                        <div className="space-y-1 text-sm">
                          {manifest.api_routes.map((route, i) => (
                            <div key={i} className="flex items-center gap-2">
                              <span className={`px-2 py-0.5 rounded text-xs font-mono ${
                                route.method === 'GET' ? 'bg-green-500/20 text-green-600' :
                                route.method === 'POST' ? 'bg-blue-100 text-blue-600' :
                                route.method === 'PUT' ? 'bg-yellow-500/20 text-yellow-600' :
                                'bg-red-500/20 text-red-600'
                              }`}>{route.method}</span>
                              <code className="text-[#6B7280]">{route.path}</code>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}

                  {activeTab === 'code' && (
                    <div className="relative">
                      <button
                        onClick={() => {
                          copyToClipboard(manifest.generated_code)
                          downloadFile(manifest.generated_code, `${manifest.agent_name.toLowerCase().replace(/\s+/g, '_')}_routes.py`)
                        }}
                        className="absolute top-2 right-2 px-3 py-1.5 bg-purple-500/20 hover:bg-purple-500/30 rounded-lg text-sm flex items-center gap-2"
                      >
                        <Download className="w-4 h-4" />
                        Download
                      </button>
                      <pre className="text-sm text-[#4B5563] font-mono whitespace-pre-wrap">{manifest.generated_code}</pre>
                    </div>
                  )}

                  {activeTab === 'sql' && (
                    <div className="relative">
                      <button
                        onClick={() => {
                          const sql = generateSQL()
                          copyToClipboard(sql)
                          downloadFile(sql, 'schema.sql')
                        }}
                        className="absolute top-2 right-2 px-3 py-1.5 bg-purple-500/20 hover:bg-purple-500/30 rounded-lg text-sm flex items-center gap-2"
                      >
                        <Download className="w-4 h-4" />
                        Download
                      </button>
                      <pre className="text-sm text-[#4B5563] font-mono whitespace-pre-wrap">{generateSQL()}</pre>
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <div className="bg-white shadow-sm rounded-2xl border border-[#E5E7EB] p-12 text-center">
                <Cpu className="w-16 h-16 text-[#6B7280] mx-auto mb-4" />
                <h3 className="text-xl font-semibold text-[#6B7280] mb-2">No Agent Built Yet</h3>
                <p className="text-[#9CA3AF]">Fill in the form and click "Build Agent" to generate a new AI Employee with the Genius-Stack Protocol.</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
