// ============================================================
// Onboarding Layout — Clean, no sidebar
// Generated by install-onboarding.js
// ============================================================

import React from 'react';

export default function OnboardingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-950 via-gray-900 to-gray-950">
      {children}
    </div>
  );
}

export const metadata = {
  title: 'Setup Wizard | WoulfAI',
  description: 'Activate your AI agent in under 10 minutes.',
};
